### ISSUE TITLE
kube-flannel containers continually crash

### ISSUE THREAD

**Issue by shineygreen** [coreos/flannel#1012]
We are running flannel in a Kubernetes 10 cluster. We are seeing the kube-flannel containers on the client nodes restart on a regular basis,

kubectl get po --namespace kube-system -l app=flannel
NAME                    READY     STATUS             RESTARTS   AGE
kube-flannel-ds-h4wwx   1/1       Running            916        6d
kube-flannel-ds-j6lzn   0/1       CrashLoopBackOff   974        6d
kube-flannel-ds-jvg4q   1/1       Running            0          6d
kube-flannel-ds-ldlvn   1/1       Running            499        3d
kube-flannel-ds-mgls2   1/1       Running            502        3d
kube-flannel-ds-qv2tt   1/1       Running            4          6d
kube-flannel-ds-qwd4l   1/1       Running            961        6d
kube-flannel-ds-wv8d5   1/1       Running            487        3d

But we don't see any error messages in the log,

kubectl logs --namespace kube-system kube-flannel-ds-h4wwx -c kube-flannel --follow=true
I0628 21:39:33.843939       1 main.go:475] Determining IP address of default interface
I0628 21:39:33.845296       1 main.go:488] Using interface with name enp129s0f0 and address 10.80.15.6
I0628 21:39:33.845312       1 main.go:505] Defaulting external address to interface address (10.80.15.6)
I0628 21:39:33.884136       1 kube.go:131] Waiting 10m0s for node controller to sync
I0628 21:39:33.884178       1 kube.go:294] Starting kube subnet manager
I0628 21:39:34.884372       1 kube.go:138] Node controller sync successful
I0628 21:39:34.884425       1 main.go:235] Created subnet manager: Kubernetes Subnet Manager - biggpu06
I0628 21:39:34.884434       1 main.go:238] Installing signal handlers
I0628 21:39:34.884521       1 main.go:353] Found network config - Backend type: vxlan
I0628 21:39:34.884588       1 vxlan.go:120] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
I0628 21:39:34.938474       1 main.go:300] Wrote subnet file to /run/flannel/subnet.env
I0628 21:39:34.938484       1 main.go:304] Running backend.
I0628 21:39:34.938496       1 main.go:322] Waiting for all goroutines to exit
I0628 21:39:34.938519       1 vxlan_network.go:60] watching for new subnet leases
I0628 21:39:35.038692       1 iptables.go:115] Some iptables rules are missing; deleting and recreating rules
I0628 21:39:35.038710       1 iptables.go:137] Deleting iptables rule: -s 10.244.0.0/16 -d 10.244.0.0/16 -j RETURN
I0628 21:39:35.039261       1 iptables.go:137] Deleting iptables rule: -s 10.244.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
I0628 21:39:35.040041       1 iptables.go:137] Deleting iptables rule: ! -s 10.244.0.0/16 -d 10.244.4.0/24 -j RETURN
I0628 21:39:35.040580       1 iptables.go:137] Deleting iptables rule: ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE
I0628 21:39:35.041179       1 iptables.go:125] Adding iptables rule: -s 10.244.0.0/16 -d 10.244.0.0/16 -j RETURN
I0628 21:39:35.042600       1 iptables.go:125] Adding iptables rule: -s 10.244.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
I0628 21:39:35.044060       1 iptables.go:125] Adding iptables rule: ! -s 10.244.0.0/16 -d 10.244.4.0/24 -j RETURN
I0628 21:39:35.045425       1 iptables.go:125] Adding iptables rule: ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE
I0628 21:39:36.039641       1 iptables.go:115] Some iptables rules are missing; deleting and recreating rules
I0628 21:39:36.039662       1 iptables.go:137] Deleting iptables rule: -s 10.244.0.0/16 -j ACCEPT
I0628 21:39:36.137518       1 iptables.go:137] Deleting iptables rule: -d 10.244.0.0/16 -j ACCEPT
I0628 21:39:36.138220       1 iptables.go:125] Adding iptables rule: -s 10.244.0.0/16 -j ACCEPT
I0628 21:39:36.139377       1 iptables.go:125] Adding iptables rule: -d 10.244.0.0/16 -j ACCEPT
I0628 21:51:22.640825       1 main.go:337] shutdownHandler sent cancel signal...
munderkofler-mba:~ sid.stuart$ kubectl logs --namespace kube-system kube-flannel-ds-h4wwx -c kube-flannel --follow=true
I0628 21:51:41.341736       1 main.go:475] Determining IP address of default interface
I0628 21:51:41.637978       1 main.go:488] Using interface with name enp129s0f0 and address 10.80.15.6
I0628 21:51:41.638034       1 main.go:505] Defaulting external address to interface address (10.80.15.6)
I0628 21:51:41.678739       1 kube.go:131] Waiting 10m0s for node controller to sync
I0628 21:51:41.678822       1 kube.go:294] Starting kube subnet manager
I0628 21:51:42.678997       1 kube.go:138] Node controller sync successful
I0628 21:51:42.679029       1 main.go:235] Created subnet manager: Kubernetes Subnet Manager - biggpu06
I0628 21:51:42.679041       1 main.go:238] Installing signal handlers
I0628 21:51:42.679175       1 main.go:353] Found network config - Backend type: vxlan
I0628 21:51:42.679259       1 vxlan.go:120] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
I0628 21:51:42.680588       1 main.go:300] Wrote subnet file to /run/flannel/subnet.env
I0628 21:51:42.680608       1 main.go:304] Running backend.
I0628 21:51:42.680627       1 main.go:322] Waiting for all goroutines to exit
I0628 21:51:42.680668       1 vxlan_network.go:60] watching for new subnet leases
I0628 22:00:59.942992       1 main.go:337] shutdownHandler sent cancel signal...

## Your Environment

* Flannel version: quay.io/coreos/flannel:v0.10.0-amd64
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: k8s.gcr.io/etcd-amd64:3.1.12
* Kubernetes version (if used): 1.10.4
* Operating System and version: Ubuntu 16.04
* Link to your project (optional):

Any suggestions on how to debug?

**Comment by shineygreen** [comment]
I could not get the Flannel pods to stop restarting, so I punted on Flannel and switched to Weave. That is stable.

**Comment by royxue** [comment]
@shineygreen 
+1 this problem.
Is switching to Weave need kubeadm reset first?

**Comment by prateek2408** [comment]
got the same error, does switching to weave need a kubeadm reset ?

**Comment by royxue** [comment]
@prateek2408 as I tried before, it doesnt

**Comment by notxcain** [comment]
I think this should be reopened to appear on flannel devs radar

**Comment by nsaboo** [comment]
It is happening too frequently, like every 10 mins flannel is getting restarted and causing all the pods to be restarted? Any idea on how to overcome this issue

**Comment by fenghejingchi** [comment]
agree. The flannel is keep restating too frequently. Plan to switch to calico
