### ISSUE TITLE
Firewall support

### ISSUE THREAD

**Issue by tristanz** [coreos/flannel#102]
Are there any plans to support firewalls in flannel?  Or is this something that should be built on top on flannel as a separate component?

I'm thinking of something akin to [GCE Firewalls](https://cloud.google.com/compute/docs/networking#firewall) where you can control traffic via source and target tags.  This would work very well with Kubernetes and allow applications to be better isolated from one another.

See discussion here:  https://github.com/GoogleCloudPlatform/kubernetes/issues/2880

**Comment by tomdee** [comment]
Network policy can be applied using Canal - https://github.com/projectcalico/canal
