### ISSUE TITLE
Can I use 192.168.0.0/16 as pod cidr with flannel?

### ISSUE THREAD

**Issue by zenglian** [coreos/flannel#1054]
I followed https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/ to create 1 master+1 slave cluster.  

There is a notice in the guide:
> For `flannel` to work correctly, you must pass `--pod-network-cidr=10.244.0.0/16` to `kubeadm init`.

I tried `--pod-network-cidr=192.168.0.0/16`, with below extra steps:

```
# before kubeadm init, clear earlier net interface on both nodes
sudo ip link del cni0
sudo ip link del flannel.1

# after create flannel
kubectl edit cm -n kube-system kube-flannel-cfg
... edit the configuration by changing network from 10.244.0.0/16 to 192.168.0.0/16 ...
kubectl delete pod -n kube-system -l app=flannel
```

But still fail to create dashboard, with error saying "api server is not reachable".
2 nginx pods are created successfully as 192.168.0.x and 192.168.1.x, but they can not ping each other.

**Comment by zenglian** [comment]
It's resolved, though not sure th exact cause.  
The above steps plus a reboot everything works.

**Comment by zenglian** [comment]
FYI: https://stackoverflow.com/questions/52963102/use-192-168-0-0-16-or-other-iprange-as-pod-cidr-for-kubernetes-flannel

**Comment by aleksarias** [comment]
@zenglian Your solution worked for me. I just had to update the configmap with the correct network cidr, reboot, and everything is now working. 

Thanks!
