### ISSUE TITLE
Flannel v0.10.0 not finding key in etcd-member (v3) in coreos

### ISSUE THREAD

**Issue by fabifrank** [coreos/flannel#1057]
## Expected Behavior
`flanneld` correctly fetching the required config key in etcd.

## Current Behavior
When starting `flanneld` which is configured correctly to connect to a local etcd v3 instance it cannot fetch the network config. As stated, `3280 main.go:349] Couldn't fetch network config: 100: Key not found (/coreos.com/network)`.

## Possible Solution
Use Kubernetes kube subnet manager?

## Steps to Reproduce (for bugs)
1. Start `etcd-member` unit in coreos
1. Push network config to etcd `ETCDCTL_API=3 etcdctl put /coreos.com/network '{\"Network\": \"10.100.0.0/16\"}'`
1. Start `flanneld`
1. Get logs of `flannel`

## Context
I am trying to set up a kubernetes cluster with `flannel`.

## Your Environment
* Flannel version: v0.10.0
* Backend used (e.g. vxlan or udp): _not set yet.._
* Etcd version: 3.3.9
* Kubernetes version (if used): _not started yet.._
* Operating System and version: CoreOS 1855.5.0

**Comment by halfcrazy** [comment]
Currently flannel does not support etcd v3 API, use "--kube-subnet-mgr" instead.

**Comment by tomdee** [comment]
Or ensure the key exists in the etcd v2 API.
