### ISSUE TITLE
Problem in forwarding packets: The IP of container gets replaced with the IP of docker or flannel interface

### ISSUE THREAD

**Issue by LuqmanSahaf** [coreos/flannel#107]
I am trying to set up `Hadoop` cluster using `Kubernetes`, `CoreOS`and `flannel` (`vxlan`). In `Hadoop`, there is a Namenode (master) and Datanodes (workers), and Datanodes register on Namenodes. Now, when Datanode (inside a container) registers itself on Namenode, it sends a request. The Namenode receives this request and registers the Datanode with the IP of the source of the packet. However, the source in the request is being replaced with the IP address of Docker interface, if Datanode lands on the same host (`minion`) as Namenode. Or the source is being replaced with Flannel interface IP, if it gets assigned to another `minion`. 

Please, see the following gists:

> logs of Container processes:
> https://gist.github.com/LuqmanSahaf/fd7ee3bf9b1766e4a5ad
> 
> TCPDump(s) of different interfaces:
> https://gist.github.com/LuqmanSahaf/88b4b9ddf2955028bfa8

Namenode catches the IP from `RPC` request and uses it to register Datanode.

Now, I want to ask a few questions:
Why is that the IP of the container is being replaced?
Is this problem related to flannel or Docker? (Because, even if the Datanode is in the same subnet (`minion`), the IP gets replaced with the Docker interface IP.)

Please, help me out with this.

**Comment by ilterpehlivan** [comment]
Hi, 
I am also facing this issue and cannot ping from my Pod in HostA to my DNS service running in HosB
The google forum link that is posted above is not reachable, could you please give the new Url for the answer ?

Thanks

**Comment by euank** [comment]
The message id remains the same, so the updated link is https://groups.google.com/d/topic/kubernetes-users/P4uh7y383oo
