### ISSUE TITLE
Unable to deploy flannel to Kubernetes since merge of pr/1043

### ISSUE THREAD

**Issue by ctas582** [coreos/flannel#1082]
I've just tried to deploy flannel to a new Kubernetes cluster, using the deployment YAML at https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml. The daemonset and pods are deployed successfully, but all the nodes fail to report as ready.

The output of `kubectl describe node <>` shows:
```
KubeletNotReady runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

Kubelet logs show:
```
cni.go:132] Error loading CNI config file /etc/cni/net.d/10-flannel.conf: no 'type'; perhaps this is a .conflist?
cni.go:172] Unable to update cni config: No valid networks found in /etc/cni/net.d
kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

It looks like the `cni-conf.json` config defined in the YAML might be in '.conflist' format.

I note that a few hours ago, pull request #1043 was merged which changed the install location of that config file to `/etc/cni/net.d/10-flannel.conf` instead of `/etc/cni/net.d/10-flannel.conflist`, saying that it is a typo. I'm not sure that is the case, the '.conflist' extension is used a number of times in other parts of the deployment YAML, and when I switched the extension back everything worked as expected.

Should #1043 be reverted?

**Comment by rajatchopra** [comment]
#1043 stands reverted. Sorry about that hassle. Thanks for reporting this.
