### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by pierreozoux** [coreos/flannel#1088]
Hi,

Here is an happy open source user, [hosting privacy](https://indie.host) with flannel ;)

In my day job, I saw a video from RedHat about OpenShift 4, and there was one slide with the status of the various CoreOS projects.
And flannel status was "maitenance only" AFAICR, but I don't remember which video.

Could you update the README with the current status of the project?

Thanks a lot for your valuable time, and the great project you gave the community.

(I have to admit it is sad to flannel going, especially because I was really happy with my setup with wireguard.)

**Comment by rajatchopra** [comment]
> (I have to admit it is sad to flannel going, especially because I was really happy with my setup with wireguard.)

It isn't going away. Certainly not. If you have noticed, some decent work related to Windows platform has been done recently.

It is somewhat true that we are running thin on having people work full time on this project (at the time of this writing, to the knowledge of this writer). Even then, it is up to the community if any major work needs to be brought about.
If you have a fix, or a feature, please post a PR and the action taken on the PR will be the proof of the pudding :).

Your enthusiasm is needed. Please file issues if you find something you are stuck on. Its alive and still kicking.
(And close this issue when you are convinced either way :)).

**Comment by pierreozoux** [comment]
Ok, I understand now it was a RedHat statement and not necessarily a community statement :)

Great, I trust you and your enthusiasm :) do you come to fosdem or know anyone going?

Cheers!
