### ISSUE TITLE
access flannel overlay network from outside

### ISSUE THREAD

**Issue by hellobinge** [coreos/flannel#1101]
hey guys,

I have question regarding accessing flannel overlay network.

We have a cluster with tens of physical machines. I've set up flannel overlay network among servers. Containers on different hosts can ping each other, and they can access outside internet. It works perfect.

But we got requirements from other teams. They need to connect to containers via TCP connection. Their app will randomly expose some TCP ports, and they need to connect to those TCP ports use their local machine (which is not in flannel overlay network). Do you guys know how to let outside traffic (TPC/UDP, Not just HTTP) access flannel overlay network?

Not just HTTP traffic. We've solved HTTP traffic with HAProxy. What if it is TCP/UDP traffic?

(previously, we don't have such problem, since we use MACVLAN. Containers and hosts are in the same network. Containers are just like physical machines. Users can freely access container via TCP, UDP, HTTP.)

Thank you!

**Comment by rajatchopra** [comment]
Create a gateway node or set of nodes which can reverse proxy layer 4 traffic. You will be implementing the service type 'load balancer' functionality. You could use macvlan on these machines.
Or if the infrastructure is bare metal, then see if metallb (https://metallb.universe.tf) is what you need.

**Comment by hellobinge** [comment]
@rajatchopra thanks rajat, I will do some more research

**Comment by rajatchopra** [comment]
Closing this issue. Please re-open if needed.
