### ISSUE TITLE
Connect issues with flannel on Centos 6.6

### ISSUE THREAD

**Issue by sidharta-s** [coreos/flannel#111]
I am running flanneld (0.2.0) on a set of OpenStack VMs .  The configuration that flannel is using is : 

```
$ etcdctl  get /coreos.com/network/config
{"Network": "10.244.0.0/16", "SubnetLen": 24, "Backend": {"Type": "udp"}}
```

On startup, flanneld seems to create a flannel0 device along with some routing table entries. An example routing table is : 

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.244.85.0     0.0.0.0         255.255.255.0   U     0      0        0 docker0
192.168.96.0    0.0.0.0         255.255.224.0   U     0      0        0 eth0
10.244.0.0      0.0.0.0         255.255.0.0     U     0      0        0 flannel0
169.254.0.0     192.168.96.1    255.255.0.0     UG    0      0        0 eth0
0.0.0.0         192.168.96.1    0.0.0.0         UG    0      0        0 eth0
```
Attempting to ping a remote IP gives an "Invalid argument" : 
```
$ ping 10.244.87.1
connect: Invalid argument
```
The same "Invalid argument" error occurs using ssh (a connection refused is expected, but I get an "Invalid argument" instead ).  Interestingly, using "nping", I am able to get a response from the other IP : 
```
$ nping -c 2 --icmp --icmp-type echo-request 10.244.87.1

Starting Nping 0.5.51 ( http://nmap.org/nping ) at 2015-01-13 23:56 UTC
SENT (0.0139s) ICMP 10.244.85.0 > 10.244.87.1 Echo request (type=8/code=0) ttl=64 id=35329 iplen=28 
RCVD (0.0155s) ICMP 10.244.87.1 > 10.244.85.0 Echo reply (type=0/code=0) ttl=62 id=14865 iplen=28 
SENT (1.0141s) ICMP 10.244.85.0 > 10.244.87.1 Echo request (type=8/code=0) ttl=64 id=35329 iplen=28 
RCVD (1.0150s) ICMP 10.244.87.1 > 10.244.85.0 Echo reply (type=0/code=0) ttl=62 id=14866 iplen=28 
 
Max rtt: 1.539ms | Min rtt: 0.792ms | Avg rtt: 1.165ms
Raw packets sent: 2 (56B) | Rcvd: 2 (56B) | Lost: 0 (0.00%)
Tx time: 1.00040s | Tx bytes/s: 55.98 | Tx pkts/s: 2.00
Rx time: 2.00228s | Rx bytes/s: 27.97 | Rx pkts/s: 1.00
Nping done: 1 IP address pinged in 2.03 seconds
$ 
```

ifconfig output from the same node : 
```
$ ifconfig
docker0   Link encap:Ethernet  HWaddr DA:39:02:81:65:8D  
          inet addr:10.244.85.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::d839:2ff:fe81:658d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:22 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:1588 (1.5 KiB)

eth0      Link encap:Ethernet  HWaddr FA:16:3E:44:27:87  
          inet addr:192.168.96.35  Bcast:192.168.127.255  Mask:255.255.224.0
          inet6 addr: fe80::f816:3eff:fe44:2787/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:269329 errors:0 dropped:0 overruns:0 frame:0
          TX packets:131516 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:85134671 (81.1 MiB)  TX bytes:18901821 (18.0 MiB)

flannel0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:10.244.85.0  P-t-P:10.244.85.0  Mask:255.255.0.0
          UP POINTOPOINT RUNNING  MTU:1472  Metric:1
          RX packets:12 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500 
          RX bytes:336 (336.0 b)  TX bytes:336 (336.0 b)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:26 errors:0 dropped:0 overruns:0 frame:0
          TX packets:26 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1370 (1.3 KiB)  TX bytes:1370 (1.3 KiB)
```

**Comment by sidharta-s** [comment]
Another thing : I started with VXLAN first and saw the connect issue there too. nping wouldn't work either (tcpdump on flannel.1 would show ARP requests going out, but not responses) - so I switched to using the UDP backend.

**Comment by eyakubovich** [comment]
@sidharta-s your config, routing table and everything else looks fine. I am not sure why connect() would fail. I will need to fire up CentOS 6.6 to dig in.

**Comment by sidharta-s** [comment]
@eyakubovich thank you. I am able to ping other IPs (just not the ones routed through flannel0). Let me know if you need any other information from me. In case it matters, these VMs are openstack instances. 

```
lspci | egrep -i 'network|ethernet'
00:03.0 Ethernet controller: Red Hat, Inc Virtio network device
```

**Comment by eyakubovich** [comment]
@sidharta-s I couldn't find (yet) CentOS 6.6 so I tried RHEL 6.6 on AWS and Rackspace and in udp mode worked fine. On AWS, it wasn't even PV mode (only HVM was available). And both run Xen so it wasn't virtio (or at least I think so).

The VXLAN didn't work but I'm not too surprised. We use DOVE extensions that have been added in kernel 3.8 and RHEL6.6 is based on 2.6.32 (not sure what has been backported).

Do you know of any public clouds that run kvm and have CentOS 6.6 image available?

Can you try pinging your own flannel0 IP? Does it also fail?

**Comment by sidharta-s** [comment]
@eyakubovich Pinging the local IP works.  (but that is routed through docker0 as per the routing table above?)

**Comment by sidharta-s** [comment]
@eyakubovich About VXLAN - it would be useful to modify README.md to indicate kernel requirements for various flannel backends. One of my reasons for picking flannel for CentOS 6.6 was that it didn't seem to require a recent kernel!

**Comment by eyakubovich** [comment]
@sidharta-s you're right, we should document kernel requirements. There's a PR we're evaluating to using a slightly different approach that doesn't require DOVE extensions. I don't remember when VXLAN proper got added but CentOS 6.6 seems to have it.

Can you try `ping -I flannel0 10.244.87.1`? Let's see if binding to the proper interface will help.

**Comment by sidharta-s** [comment]
@eyakubovich any connect() calls through flannel0 (including -I) failed.  As a last resort, I destroyed this cluster I created an all new openstack cluster running CentOS 6.6/flannel and docker. ping across the cluster appears to succeed now. I am not sure what caused my first cluster to end up in this state. I'll close this issue for now. Thanks for looking into this!

**Comment by kjvalencik** [comment]
Can anyone comment on whether VXLAN backend works or not in CentOS 6.6 (2.6.32 kernel)? Thanks!
