### ISSUE TITLE
why flannel delpoy does not care about installing related cni binaries

### ISSUE THREAD

**Issue by mars1024** [coreos/flannel#1126]
I'm wondering why flanneld deploy does not care about intsalling related cni binaries. I've found that early edition flanneld deploy used **flannel-cni** image to help copy related cni binaries to `/opt/cni/bin` hostpath, but in latest edition flanneld deploy only copy netconf file to `/etc/cni/net.d` hostpath.
Why such a change has been made? I think this will lead to a strong dependence of flanneld deploy on cluster-init tools like kubeadm and a mismatch between flanneld and flannel-related cni binaries.

**Comment by vorburger** [comment]
From what (little) I understand, the `flannel` CNI plugin (now?) lives at https://github.com/containernetworking/plugins/blob/master/plugins/meta/flannel/README.md (as opposed to `flanneld`, from this project). 

I only understood the difference as I was trying to figure out which version I had for #1159.

**Comment by mars1024** [comment]
I think i've found out why flannel does not care about CNI plugin's deployment, this is because the official kubelet rpm has already contained [this](https://github.com/kubernetes/release/blob/bb92cb30c5c9de9e43c6d4076546caf5886b91a4/rpm/kubelet.spec#L134).

But I have made some changes to flannel cni plugin, so I build it in my repo and deploy it with daemonset, just like Calico.

**Comment by mars1024** [comment]
Since I've resolved this, closing this .cc @vorburger
