### ISSUE TITLE
IPSec Routing Issues

### ISSUE THREAD

**Issue by martin31821** [coreos/flannel#1131]
I tried to fix the IPSec backend to allow it to be used with kubernetes the last few days. After lots of debugging and logging/tcpdump, I could reproduce it today:

## Setup

- k8s 1.14.1, setup with kubespray
- Container Linux 2079.3.0, Linux 4.19 LTS
- flannel with custom patches
- Pod Network: 10.224.0.0/12
- Service Network: 10.192.0.0/12
- Node Subnet: 10.224.0.0/20 - 10.224.64.0/20
- A vti interface is added on every node, with the Node Network as ip address (just like the vxlan backend)
- I tried several ways of route setup:
  - `10.224.0.0/12 dev flannel-vti scope global`
  - `10.224.16.0/20 dev flannel-vti via 10.224.16.0 onlink` 
  - Doesn't change anything

## Expected Behavior

- Pod->Pod, Pod->Service, Pod->Host, Host->Pod, Host->Service, Host->Host should work from every node to every other node

## Current Behavior

- All works when having even prefixes (in my scenario there are three: 10.224.0.0/20, 10.224.32.0/20 and 10.224.64.0/20)
- As soon as I try Pod->Pod, Pod->Service, Host->Pod, Host->Service from a node with an even prefix to a node with an odd prefix (10.224.16.0/20 or 10.224.48.0/20), the packets get lost at the target node after the iptables `nat` table after the `PREROUTING` chain.
According to Wikipedia, the next step in the processing chain:
![https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Netfilter-packet-flow.svg/1920px-Netfilter-packet-flow.svg.png](https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Netfilter-packet-flow.svg/1920px-Netfilter-packet-flow.svg.png)

Is the route selection. 
When I throw the received packet into `ip route get $PACKETSPEC` I get the correct route which would route the packet to the correct pod.
However, the packet won't get received at the pod itself, i.e. it is dropped in the kernel during the routing process.

## Possible Solution

I don't know why, but choosing only even networks seems to work for my use case. 
I don't consider this a solution either.

## Steps to Reproduce (for bugs)

I can provide access to a live system on request.

**Comment by martin31821** [comment]
For reference, here are two screenshots from iptables TRACE targets for two pods:
The first one is on an odd subnet, the second one on an even subnet.

![odd](https://user-images.githubusercontent.com/5557633/56868580-7bb66b00-69f4-11e9-9492-9ed755cef72d.png)
![even](https://user-images.githubusercontent.com/5557633/56868583-87a22d00-69f4-11e9-93d7-a43029188c6c.png)

**Comment by martin31821** [comment]
Got a little bit further today, I managed to get the following stuff working:
- Pod -> Pod
- Pod -> Service -> Pod
- Pod -> Host
- Host -> Pod

So the only thing that's missing from a functional implementation is the part Host->Service->Pod.
Current state of Host->Service->Pod is that the host is:
- IPVS forward lookup works, so when I start a connection to a service (e.g. 10.206.136.31) it will send packages out on lo with src=10.206.136.31 dst=10.206.136.31, iptables will flag this package as masquerade-required (KUBE-MARK-MASQ chain)
- Afterwards, it traverses the IPVS kernel stuff, the packet looks like src=10.206.136.31 dst=10.224.48.59 
- Afterwards, it traverses the iptables postrouting stage where the packet will be masqueraded.
- Masquerading the packet yields the public node IP as source IP which will then be encapsulated and sent to the other client where the request is processed.
- When the response packet is received on the original node, it passes the following iptables tables:
  - raw:PREROUTING
  - filter:INPUT
  - filter:KUBE-FIREWALL
- After those chains netfilter passes the packet back to the kernel and then it's lost.
If anyone could help or has debugging tips, I'd be happy to test stuff.

**Comment by martin31821** [comment]
Finally managed to fix this annoying issue. I changed the source IP address of the IPVS interface to match the CNI interface address, disabled xfrm policies on the CNI interface and now it just works.

**Comment by pmcq** [comment]
Hi @martin31821, I am experiencing this same problem.  Is the solution you described in the open PR linked in or are these steps that I could follow?  If the latter can you help clarify how to make these configuration changes?

**Comment by martin31821** [comment]
The open PR fixes the issue (at least in our configuration & as far as I can tell).
We're using this version in one of our production clusters, but we'll migrate to cilium soon to unify our infrastructure, so I won't be able to do fixes there anymore, but feel free to adopt it.

**Comment by pmcq** [comment]
I see, thanks.  It seems like this github issue should remain open at the least since it is an unresolved issue (unless we went off of a fork with that patch) - is it possible to remove all of the vendor lib changes introduced with that PR?  It looks like there's really only about 10 files changed and then that PR is un-mergeable due to conflicts with all of the vendor changes, but I wasn't sure if they were required.

As an aside, do you know if cilium's usage of IPSec has this same issue?

**Comment by martin31821** [comment]
In our infrastructure, they don't suffer from this problem because they use eBPF directly beyond their input chain. 
Some vendor changes were neccessary AFAIR, because I needed to update the netlink api.

**Comment by hvenev-vmware** [comment]
I've also hit the same issue. I fixed Node->Pod by adding a route:

```
    # ip route add CLUSTER_CIDR dev cni0
```

For Node -> Service -> Pod, I tried fixing the service route:

```
# ip route replace local SERVICE_IP src NODE_CLUSTER_IP dev kube-ipvs0 proto kernel scope host table local
```

However that didn't work (conntrack reported the response packet as invalid). What else did you do?

**Comment by hvenev-vmware** [comment]
My findings were that reply packets get dropped because they didn't match the xfrm policy. One option is to disable policy checking. However that seemed like a bit of an overkill to me and I'm not sure what the security implications would be.

Instead, the following rule helped:

```
# ip xfrm policy add src SERVICE_CIDR dst POD_CIDR dir in priority 0 ptype main tmpl proto esp reqid 11 mode tunnel
```

reqid 11 is the default used by flannel. By omitting the source and destination, I believe all are accepted.
