### ISSUE TITLE
DUPs and Logs

### ISSUE THREAD

**Issue by jpmx** [coreos/flannel#114]
Hi!,

Using `CoreOS: 561.0.0` I see a lot of duplicate packets when running `ping` inside a container with vxlan, same results pinging between different containers and outside hosts:

```
64 bytes from 10.1.61.2: icmp_seq=557 ttl=62 time=0.245 ms
64 bytes from 10.1.61.2: icmp_seq=557 ttl=62 time=2.59 ms (DUP!)
64 bytes from 10.1.61.2: icmp_seq=558 ttl=62 time=0.321 ms
64 bytes from 10.1.61.2: icmp_seq=558 ttl=62 time=2.47 ms (DUP!)
64 bytes from 10.1.61.2: icmp_seq=559 ttl=62 time=0.257 ms
64 bytes from 10.1.61.2: icmp_seq=560 ttl=62 time=0.242 ms
```

```
# journalctl -f -t sdnotify-proxy
Jan 20 20:58:11 coreos1 sdnotify-proxy[1376]: I0120 20:58:11.499341 00001 device.go:228] calling NeighSet: 10.1.61.2, 06:32:53:65:0f:9a
Jan 20 20:58:11 coreos1 sdnotify-proxy[1376]: I0120 20:58:11.499601 00001 vxlan.go:269] AddL3 succeeded
Jan 20 20:58:31 coreos1 sdnotify-proxy[1376]: I0120 20:58:31.676323 00001 vxlan.go:237] Ignoring not a miss: 06:32:53:65:0f:9a, 10.1.61.2
Jan 20 20:58:39 coreos1 sdnotify-proxy[1376]: I0120 20:58:39.834131 00001 vxlan.go:237] Ignoring not a miss: 06:32:53:65:0f:9a, 10.1.61.2
Jan 20 20:58:40 coreos1 sdnotify-proxy[1376]: I0120 20:58:40.836138 00001 vxlan.go:237] Ignoring not a miss: 06:32:53:65:0f:9a, 10.1.61.2
Jan 20 20:58:41 coreos1 sdnotify-proxy[1376]: I0120 20:58:41.838137 00001 vxlan.go:237] Ignoring not a miss: 06:32:53:65:0f:9a, 10.1.61.2
```

`etcdctl get /coreos.com/network/config`:
```json
{
  "Network": "10.1.0.0/16",
  "SubnetLen": 30,
  "Backend": {
    "Type": "vxlan",
    "VNI": 1
  }
}
```

**Comment by eyakubovich** [comment]
@jpmx With a /30, there's only 1 IP for container (4 total -- one for flannel.1, one for docker0, and broadcast). It should still theoretically work but I wonder if it's an off by one bug. Are you able to widen the SubnetLen to 24 and see if it persists?

**Comment by jpmx** [comment]
Hi @eyakubovich - same result with /24

```
64 bytes from 10.1.61.2: icmp_seq=383 ttl=62 time=0.298 ms
64 bytes from 10.1.61.2: icmp_seq=383 ttl=62 time=2.24 ms (DUP!)
64 bytes from 10.1.61.2: icmp_seq=384 ttl=62 time=0.275 ms
64 bytes from 10.1.61.2: icmp_seq=384 ttl=62 time=2.41 ms (DUP!)
64 bytes from 10.1.61.2: icmp_seq=385 ttl=62 time=0.284 ms
64 bytes from 10.1.61.2: icmp_seq=385 ttl=62 time=2.19 ms (DUP!)
64 bytes from 10.1.61.2: icmp_seq=386 ttl=62 time=0.292 ms
```

The containers are in different hosts connected in the same LAN via a bonded interface (bond1)

```
[root@coreos1 ~]# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP mode DEFAULT qlen 1000
    link/ether 00:25:90:ad:3d:f5 brd ff:ff:ff:ff:ff:ff
3: eth1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP mode DEFAULT qlen 1000
    link/ether 00:25:90:ad:3d:f5 brd ff:ff:ff:ff:ff:ff
4: eth2: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT qlen 1000
    link/ether 00:25:90:ad:3d:f7 brd ff:ff:ff:ff:ff:ff
5: eth3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond1 state UP mode DEFAULT qlen 1000
    link/ether 00:25:90:ad:3d:f7 brd ff:ff:ff:ff:ff:ff
8: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 00:25:90:ad:3d:f5 brd ff:ff:ff:ff:ff:ff
9: bond1: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT
    link/ether 00:25:90:ad:3d:f7 brd ff:ff:ff:ff:ff:ff
10: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT
    link/ether 96:04:30:fa:3c:af brd ff:ff:ff:ff:ff:ff
11: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
13: veth09cce8a: <BROADCAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master docker0 state UP mode DEFAULT
    link/ether ae:8d:37:3f:eb:a6 brd ff:ff:ff:ff:ff:ff
```

**Comment by jpmx** [comment]
I disabled the `bond1` interface on both hosts and the duplicate packages still appears

**Comment by eyakubovich** [comment]
@jpmx I ran it on AWS (there's a single interface there, of course) and no dups. So let's try to understand what causes this in your setup. Without bonding, can you please print your routing table (`ip route`). Also, just to make sure it is flannel related, it is OK with just pinging real interface (e.g. eth0) on the host, correct? Can you also ping flannel.1 interface outside of container.

**Comment by jpmx** [comment]
I have this setup, public: `bond0 = eth0 + eth1` - private: `eth2` (`bond1` and `eth3` are disabled)

Tested `host-to-host` no dups, `container-to-container` dups found, `flannel.1-to-flannel.1` dups found

![screen shot 2015-01-21 at 1 14 34 am](https://cloud.githubusercontent.com/assets/746067/5832440/f065b12a-a10a-11e4-97fc-a311bb01e540.png)

**Comment by eyakubovich** [comment]
@jpmx By default, flannel uses the interface associated with a default route (`bond0` in your case). It can be overridden with `--iface` cmd line parameter or `interface` option in flannel section of cloud-config. I'm not sure if you're already overriding it. If not, can we run two more tests, please. First, ping each host via their public IP to check for dups. Second, reconfigure flannel to use your private interface (without the bond) and see if the dups continue.

**Comment by jpmx** [comment]
@eyakubovich I had the default flannel settings and when using `interface: bond1` the DUPs between containers, flannel interface and private IP disappears but I keep seeing DUPs on public interface (bond0)

### with default flannel settings (see windows titles for details)
![screen shot 2015-01-21 at 2 49 42 pm](https://cloud.githubusercontent.com/assets/746067/5845073/b7d846b4-a17e-11e4-9f3f-6f9413d5cf31.png)

### with `interface: bond1` on flannel settings (see windows titles for details)
![screen shot 2015-01-21 at 3 02 32 pm](https://cloud.githubusercontent.com/assets/746067/5845079/c2271faa-a17e-11e4-8821-c77f26c558e9.png)

**Comment by eyakubovich** [comment]
@jpmx so it looks like it's not a flannel issue but a bonding issue (maybe CoreOS specific, maybe hardware). I'm filing a generic CoreOS bug.

**Comment by jpmx** [comment]
@eyakubovich as you suggested, my ISP just confirmed to me that this is a switch-specific problem and they are investigating with the manufacturer

Thanks for your help!
