### ISSUE TITLE
why does the flannel based docker container can't access the outside world

### ISSUE THREAD

**Issue by WIZARD-CXY** [coreos/flannel#115]
Hello guys~
       I uses the flannel to build a overlay network for my kubernetes cluster, and I am wondering why the container can't access the outside world, for example ,ping 8.8.8.8 never succeeded, it can only access the overlay network.
      I enabled the ip_forward , iptables and routing table settings seems all ok and flannel uses udp mode. So I want to know the reason, Thanks in advance!

**Comment by eyakubovich** [comment]
@WIZARD-CXY Are you running this in a public cloud? If you can ping 8.8.8.8 outside of a container but not inside, can you check that you have IP Masquerading rule turned on: `sudo iptables -t nat -L -n`. This rule is usually installed by Docker daemon.

**Comment by WIZARD-CXY** [comment]
No, I am using flannel in my lab ,a private network. the host that docker containers on can ping 8.8.8.8.
The output of your suggested command is
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  10.0.52.0/24         0.0.0.0/0           
MASQUERADE  all  --  10.1.0.0/16          0.0.0.0/0           
MASQUERADE  all  --  10.1.0.0/16          0.0.0.0/0           
MASQUERADE  all  --  10.2.0.0/16          0.0.0.0/0

but the flannel0 has ip 10.0.20.0, is it the source of error?
And After I run command `sudo iptables -t nat -A POSTROUTING -o flannel0 -j MASQUERADE` or `sudo iptables -t nat -A POSTROUTING -o docker0 -j MASQUERADE` .The problem also exists.

**Comment by eyakubovich** [comment]
@WIZARD-CXY This looks odd. If your Docker bridge is on 10.0.20.0/24 network (docker0 should have IP 10.0.20.1), there should be a rule for masquerading traffic from 10.0.20.0/24. However, there's usually a separate DOCKER chain with few entries. What version of Docker are you running? And can you also paste the command line that's passed to start docker daemon.

**Comment by WIZARD-CXY** [comment]
The configuration passed to docker daemon is 
DOCKER_OPTS="--insecure-registry 10.10.103.215:5000 -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock --bip=10.0.20.1/24 --mtu=1472"
docker version is  1.3.2 which is not very old.

**Comment by eyakubovich** [comment]
@WIZARD-CXY DOCKER_OPTS look good and Docker 1.3.2 is also fine. Your POSTROUTING chain in nat table should look like:

```
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  10.0.20.0/24        0.0.0.0/0           
```

I really don't know what maybe causing this. Can you stop docker, clear out the nat table (`iptables -t nat -F`) and start docker again. Maybe also delete the bridge after you stop docker (`ip link del docker0`)

**Comment by WIZARD-CXY** [comment]
It is the masqurade error, I reflush the nat table with `iptables -t nat -F` and restart docker and the container can access the outside world.
I think maybe it is because docker may not update the iptables DOCKER chain detail until docker find there is no existence of this chain .
Thank you
