### ISSUE TITLE
kubectl apply -f kube-flannel.yml failed

### ISSUE THREAD

**Issue by MarioZuo** [coreos/flannel#1163]
After I install and configure k8s, I try to configure flannel. I use cmd:
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml
But it warned: Error from server (NotFound): the server could not find the requested resource
I also try to wget the yml. Then kubectl apply -f kube-flannel.yml. but the same issue happened.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Here is the error log when I run kubectl apply -f ./kube-flannel.yml -v=8
I0719 10:59:06.160018    6406 loader.go:357] Config loaded from file /etc/kubernetes/admin.conf
I0719 10:59:06.162286    6406 round_trippers.go:415] GET https://10.10.18.127:6443/swagger-2.0.0.pb-v1
I0719 10:59:06.162314    6406 round_trippers.go:422] Request Headers:
I0719 10:59:06.162325    6406 round_trippers.go:425]     Accept: application/json, */*
I0719 10:59:06.162336    6406 round_trippers.go:425]     User-Agent: kubectl/v1.9.11 (linux/amd64) kubernetes/1bfeeb6
I0719 10:59:06.173359    6406 round_trippers.go:440] Response Status: 404 Not Found in 11 milliseconds
I0719 10:59:06.173391    6406 round_trippers.go:443] Response Headers:
I0719 10:59:06.173402    6406 round_trippers.go:446]     Date: Fri, 19 Jul 2019 02:59:06 GMT
I0719 10:59:06.173412    6406 round_trippers.go:446]     Content-Type: application/json
I0719 10:59:06.173421    6406 round_trippers.go:446]     Content-Length: 487
I0719 10:59:06.174485    6406 request.go:873] Response Body: {
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/healthz",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/crd-informer-synced",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/metrics",
    "/openapi/v2",
    "/version"
  ]
}
I0719 10:59:06.175596    6406 helpers.go:201] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse",
        "message": "unknown"
      }
    ]
  },
  "code": 404
}]
F0719 10:59:06.175665    6406 helpers.go:119] Error from server (NotFound): the server could not find the requested resource

As I checked, firewalld and selinux are both disabled.
## Your Environment

* Flannel version:
https://raw.githubusercontent.com/coreos/flannel/62e44c867a2846fefb68bd5f178daf4da3095ccb/Documentation/kube-flannel.yml
* Backend used (e.g. vxlan or udp):
* Etcd version:
etcd:3.3.10
* Kubernetes version (if used):
v1.15.0
* Operating System and version:
3.10.0-957.el7.x86_64
* Link to your project (optional):

**Comment by git006** [comment]
we cannot pull it from china too.

**Comment by MarioZuo** [comment]
> 
> 
> we cannot pull it from china too.

Then what should I do?  ^o^?

**Comment by arasananbu** [comment]
Could you please try git cloning the repo and apply the yml file locally.

curl(raw content) would have been blocked for any reason. GIt might work.

**Comment by rajatchopra** [comment]
Closing based on suggestion in [this comment](https://github.com/coreos/flannel/issues/1163#issuecomment-536026600). Please re-open if issue is still unresolved.
