### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by 15838028035** [coreos/flannel#1190]
![图片](https://user-images.githubusercontent.com/12193885/65649467-3a74c680-e039-11e9-9c7e-18cd62824358.png)

**Comment by eddiesimeon** [comment]
there is a PR to fix this issue: 
https://github.com/coreos/flannel/pull/1174 

we are waiting for a maintainer to merge in the PR

Use the following kube-flannel.yml file in the mean time to fix your issue:
https://github.com/coreos/flannel/blob/701c2e8749714022758d5360fbe627005901349c/Documentation/kube-flannel.yml

**Comment by arasananbu** [comment]
#1174 merged.
Closing the issue
