### ISSUE TITLE
Where I can get docker image  of flannel other than quay.io/repository/coreos/flannel

### ISSUE THREAD

**Issue by oneslideicywater** [coreos/flannel#1223]
It's a improvement feedback, I am at the right place to question?
## Expected Behavior
I use `kubectl apply -f url_to_flannel.yml` and failed. After troubleshooting,It 's my network reason,
I can't fetch image from `quay.io/repository/coreos/flannel`, And I found your releases page:
`https://github.com/coreos/flannel/releases` ,I can't tag it `.docker` file to `quay.io/coreos/flannel:v0.11.0-amd64`  because it has no tag.

So any alternatives to fetch the flannel images?

**Comment by oneslideicywater** [comment]
```bash
wget https://github.com/coreos/flannel/releases/download/v0.11.0/flanneld-v0.11.0-amd64.docker
```
and what can I do with this file to tag it as kubernetes request?
```
[root@localhost ~]# journalctl -fu kubelet
-- Logs begin at Sun 2019-11-10 14:25:12 EST. --
Nov 11 20:38:42 k8s-master kubelet[27869]: E1111 20:38:42.896019   27869 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Nov 11 20:38:46 k8s-master kubelet[27869]: W1111 20:38:46.496271   27869 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Nov 11 20:38:47 k8s-master kubelet[27869]: E1111 20:38:47.897181   27869 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Nov 11 20:38:48 k8s-master kubelet[27869]: E1111 20:38:48.199334   27869 pod_workers.go:191] Error syncing pod 0a620b01-49cd-498f-8f3f-70a6ed042484 ("kube-flannel-ds-amd64-lkclv_kube-system(0a620b01-49cd-498f-8f3f-70a6ed042484)"), skipping: failed to "StartContainer" for "install-cni" with ImagePullBackOff: "Back-off pulling image \"quay.io/coreos/flannel:v0.11.0-amd64\""
Nov 11 20:38:51 k8s-master kubelet[27869]: W1111 20:38:51.496883   27869 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Nov 11 20:38:52 k8s-master kubelet[27869]: E1111 20:38:52.899501   27869 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Nov 11 20:38:56 k8s-master kubelet[27869]: W1111 20:38:56.497534   27869 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
Nov 11 20:38:57 k8s-master kubelet[27869]: E1111 20:38:57.903069   27869 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Nov 11 20:39:01 k8s-master kubelet[27869]: E1111 20:39:01.200085   27869 pod_workers.go:191] Error syncing pod 0a620b01-49cd-498f-8f3f-70a6ed042484 ("kube-flannel-ds-amd64-lkclv_kube-system(0a620b01-49cd-498f-8f3f-70a6ed042484)"), skipping: failed to "StartContainer" for "install-cni" with ImagePullBackOff: "Back-off pulling image \"quay.io/coreos/flannel:v0.11.0-amd64\""
```

**Comment by oneslideicywater** [comment]
Sorry for my stupid mistake: 
make it using:
```bash
wget https://github.com/coreos/flannel/releases/download/v0.11.0/flanneld-v0.11.0-amd64.docker
docker load < flanneld-v0.11.0-amd64.docker
```

**Comment by valdemarpavesi** [comment]
thanks for your help

`
$ wget https://github.com/coreos/flannel/releases/download/v0.11.0/flanneld-v0.11.0-amd64.docker
docker load < flanneld-v0.11.0-amd64.docker

flanneld-v0.11.0-amd64.docker     100%[============================================================>]  52.82M  60.9MB/s    in 0.9s    

2020-03-26 12:55:09 (60.9 MB/s) - ‘flanneld-v0.11.0-amd64.docker’ saved [55390720/55390720]

root@vcp-tsics-vm1:/tmp# docker load < flanneld-v0.11.0-amd64.docker
7bff100f35cb: Loading layer [==================================================>]  4.672MB/4.672MB
5d3f68f6da8f: Loading layer [==================================================>]  9.526MB/9.526MB
9b48060f404d: Loading layer [==================================================>]  5.912MB/5.912MB
3f3a4ce2b719: Loading layer [==================================================>]  35.25MB/35.25MB
9ce0bb155166: Loading layer [==================================================>]   5.12kB/5.12kB
Loaded image: quay.io/coreos/flannel:v0.11.0-amd64`
