### ISSUE TITLE
557.2.0 - Everything is broken: flanneld failed: "Unable to find image locally" - quay.io/coreos/flannel:0.2.1

### ISSUE THREAD

**Issue by msumme** [coreos/flannel#123]
I'm getting the following with 557.2.0 - since I have a dependency for docker on flanneld as a workaround to them sometimes starting out of order, nothing is working.

I'm getting the following errors:

![image](https://cloud.githubusercontent.com/assets/462931/6052104/8e65f490-ac94-11e4-944b-a845929f3422.png)

Is this simply that an image has not been pushed to the flannel repository?  

Does anybody know a workaround for this?

**Comment by eyakubovich** [comment]
@msumme Thank you for reporting. Was doing tagging in git and quay and got them mixed up for a sec. It's labeled `v0.2.1` instead of `0.2.1` in the registry. Will fix immediately.

**Comment by msumme** [comment]
@eyakubovich Thanks for the quick reply / fix.

**Comment by eyakubovich** [comment]
Fixed.
