### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by benmoss** [coreos/flannel#1231]
It's been about 11 months since the last release, is it possible to cut a new one?

**Comment by tvinhas** [comment]
Why? What specific feature are you looking for?

**Comment by benmoss** [comment]
https://github.com/coreos/flannel/pull/1096 is the feature that's needed

**Comment by pradipd** [comment]
It would be great to get a new release out with this fix.  @dineshgovindasamy as an FYI.

**Comment by balchua** [comment]
I am looking for the `--net-config-path` option.  when is the next release? :) thanks!

**Comment by benmoss** [comment]
@rajatchopra pinging you on this since you seem to be one of the few active maintainers here

**Comment by benmoss** [comment]
Closing since https://github.com/coreos/flannel/releases/tag/v0.12.0 was released
