### ISSUE TITLE
flannel doesn't renew lease on time before the ttl time 

### ISSUE THREAD

**Issue by zkcarterlau** [coreos/flannel#1240]
## Current Behavior
I run flanneld outside of k8s cluster.
One k8s workernode's flannel daemon shutdown automatically after running for 24hours.But other nodes in cluster work fine.
As the flanneld log shows below,flannel started at Dec 27 10:31:09 and it shutdown automatically at Dec 28 10:31:08.It should have renewed the lease at Dec 28 09:31:09(one hour before ttl),but it didn't finally

The question is why it fails to renew lease and the flannel logs show nothing about it.

##flanneld logs

> Dec 27 10:31:09 000234k8sqaprod flanneld[9367]: I1227 10:31:09.098062    9367 iptables.go:167] Deleting iptables rule: ! -s 0.0.0.0/0 -d 0.0.0.0/0
Dec 27 10:31:09 000234k8sqaprod flanneld[9367]: I1227 10:31:09.105981    9367 main.go:317] Wrote subnet file to /run/flannel/subnet.env
Dec 27 10:31:09 000234k8sqaprod flanneld[9367]: I1227 10:31:09.106054    9367 main.go:321] Running backend.
Dec 27 10:31:09 000234k8sqaprod flanneld[9367]: I1227 10:31:09.106335    9367 vxlan_network.go:60] watching for new subnet leases
Dec 27 10:31:09 000234k8sqaprod flanneld[9367]: I1227 10:31:09.134511    9367 main.go:429] Waiting for 23h0m7.299005107s to renew lease
Dec 27 10:31:09 000234k8sqaprod systemd[1]: Started Flanneld overlay address etcd agent.
Dec 28 10:31:08 000234k8sqaprod flanneld[9367]: E1228 10:31:08.378118    9367 main.go:432] Lease has been revoked. Shutting down daemon.
Dec 28 10:31:08 000234k8sqaprod flanneld[9367]: I1228 10:31:08.378234    9367 main.go:366] Stopping shutdownHandler...
Dec 28 10:31:08 000234k8sqaprod flanneld[9367]: I1228 10:31:08.378269    9367 main.go:339] Waiting for all goroutines to exit
Dec 28 10:31:08 000234k8sqaprod flanneld[9367]: I1228 10:31:08.379970    9367 main.go:342] Exiting cleanly...

## Your Environment

* Flannel version: 0.10(not in k8s cluster)
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.3.13
* Kubernetes version (if used): 1.15
* Operating System and version: Linux 3.10.0-957.21.3.el7.x86_64
* Link to your project (optional):

**Comment by Lincoln-dac** [comment]
you can use command check  subnet read ttl key like this 
etcdctl ls /coreos.com/network/subnets            
/coreos.com/network/subnets/10.5.34.0-24
$ etcdctl -o extended get /coreos.com/network/subnets/10.5.34.0-24
Key: /coreos.com/network/subnets/10.5.34.0-24
Created-Index: 5
Modified-Index: 5
TTL: 85925
Index: 6

{"PublicIP":"10.37.7.195","BackendType":"vxlan","BackendData":{"VtepMAC":"82:4b:b6:2f:54:4e"}}
