### ISSUE TITLE
Watch of subnet leases failed because etcd index outside history window

### ISSUE THREAD

**Issue by josselin-c** [coreos/flannel#125]
Hello,
I'm using kubernetes + flannel on a test cluster of two machines.
At first everything is fine but after a while kubernetes has problem scheduling new pods and I get "Failed to find an IP for pod foo/bar-xabf" in the logs.
This seems to always appear after flannel throws a warning about etcd:

```
Feb 09 15:14:53 b7.dev.g8teway.com systemd[1]: Started flanneld.service.
Feb 09 15:14:53 b7.dev.g8teway.com flanneld[7224]: I0209 15:14:53.453729 07224 main.go:261] Installing signal handlers
Feb 09 15:14:53 b7.dev.g8teway.com flanneld[7224]: I0209 15:14:53.453980 07224 main.go:211] Using 176.31.105.64 as external interface
Feb 09 15:14:53 b7.dev.g8teway.com flanneld[7224]: I0209 15:14:53.540713 07224 subnet.go:83] Subnet lease acquired: 10.244.34.0/24
Feb 09 15:14:53 b7.dev.g8teway.com flanneld[7224]: I0209 15:14:53.542971 07224 ipmasq.go:33] Adding iptables rule: FLANNEL -d 10.244.0.0/16 -j ACCEPT
Feb 09 15:14:53 b7.dev.g8teway.com flanneld[7224]: I0209 15:14:53.545806 07224 ipmasq.go:33] Adding iptables rule: FLANNEL ! -d 224.0.0.0/4 -j MASQUERADE
Feb 09 15:14:53 b7.dev.g8teway.com flanneld[7224]: I0209 15:14:53.547660 07224 ipmasq.go:33] Adding iptables rule: POSTROUTING -s 10.244.0.0/16 -j FLANNEL
Feb 09 15:14:53 b7.dev.g8teway.com flanneld[7224]: I0209 15:14:53.549133 07224 main.go:228] UDP mode initialized
Feb 09 15:14:53 b7.dev.g8teway.com flanneld[7224]: I0209 15:14:53.549159 07224 udp.go:198] Watching for new subnet leases
Feb 09 15:14:53 b7.dev.g8teway.com flanneld[7224]: I0209 15:14:53.549340 07224 udp.go:223] Subnet added: 10.244.11.0/24
Feb 09 17:39:53 b7.dev.g8teway.com flanneld[7224]: W0209 17:39:53.562142 07224 subnet.go:410] Watch of subnet leases failed because etcd index outside history window
Feb 09 17:39:53 b7.dev.g8teway.com flanneld[7224]: I0209 17:39:53.562497 07224 udp.go:228] Subnet removed: 10.244.34.0/24
```

```
[root@b7 ~]# flanneld --version
0.2.1+git
```
Compiled from 8fe5bfa93eabee4ba5ce5e72b070c09d794b7620

**Comment by eyakubovich** [comment]
@josselin-c That warning reflects that flannel fell behind, trying to monitor etcd's stream of events. That can be because etcd had a flurry of activity or some other delay. flannel recovers by doing a complete snapshot. By itself, it's harmless and it doesn't effect its operation. I'm not familiar with k8s code (/cc @kelseyhightower can you help?) but I suspect that the common link here is busy etcd. I'm not sure if it was k8s that caused the activity in the first place or some external factor.

**Comment by josselin-c** [comment]
Indeed, looking at my etcd (0.4.6) logs I get lines like ```warning: heartbeat time out peer="b8" missed=1 backoff="2s"```. According to coreos/etcd#975 it might be because I have a lot of keys stored.
It appears k8s is creating a lot of 'events' entries (I have 12k) when some pods are failing. Theses events take time to snapshot. I'll try to update to etcd 2.0 see if things improve.

@eyakubovich Is it normal I get ```Subnet removed: 10.244.XX.0/24``` when the watch fails?

**Comment by eyakubovich** [comment]
@josselin-c It's normal. It's actually a bug that I need to address but it's harmless -- just an extra line get printed. The subnet you see is "your own" so it's a noop to remove it from yourself.

**Comment by josselin-c** [comment]
Okay well, for now I identified and fixed the k8s problem which created a lot of events. Thanks for your help!
