### ISSUE TITLE
DNS reosultion not working Kubernetes

### ISSUE THREAD

**Issue by cogni-manik** [coreos/flannel#1252]
Kubernetes not able to resolve DNS. Container/Pods not able to access Internet. 

I have a Kubernetes 2 node cluster on separate AWS EC2 instances (t2.Medium) container networking has been done using. 
Flannel version: flannel:v0.10.0-amd64 (image)
Kubernetes version: 1.15.3 

DNS Logs
![Screenshot from 2020-02-10 10-44-11](https://user-images.githubusercontent.com/60781535/74122798-6b255900-4bf2-11ea-80b9-416917ccf032.png)

Nodes
![Screenshot from 2020-02-10 10-38-06](https://user-images.githubusercontent.com/60781535/74122499-86439900-4bf1-11ea-9ef2-48fc3938bca9.png)

Kubernetes svc:
![Screenshot from 2020-02-10 10-45-56](https://user-images.githubusercontent.com/60781535/74122826-8b551800-4bf2-11ea-8b8b-145010fde493.png)

![Screenshot from 2020-02-10 10-47-52](https://user-images.githubusercontent.com/60781535/74122894-d2430d80-4bf2-11ea-8b51-b13c8a92197a.png)

![Screenshot from 2020-02-10 10-46-49](https://user-images.githubusercontent.com/60781535/74122868-af185e00-4bf2-11ea-9bee-bd95bb49e28d.png)

At times when I delete core-dns pods, the DNS issue gets resolved for some time but it is not consistant. Please suggest what can be done. I flannel mapping may have something to do with this. Please let me know if any other information is also needed.

**Comment by rajatchopra** [comment]
Flannel has less to do with DNS resolution. If internet can be reached from the host with an IP address, and you cannot reach that IP address (not DNS host, but IP address) from inside the container then it is flannel's responsibility.

You should check your core-dns pod health and configuration.
Also check the kubelet DNS settings.
Does the host have a misleading DNS nameserver?
