### ISSUE TITLE
Flannel cni0 interface conflict with subnet gateway

### ISSUE THREAD

**Issue by reno138** [coreos/flannel#1258]
When creating a default install of flannel, it created a the cni0 interface with the same IP as the subnet gateway.

Side note - this is in no way an issue with this software - this is an issue with user knowledge (me being the user). I don't understand why it would default to this IP on the cni0 interface. 

## Expected Behavior
I really don't know as I'm terribly new to all this and trying to learn

## Current Behavior
Stopping subnet traffic egress due to ip address conflict with the default gateway

## Possible Solution
This is exactly why I'm here. I can see a lot of "how to set up" and "this is what these do" but I'm either missing how to reconfigure it, or it's flying far above my head

## Context
Just following some guides online and trying to learn about docker/kubernetes/etc and installed flannel as the doc suggested. Trying to get a basic config spun up to I can start learning about management and deployment. But, a working example on my little test esxi box would be great to start with. 

## Your Environment
ESXi host - Ubuntu 19.10 - all related machines on a single subnet/flat network. 

I know this is a really basic question, but I didn't want to just go changing things since I'm getting close (as far as I can tell) to having a "working" environment. Thanks in advance for helping out an old IT dog trying to learn new tricks. If there is some documentation that assumes I crawled out of a womb yesterday, please point me in that direction. 

Thanks-

**Comment by rajatchopra** [comment]
When you choose flannel, you also choose the subnet to use. See this line: https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml#L128

Two things:
 - You should change this some local unused overlay subnet scheme that isn't used on your host network.
 - This will also require that you run kubernetes with the newly chosen subnet, a mismatch in kube arguments and flannel's network CIDR will also result in broken networking.
