### ISSUE TITLE
flannel falling behind etcd causes spurious message

### ISSUE THREAD

**Issue by eyakubovich** [coreos/flannel#126]
```
eb 09 17:39:53 b7.dev.g8teway.com flanneld[7224]: W0209 17:39:53.562142 07224 subnet.go:410] Watch of subnet leases failed because etcd index outside history window
Feb 09 17:39:53 b7.dev.g8teway.com flanneld[7224]: I0209 17:39:53.562497 07224 udp.go:228] Subnet removed: 10.244.34.0/24
```

Subnet removed refers to its own subnet and this should be handled properly as to not print that line.

**Comment by philipphug** [comment]
I have the same issue and it often results in losing connectivity between the hosts. I need to restart flanneld to restore connectivity again.

**Comment by eyakubovich** [comment]
@philipphug I was not aware of this issue causing connectivity loss. This is with default "udp" backend, correct? Does this cause you to lose connectivity between all hosts or just some?

**Comment by lemenkov** [comment]
I personally sometimes see this message ("Watch of subnet leases failed because etcd index outside history window") as well. But so far it never resulted in a connectivity issues. I'm using "UDP" backend if it matters.

**Comment by philipphug** [comment]
The problem I experienced was that the subnet entries (/coreos.com/network/subnets/XXXX-24) were overwritten with an empty value for some reason which then caused the connectivity issues.
This happened mostly when there was too much load on the etcd machines which caused timeouts and leader elections.

**Comment by eyakubovich** [comment]
Is this still an issue? Needs confirmation.

**Comment by eyakubovich** [comment]
Should be fixed by https://github.com/coreos/flannel/pull/286
