### ISSUE TITLE
failed to open TUN device: open /dev/net/tun: no such file or directory

### ISSUE THREAD

**Issue by ShixiongQi** [coreos/flannel#1267]
When I try to run the flannel in UDP backend, the daemonset generated such error,

E0314 07:34:42.567235       1 main.go:289] Error registering network: failed to open TUN device: open /dev/net/tun: no such file or directory

I try to use "cat  /dev/net/tun" and the output is 

cat: /dev/net/tun: File descriptor in bad state

So the tun seems to be working properly. I think the problem could be in the pod security settings in flannel daemonset. Is there any hint on how to setting the privilege of the flannel daemonset container?

## Possible Solution

 I think the possible solution is to set the privilege of the flannel daemonset container as the root user so it can access the /dev/net/tun

## Steps to Reproduce (for bugs)

1. use kubeadm to init a 2-node k8s cluster with pod_cidr = 10.244.0.0/16
2. change the flannel backend to udp mode (in kube-flannel.yaml)
3. apply the yaml file

## Your Environment

* Flannel version: v0.11.0
* Backend used (e.g. vxlan or udp): udp
* Etcd version: use k8s api instead
* Kubernetes version (if used): 1.17
* Operating System and version: ubuntu 16.04
* Link to your project (optional):

**Comment by jiangshan-baishan** [comment]
+1, same issue

**Comment by ShixiongQi** [comment]
> +1, same issue

change the setting of daemonset to this
        **securityContext:
          privileged: true**

**Comment by jiangshan-baishan** [comment]
> > +1, same issue
> 
> change the setting of daemonset to this
> **securityContext: privileged: true**

thx

**Comment by hakman** [comment]
@rajatchopra I bumped into the same issue myself when trying to upgrade the Kops manifest to 0.13.0. Would mounting `/dev/net` be suitable solution?
https://github.com/kubernetes/kops/pull/10064/commits/ad58111178fe7f03c5d75b6b1130650d8ad0ac44
