### ISSUE TITLE
Failed to create/clear FLANNEL chain in NAT table: exit status 3

### ISSUE THREAD

**Issue by kaixi** [coreos/flannel#129]
I've followed the instructions in https://coreos.com/docs/cluster-management/setup/flannel-config/ 
and since v591.0.0 the flanneld service fails with the following error:

    Failed to create/clear FLANNEL chain in NAT table: exit status 3

**Comment by rimusz** [comment]
I'm getting the same error on v593.0.0 too

**Comment by eyakubovich** [comment]
@kaixi @rimusz We're looking into this.
