### ISSUE TITLE
Flannel interface remains in "configuring" state and network-online.target is never reached.

### ISSUE THREAD

**Issue by erimatnor** [coreos/flannel#132]
I am trying to run Flannel via cloud-config, using the provided flanneld.service systemd unit that comes bundled with CoreOS stable (557.2.0). The Flannel container is successfully pulled and the flannel.1 interface comes up. However, the interface is left in a "configuring" state, as reported by networkctl. This means that network-online.target is never reached and prohibits any services dependent on this target from running. It seems that systemd/networkd is trying to configure the Flannel interface with DHCP, using the default .network file. Adding the following unit file solves the problem:

    - name: flannel.network
      command: start
      content: |
        [Match]
        Name=flannel.1

        [Network]
        DHCP=no

**Comment by eyakubovich** [comment]
@erimatnor Thank you for reporting. I bet we haven't run into this due to a race -- if flannel takes a bit to startup, network-online.target gets hit first.
