### ISSUE TITLE
Support env vars like FLANNEL_ETCD_ENDPOINTS

### ISSUE THREAD

**Issue by psi-4ward** [coreos/flannel#133]
Im missing the ability to set `-etcd-endpoints` `-etcd-cafile` `-etcd-certfile` and `-etcd-keyfile` via Environment variables (systemd drop in) like fleet and etcd

**Comment by eyakubovich** [comment]
@psi-4ward you should be able to set FLANNELD_ETCD_ENDPOINTS, FLANNELD_ETCD_CAFILE and FLANNELD_ETCD_KEYFILE env vars. If you're using CoreOS and cloud-config, you should be able to set them in coreos.flannel section: https://coreos.com/docs/cluster-management/setup/cloudinit-cloud-config/#configuration-parameters

Let me know if it doesn't work for you.

**Comment by psi-4ward** [comment]
Nice! But theres one more question. 
The ca, cert and key files resists in a directory on the host. As far as i can see flannel gets started using the `quay.io/coreos/flannel` container. Cant imagine how the container can access the files? Currently i inject the folder as volume but i dont see a way how the coreos builtin flannel service can do that using the systemd drop in.

**Comment by eyakubovich** [comment]
@psi-4ward you're right! This is a big oversight on our end. We will address that but for now you can work around it by copying those files (e.g. in ExecStartPre via dropin) into `/run/flannel` since that gets pulled into container.

**Comment by eyakubovich** [comment]
Fixed in https://github.com/coreos/coreos-overlay/pull/1126
