### ISSUE TITLE
Flannel stops working on openstack 

### ISSUE THREAD

**Issue by sramak1396c** [coreos/flannel#134]
Container IP's fails to respond to ping or wget.

- openstack environment
- running coreos
- 2 interfaces , 1 private on 192.168.1.*
- flannel running on private interface , explicitly , using iface parameter
- Source , routing table
kube-master kubernetes # netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         *.*.*.1   0.0.0.0         UG        0 0          0 eth1
0.0.0.0         192.168.1.1     0.0.0.0         UG        0 0          0 eth0
10.244.0.0      0.0.0.0         255.255.0.0     U         0 0          0 flannel.1
96.*.*.0    0.0.0.0         255.255.254.0   U         0 0          0 eth1
96.*.*.1    0.0.0.0         255.255.255.255 UH        0 0          0 eth1
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
192.168.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth0

- destination routing table
kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3 core # netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         96.*.*.1    0.0.0.0         UG        0 0          0 eth1
0.0.0.0         192.168.1.1     0.0.0.0         UG        0 0          0 eth0
10.244.0.0      0.0.0.0         255.255.0.0     U         0 0          0 flannel.1
10.244.23.0     0.0.0.0         255.255.255.0   U         0 0          0 docker0
96.*.*.0    0.0.0.0         255.255.254.0   U         0 0          0 eth1
96.*.*.1    0.0.0.0         255.255.255.255 UH        0 0          0 eth1
192.168.1.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
192.168.1.1     0.0.0.0         255.255.255.255 UH        0 0          0 eth0
- wget works from the local machine

- snippet of flannel logs from source
Mar 01 23:01:04 kube-master.novalocal flanneld[637]: I0301 23:01:04.454272 00637 vxlan.go:264] L3 miss: 10.244.23.3
Mar 01 23:01:04 kube-master.novalocal flanneld[637]: I0301 23:01:04.454354 00637 device.go:228] calling NeighSet: 10.244.23.3, 9a:db:bb:0a:8e:66
Mar 01 23:01:04 kube-master.novalocal flanneld[637]: I0301 23:01:04.454478 00637 vxlan.go:275] AddL3 succeeded
Mar 01 23:01:36 kube-master.novalocal flanneld[637]: I0301 23:01:36.397462 00637 vxlan.go:243] Ignoring not a miss: 9a:db:bb:0a:8e:66, 10.244.23.3
Mar 01 23:02:15 kube-master.novalocal flanneld[637]: I0301 23:02:15.579497 00637 vxlan.go:243] Ignoring not a miss: 9a:db:bb:0a:8e:66, 10.244.23.3
Mar 01 23:02:16 kube-master.novalocal flanneld[637]: I0301 23:02:16.581483 00637 vxlan.go:243] Ignoring not a miss: 9a:db:bb:0a:8e:66, 10.244.23.3
Mar 01 23:02:17 kube-master.novalocal flanneld[637]: I0301 23:02:17.583534 00637 vxlan.go:243] Ignoring not a miss: 9a:db:bb:0a:8e:66, 10.244.23.3
Mar 01 23:02:19 kube-master.novalocal flanneld[637]: I0301 23:02:19.941107 00637 vxlan.go:264] L3 miss: 10.244.23.3
Mar 01 23:02:19 kube-master.novalocal flanneld[637]: I0301 23:02:19.941187 00637 device.go:228] calling NeighSet: 10.244.23.3, 9a:db:bb:0a:8e:66
Mar 01 23:02:19 kube-master.novalocal flanneld[637]: I0301 23:02:19.941312 00637 vxlan.go:275] AddL3 succeeded
- snippet of flannel logs from target
Mar 01 23:01:51 kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3.novalocal flanneld[626]: I0301 23:01:51.658123 00626 device.go:228] calling NeighSet: 10.244.78.0, 12:00:66:fe:e3:ee
Mar 01 23:01:51 kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3.novalocal flanneld[626]: I0301 23:01:51.658420 00626 vxlan.go:275] AddL3 succeeded
Mar 01 23:02:15 kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3.novalocal flanneld[626]: I0301 23:02:15.960275 00626 vxlan.go:243] Ignoring not a miss: 12:00:66:fe:e3:ee, 10.244.78.0
Mar 01 23:02:24 kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3.novalocal flanneld[626]: I0301 23:02:24.693849 00626 vxlan.go:243] Ignoring not a miss: 12:00:66:fe:e3:ee, 10.244.78.0
Mar 01 23:02:25 kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3.novalocal flanneld[626]: I0301 23:02:25.695899 00626 vxlan.go:243] Ignoring not a miss: 12:00:66:fe:e3:ee, 10.244.78.0
Mar 01 23:02:26 kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3.novalocal flanneld[626]: I0301 23:02:26.697861 00626 vxlan.go:243] Ignoring not a miss: 12:00:66:fe:e3:ee, 10.244.78.0
Mar 01 23:02:29 kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3.novalocal flanneld[626]: I0301 23:02:29.057893 00626 vxlan.go:264] L3 miss: 10.244.78.0
Mar 01 23:02:29 kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3.novalocal flanneld[626]: I0301 23:02:29.057994 00626 device.go:228] calling NeighSet: 10.244.78.0, 12:00:66:fe:e3:ee
Mar 01 23:02:29 kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3.novalocal flanneld[626]: I0301 23:02:29.058216 00626 vxlan.go:275] AddL3 succeeded
Mar 01 23:02:53 kube-slave-45014c55-c671-407f-b3c8-1430ffd33dc3.novalocal flanneld[626]: I0301 23:02:53.400128 00626 vxlan.go:243] Ignoring not a miss: 12:00:66:fe:e3:ee, 10.244.78.

Running out of ideas , appreciate any help.

Thanks

**Comment by eyakubovich** [comment]
@sramak1396c everything i see look ok. I do see that source doesn't have docker0 but that shouldn't matter. Can you please also dump `ip addr` on both source and target -- I want to check that the MACs line up with the logs.

Next step would be to use `toolbox` and run `tcpdump`. Keep pinging target.
First look at source's `flannel.1`:
`$ sudo toolbox /sbin/tcpdump -i flannel.1 icmp`
Then source's `eth0`:
`$ sudo toolbox /sbin/tcpdump -i eth0 udp port 8472`

If you see requests going out on both but not coming back, look on target's `eth0` and `flannel.1`.

Let me know your findings.

**Comment by sramak1396c** [comment]
I don't see requests going out on flannel.1 or eth0.

More findings.

container ping works between minions
master to container ping not working

In minions, there veth interface attached to docker0 , which is missing in master. Not sure if that's a cause.

minion :  ip addr output

kube-slave-b54f5624-9640-4546-bd91-48f6ab459abc core # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP qlen 1000
    link/ether fa:16:3e:1a:cc:f5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.7/24 brd 192.168.1.255 scope global dynamic eth0
       valid_lft 83sec preferred_lft 83sec
    inet6 fe80::f816:3eff:fe1a:ccf5/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP qlen 1000
    link/ether fa:16:3e:f1:15:96 brd ff:ff:ff:ff:ff:ff
    inet 96.119.144.215/23 brd 96.119.145.255 scope global dynamic eth1
       valid_lft 110sec preferred_lft 110sec
    inet6 2001:558:fc0e:0:f816:3eff:fef1:1596/64 scope global dynamic
       valid_lft 2591883sec preferred_lft 604683sec
    inet6 fe80::f816:3eff:fef1:1596/64 scope link
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN
    link/ether ca:28:0c:34:26:e2 brd ff:ff:ff:ff:ff:ff
    inet 10.244.45.0/16 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::c828:cff:fe34:26e2/64 scope link
       valid_lft forever preferred_lft forever
5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 10.244.45.1/24 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5484:7aff:fefe:9799/64 scope link
       valid_lft forever preferred_lft forever
9: veth6365233: <BROADCAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master docker0 state UP
    link/ether be:9f:1f:91:c3:22 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::bc9f:1fff:fe91:c322/64 scope link
       valid_lft forever preferred_lft forever


master: ip addr output




----
output of ip addr
---
kube-master kubernetes # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:1c:fe:e9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.2/24 brd 192.168.1.255 scope global dynamic eth0
       valid_lft 74sec preferred_lft 74sec
    inet6 fe80::f816:3eff:fe1c:fee9/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:29:97:36 brd ff:ff:ff:ff:ff:ff
    inet 96.119.144.198/23 brd 96.119.145.255 scope global dynamic eth1
       valid_lft 76sec preferred_lft 76sec
    inet6 2001:558:fc0e:0:f816:3eff:fe29:9736/64 scope global mngtmpaddr dynamic 
       valid_lft 2591847sec preferred_lft 604647sec
    inet6 fe80::f816:3eff:fe29:9736/64 scope link 
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 8e:61:72:24:5d:9a brd ff:ff:ff:ff:ff:ff
    inet 10.244.78.0/16 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::8c61:72ff:fe24:5d9a/64 scope link 
       valid_lft forever preferred_lft forever
kube-master kubernetes # ps -ef|grep -i flannel
root       639     1  0 20:58 ?        00:00:00 /opt/bin/flanneld --iface=eth0
root      1315   718  0 21:01 pts/0    00:00:00 grep --colour=auto -i flannel

----

**Comment by sramak1396c** [comment]
Sorry , accidently closed this issue. 

Thanks

**Comment by sramak1396c** [comment]
Ping output

kube-master kubernetes # ping 10.244.45.3
PING 10.244.45.3 (10.244.45.3) 56(84) bytes of data.
From 10.244.78.0: icmp_seq=1 Destination Host Unreachable
From 10.244.78.0: icmp_seq=2 Destination Host Unreachable
From 10.244.78.0: icmp_seq=3 Destination Host Unreachable
From 10.244.78.0: icmp_seq=4 Destination Host Unreachable
From 10.244.78.0: icmp_seq=5 Destination Host Unreachable
From 10.244.78.0: icmp_seq=6 Destination Host Unreachable
From 10.244.78.0: icmp_seq=7 Destination Host Unreachable

**Comment by sramak1396c** [comment]
kube-master kubernetes # toolbox
Spawning container root-fedora-latest on /var/lib/toolbox/root-fedora-latest.
Press ^] three times within 1s to kill container.
-bash-4.3# tcpdump -i flannel.1 icmp
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on flannel.1, link-type EN10MB (Ethernet), capture size 262144 bytes

Just hanging , no packets there

**Comment by eyakubovich** [comment]
@sramak1396c btw, did it stop working or this never worked?

**Comment by sramak1396c** [comment]
Worked initially , when I built the cluster. Then it just stopped working.

Let me rebuilt the cluster and see if I can reproduce again.

Thanks

**Comment by sramak1396c** [comment]
Default route 0.0.0.0 on private interface of 192.168.1.0/24 , seems to be the culprit. I rebuilt the cluster , and it's running ok now. 

The issue seems to be specific to coreos and openstack.  I added changes to the cloud-config to remove the default route for private network.

I am going to look into better way to handle in CoreOS , but  workaround on cloud-config fixed it for me now.

Thanks
Sriram

## Changes made to master.yaml

   - name: remove-private-network.service
      command: start
      content: |
        [Unit]
        Description=Remove default Private routing
        Requires=network-online.target
        After=network-online.target

        [Service]
        ExecStart=/usr/bin/route del -net 0.0.0.0 gateway 192.168.1.1
        RemainAfterExit=yes
        Type=oneshot

    - name: setup-network-environment.service
      command: start
      content: |
        [Unit]
        Description=Setup Network Environment
        Documentation=https://github.com/kelseyhightower/setup-network-environment
        Requires=remove-private-network.service
        After=remove-private-network.service

        [Service]
        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
        ExecStartPre=/usr/bin/wget -N -P /opt/bin https://storage.googleapis.com/k8s/setup-network-environment 
        ExecStartPre=/usr/bin/chmod +x /opt/bin/setup-network-environment
        ExecStart=/opt/bin/setup-network-environment
        RemainAfterExit=yes
        Type=oneshot

**Comment by eyakubovich** [comment]
@sramak1396c It'd be interesting to understand why this helps. You had more specific routes for both flannel and private networks so default route shouldn't have been hit.
