### ISSUE TITLE
Pod cann't  access Internet when I use flannel in K8s Cluster

### ISSUE THREAD

**Issue by ZuoGuocai** [coreos/flannel#1373]
I deploy flannel vxlan via  kube-flannel.yml in my k8s cluster. 
A pod connect  B pod working well(These are in different nodes).But  both of pods can not access Internet. 

I search stackoverflow  and find a  solution -- turn off the ipMasq（https://stackoverflow.com/questions/44119425/how-to-turn-off-ip-masquerade-in-flannel）.

So  I update the  kube-flannel.yml and set `"ipMasq": false,`  in sector  cni-conf.json  or sector net-conf.json as below ,
Then I delete  flannel pod and  clean files  like /etc/cni/ , /var/run/flannel/subnet.env  and apply again .But I still find `FLANNEL_IPMASQ=true` when I execute the command `cat /var/run/flannel/subnet.env` 

kube-flannel.yaml

```
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "ipMasq": false,
      "Backend": {
        "Type": "vxlan",
        "VNI": 4096,
        "Port": 4789
      }
    }




```

**Comment by chestack** [comment]
remove command line Opts "--ip-masq"
