### ISSUE TITLE
Containers service discovery using flanneld

### ISSUE THREAD

**Issue by zxcvbn97** [coreos/flannel#138]
Hello, 

I am asking for best practices of discovering services for containers using flannel. 

My current setup is a CoreOS machine with ip 10.1.69.1. It hosts two containers:
- client container runs a client with ip 10.1.69.2
- server container is a web server (nginx) with ip 10.1.69.3
  The three machines can ping each other using flannel overlay network. 

I am trying to setup service discovery so that the client can discover the server IP address using a service such as etcd. I imagine the server will set a key like server_ip=10.1.69.3, then the client can read it using service discovery. But I'm not sure how to implement this. 

Should I use existing etcd of the CoreOS machine, or should I use another container exclusively for etcd? 

Thanks!

**Comment by PierreKircher** [comment]
skydns ?

**Comment by cdpb** [comment]
@PierreKircher how can I define a static ip within the flannel layer for skydns, because that is important for the dns. I don't want to bind the service on a single node ( see #167 )

**Comment by siteshen** [comment]
```bash
while true; do
    container_name="db-slave-1"
    ip=$(docker inspect --format "{{ .NetworkSettings.IPAddress }}" $container_name)
    check_cmd=$(echo "PGPASSWORD=123456 psql -h $ip db_name username  -c \\"select max(id) from things\\" ")
    docker exec $container_name bash -c "$check_cmd"
    if [ $? -eq 0 ]; then
        etcdctl set /servics/db-slave/1 $ip:5432 -ttl 30
    else
        etcdctl rm  /servics/db-slave/1
    fi
    sleep 20
done

**Comment by tomdee** [comment]
This issue is out of scope for flannel
