### ISSUE TITLE
cni0 mac change brings network interrupt from Pod to other network

### ISSUE THREAD

**Issue by wyike** [coreos/flannel#1381]
In our kubernetes cluster, we observed cni0 mac change per vethes churn to its slaved lowest value of veth mac ; currently we believe this is a by design behavior for linux bridge(find some code but not sure if the exact code place: [code](https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/bridge.go#L187) and some materials like [this](https://bugzilla.redhat.com/show_bug.cgi?id=609463 ), [this](https://github.com/containernetworking/cni/issues/285), please correct me if understanding wrong).

When running long time traffic from Pod like TCP traffic or continuous ICMP, we observed obvious network interrupt because at the same time we delete the Pod which veth mac is just the cni0 using for its mac, so cni0 mac value changes to another one. 

**For ICMP traffic, in our environment**:
1.ICMP from Pod to outside VM, we observe 33 packets loss, network interrupt for ~33 seconds 

> 64 bytes from 192.168.111.125: icmp_seq=78 ttl=62 time=1.35 ms
64 bytes from 192.168.111.125: icmp_seq=79 ttl=62 time=1.37 ms
64 bytes from 192.168.111.125: icmp_seq=80 ttl=62 time=1.57 ms
64 bytes from 192.168.111.125: icmp_seq=81 ttl=62 time=1.42 ms
64 bytes from 192.168.111.125: icmp_seq=82 ttl=62 time=1.88 ms
64 bytes from 192.168.111.125: icmp_seq=116 ttl=62 time=1.40 ms
64 bytes from 192.168.111.125: icmp_seq=117 ttl=62 time=1.39 ms
64 bytes from 192.168.111.125: icmp_seq=118 ttl=62 time=1.47 ms
64 bytes from 192.168.111.125: icmp_seq=119 ttl=62 time=1.34 ms
64 bytes from 192.168.111.125: icmp_seq=120 ttl=62 time=1.37 ms
64 bytes from 192.168.111.125: icmp_seq=121 ttl=62 time=1.44 ms
64 bytes from 192.168.111.125: icmp_seq=122 ttl=62 time=1.60 ms
--- 192.168.111.125 ping statistics ---
147 packets transmitted, 114 received, 22.449% packet loss, time 1096ms
rtt min/avg/max/mdev = 0.902/1.548/8.467/0.857 ms

From tcpdump packet captured, we see ARP keep asking the old cni0 mac but no response till ARP to broadcast and get the new cni0 mac addr, then packet from Pod can be passed to cni0, and afterwards forwarding continues.
![image](https://user-images.githubusercontent.com/48750673/101755823-4e0e2f00-3b10-11eb-9914-4dbbe3544fbf.png)

2. ICMP from Pod to another Pod, we observe 16 packet loss, network interrupt for ~16 seconds

**For TCP traffic:**
With iperf, from Pod to outside VM, we observed 100~200s network interrupt for iperf client itself keeping trying TCP retransmission and finally recover the transmission in existed TCP connection. 

Have we already been aware of this result introduced by the cni0 bridge mac change? Do we have any methods/special configuration to improve the situation?

## Your Environment

* Flannel version: v0.11.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.4.13
* Kubernetes version (if used): 1.19.2
* Operating System and version: cluster worker nodes are 16.04.1-Ubuntu
* Link to your project (optional): 
* Cni config
> /etc/cni/net.d/50-flannel.conflist
{
    "name": "flannel-network",
    "cniVersion": "0.3.1",
    "plugins": [
            {
                    "type": "flannel",
                    "delegate": {
                            "hairpinMode": true,
                            "isDefaultGateway": true
                    }
            },
            {
                    "type": "portmap",
                    "capabilities": {
                            "portMappings": true
                    }
            }
    ]
}

**Comment by vincentmli** [comment]
the same line code actually says the bridge will be set to  fixed MAC  when the bridge gets created, am I miss anything?

https://github.com/containernetworking/plugins/blob/master/plugins/main/bridge/bridge.go#L187
<pre>
	// Set the bridge's MAC to itself. Otherwise, the bridge will take the
	// lowest-numbered mac on the bridge, and will change as ifs churn
	if err := netlink.LinkSetHardwareAddr(br, br.Attrs().HardwareAddr); err != nil {
		return fmt.Errorf("could not set bridge's mac: %v", err)
	}
</pre>

**Comment by wyike** [comment]
Hi Vincent, yes we deeper investigated the code afterwards, got clear of the flannel workflow and identified our product pre-created a cni0 with docker introducing the issue. 
I'll close this issue. Thanks.
