### ISSUE TITLE
Failed to restart Flannel HostGW mode in Windows(Server Core, version 1909) with K8S 1.18

### ISSUE THREAD

**Issue by thxCode** [coreos/flannel#1391]
## Expected Behavior

Following the official guide or using other platforms(like ACK) to setup HostGW mode in Windows (Server Core, version 1909) with K8S 1.18, and then restart the flannel process or the host. The flannel should continue to run.

## Current Behavior

Failed to restart flannel.
![image](https://user-images.githubusercontent.com/3394724/103163234-7eefa300-4836-11eb-8bb4-756608443bb1.png)

## Possible Solution

As a workaround, we need to remove the `${NETWORK_NAME}_ep` HNSEndpoint manually.
```
Get-HNSEndpoint | ? VirtualNetworkName -eq "cbr0" | ? Name -eq "cbr0_ep" | Remove-HNSEndpoint
```

## Steps to Reproduce (for bugs)

1. Setup K8S 1.18 cluster via any platforms that passed the Certified Kubernetes Conformance Program, like ACK
2. Setup the Windows Node.

## Context

It seems that Windows has added validation to check the re-add action of the same HNSEndpoint.

The same issue has been reported in the K8S community: https://github.com/kubernetes-sigs/sig-windows-tools/issues/94

## Your Environment

* Flannel version: v0.13.0
* Backend used (e.g. vxlan or udp): host-gw
* Etcd version: 
* Kubernetes version (if used): 1.18.8
* Operating System and version: Windows (Server Core, version 1909)
* Link to your project (optional):

**Comment by luthermonson** [comment]
@thxCode thanks frank!

**Comment by thxCode** [comment]
@luthermonson cheers
