### ISSUE TITLE
Flannel sunnet does not match the subnet set by Docker

### ISSUE THREAD

**Issue by lklkxcxc** [coreos/flannel#1393]
## Current Behavior

Flanneld Service The output error：
```
Dec 29 13:41:12 kube-node-2 flanneld-start[15205]: I1229 13:41:12.913005   15205 network.go:243] L3 miss but route for 192.168.47.7 not found
Dec 29 13:41:13 kube-node-2 flanneld-start[15205]: I1229 13:41:13.914890   15205 network.go:243] L3 miss but route for 192.168.47.7 not found
```

## Steps to Reproduce (for bugs)

1. Check Flannel sunnet does not match the subnet set by Docker
```
cat /run/flannel/docker     
DOCKER_OPT_BIP="--bip=192.168.27.1/24"
DOCKER_OPT_IPMASQ="--ip-masq=true"
DOCKER_OPT_MTU="--mtu=1450"
cat /run/flannel/subnet.env 
FLANNEL_NETWORK=192.168.0.0/17
FLANNEL_SUBNET=192.168.19.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false
```
2.Restart Flannel servicce  sunnet the same in /run/flannel/subnet.env and /run/flannel/docker file，network become normal.

## Your Environment

* Flannel version: 0.7.1
* Backend used (e.g. vxlan or udp): udp
* Etcd version:3.3.11-2
* Kubernetes version (if used): v1.12.4
* Operating System and version: CentOS 7.7
* Link to your project (optional):

**Comment by luthermonson** [comment]
@lklkxcxc  youre running an old version of flannel can you try and recreate in v0.12.0 or greater? there's suspicions that youre using an older subnet.env or something, leftover data maybe?  we are going to mark this closed and reopen if it doesnt work in later versions.

**Comment by rajatchopra** [comment]
Closing this issue. Please re-open if needed.
