### ISSUE TITLE
"rancher/flannel-cni-plugin:v1.2" repository does not exist

### ISSUE THREAD

**Issue by cjhouser** [coreos/flannel#1482]
## Expected Behavior

I attempted to deploy Flannel into a Kubernetes cluster by applying the YAML from the [README](https://github.com/flannel-io/flannel#deploying-flannel-manually). I assume that it's supposed to work as is, but that may be incorrect.

## Current Behavior

Applying the YAML causes ErrImagePull on the kube-flannel-ds pod. I checked Dockerhub for the image in question (rancher/flannel-cni-plugin), but it hasn't been pushed.

```
$ kubectl describe pod -n kube-system kube-flannel-ds-h4mtc
Name:                 kube-flannel-ds-h4mtc
Namespace:            kube-system
Status:               Pending
Init Containers:
  install-cni-plugin:
    Container ID:
    Image:         rancher/flannel-cni-plugin:v1.2
    Image ID:
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  2m27s                default-scheduler  Successfully assigned kube-system/kube-flannel-ds-h4mtc to control
  Normal   Pulling    53s (x4 over 2m24s)  kubelet            Pulling image "rancher/flannel-cni-plugin:v1.2"
  Warning  Failed     52s (x4 over 2m23s)  kubelet            Failed to pull image "rancher/flannel-cni-plugin:v1.2": rpc error: code = Unknown desc = Error response from daemon: pull access denied for rancher/flannel-cni-plugin, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed     52s (x4 over 2m23s)  kubelet            Error: ErrImagePull
  Warning  Failed     25s (x6 over 2m22s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    11s (x7 over 2m22s)  kubelet            Back-off pulling image "rancher/flannel-cni-plugin:v1.2"
```

## Possible Solution

Push flannel-cni-plugin to Dockerhub.
If rc1 in the Flannel version means that it's still in testing or something similar: the YAML on the main README.md should reference a release version, like v0.14.0

## Context

I'm setting up a Kubernetes cluster with kubeadm on a a few Raspberry Pi's and tried to use Flannel as a Kubernetes networking solution. Flannel was mentioned [here](https://kubernetes.io/docs/concepts/cluster-administration/networking/#flannel). I will try Flannel v0.14.0.

## Your Environment

* Flannel version: [v0.15.0-rc1](https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml)
* Kubernetes version (if used):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
```
* Operating System and version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by ormissia** [comment]
I have the same confusion.
Where is rancher/flannel-cni-plugin:v1.2 ?
🤔

**Comment by ormissia** [comment]
> I have the same confusion. Where is rancher/flannel-cni-plugin:v1.2 ? 🤔

I currently choose v0.14.1

**Comment by lwr20** [comment]
Looks like this was caused by this commit: https://github.com/flannel-io/flannel/commit/1a62caf48086ce78c46a438679f90e39aeed8c44

**Comment by N00ree** [comment]
I also have some weird errors pulling the image and realized that there is a typo in the version.

![grafik](https://user-images.githubusercontent.com/61552289/137490198-dacc6fd5-093e-4390-ab80-6e89c4b900b5.png)

The dot is missing in there.

Can this be the reason?

**Comment by Wunderharke** [comment]
https://github.com/flannel-io/flannel/commit/38e7eff19baff456eb29bd20421068eb4d455af2 Some active contributor should verify that those are legitimate images first.

**Comment by luthermonson** [comment]
https://github.com/flannel-io/flannel/pull/1484
