### ISSUE TITLE
coreos flannel failed to acquire subnet : 502

### ISSUE THREAD

**Issue by monkey-H** [coreos/flannel#150]
I trying out flannel using coreos-vagrant. I start up 3 hosts and install the flannel binary in each of them. I add the network configuration using etcdctl and then start flannel on each host using

sudo /home/core/flannel/bin/flanneld -iface=eth1

then, I get 
core@core-01 ~/flannel $ ./bin/flanneld -iface=eth1
I0403 19:05:00.972738 14797 main.go:275] Installing signal handlers
I0403 19:05:00.973345 14797 main.go:225] Using 172.17.8.101 as external interface
I0403 19:05:00.974162 14797 subnet.go:334] Picking subnet in range 10.0.1.0 ... 10.0.255.0
E0403 19:05:00.974405 14797 subnet.go:104] Failed to acquire subnet: 502:  (unhandled http status [Temporary Redirect] with body []) [0]
I0403 19:05:01.975828 14797 subnet.go:334] Picking subnet in range 10.0.1.0 ... 10.0.255.0
E0403 19:05:01.976611 14797 subnet.go:104] Failed to acquire subnet: 502:  (unhandled http status [Temporary Redirect] with body []) [0]

I checked flannel status also,
core@core-01 ~/flannel $ systemctl status flannel -l
● flannel.service
   Loaded: loaded (/etc/systemd/system/flannel.service; static; vendor preset: disabled)
   Active: active (running) since Fri 2015-04-03 18:10:31 UTC; 1min 45s ago
  Process: 14284 ExecStartPre=/usr/bin/etcdctl mk /coreos.com/network/config {"Network":"10.0.0.0/16"} (code=exited, status=0/SUCCESS)
  Process: 14278 ExecStartPre=/usr/bin/etcdctl rm /coreos.com/network/ --recursive (code=exited, status=0/SUCCESS)
 Main PID: 14291 (flanneld)
   CGroup: /system.slice/flannel.service
           └─14291 /home/core/flannel/bin/flanneld -iface=eth1

Apr 03 18:12:12 core-01 flanneld[14291]: I0403 18:12:12.544148 14291 subnet.go:334] Picking subnet in range 10.0.1.0 ... 10.0.255.0
Apr 03 18:12:12 core-01 flanneld[14291]: E0403 18:12:12.546241 14291 subnet.go:104] Failed to acquire subnet: 502:  (unhandled http status [Temporary Redirect] with body []) [0]
Apr 03 18:12:13 core-01 flanneld[14291]: I0403 18:12:13.546827 14291 subnet.go:334] Picking subnet in range 10.0.1.0 ... 10.0.255.0
Apr 03 18:12:13 core-01 flanneld[14291]: E0403 18:12:13.547829 14291 subnet.go:104] Failed to acquire subnet: 502:  (unhandled http status [Temporary Redirect] with body []) [0]
Apr 03 18:12:14 core-01 flanneld[14291]: I0403 18:12:14.549020 14291 subnet.go:334] Picking subnet in range 10.0.1.0 ... 10.0.255.0
Apr 03 18:12:14 core-01 flanneld[14291]: E0403 18:12:14.549425 14291 subnet.go:104] Failed to acquire subnet: 502:  (unhandled http status [Temporary Redirect] with body []) [0]
Apr 03 18:12:15 core-01 flanneld[14291]: I0403 18:12:15.550523 14291 subnet.go:334] Picking subnet in range 10.0.1.0 ... 10.0.255.0
Apr 03 18:12:15 core-01 flanneld[14291]: E0403 18:12:15.552198 14291 subnet.go:104] Failed to acquire subnet: 502:  (unhandled http status [Temporary Redirect] with body []) [0]
Apr 03 18:12:16 core-01 flanneld[14291]: I0403 18:12:16.552843 14291 subnet.go:334] Picking subnet in range 10.0.1.0 ... 10.0.255.0
Apr 03 18:12:16 core-01 flanneld[14291]: E0403 18:12:16.554038 14291 subnet.go:104] Failed to acquire subnet: 502:  (unhandled http status [Temporary Redirect] with body []) [0]

core-02 is the same with core-01, but core-03 is different.
core@core-03 ~/flannel $ sudo ./bin/flanneld -iface=eth1
I0403 18:58:02.990720 13355 main.go:275] Installing signal handlers
I0403 18:58:02.990992 13355 main.go:225] Using 172.17.8.103 as external interface
I0403 18:58:03.002163 13355 subnet.go:97] Subnet lease acquired: 10.0.22.0/24
I0403 18:58:03.005791 13355 main.go:242] UDP mode initialized
I0403 18:58:03.005841 13355 udp.go:212] Watching for new subnet leases

and this is my routing table
core@core-01 ~/flannel $ netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         10.0.2.2        0.0.0.0         UG        0 0          0 eth0
10.0.2.0        0.0.0.0         255.255.255.0   U         0 0          0 eth0
10.0.2.2        0.0.0.0         255.255.255.255 UH        0 0          0 eth0
10.1.0.0        0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.17.8.0      0.0.0.0         255.255.255.0   U         0 0          0 eth1

any idea?

**Comment by monkey-H** [comment]
core@core-01 ~/flannel $ etcdctl get coreos.com/network/config
{"Network":"10.0.0.0/16"}

**Comment by sandric** [comment]
Having the same issue. What are we doing wrong?

**Comment by monkey-H** [comment]
I am using CoreOS beta (557.0.0)
Any idea?

**Comment by monkey-H** [comment]
I changed to stable version , then it's ok !
