### ISSUE TITLE
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

### ISSUE THREAD

**Issue by monkey-H** [coreos/flannel#154]
I have a coreos cluster of two machines.

core@coreos1 / $ fleetctl list-machines
MACHINE		IP		METADATA
6b8cd3b1...	114.212.189.136	-
cccd5129...	114.212.189.140	-

And I want to link them with flannel.

I installed flannel and I want to restart docker. However, I got an error of cannot connect to the docker daemon. 

core@coreos1 / $ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef-dirty
OS/Arch (client): linux/amd64
FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

Here is my docker.service and flannel.service in /etc/systemd/system

core@coreos1 /etc/systemd/system $ cat flannel.service 
[Unit]
Description=flannel
Requires=etcd.service
After=etct.service

[Service]
ExecStartPre=-/usr/bin/etcdctl mk /coreos.com/network/config '{"Network":"10.0.0.0/16"}'
ExecStart=/opt/bin/flanneld

[Install]
WantedBy=multi-user.target

core@coreos1 /etc/systemd/system $ cat docker.service 
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=docker.socket early-docker.target network.target
Requires=docker.socket early-docker.target

[Service]
Environment=TMPDIR=/var/tmp
EnvironmentFile=-/run/flannel/subnet.env
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
#ExecStartPre=source /run/flannel/subnet.env
#ExecStartPre=sudo ifconfig docker0 ${FLANNEL_SUBNET}
#ExecStartPre=echo hello
#ExecStartPre=echo ${FLANNEL_SUBNET}
ExecStart=/usr/lib/coreos/dockerd --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU} --daemon --host=fd:// 

[Install]
WantedBy=multi-user.target

When I run ps -ef | grep docker , I get this. 
core@coreos1 / $ ps -ef | grep docker
root      7367     1  0 10:03 ?        00:00:00 docker --bip=10.0.22.1/24 --mtu=1472 --daemon --host=fd://
core      7559  2424  0 10:18 pts/0    00:00:00 grep --colour=auto docker

And 
core@coreos1 / $ sudo systemctl status docker -l
● docker.service - Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2015-04-16 10:03:31 UTC; 15min ago
     Docs: http://docs.docker.com
 Main PID: 7367 (docker)
   CGroup: /system.slice/docker.service
           └─7367 docker --bip=10.0.22.1/24 --mtu=1472 --daemon --host=fd://

Apr 16 10:03:31 coreos1 dockerd[7367]: time="2015-04-16T10:03:31Z" level="info" msg="+job serveapi(fd://)"
Apr 16 10:03:31 coreos1 dockerd[7367]: time="2015-04-16T10:03:31Z" level="info" msg="+job init_networkdriver()"
Apr 16 10:03:31 coreos1 dockerd[7367]: time="2015-04-16T10:03:31Z" level="info" msg="Listening for HTTP on fd ()"
Apr 16 10:03:31 coreos1 dockerd[7367]: time="2015-04-16T10:03:31Z" level="info" msg="-job init_networkdriver() = OK (0)"
Apr 16 10:03:31 coreos1 dockerd[7367]: time="2015-04-16T10:03:31Z" level="info" msg="Loading containers: start."
Apr 16 10:03:31 coreos1 dockerd[7367]: ......
Apr 16 10:03:31 coreos1 dockerd[7367]: time="2015-04-16T10:03:31Z" level="info" msg="Loading containers: done."
Apr 16 10:03:31 coreos1 dockerd[7367]: time="2015-04-16T10:03:31Z" level="info" msg="docker daemon: 1.5.0 a8a31ef-dirty; execdriver: native-0.2; graphdriver: overlay"
Apr 16 10:03:31 coreos1 dockerd[7367]: time="2015-04-16T10:03:31Z" level="info" msg="+job acceptconnections()"
Apr 16 10:03:31 coreos1 dockerd[7367]: time="2015-04-16T10:03:31Z" level="info" msg="-job acceptconnections() = OK (0)"

core@coreos1 / $ sudo systemctl status flannel -l
● flannel.service - flannel
   Loaded: loaded (/etc/systemd/system/flannel.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2015-04-16 10:01:51 UTC; 17min ago
  Process: 7319 ExecStartPre=/usr/bin/etcdctl mk /coreos.com/network/config {"Network":"10.0.0.0/16"} (code=exited, status=4)
 Main PID: 7326 (flanneld)
   CGroup: /system.slice/flannel.service
           └─7326 /opt/bin/flanneld

Apr 16 10:01:51 coreos1 etcdctl[7319]: Error:  105: Key already exists (/coreos.com/network/config) [161111]
Apr 16 10:01:51 coreos1 systemd[1]: Started flannel.
Apr 16 10:01:51 coreos1 flanneld[7326]: I0416 10:01:51.052138 07326 main.go:275] Installing signal handlers
Apr 16 10:01:51 coreos1 flanneld[7326]: I0416 10:01:51.052187 07326 main.go:137] Determining IP address of default interface
Apr 16 10:01:51 coreos1 flanneld[7326]: I0416 10:01:51.053088 07326 main.go:225] Using 114.212.189.136 as external interface
Apr 16 10:01:51 coreos1 flanneld[7326]: I0416 10:01:51.147024 07326 subnet.go:97] Subnet lease acquired: 10.0.22.0/24
Apr 16 10:01:51 coreos1 flanneld[7326]: I0416 10:01:51.148313 07326 main.go:242] UDP mode initialized
Apr 16 10:01:51 coreos1 flanneld[7326]: I0416 10:01:51.148339 07326 udp.go:212] Watching for new subnet leases

Anyone can help me ? Why I cannot connect to the docker daemon when I can see it in ps -ef | grep docker ?

**Comment by eyakubovich** [comment]
@monkey-H apologies for the delayed response. Your docker daemon is started with `--host=fd://` so it will be socket activated. Make sure docker.socket uses the standard `ListenStream=/var/run/docker.sock`.

However, since you're running CoreOS, the latest images in all the channels ship flannel. You should be able to just follow instructions at https://coreos.com/docs/cluster-management/setup/flannel-config/ to set flannel up.

**Comment by monkey-H** [comment]
Thank you，I restarted the computer, and it worked.
