### ISSUE TITLE
Chicken/egg: docker0 IP in docker daemon --dns options

### ISSUE THREAD

**Issue by JeanMertz** [coreos/flannel#156]
Is there a way to know which IP will be assigned to the docker0 bridge before running `docker --daemon` when using Flannel?

My use case is that I want to set the `--dns` flag on the docker daemon to the docker0 bridge IP, to be used with Consul dns querying.

The only thing I have is `DOCKER_OPT_BIP`, which provides a range, but no definitive IP.

**Comment by eyakubovich** [comment]
`DOCKER_OPT_BIP` will actually be something like `--bip=10.0.23.1/24` and `10.0.23.1` will be the IP of docker0.

**Comment by JeanMertz** [comment]
Ah yes, you are correct. This is working as expected now :+1:
