### ISSUE TITLE
ping cross host but not visit

### ISSUE THREAD

**Issue by wangxin201492** [coreos/flannel#157]
I build flannel cross host .both hosts open 8285/udp,and container can ping each other.
hostA : flannel : 10.0.68.0
hostB : flannel : 10.0.70.0

the both host run a container and listen 80.
but i can't visit the container in the other host.
something like the following output:
[root@hostA log]# curl 10.0.70.3
curl: (7) Failed connect to 10.0.70.3:80; No route to host

and when i exec curl 10.0.70.3 in hostB, I got the truth.

 need i do something like firewalld?

**Comment by eyakubovich** [comment]
Can  you paste the output of `ip route`? There should be a `10.0.0.0/16 -> flannel0` route.

**Comment by eyakubovich** [comment]
As we don't have additional info, hard to debug.
