### ISSUE TITLE
Container IP from a BindTo unit (discovery service)

### ISSUE THREAD

**Issue by bencevans** [coreos/flannel#158]
I'm using a CoreOS cluster of 3 machines and flannel to bridge the networking of containers between hosts.

I've got a web-service that I want to push the host:port of into etcd for discovery but can't find a way to get the IP address of the docker container that's running in the main service. Is there a reccomended way of publishing a service to ETCD.

Main Service Unit File:
```ini
[Unit]
Description=Demo Web App
After=docker.service
After=etcd.service

[Service]
User=core
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill demo_web
ExecStartPre=-/usr/bin/docker rm demo_web
ExecStartPre=/usr/bin/docker pull [redacted]
ExecStart=/usr/bin/docker run --name demo_web [redacted]
ExecStop=/usr/bin/docker stop demo_web
```

Discovery Service Unit File:
```ini
[Unit]
Description=Announce Demo Web Publisher
BindsTo=demo_web.service
After=demo_web.service

[Service]
ExecStart=/bin/bash -c "FLANNEL_HOST=$(ifconfig flannel0 | awk '/\<inet\>/ { print $2}') && while true; do etcdctl set /services/loadbalancer/upstream/app1 \"$FLANNEL_HOST:3000\" --ttl 60 && etcdctl set /services/loadbalancer/domain demoweb.co.uk; sleep 45;done"

[X-Fleet]
MachineOf=demo_web.service
```

The IP address that is currently being published is that of the host the container is run on. How am I able to get the containers IP and publish it to Etcd?

Cheers,

Ben

**Comment by eyakubovich** [comment]
The easiest is to just use Docker inspect to get the IP:
`docker inspect -f '{{.NetworkSettings.IPAddress}}' demo_web`

However, since it takes a bit for container to start, you have to wrap this in a polling loop:
```
ExecStart=/bin/bash -c "while ! IP=$(docker inspect -f '{{.NetworkSettings.IPAddress}}' demo_web) && [ -n "$IP" ]; do sleep 1; done; while true; do etcdctl set /services/loadbalancer/upstream/app1 \"$IP:3000\" --ttl 60 && etcdctl set /services/loadbalancer/domain demoweb.co.uk; sleep 45; done"
```

There's also a registrator project that you may be interested in: https://github.com/gliderlabs/registrator

**Comment by bencevans** [comment]
That's brilliant thanks!

I'd got most of it together but was obviously being a bit dosey and forgot to use a container name to reference it from a separate service file!

**Comment by felixsanz** [comment]
@eyakubovich Sorry for bumping this old issue but since the service has `After=demo_web.service`, is that not enough to avoid "since it takes a bit for container to start..." ?

The discovery service should always get the main service container IP, i'm wrong?
