### ISSUE TITLE
Hello World Example

### ISSUE THREAD

**Issue by PeterLamar** [coreos/flannel#165]
Where is the best place to start learning the networking in regards to the k8's cluster deployments? Flannel doesn't seem to have a clear hello world example. What would be the best way to create one?

**Comment by eyakubovich** [comment]
Have you looked at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/networking.md

**Comment by PeterLamar** [comment]
I actually ended up using the flannel portion in this article. It has a few straight forward steps to send a packet around using flannel. One glance at the article and I understood a simple flannel stand alone use case. 

http://www.generictestdomain.net/docker/weave/networking/stupidity/2015/04/05/weave-is-kinda-slow/
