### ISSUE TITLE
Bug when using a Peer to Peer link instead of regular IP/Gateway setup

### ISSUE THREAD

**Issue by p0ns** [coreos/flannel#168]
Hello! 

I found a bug while deploying flannel on CoreOS stable (633.1.0). I have 3 instances, all with public IP addresses, but in this case, the network uses a Peer to Peer link instead of the regular IP with a gateway in it's subnet.

.network file
          [Match]
          MACAddress=02:00:00:c5:xx:xx
          [Address]
          Address=xx.x5.xx.235
          Peer=xx.x9.xx.254
          [Network]
          Gateway=xx.x9.x.254

As it seems, flannel fails to find the correct IP address in all setups. When using the straight IP address as INTERFACE parameter, it doesn't find an interface matching the IP and fails to start completely. 
When using the actual ens3 interface as INTERFACE, it will find xx.x9.x.254 (the point-to-point gw) instead of my ip address xx.x5.xx.235

May 08 05:16:26 core1.host sdnotify-proxy[614]: I0508 05:16:26.606448 00001 main.go:211] Using xx.x9.x.254 as external interface

This is the current OVH failover IP setup, and overall in other aspects of CoreOS, it works fine, but in this case, it wont let me link correctly with my other peers, cause the IP published is not the right one. 

I'm able to provide feedback, and also, if guided properly on how to deploy a fresh code of flannel copy, I could make a patch myself.

Thanks!

Felipe

**Comment by p0ns** [comment]
I forgot to mention, when the IP address is specified, flannel will fail to start completely.

**Comment by eyakubovich** [comment]
@p0ns This is a bit surprising. Can you please provide a bit more information to help us figure out the problem:
1. What is the actual type of the point-to-point interface? (e.g. gre tunnel)
2. Can you paste the output of `ip addr show $INTERFACE`

**Comment by p0ns** [comment]
core0 machine without issues
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet x.x.x.x/29 brd x.x.x.63 scope global eth0
       valid_lft forever preferred_lft forever

core1, machine with issues
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 02:00:00:c5:xx:xx brd ff:ff:ff:ff:ff:ff
    inet xx.x5.xx.235 peer xx.x9.x.254/24 scope global ens3
       valid_lft forever preferred_lft forever

The difference seems to be that instead of a broadcast, it broadcasts on it's own IP and has a *peer* address, which is the gateway.

The interface is an actual ethernet interface, but the difference is that, as you can see in the .network file I put in the past message, it's not setup regularly with a gateway but a Peer address that acts as such.

**Comment by eyakubovich** [comment]
@p0ns thanks. I'll try to replicate this to see what's going on. One theory is that the peer IP shows up in the list of interface assigned IP's. That would explain why `--iface=ens3` picks it up -- it maybe first in the list. But if both `xx.x5.xx.235` and `xx.x9.xx.254` are returned, I don't understand why `--iface=xx.x5.xx.235` does not work.

**Comment by p0ns** [comment]
When the IP is specified, the log says it can't find the interface to which the IP address belongs to. 

One simple theory I have is that, when the interface is specified with --iface=ens3 the code is looking for the first full xxx.xxx.xxx.xxx/yy combination in the inet line, hence finding the peer IP in the error case. 

If you need, I can give you access to my cluster so you can debug it. 

Thanks again! 

Felipe

**Comment by eyakubovich** [comment]
@p0ns I've recreated the problem. Since the ethernet interface is not point-to-point device (the address is), Go library screws up and picks the wrong address (I'm not sure why their logic is the way it is). I've switched to using the netlink library and fixed the problem. The bug fix should land soon and I'll do a point release.

**Comment by eyakubovich** [comment]
@p0ns 0.4.1 is now available with this bug fix. You can try it by placing
`Environment=FLANNEL_VER=0.4.1` into you flanneld.service dropin.

**Comment by p0ns** [comment]
It works! After setting it up in the 3 nodes, one of em hit issue #112 and was getting a 172.x address instead of the 10.x on docker0, but I used the fix proposed in there, and I got em all connected.

Thank you for your work :+1:
