### ISSUE TITLE
Pause causes losing first ping packet

### ISSUE THREAD

**Issue by danielschonfeld** [coreos/flannel#172]
Using flannel as the overlay for my Kubernetes cluster with CoreOS 675.0.0 and have a dedicated etcd cluster running CoreOS 668.2.0.

Whenever I try to access my kubernetes services, it seems some requests get a slight pause that is pretty noticeable.  Investigating it, I found that SSHing into my k8s nodes and trying to ping the different pods that are located on other nodes, I see the first ping packet completely lost.  After doing that excursive for the first time, the next time I run ping command all packets seem to be fine.  

Giving it a bit of time to relax and not sending any traffic to those IPs, then SSHing again and attempting the same excursive again, the first ICMP packet again is lost.

I'm not yet able to determine how much time it takes until this staleness becomes a problem needing what seems like a 'refresh'

I did notice however that doing `ip -s neighbor list` shows those POD IPs as STALE pretty often.  And it when pinging, it takes a good amount of pings (like 10 packets) to become REACHABLE again and then very quickly (in the order of 10-20 seconds) it becomes STALE again.

Incidentally *not* every time an IP is marked STALE, pinging it would have it lose the first packet.

**Comment by eyakubovich** [comment]
@danielschonfeld Are you running the default or VXLAN backend?

**Comment by danielschonfeld** [comment]
vxlan backend but just to make sure.... is the distinction is all about doing the following?

`/usr/bin/etcdctl set /coreos.com/network/config '{"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}}'`

**Comment by eyakubovich** [comment]
yes, that changes the backend.

flannel's vxlan backend does not mark arp or fdb entries as permanent. It lets them expire just like any other arp entry would. Once it expires, the misses are sent up to flanneld and it pushes the values back into the kernel. 

Can you let them expire then do a single ping (`ping -c 1`) and see what's in the logs. vxlan is verbose so you should see lines notifying of L2 and L3 misses and whether AddL2 and AddL3 succeeded. If you could paste the output, it would be helpful.

**Comment by danielschonfeld** [comment]
you said to let them expire, what signifies them expiring?

**Comment by eyakubovich** [comment]
you said relaxing it a bit and then trying ping again causes it the first ping packet to get dropped.
So try once when it has reached STALE state and once when it has been completely expunged from the arp cache (just do `ip neigh flush`)

**Comment by danielschonfeld** [comment]
Before i did this, i checked all entires that use flannel.1 in `ip -s neighbor list` were showing STALE. This is what I got:
```
$ ping -c 1 10.244.75.12
PING 10.244.75.12 (10.244.75.12) 56(84) bytes of data.

--- 10.244.75.12 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

And tailing journalctl -u flannel gave me these new entries after i pinged:
```
May 14 22:15:43 node1.c.my-project.internal sdnotify-proxy[725]: I0514 22:15:43.342992 00001 vxlan.go:268] L2 miss: 36:55:bc:7d:22:26
May 14 22:15:43 node1.c.my-project.internal sdnotify-proxy[725]: I0514 22:15:43.343242 00001 device.go:216] calling NeighAdd: 10.240.219.115, 36:55:bc:7d:22:26
May 14 22:15:43 node1.c.my-project.internal sdnotify-proxy[725]: I0514 22:15:43.343484 00001 vxlan.go:279] AddL2 succeeded
May 14 22:15:51 node1.c.my-project.internal sdnotify-proxy[725]: I0514 22:15:51.362256 00001 vxlan.go:263] Ignoring not a miss: 36:55:bc:7d:22:26, 10.244.75.12
May 14 22:15:52 node1.c.my-project.internal sdnotify-proxy[725]: I0514 22:15:52.364337 00001 vxlan.go:263] Ignoring not a miss: 36:55:bc:7d:22:26, 10.244.75.12
May 14 22:15:53 node1.c.my-project.internal sdnotify-proxy[725]: I0514 22:15:53.366234 00001 vxlan.go:263] Ignoring not a miss: 36:55:bc:7d:22:26, 10.244.75.12
```

**Comment by danielschonfeld** [comment]
Running `sudo ip -s neigh flush dev flannel.1` and then verifying using `ip -s neighbor list` shows all entries pertaining to flannel.1 as `FAILED`.

I get the following ping results: (notice this time how odd it is, the packet actually goes through the first time... but I've only waited 5 minutes so i'm not sure what to make out of it)

```
$ ping -c 1 10.244.75.12
PING 10.244.75.12 (10.244.75.12) 56(84) bytes of data.
64 bytes from 10.244.75.12: icmp_seq=1 ttl=63 time=2.49 ms

--- 10.244.75.12 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 2.498/2.498/2.498/0.000 ms
```

And journalctl -f -u flannel adds the following lines:

```
May 14 22:20:21 node1.c.my-project.internal sdnotify-proxy[725]: I0514 22:20:21.801983 00001 vxlan.go:284] L3 miss: 10.244.75.12
May 14 22:20:21 node1.c.my-project.internal sdnotify-proxy[725]: I0514 22:20:21.802235 00001 device.go:242] calling NeighSet: 10.244.75.12, 36:55:bc:7d:22:26
May 14 22:20:21 node1.c.my-project.internal sdnotify-proxy[725]: I0514 22:20:21.802479 00001 vxlan.go:295] AddL3 succeeded
May 14 22:20:39 node1.c.my-project.internal sdnotify-proxy[725]: I0514 22:20:39.556219 00001 vxlan.go:263] Ignoring not a miss: 36:55:bc:7d:22:26, 10.244.75.12
```

**Comment by eyakubovich** [comment]
So L3 misses (arp) are handled ok -- without packet loss. But L2 misses (fdb, that's vxlan part) result in dropped packets. I now recall that I have seen this but I don't remember tracking it down in the kernel on what causes this. Marking as bug and will investigate.

**Comment by danielschonfeld** [comment]
In the mean time, will downgrading to a different kernel solve this issue?

**Comment by eyakubovich** [comment]
I am not sure. I haven't followed vxlan changes in the kernel.

**Comment by danielschonfeld** [comment]
@eyakubovich @MohdAhmad how would I know what CoreOS release this solution is included in?

**Comment by eyakubovich** [comment]
@danielschonfeld It's not yet released (we haven't tagged a version since the merge). Actually we just found a bug related to this. We can update this issue once this lands in alpha.

**Comment by yanyixing** [comment]
@eyakubovich ,does this bug fixed ,i have got this problem
