### ISSUE TITLE
For aws-vpc backend, only delete routes if they are a black hole

### ISSUE THREAD

**Issue by micahhausler** [coreos/flannel#186]
I'm loving the aws-vpc backend, but currently you can't run more than one cluster under the same route table, as they risk overwriting each other's routes.

Currently, flannel just [deletes an existing route if it already exists](https://github.com/coreos/flannel/blob/9cbad3b7f08e8e2a803d00dbbeeba3a4442e790b/backend/awsvpc/awsvpc.go#L106-L112). It would be great if this delete could only occur if the route exists and is a Black Hole.

![screen shot 2015-05-22 at 2 46 11 pm](https://cloud.githubusercontent.com/assets/791000/7777509/a737c07e-0091-11e5-8c42-1893df294506.png)

**Comment by eyakubovich** [comment]
@micahhausler I think checking for Black Hole is a good idea but I am not sure I understand what you mean by running multiple clusters. Do you mean that multiple flannel networks that use same IP address range but are not related to each other? In that case why not just have separate routing tables? You have to specify the route table in the config anyway.

**Comment by micahhausler** [comment]
Yea you are right. It would be better to just use separate routing tables.
