### ISSUE TITLE
HTTP API for network create

### ISSUE THREAD

**Issue by eyakubovich** [coreos/flannel#187]
Currently to define a new network you need to talk to etcd directly. This would add a `flannel server` endpoint that would let you configure the initial network state through that API.

**Comment by philips** [comment]
@eyakubovich can you flesh this out a bit more?

**Comment by eyakubovich** [comment]
@philips I actually started working this out about two weeks ago but I haven't gotten an interface that really worked. The main obstacle is per backend configuration and how to represent it and where to validate it. I also have to keep in mind that his api will be used by flannelctl so its UX is also a consideration here.
