### ISSUE TITLE
Question: what iptables-resync is used for? 

### ISSUE THREAD

**Issue by V0idk** [coreos/flannel#1897]
![image](https://github.com/flannel-io/flannel/assets/17514799/57762728-6ef2-4785-9155-ea01922005aa)

I see `getRules()` is alway not changed if `HasNerwork()` is false(not specfic option `use-multi-cluster-cidr`), so can we reduce resync period or not resync when we are not using  `use-multi-cluster-cidr`? 

Motivation: iptable query occupy iptable lock too long when has many pod and service.

**Comment by thomasferrandiz** [comment]
Hi @V0idk 
the periodic resync of the iptables rules is there to ensure that the rules created by flannel are not removed by another program. 
Normally, if the rules are not modified, iptables should not run again.

In any case, if the resync period is too short on your system, you can configure it through the `--iptables-resync` flag.
See the doc [here](https://github.com/flannel-io/flannel/blob/master/Documentation/configuration.md#key-command-line-options).
