### ISSUE TITLE
Bridge ip (...) does not match existing bridge configuration

### ISSUE THREAD

**Issue by greenpau** [coreos/flannel#195]
Environment:

* OS: CentOS 7
* etcdctl version 2.0.9
* flanneld version 0.2.0

After adding `flannel` service on CentOS 7 and restarting `docker.service`, I received the following error and the `docker` service refused to start:

```
Jun 01 19:27:09 ip-192-168-16-66.inf.ise.com systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jun 01 19:27:09 ip-192-168-16-66.inf.ise.com docker[30482]: time="2015-06-01T19:27:09Z" level=fatal msg="Shutting down daemon due to errors: Bridge ip (172.17.42.1) does
Jun 01 19:27:09 ip-192-168-16-66.inf.ise.com docker[30482]: time="2015-06-01T19:27:09Z" level=info msg="-job init_networkdriver() = ERR (1)"
Jun 01 19:27:09 ip-192-168-16-66.inf.ise.com docker[30482]: Bridge ip (172.17.42.1) does not match existing bridge configuration 10.252.30.1
```

`flanneld` config is:

```
# etcdctl get /coreos.com/network/config
{
    "Network": "10.252.0.0/16",
    "SubnetLen": 24,
    "SubnetMin": "10.252.0.0",
    "SubnetMax": "10.252.31.0",
    "Backend": {
        "Type": "udp",
        "Port": 7890
    }
}
```

`docker0` interface looks like:

```
# ip addr show dev docker0
9: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::5484:7aff:fefe:9799/64 scope link
       valid_lft forever preferred_lft forever
#
```

Initially, I stopped `flanneld`, disabled it, and tried to start the `docker` service again:

```
systemctl stop flanneld
systemctl disable flanneld
```

I noticed `flannel.conf` was still dropped-in when querying the status of `docker`:

```
# systemctl status docker
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
  Drop-In: /usr/lib/systemd/system/docker.service.d
           └─flannel.conf
```

After removing the `flannel.conf`, my `docker` was alive again:

```
rm -rf /usr/lib/systemd/system/docker.service.d/flannel.conf
```

How do I solve the "*Bridge ip (...) does not match existing bridge configuration*" error?

**Comment by eyakubovich** [comment]
This happens docker started before flannel, created a bridge and assigned an IP address to it (172.x.x.x).  However, docker does not delete the bridge when it's stopped. And when it starts up again it will error out if the IP you're trying to assign to it differs from existing.

You need to place a Requires= and After= clauses into docker.service to make sure it starts after flannel.

**Comment by greenpau** [comment]
@eyakubovich , like this?

```
After=flanneld.service
Requires=flanneld.service
```

**Comment by eyakubovich** [comment]
@greenpau Correct.

**Comment by greenpau** [comment]
merely changing the `docker` service unit did not help. The docker still has its old IP and thus failing.

I had to run the following command each time I made a change to my `etcd` config.
```
ip link set dev docker0 down
brctl delbr docker0
```
