### ISSUE TITLE
static flanneld topology - add lease reservations

### ISSUE THREAD

**Issue by greenpau** [coreos/flannel#197]
@eyakubovich , I have two nodes running `flanneld` and `etcd` with the following configuration:

```
cat > /etc/etcd/etcd.conf << EOF
ETCD_NAME=default
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_CLIENT_URLS="http://localhost:4001"
EOF

cat > /etc/sysconfig/flanneld << EOF
FLANNEL_ETCD="http://127.0.0.1:4001"
FLANNEL_ETCD_KEY="/coreos.com/network"
EOF
```

Each hosts has a different config `etcd` configuration:
1. Host A:
   
   ```
   etcdctl rm /coreos.com/network/ --recursive
   etcdctl mk /coreos.com/network/config '{
       "Network": "10.252.1.0/24",
       "SubnetLen": 25,
       "Backend": {
           "Type": "udp",
           "Port": 7890
       }
   }'
   ```
2. Host B:
   
   ```
   etcdctl rm /coreos.com/network/ --recursive
   etcdctl mk /coreos.com/network/config '{
       "Network": "10.252.2.0/24",
       "SubnetLen": 25,
       "Backend": {
           "Type": "udp",
           "Port": 7890
       }
   }'
   ```

I would like to statically define `flanneld` peers and topology.

How do I make Host A aware of Host B subnets and vice-versa without `etcd` discovery?

**Comment by eyakubovich** [comment]
@greenpau flannel does not work this way. With flannel, all your hosts use the same etcd cluster (so they   all see the same key space) and use the same network configuration. The "Network" specifies the IP address space for all your nodes. It then gets carved up into subnets (based on SubnetLen) and handed out automatically to the hosts. There're no static definitions for host subnets or their underlying public IPs (at least not yet).

Also, `FLANNEL_ETCD_KEY` should be `FLANNEL_ETCD_PREFIX`.

**Comment by greenpau** [comment]
> @eyakubovich , With flannel, all your hosts use the same etcd cluster (so they all see the same key space) and use the same network configuration. 

Understood. I will have a single configuration that looks like:

```
etcdctl rm /coreos.com/network/ --recursive
etcdctl mk /coreos.com/network/config '{
    "Network": "10.252.0.0/16",
    "SubnetLen": 24,
    "Backend": {
        "Type": "udp",
        "Port": 7890
    }
}'
```

Is `FLANNEL_ETCD_KEY` decommissioned?

How does Host A know not to issue an overlapping IP address on Host B?

**Comment by greenpau** [comment]
@eyakubovich , is there a deterministic way to assign subnets to hosting nodes?

**Comment by greenpau** [comment]
@eyakubovich , changing `FLANNEL_ETCD_KEY` to `FLANNEL_ETCD_PREFIX` results in:

```
# systemctl status flanneld
flanneld.service - Flanneld overlay address etcd agent
   Loaded: loaded (/etc/systemd/system/flanneld.service; enabled)
   Active: failed (Result: timeout) since Tue 2015-06-02 17:47:25 UTC; 1min 2s ago
 Main PID: 20131

Jun 02 17:47:18 ip-192-168-16-146 flanneld[20131]: E0602 17:47:18.108957 20131 main.go:151] Failed to create SubnetManager: 100: Key not foun...fig) [5]
Jun 02 17:47:19 ip-192-168-16-146 flanneld[20131]: E0602 17:47:19.109649 20131 main.go:151] Failed to create SubnetManager: 100: Key not foun...fig) [5]
Jun 02 17:47:20 ip-192-168-16-146 flanneld[20131]: E0602 17:47:20.110394 20131 main.go:151] Failed to create SubnetManager: 100: Key not foun...fig) [5]
Jun 02 17:47:21 ip-192-168-16-146 flanneld[20131]: E0602 17:47:21.111167 20131 main.go:151] Failed to create SubnetManager: 100: Key not foun...fig) [5]
Jun 02 17:47:22 ip-192-168-16-146 flanneld[20131]: E0602 17:47:22.111920 20131 main.go:151] Failed to create SubnetManager: 100: Key not foun...fig) [5]
Jun 02 17:47:23 ip-192-168-16-146 flanneld[20131]: E0602 17:47:23.112632 20131 main.go:151] Failed to create SubnetManager: 100: Key not foun...fig) [5]
Jun 02 17:47:24 ip-192-168-16-146 flanneld[20131]: E0602 17:47:24.113395 20131 main.go:151] Failed to create SubnetManager: 100: Key not foun...fig) [5]
Jun 02 17:47:25 ip-192-168-16-146 systemd[1]: flanneld.service operation timed out. Terminating.
Jun 02 17:47:25 ip-192-168-16-146 systemd[1]: Failed to start Flanneld overlay address etcd agent.
Jun 02 17:47:25 ip-192-168-16-146 systemd[1]: Unit flanneld.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
#
```

**Comment by greenpau** [comment]
> @greenpau , is there a deterministic way to assign subnets to hosting nodes?

Perhaps the best way is to set them in `/run/flannel/docker` and `/run/flannel/subnet.env`.

**Comment by eyakubovich** [comment]
@greenpau First, my apologies regarding `FLANNEL_ETCD_PREFIX`. I forgot a `D` at the end. It should be `FLANNELD_ETCD_PREFIX`. 

Second, there is no deterministic way to assign subnets. It functions like DHCP server where the client doesn't control the assigned IP. May I ask why you'd like to have a known subnet? We do plan to add something akin to DHCP reservations when we'll have `flannelctl` utility. This will allow to reserve a subnet for a host like:
`flannelctl reserve-subnet 10.252.42.0/24 192.168.4.5`

**Comment by greenpau** [comment]
> @eyakubovich , It should be FLANNELD_ETCD_PREFIX

will try it out.

> @eyakubovich May I ask why you'd like to have a known subnet?

Sure. In my use case, application is configured to use IP addresses and not tied to DNS at all. This, reservation would help.

Personally, I am not too excited to have overlapping subnets, e.g. `10.252.42.0/24` and  (`10.252.0.0/16` with gateway being `10.252.42.0`). There are kernel checks that might fail because of kernel might think that `10.252.42.0` is the network ID of `10.252.42.0/24`.

I would rather have `flannel%d`interface set to the last IP in the range, i.e. `10.252.42.254`.

**Comment by eyakubovich** [comment]
@greenpau I agree that it's not great to have these overlapping subnets. Theoretically it should work (and does for the most part) but we have found odd corner cases. I'd love to move it to the last IP but I don't think I can tell docker not to use it (you can only give docker a subnet via --bip and it'll give out all addresses up to .255). Obviously for non-docker cases, this is not a concern. Perhaps we should make IP assignment to flannel interface be more configurable. In some cases, it shouldn't even have an IP (e.g. if it's bridged into docker0).

**Comment by greenpau** [comment]
@eyakubovich , I understand the logic. However, given that you are defaulting on `/24` on docker bridge, it seems highly unlikely that docker will lease `.254` address.

**Comment by goacid** [comment]
Regarding reserving subnet, I think it could be a huge improvment.
I've some applications running in docker which are sticked to IP addresses, and each change means full reconfiguration, downtime and so on... 
So if I can reserve a subnet per host, and also fix some IP per VM, it will fix all my troubles.

**Comment by tomdee** [comment]
There is some support for reservations documented here - https://github.com/coreos/flannel/blob/master/Documentation/reservations.md#reservations
