### ISSUE TITLE
How to do service registration in side-kick file when using flannel

### ISSUE THREAD

**Issue by karthikus** [coreos/flannel#198]
Before using flannel, I was registration my service ( COREOS_PRIVATE_IPV4) of the host after performing health checks in my side-kick unit file. I have implemented flannel now and with that I need to register the container IP address in the side-kick unit file. Is there a suggested workflow to do that ?

-Karthik

**Comment by eyakubovich** [comment]
`docker insect` will report eh IP address of the container. Please see https://github.com/coreos/flannel/issues/158 for details.
