### ISSUE TITLE
Tapping traffic between containers using Bro IDS

### ISSUE THREAD

**Issue by sbaks0820** [coreos/flannel#208]
I've been trying to figure out a way to use bro to monitor traffice between two docker containers. I know how to run bro inside a container and monitor that container's network, but I can't figure how to do the job from the outiside.

**Comment by eyakubovich** [comment]
@sbaks0820 Do you want to monitor the traffic between two containers on the same host? Like traffic that goes over docker0 bridge? In that case it maybe more helpful to post on docker lists.

**Comment by sbaks0820** [comment]
I want to be able to do it between different mahines, but given the time I have is too much work. I do want to do it on the same host through the docker0 interface. It's probably a better idea to post about this on docker lists.

**Comment by eyakubovich** [comment]
Closing as not flannel specific.
