### ISSUE TITLE
Question: Can i get the flannel ip allocated to a container via etcd?

### ISSUE THREAD

**Issue by 0x4139** [coreos/flannel#213]
I am looking for a way for the services to autoconfigurate themselves inside a cluster, at this moment i want to use confd to update the host file on each physical machine. Not really sure if it's a good ideea.

**Comment by eyakubovich** [comment]
@0x4139 There's no one best way. You can update hosts file, just have a wrapper script that pulls values out of etcd via etcdctl, or you can use [SkyDNS](https://github.com/skynetservices/skydns) and use SRV records.
