### ISSUE TITLE
etcd2 tls support

### ISSUE THREAD

**Issue by Nalum** [coreos/flannel#222]
Does flannel currently support tls secured etcd2?

**Comment by eyakubovich** [comment]
Yes, although the documentation is not the greatest. See flags: https://github.com/coreos/flannel#key-command-line-options

And https://github.com/coreos/etcd/blob/master/Documentation/security.md#example-2-client-to-server-authentication-with-https-client-certificates talks a bit more about this.

**Comment by Nalum** [comment]
Thanks, so does flannel use the environment vars `FLANNEL_*`? e.g. `FLANNEL_ETCD_KEYFILE`

**Comment by eyakubovich** [comment]
yes but it's `FLANNELD_ETCD_KEYFILE`. So it's `FLANNELD_*` and then upper case option name with hyphens replaced with underscores. A PR to document this would be really appreciated. It was initially not documented as it was primarily done for integration with CoreOS cloud-init but it's useful on its own as well.

**Comment by Nalum** [comment]
If I get my set up working and have time I'll look at doing so.

**Comment by eyakubovich** [comment]
@Nalum I was updating readme last night the next next release and inserted a section on env vars. Thank you for volunteering nevertheless.

**Comment by MohdAhmad** [comment]
Fixed by #227
