### ISSUE TITLE
aws-vpc backend: flannel should be able to disable SrcDestCheck

### ISSUE THREAD

**Issue by vaijab** [coreos/flannel#230]
Flannel requires `SrcDestCheck` to be disabled on each instance when `aws-vpc` backend is used (see how http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_NAT_Instance.html#EIP_Disable_SrcDestCheck).

There is no easy way to disable `SrcDestCheck` when CoreOS is managed by CloudFormation in an ASG. So flannel seems like a good candidate to disable instance `SrcDestCheck` attribute when it starts?

IAM policy action that is required to do so is `ec2:ModifyInstanceAttribute`.

**Comment by eyakubovich** [comment]
I think that's a good idea. If the policy permits it, it should make the change. Do you think it's reasonable to do that by default or should it require an explicit switch?

**Comment by vaijab** [comment]
I think it makes sense to try and disable `SrcDestCheck` by default. Having a switch to turn off this behaviour would help as well I guess - similar behaviour to how routing table id gets discovered.

**Comment by vaijab** [comment]
Thanks!
