### ISSUE TITLE
Timers are Consistently Not Scheduled

### ISSUE THREAD

**Issue by osterman** [coreos/flannel#236]
Timers are working (sporadically), but after upgrading to 717.1.0 and moving to etcd2, I cannot figure out why certain timers are no longer working anymore. 

Here's a demonstration that certain timers started with fleet *are* working correctly.

    core@core3 ~ $ systemctl list-timers --all
    NEXT                         LEFT          LAST                         PASSED       UNIT                            ACTIVATES
    Wed 2015-07-01 03:14:24 UTC  34s left      Wed 2015-07-01 03:13:24 UTC  25s ago      motdgen.timer                   motdgen.service
    Wed 2015-07-01 03:15:00 UTC  1min 10s left Wed 2015-07-01 03:10:00 UTC  3min 49s ago core_os_firewall.timer          core_os_firewall.service
    Wed 2015-07-01 03:20:05 UTC  6min left     Wed 2015-07-01 03:10:05 UTC  3min 44s ago osterman_mysqldump.timer        osterman_mysqldump.service
    Wed 2015-07-01 03:20:05 UTC  6min left     Wed 2015-07-01 03:10:05 UTC  3min 44s ago tp_mysqldump.timer              tp_mysqldump.service
    Wed 2015-07-01 03:20:05 UTC  6min left     Wed 2015-07-01 03:10:05 UTC  3min 44s ago ib_mysqlhotcopy@web_mysql.timer ib_mysqlhotcopy@web_mysql.service
    Wed 2015-07-01 20:25:46 UTC  17h left      Tue 2015-06-30 20:25:47 UTC  6h ago       systemd-tmpfiles-clean.timer    systemd-tmpfiles-clean.service
    n/a                          n/a           n/a                          n/a          update-engine-stub.timer        update-engine-stub.service

Here's an example of destroy+start of a timer that *never* becomes registered or started.

    Calling destroy on isc/mysqlhotcopy@mysql(timer)
    2015/07/01 11:25:39 DEBUG http.go:28: HTTP DELETE http://domain-sock/fleet/v1/units/isc_mysqlhotcopy%40mysql.timer?alt=json
    2015/07/01 11:25:39 DEBUG fleetctl.go:368: Establishing remote fleetctl proxy to /var/run/fleet.sock
    2015/07/01 11:25:46 DEBUG http.go:31: HTTP DELETE http://domain-sock/fleet/v1/units/isc_mysqlhotcopy%40mysql.timer?alt=json 204 No Content
    Destroyed isc_mysqlhotcopy@mysql.timer
    Calling start on isc/mysqlhotcopy@mysql(timer)
    2015/07/01 11:25:50 DEBUG http.go:28: HTTP GET http://domain-sock/fleet/v1/units/isc_mysqlhotcopy%40mysql.timer?alt=json
    2015/07/01 11:25:50 DEBUG fleetctl.go:368: Establishing remote fleetctl proxy to /var/run/fleet.sock
    2015/07/01 11:25:51 DEBUG http.go:31: HTTP GET http://domain-sock/fleet/v1/units/isc_mysqlhotcopy%40mysql.timer?alt=json 404 Not Found
    2015/07/01 11:25:51 DEBUG fleetctl.go:489: Unit(isc_mysqlhotcopy@mysql.timer) found in local filesystem
    2015/07/01 11:25:51 DEBUG http.go:28: HTTP PUT http://domain-sock/fleet/v1/units/isc_mysqlhotcopy%40mysql.timer?alt=json
    2015/07/01 11:25:53 DEBUG http.go:31: HTTP PUT http://domain-sock/fleet/v1/units/isc_mysqlhotcopy%40mysql.timer?alt=json 201 Created
    2015/07/01 11:25:53 DEBUG fleetctl.go:578: Created Unit(isc_mysqlhotcopy@mysql.timer) in Registry
    2015/07/01 11:25:53 DEBUG http.go:28: HTTP GET http://domain-sock/fleet/v1/units/isc_mysqlhotcopy%40mysql.timer?alt=json
    2015/07/01 11:25:53 DEBUG http.go:31: HTTP GET http://domain-sock/fleet/v1/units/isc_mysqlhotcopy%40mysql.timer?alt=json 200 OK
    2015/07/01 11:25:53 DEBUG fleetctl.go:715: Setting Unit(isc_mysqlhotcopy@mysql.timer) target state to launched
    2015/07/01 11:25:53 DEBUG http.go:28: HTTP PUT http://domain-sock/fleet/v1/units/isc_mysqlhotcopy%40mysql.timer?alt=json
    2015/07/01 11:25:56 DEBUG http.go:31: HTTP PUT http://domain-sock/fleet/v1/units/isc_mysqlhotcopy%40mysql.timer?alt=json 204 No Content
    Triggered unit isc_mysqlhotcopy@mysql.timer start

Ordinarily, in fleet's logs, I would see something like this (example is a different timer):

    INFO reconcile.go:330: AgentReconciler completed task: type=LoadUnit job=isc_mysqldump.timer reason="unit scheduled here but not loaded"
    INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=isc_mysqldump.timer reason="unit currently loaded but desired state is launched"

But I'm seeing nothing in fleet's logs at all. It's like the requests don't happen. 

I am seeing these messages sporadically and when I try to submit the timers:

    INFO client.go:298: Response 500 Internal Server Error from http://localhost:4001/ unusable

But the cluster is *healthy* AND I can submit anything that's not a timer with 100% success.

    core@core2 ~ $ etcdctl cluster-health
    cluster is healthy
    member b1f5a744e7eb8a32 is healthy
    member b82916e38bfdd52c is healthy
    member c13bfaa4f4094373 is healthy

**Comment by osterman** [comment]
Resolved. Configuration error realated to `MachineOf=%p.service`. In an effort to document the problem, I uncovered the problem. Thanks for being a sounding board.

**Comment by jonboulle** [comment]
This issue was moved to coreos/fleet#1283
