### ISSUE TITLE
Question: How to get traffic into the Flannel overlay

### ISSUE THREAD

**Issue by xyleth** [coreos/flannel#238]
Hello,

Apologies up front if this is the wrong place for this - please feel free to point me to the correct place.

I'm trialling out a CoreOS cluster with Flannel networking using the VMX backend.  I have a separate etcd2 cluster for the config and a pool of worker nodes running etcd2 proxies.  Flannel is configured to start on the workers and assigns each of them a /24 from the /16 I defined.  I can start containers on each node and they can all communicate with each other via their flannel network IP's cross machine just fine.  The containers can also ping out to other hosts on the network that aren't part of the flannel network.

What I can't figure out, for the life of me, is how I can get a host that is outside the flannel overlay network to consume services offered by a container that is on the overlay network.  I _think_ I need to use a access layer like HAProxy that bridges both the traditional network and the flannel overlay network - but I can't discern the correct magic to make that work.

What I want is to have a number of containers running a web application be reachable via a HAProxy container from machines that are not part of the overlay network - or indeed the wider 'net.  I've tried docker run --net:host or docker run -p <host-IP>:80:80 and a few other variations when starting the HAProxy container but it remains resolutely inaccessible from any host outside the CoreOS cluster participating in the overlay.

Can someone point me in the right direction for how to get this working?  I can really see the potential of Flannel combined with containers but not being able to offer services external to the overlay limits the use cases.

Many thanks for your time,

**Comment by eyakubovich** [comment]
@xyleth you're correct that the best option is to use something like HAProxy as the gateway into your cluster and into the flannel network. So the idea is that HAProxy listens on non-flannel IP (either via `--net=host` or through a port mapping like `-p 80:80` but load balances onto backend instances inside flannel network (by "flannel" IP). If you're using `--net=host` options, just make sure HAProxy binds to all interfaces (`*`) or to the host interface (not `flannel.1`).

It may be easier to debug with `--net=host` and HAProxy bound to all interfaces. If you run `sudo netstat -antp`, do you see HAProxy listening on `0.0.0.0`? If you just `nc` to it from the same host (but not in a container), does that work? What about from a neighbor host (also not in a container)? If that works, shutdown flannel on this neighbor host and try again.

**Comment by xyleth** [comment]
So - fresh day, fresh eyes, solved the problem!

The problem wasn't actually docker or flannel at all.  For the reference of any future googlers who end up on this page - running docker as eyakubovich described works perfectly.  Either --net=host or a more specific -p <HOST IP>:<HOST PORT>:<CONTAINER PORT> works and enables external traffic to reach the HAProxy instance.

If it doesn't seem to be working despite everything being setup correctly be sure to check any firewalls in your environment.  Just because you have SSH access to a docker host doesn't mean you also have HTTP access!  As I found out to the cost of several fruitless hours twiddling Docker when I should have been looking elsewhere o_O

I have it all working now and it's as brilliant as I expected.  Thanks for the response and I'll try not to be so daft next time.

**Comment by mootezbessifi** [comment]
@eyakubovich @xyleth according to this post, may you answer my [question](http://stackoverflow.com/questions/41096951/how-to-connect-local-java-service-to-remote-kubernetes-services) ?
