### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Pensu** [coreos/flannel#242]
So, I am trying to run flanneld on my ubuntu 15.04 system. I have build etcd and it is running fine:

```
pensu@ubuntu:~/etcd$ ./bin/etcd
2015/07/9 01:21:01 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2015/07/9 01:21:01 etcdmain: no data-dir provided, using default data-dir ./default.etcd
2015/07/9 01:21:01 etcdmain: the server is already initialized as member before, starting as etcd member...
2015/07/9 01:21:01 etcdmain: listening for peers on http://localhost:2380
2015/07/9 01:21:01 etcdmain: listening for peers on http://localhost:7001
2015/07/9 01:21:01 etcdmain: listening for client requests on http://localhost:2379
2015/07/9 01:21:01 etcdmain: listening for client requests on http://localhost:4001
2015/07/9 01:21:01 etcdserver: recovered store from snapshot at index 60006
2015/07/9 01:21:01 etcdserver: name = default
2015/07/9 01:21:01 etcdserver: data dir = default.etcd
2015/07/9 01:21:01 etcdserver: member dir = default.etcd/member
2015/07/9 01:21:01 etcdserver: heartbeat = 100ms
2015/07/9 01:21:01 etcdserver: election = 1000ms
2015/07/9 01:21:01 etcdserver: snapshot count = 10000
2015/07/9 01:21:01 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/07/9 01:21:01 etcdserver: loaded cluster information from store: <nil>
2015/07/9 01:21:01 etcdserver: restarting member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit index 63939
2015/07/9 01:21:01 raft: ce2a822cea30bfca became follower at term 7
2015/07/9 01:21:01 raft: newRaft ce2a822cea30bfca [peers: [ce2a822cea30bfca], term: 7, commit: 63939, applied: 60006, lastindex: 63939, lastterm: 7]
2015/07/9 01:21:01 etcdserver: starting server... [version: 2.1.0-rc.0+git, cluster version: 2.1.0]
2015/07/9 01:21:02 raft: ce2a822cea30bfca is starting a new election at term 7
2015/07/9 01:21:02 raft: ce2a822cea30bfca became candidate at term 8
2015/07/9 01:21:02 raft: ce2a822cea30bfca received vote from ce2a822cea30bfca at term 8
2015/07/9 01:21:02 raft: ce2a822cea30bfca became leader at term 8
2015/07/9 01:21:02 raft: raft.node: ce2a822cea30bfca elected leader ce2a822cea30bfca at term 8
2015/07/9 01:21:02 etcdserver: published {Name:default ClientURLs:[http://localhost:2379 http://localhost:4001]} to cluster 7e27652122e8b2ae
```

Now, I build flannel and ran sudo ./bin/flanneld and I am getting run time error along with a bunch of goroutines:

```
go-etcd2015/07/09 01:40:23 DEBUG: recv.response.from 
go-etcd2015/07/09 01:40:23 DEBUG: recv.success 
I0709 01:40:23.355832 02558 udp.go:247] Subnet added: 10.14.32.0/20
go-etcd2015/07/09 01:40:23 DEBUG: rawWatch /coreos.com/network/subnets []
go-etcd2015/07/09 01:40:23 DEBUG: get /coreos.com/network/subnets [http://127.0.0.1:4001]
go-etcd2015/07/09 01:40:23 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets?recursive=true&wait=true&waitIndex=129
go-etcd2015/07/09 01:40:23 DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/coreos.com/network/subnets?recursive=true&wait=true&waitIndex=129 | method GET
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0]

goroutine 28 [running]:
udp.setRoute
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/cproxy.go:66
github_com_coreos_flannel_backend_udp.processSubnetEvents.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:249
github_com_coreos_flannel_backend_udp.monitorEvents.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:235
github_com_coreos_flannel_backend_udp.Run.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:141
network.$nested4
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/network/network.go:109
created by github_com_coreos_flannel_network.Run.pN41_github_com_coreos_flannel_network.Network
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/network/network.go:108

goroutine 16 [chan receive]:
main.main
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/main.go:288
created by main
    ../../../src/libgo/runtime/go-main.c:42

goroutine 18 [finalizer wait]:
created by runtime_createfing
    ../../../src/libgo/runtime/mgc0.c:2572

goroutine 19 [syscall]:
    goroutine in C code; stack unavailable
created by os_signal..import
    ../../../src/libgo/go/os/signal/signal_unix.go:25

goroutine 20 [chan receive]:
github_com_coreos_flannel_Godeps__workspace_src_github_com_golang_glog.flushDaemon.pN79_github_com_coreos_flannel_Godeps__workspace_src_github_com_golang_glog.loggingT
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog/glog.go:839
created by glog.$init0
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog/glog.go:406

goroutine 24 [chan receive]:
github_com_coreos_flannel_network.Run.pN41_github_com_coreos_flannel_network.Network
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/network/network.go:113
main.$nested2
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/main.go:217
created by main.initAndRun
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/main.go:199

goroutine 26 [IO wait]:
net.runtime_pollWait
    ../../../src/libgo/runtime/netpoll.goc:151
net.Wait.pN12_net.pollDesc
    ../../../src/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
    ../../../src/libgo/go/net/fd_poll_runtime.go:89
net.Read.pN9_net.netFD
    ../../../src/libgo/go/net/fd_unix.go:242
net.Read.pN8_net.conn
    ../../../src/libgo/go/net/net.go:121
net.Read.pN11_net.TCPConn
    ../../../src/libgo/go/net/tcpsock_posix.go:57
net_http.Read.N22_net_http.noteEOFReader
    ../../../src/libgo/go/net/http/transport.go:1270
bufio.fill.pN12_bufio.Reader
    ../../../src/libgo/go/bufio/bufio.go:97
bufio.Peek.pN12_bufio.Reader
    ../../../src/libgo/go/bufio/bufio.go:132
net_http.readLoop.pN20_net_http.persistConn
    ../../../src/libgo/go/net/http/transport.go:842
created by net_http.dialConn.pN18_net_http.Transport
    ../../../src/libgo/go/net/http/transport.go:660

goroutine 27 [runnable]:
net_http.writeLoop.pN20_net_http.persistConn
    ../../../src/libgo/go/net/http/transport.go:945
created by net_http.dialConn.pN18_net_http.Transport
    ../../../src/libgo/go/net/http/transport.go:661

goroutine 29 [syscall]:
    goroutine in C code; stack unavailable
created by github_com_coreos_flannel_backend_udp.Run.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:131

goroutine 30 [select]:
github_com_coreos_flannel_subnet.LeaseRenewer
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/subnet/renew.go:32
udp.$nested1
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:137
created by github_com_coreos_flannel_backend_udp.Run.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:136

goroutine 31 [select]:
github_com_coreos_flannel_subnet.watchSubnets.pN51_github_com_coreos_flannel_subnet.etcdSubnetRegistry
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/subnet/registry.go:151
github_com_coreos_flannel_subnet.WatchLeases.pN44_github_com_coreos_flannel_subnet.EtcdManager
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/subnet/etcd.go:313
github_com_coreos_flannel_subnet.WatchLeases
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/subnet/watch.go:33
udp.$nested2
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:228
created by github_com_coreos_flannel_backend_udp.monitorEvents.pN48_github_com_coreos_flannel_backend_udp.UdpBackend
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/udp.go:227

goroutine 33 [select]:
net_http.roundTrip.pN20_net_http.persistConn
    ../../../src/libgo/go/net/http/transport.go:1082
net_http.RoundTrip.pN18_net_http.Transport
    ../../../src/libgo/go/net/http/transport.go:235
http.send
    ../../../src/libgo/go/net/http/client.go:219
net_http.send.pN15_net_http.Client
    ../../../src/libgo/go/net/http/client.go:142
net_http.doFollowingRedirects.pN15_net_http.Client
    ../../../src/libgo/go/net/http/client.go:367
net_http.Do.pN15_net_http.Client
    ../../../src/libgo/go/net/http/client.go:174
github_com_coreos_flannel_Godeps__workspace_src_github_com_coreos_go_etcd_etcd.SendRequest.pN85_github_com_coreos_flannel_Godeps__workspace_src_github_com_coreos_go_etcd_etcd.Client
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go:238
github_com_coreos_flannel_Godeps__workspace_src_github_com_coreos_go_etcd_etcd.getCancelable.pN85_github_com_coreos_flannel_Godeps__workspace_src_github_com_coreos_go_etcd_etcd.Client
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go:51
github_com_coreos_flannel_Godeps__workspace_src_github_com_coreos_go_etcd_etcd.watchOnce.pN85_github_com_coreos_flannel_Godeps__workspace_src_github_com_coreos_go_etcd_etcd.Client
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/watch.go:96
github_com_coreos_flannel_Godeps__workspace_src_github_com_coreos_go_etcd_etcd.RawWatch.pN85_github_com_coreos_flannel_Godeps__workspace_src_github_com_coreos_go_etcd_etcd.Client
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/watch.go:61
subnet.$nested0
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/subnet/registry.go:132
created by github_com_coreos_flannel_subnet.watchSubnets.pN51_github_com_coreos_flannel_subnet.etcdSubnetRegistry
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/subnet/registry.go:129

goroutine 34 [runnable]:
created by github_com_coreos_flannel_Godeps__workspace_src_github_com_coreos_go_etcd_etcd.SendRequest.pN85_github_com_coreos_flannel_Godeps__workspace_src_github_com_coreos_go_etcd_etcd.Client
    /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go:146
```

I have created the config file too, any idea what could be causing this problem?

**Comment by eyakubovich** [comment]
@Pensu It looks like it crashes when it tries to call into C code (or it crashes inside C code). Let's make sure it's not something wrong with your build. If you're on x86-64 arch, can you try the pre-built binary we provide: https://github.com/coreos/flannel/releases/download/v0.5.0/flannel-0.5.0-linux-amd64.tar.gz

If that also crashes, we'll can try running it under gdb to get a better idea. If it works, we'll try to understand why the build is broken.

**Comment by jcollie** [comment]
Not sure if it's the exact same problem, but I get the same error message.  I'm using the pre-built binaries on a Fedora 22 system.

# /opt/flannel/flannel-0.5.0/flanneld -ip-masq -etcd-endpoints http://127.0.0.1:2379
I0709 13:55:06.246292 29102 main.go:275] Installing signal handlers
I0709 13:55:06.246777 29102 main.go:141] Determining IP address of default interface
I0709 13:55:06.248235 29102 main.go:189] Using 161.210.221.8 as external interface
go-etcd2015/07/09 13:55:06 DEBUG: get /coreos.com/network/config [http://127.0.0.1:2379]
go-etcd2015/07/09 13:55:06 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false
go-etcd2015/07/09 13:55:06 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false | method GET
go-etcd2015/07/09 13:55:06 DEBUG: recv.response.from 
go-etcd2015/07/09 13:55:06 DEBUG: recv.success 
go-etcd2015/07/09 13:55:06 DEBUG: get /coreos.com/network/config [http://127.0.0.1:2379]
go-etcd2015/07/09 13:55:06 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false
go-etcd2015/07/09 13:55:06 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false | method GET
go-etcd2015/07/09 13:55:06 DEBUG: recv.response.from 
go-etcd2015/07/09 13:55:06 DEBUG: recv.success 
go-etcd2015/07/09 13:55:06 DEBUG: get /coreos.com/network/subnets [http://127.0.0.1:2379]
go-etcd2015/07/09 13:55:06 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false
go-etcd2015/07/09 13:55:06 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false | method GET
go-etcd2015/07/09 13:55:06 DEBUG: recv.response.from 
go-etcd2015/07/09 13:55:06 DEBUG: recv.success 
I0709 13:55:06.261982 29102 etcd.go:136] Found lease (10.16.9.0/24) for current IP (161.210.221.8), reusing
go-etcd2015/07/09 13:55:06 DEBUG: put /coreos.com/network/subnets/10.16.9.0-24, {"PublicIP":"161.210.221.8"}, ttl: 86400, [http://127.0.0.1:2379]
go-etcd2015/07/09 13:55:06 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets/10.16.9.0-24
go-etcd2015/07/09 13:55:06 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/subnets/10.16.9.0-24 | method PUT
go-etcd2015/07/09 13:55:06 DEBUG: recv.response.from 
go-etcd2015/07/09 13:55:06 DEBUG: recv.success 
I0709 13:55:06.292205 29102 etcd.go:91] Subnet lease acquired: 10.16.9.0/24
I0709 13:55:06.302705 29102 ipmasq.go:47] Adding iptables rule: FLANNEL -d 10.16.0.0/16 -j ACCEPT
I0709 13:55:06.312506 29102 ipmasq.go:47] Adding iptables rule: FLANNEL ! -d 224.0.0.0/4 -j MASQUERADE
I0709 13:55:06.321538 29102 ipmasq.go:47] Adding iptables rule: POSTROUTING -s 10.16.0.0/16 -j FLANNEL
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ded84]

goroutine 16 [running]:
github.com/coreos/flannel/subnet.LeaseRenewer(0x7fc04d6783e8, 0xc20800b0c0, 0x7fc04d678310, 0xc20802ab60, 0x0, 0x0, 0x0)
	/opt/flannel/gopath/src/github.com/coreos/flannel/subnet/renew.go:29 +0x4e4
github.com/coreos/flannel/backend/alloc.(*AllocBackend).Run(0xc20800b100)
	/opt/flannel/gopath/src/github.com/coreos/flannel/backend/alloc/alloc.go:54 +0x6a
github.com/coreos/flannel/network.func·005()
	/opt/flannel/gopath/src/github.com/coreos/flannel/network/network.go:109 +0x4c
created by github.com/coreos/flannel/network.(*Network).Run
	/opt/flannel/gopath/src/github.com/coreos/flannel/network/network.go:111 +0xfb

goroutine 1 [chan receive]:
main.main()
	/opt/flannel/gopath/src/github.com/coreos/flannel/main.go:288 +0xa2a

goroutine 5 [chan receive]:
github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0xd4d1e0)
	/opt/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
created by github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog.init·1
	/opt/flannel/gopath/src/github.com/coreos/flannel/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [chan receive]:
github.com/coreos/flannel/network.(*Network).Run(0xc20800a880, 0x7fc04d6783e8, 0xc20800a440)
	/opt/flannel/gopath/src/github.com/coreos/flannel/network/network.go:113 +0x134
main.func·003(0xc20800a880)
	/opt/flannel/gopath/src/github.com/coreos/flannel/main.go:217 +0x268
created by main.initAndRun
	/opt/flannel/gopath/src/github.com/coreos/flannel/main.go:220 +0x84b

goroutine 11 [IO wait]:
net.(*pollDesc).Wait(0xc208010760, 0x72, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010760, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010700, 0xc2080bb000, 0x1000, 0x1000, 0x0, 0x7fc04d677e68, 0xc2080ca4e0)
	/usr/src/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20802c0c0, 0xc2080bb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fc04d679618, 0xc20802c0c0, 0xc208090268, 0xc2080bb000, 0x1000, 0x1000, 0x7fb260, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc20801f200, 0xc2080bb000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc20804e720)
	/usr/src/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc20804e720, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc208090210)
	/usr/src/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc208090210)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc

**Comment by jcollie** [comment]
I get the same error on a CentOS 7 system.

**Comment by eyakubovich** [comment]
@jcollie Your crash is `alloc` backend specific. I will fix it today and cut 0.5.1 release.

**Comment by jcollie** [comment]
@eyakubovich Thanks!

**Comment by eyakubovich** [comment]
@jcollie Your crashed is fixed by https://github.com/coreos/flannel/pull/245

**Comment by Pensu** [comment]
@eyakubovich Hi, sorry for  the delayed reply. I am not on x86-64 arch, so I have to build it manually. Though it builds up cleanly:

```
pensu@ubuntu:~/flannel$ ./build 
Building flanneld...
pensu@ubuntu:~/flannel$ 
```

Is there any other way to figure out what is wrong with my build?
And yeah, I am using gccgo.

**Comment by Pensu** [comment]
Update: So, I tried to run it once again, after building it again, and here is the new error I am getting:

```
go-etcd2015/07/15 03:32:52 DEBUG: get /coreos.com/network/subnets [http://127.0.0.1:2379]
go-etcd2015/07/15 03:32:52 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false
go-etcd2015/07/15 03:32:52 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false | method GET
go-etcd2015/07/15 03:32:52 DEBUG: recv.response.from 
go-etcd2015/07/15 03:32:52 DEBUG: recv.success 
I0715 03:32:52.866715 12871 etcd.go:136] Found lease (10.16.0.0/20) for current IP (192.168.122.42), reusing
go-etcd2015/07/15 03:32:52 DEBUG: put /coreos.com/network/subnets/10.16.0.0-20, {"PublicIP":"192.168.122.42"}, ttl: 86400, [http://127.0.0.1:2379]
go-etcd2015/07/15 03:32:52 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets/10.16.0.0-20
go-etcd2015/07/15 03:32:52 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/subnets/10.16.0.0-20 | method PUT
go-etcd2015/07/15 03:32:52 DEBUG: recv.response.from 
go-etcd2015/07/15 03:32:52 DEBUG: recv.success 
I0715 03:32:52.943912 12871 etcd.go:91] Subnet lease acquired: 10.16.0.0/20
E0715 03:32:52.944113 12871 network.go:71] Failed to initialize network  (type UDP): failed to lookup interface flannel%d
go-etcd2015/07/15 03:32:53 DEBUG: get /coreos.com/network/config [http://127.0.0.1:2379]
go-etcd2015/07/15 03:32:53 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false
go-etcd2015/07/15 03:32:53 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false | method GET
go-etcd2015/07/15 03:32:53 DEBUG: recv.response.from 
go-etcd2015/07/15 03:32:53 DEBUG: recv.success 
go-etcd2015/07/15 03:32:53 DEBUG: get /coreos.com/network/subnets [http://127.0.0.1:2379]
go-etcd2015/07/15 03:32:53 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false
go-etcd2015/07/15 03:32:53 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/subnets?quorum=false&recursive=true&sorted=false | method GET
go-etcd2015/07/15 03:32:53 DEBUG: recv.response.from 
go-etcd2015/07/15 03:32:53 DEBUG: recv.success 
I0715 03:32:53.947115 12871 etcd.go:136] Found lease (10.16.0.0/20) for current IP (192.168.122.42), reusing
go-etcd2015/07/15 03:32:53 DEBUG: put /coreos.com/network/subnets/10.16.0.0-20, {"PublicIP":"192.168.122.42"}, ttl: 86400, [http://127.0.0.1:2379]
go-etcd2015/07/15 03:32:53 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/subnets/10.16.0.0-20
go-etcd2015/07/15 03:32:53 DEBUG: send.request.to http://127.0.0.1:2379/v2/keys/coreos.com/network/subnets/10.16.0.0-20 | method PUT
go-etcd2015/07/15 03:32:54 DEBUG: recv.response.from 
go-etcd2015/07/15 03:32:54 DEBUG: recv.success 
I0715 03:32:54.082400 12871 etcd.go:91] Subnet lease acquired: 10.16.0.0/20
E0715 03:32:54.083174 12871 network.go:71] Failed to initialize network  (type UDP): failed to lookup interface flannel%d
```

@eyakubovich And it just keeps on looping like that. Is that my system's issue not to be able to work with udp or gccgo problem?

**Comment by eyakubovich** [comment]
@Pensu This is very odd. It seems like it is able to create a TUN device but does not return the device name (kernel gets asked to create a "flannel%d" device and it's supposed to replace %d with a number and return the actual name). Since there's a bit of unsafe pointer casting that happens, I wonder if this does not work well in gogcc+your arch. Is your arch supported by official Go compiler? Can you test with that?

**Comment by Pensu** [comment]
@eyakubovich I have a flannel device with me:
```
pensu@ubuntu:~/flannel$ ifconfig
docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99  
          inet addr:10.10.112.1  Bcast:10.10.127.255  Mask:255.255.240.0
          inet6 addr: fe80::5484:7aff:fefe:9799/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:106 errors:0 dropped:0 overruns:0 frame:0
          TX packets:81 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:8128 (8.1 KB)  TX bytes:9034 (9.0 KB)

eth0      Link encap:Ethernet  HWaddr 52:54:c7:a8:7a:40  
          inet addr:192.168.122.119  Bcast:192.168.122.255  Mask:255.255.255.0
          inet6 addr: fe80::5054:c7ff:fea8:7a40/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1408181 errors:0 dropped:7 overruns:0 frame:0
          TX packets:1339446 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:349216618 (349.2 MB)  TX bytes:141199500 (141.1 MB)

flannel.1 Link encap:Ethernet  HWaddr 02:46:8f:eb:c9:b6  
          inet addr:10.0.87.0  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::46:8fff:feeb:c9b6/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:41 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:42916 errors:0 dropped:0 overruns:0 frame:0
          TX packets:42916 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2748640 (2.7 MB)  TX bytes:2748640 (2.7 MB)

vethcdc728a Link encap:Ethernet  HWaddr 96:3a:d5:58:b8:77  
          inet6 addr: fe80::943a:d5ff:fe58:b877/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1450  Metric:1
          RX packets:26 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2244 (2.2 KB)  TX bytes:774 (774.0 B)
```
Now, sometimes I get that panic error and sometimes this device error. And my arch isn't supported by official go compiler. Is there any other to figure out what exactly could be causing this problem?

**Comment by eyakubovich** [comment]
@Pensu From earlier logs, it looked like you were using `udp` (default) backend. But if you have `flannel.1` interface, that's from `vxlan` backend. Is the `flannel.1` interface left from a previous config? If you tried `vxlan` backend, did that work?

Can you run flannel under `gdb` and see where it segfaults and poke around? What arch are you using? I can try to check if there're any issues filed with gcc regarding that arch and calling out to C.

**Comment by Pensu** [comment]
@eyakubovich Yeah, I tried with vxlan too and it didn't work. Looks like with vxlan, I am not able to return that particular device and with udp I am getting that panic error. 

Sure, I will try to run flannel under gdb. I am using ppc64le.

**Comment by Pensu** [comment]
@eyakubovich So I ran flannel with gdb and looks like NetworkOrder() is failing. I don't know for sure, as my gdb skills are not that strong. Here is what I am getting:

```
(gdb) 
github_com_coreos_flannel_pkg_ip.NetworkOrder.N36_github_com_coreos_flannel_pkg_ip.IP4 (pointer=0xc208010660)
    at /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/pkg/ip/ipnet.go:67
67			a, b, c, d := byte(ip>>24), byte(ip>>16), byte(ip>>8), byte(ip)
(gdb) 
68			return uint32(a) | (uint32(b) << 8) | (uint32(c) << 16) | (uint32(d) << 24)
(gdb) 
65	func (ip IP4) NetworkOrder() uint32 {
(gdb) 
udp.setRoute (ctl=0xc208011070, param=3232266794, param=3232266794, nextHopPort=7890)
    at /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/cproxy.go:67
67			cmd:           C.CMD_SET_ROUTE,
(gdb) 
66		cmd := C.command{
(gdb) 

Program received signal SIGSEGV, Segmentation fault.
udp.setRoute (ctl=0xc208011070, param=3232266794, param=3232266794, nextHopPort=7890)
    at /home/pensu/work/flannel/gopath/src/github.com/coreos/flannel/backend/udp/cproxy.go:66
66		cmd := C.command{
```

Any thoughts?

**Comment by Pensu** [comment]
I tried to run a sample program to get value of C.CMD_SET_ROUTE, but the program threw an error:

```
pensu@ubuntu:~$ go run test.go 
# command-line-arguments
could not determine kind of name for C.CMD_SET_ROUTE
```

And I am not able to find where exactly that variable is defined.

**Comment by eyakubovich** [comment]
@Pensu I don't know why it would be segfaulting when just doing integer bitwise operations. Maybe it's segfaulting when calling `NativelyLittle()`. Can you try to determine from the gdb if `NativeEndian` (https://github.com/coreos/flannel/blob/master/pkg/ip/endianess.go#L26) is set to something valid? You can also try to put `fmt.Printf` statements around that region to see where it's segfaulting and locate the bad pointer. I wish I had access to ppc64le machine so that I could test.

**Comment by Pensu** [comment]
Okay, I have one more thought. I put one fmt.Println(C.CMD_SET_ROUTE), just before C.command{} statement, and it segfaulted even before reaching that. Could the issue be with C call only? Can you try to replicate the issue with gccgo?

**Comment by eyakubovich** [comment]
I'm thinking it might be gccgo + ppc64le specific issue of calling into C code. Can you just make a very simple Go program that will call in to C (like just call C.getpid()) and see if that works?

**Comment by Pensu** [comment]
@eyakubovich Ok, I tried that. Here is the result:

```
pensu@ubuntu:~$ go run test_new.go 
# command-line-arguments
could not determine kind of name for C.getpid
```

Here is the content of test_new.go:
```
pensu@ubuntu:~$ cat test_new.go 
package main
import "C"
import "fmt"

func main(){
	fmt.Println(C.getpid())
}
```

Yeah, it doesn't work! Do I need a header file or anything for that? Or "import C" takes care of that?

**Comment by Pensu** [comment]
@eyakubovich The C calls are working fine, here is the program I am running:
```
pensu@ubuntu:~$ cat test_new.go 
package main

// #include<sys/types.h>
// #include<unistd.h>
import "C"
import "fmt"

func main(){
	fmt.Println(C.getpid())
}
```

And here is the output:
```
pensu@ubuntu:~$ go run test_new.go
27927
```


And I checked NativeEndian too, it's working completely fine. It returns "ture" only.

**Comment by tomdee** [comment]
Closing this stale issue
