### ISSUE TITLE
docker seems to start before flannel sets the network so docker0 remains 172

### ISSUE THREAD

**Issue by jon-shanks** [coreos/flannel#246]
For some reason, docker initiates and sets the networking for the interface before flannel runs and sets the /run/flannel_docker_opts.env . Despite reboots for some reason it never manages to pick up the correct network:

I can see docker.service sources the run flannel docker opts:
EnvironmentFile=-/run/flannel_docker_opts.env

However 
ip addr show dev docker0
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/ether 2a:e4:02:28:63:1e brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0

cat /run/flannel_docker_opts.env
DOCKER_OPT_BIP="--bip=10.102.20.1/24"
DOCKER_OPT_IPMASQ="--ip-masq=false"
DOCKER_OPT_MTU="--mtu=1450"

The link has to be downed and the service restarted to place this on the network. I've set the drop in for the network set for etcd for flannel to Type=notify though the flannel service is set  to notify anyway

**Comment by jon-shanks** [comment]
-- Reboot --
Jul 09 21:03:21 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk systemd[1]: Started Docker Application Container Engine.
Jul 09 21:03:21 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk systemd[1]: Starting Docker Application Container Engine...
Jul 09 21:03:21 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk dockerd[606]: time="2015-07-09T21:03:21Z" level=info msg="+job serveapi(fd://)"
Jul 09 21:03:21 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk dockerd[606]: time="2015-07-09T21:03:21Z" level=info msg="Listening for HTTP on fd ()"
Jul 09 21:03:21 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk dockerd[606]: time="2015-07-09T21:03:21Z" level=info msg="+job init_networkdriver()"
Jul 09 21:03:21 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk systemd[1]: Starting Network fabric for containers...
Jul 09 21:03:22 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk dockerd[606]: time="2015-07-09T21:03:22Z" level=info msg="-job init_networkdriver() = OK (0)"
Jul 09 21:03:23 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk dockerd[606]: time="2015-07-09T21:03:23Z" level=info msg="Loading containers: start."
Jul 09 21:03:23 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk dockerd[606]: time="2015-07-09T21:03:23Z" level=info msg="Loading containers: done."
Jul 09 21:03:23 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk dockerd[606]: time="2015-07-09T21:03:23Z" level=info msg="docker daemon: 1.6.2 7c8fca2-dirty; execdriver: n
Jul 09 21:03:23 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk dockerd[606]: time="2015-07-09T21:03:23Z" level=info msg="+job acceptconnections()"
Jul 09 21:03:23 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk dockerd[606]: time="2015-07-09T21:03:23Z" level=info msg="-job acceptconnections() = OK (0)"
Jul 09 21:03:23 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk dockerd[606]: time="2015-07-09T21:03:23Z" level=info msg="Daemon has completed initialization"
Jul 09 21:03:25 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk etcdctl[690]: { "Network": "10.102.0.0/16", "Backend" : { "Type" : "vxlan" } }
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.217817 00001 main.go:278] Installing signal handlers
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.218007 00001 main.go:138] Determining IP address of default interface
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.218243 00001 main.go:228] Using 10.70.2.18 as external interface
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.543657 00001 subnet.go:97] Subnet lease acquired: 10.102.20.0/24
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.588362 00001 ipmasq.go:47] Adding iptables rule: FLANNEL -d 10.102.0.0/
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.591035 00001 ipmasq.go:47] Adding iptables rule: FLANNEL ! -d 224.0.0.0
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.593387 00001 ipmasq.go:47] Adding iptables rule: POSTROUTING -s 10.102.
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.596659 00001 main.go:245] VXLAN mode initialized
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.596710 00001 vxlan.go:141] Watching for L2/L3 misses
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.596750 00001 vxlan.go:147] Watching for new subnet leases
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.602333 00001 vxlan.go:210] Subnet added: 10.102.24.0/24
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk sdnotify-proxy[747]: I0709 21:03:26.602564 00001 vxlan.go:210] Subnet added: 10.102.3.0/24
Jul 09 21:03:26 dvcorshnode01.dev.checkingservice.homeoffice.gov.uk systemd[1]: Started Network fabric for containers.

**Comment by eyakubovich** [comment]
@jon-shanks Are you using cloud-config? If so, can you make sure that flannel is listed first in your cloud-config and other units that start up docker container list `flanneld.service` as a dependency (via Requires=). Please see https://coreos.com/docs/cluster-management/setup/flannel-config/#enabling-flannel-via-cloud-config for more info.

If that does not help, could you provide your cloud-config and also the output of `journalctl -b -u docker.service -u early-docker.service -u flanneld.service`.

**Comment by Smana** [comment]
Hi all,

I've the same issue there : docker starts the bridge docker0 instead of binding on the flannel network.

Please find my cloud-config here based on this configuration https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md :

https://gist.github.com/Smana/d337d6e987261fd60b0d

flannel seems to be working : 
```
�� flanneld.service - Network fabric for containers
   Loaded: loaded (/usr/lib64/systemd/system/flanneld.service; static; vendor preset: disabled)
  Drop-In: /etc/systemd/system/flanneld.service.d
           ������50-network-config.conf
   Active: active (running) since Fri 2015-07-10 12:46:41 UTC; 11min ago
     Docs: https://github.com/coreos/flannel
  Process: 825 ExecStartPost=/usr/bin/docker run --net=host --rm -v /run:/run quay.io/coreos/flannel:${FLANNEL_VER} /opt/bin/mk-docker-opts.sh -d /run/flannel_docker_opts.env -i (code=exited, status=0/SUCCESS)
  Process: 728 ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config {"Network":"10.244.0.0/16", "Backend": {"Type": "vxlan"}} (code=exited, status=0/SUCCESS)
  Process: 726 ExecStartPre=/usr/bin/touch /run/flannel/options.env (code=exited, status=0/SUCCESS)
  Process: 724 ExecStartPre=/usr/bin/mkdir -p ${ETCD_SSL_DIR} (code=exited, status=0/SUCCESS)
  Process: 720 ExecStartPre=/usr/bin/mkdir -p /run/flannel (code=exited, status=0/SUCCESS)
  Process: 718 ExecStartPre=/sbin/modprobe ip_tables (code=exited, status=0/SUCCESS)
 Main PID: 735 (sdnotify-proxy)
   Memory: 48.0K
      CPU: 49ms
   CGroup: /system.slice/flanneld.service
           ������735 /usr/libexec/sdnotify-proxy /run/flannel/sd.sock /usr/bin/docker run --net=host --privileged=true --rm --volume=/run/flannel:/run/flannel --env=NOTIFY_SOCKET=/run/flannel/sd.sock --env=AWS_ACCESS_KEY_ID= --env=AWS_SECRET_ACCESS_KEY= --env-file=/run/flannel/options.env --volume=/usr/share/ca-certif...
           ������739 /usr/bin/docker run --net=host --privileged=true --rm --volume=/run/flannel:/run/flannel --env=NOTIFY_SOCKET=/run/flannel/sd.sock --env=AWS_ACCESS_KEY_ID= --env=AWS_SECRET_ACCESS_KEY= --env-file=/run/flannel/options.env --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro --volume=/etc/ssl/etcd:/...

Jul 10 12:46:41 coreos0 sdnotify-proxy[735]: I0710 12:46:41.495377 00001 subnet.go:97] Subnet lease acquired: 10.244.19.0/24
Jul 10 12:46:41 coreos0 sdnotify-proxy[735]: I0710 12:46:41.510800 00001 ipmasq.go:47] Adding iptables rule: FLANNEL -d 10.244.0.0/16 -j ACCEPT
Jul 10 12:46:41 coreos0 sdnotify-proxy[735]: I0710 12:46:41.518456 00001 ipmasq.go:47] Adding iptables rule: FLANNEL ! -d 224.0.0.0/4 -j MASQUERADE
Jul 10 12:46:41 coreos0 sdnotify-proxy[735]: I0710 12:46:41.525240 00001 ipmasq.go:47] Adding iptables rule: POSTROUTING -s 10.244.0.0/16 -j FLANNEL
Jul 10 12:46:41 coreos0 sdnotify-proxy[735]: I0710 12:46:41.538302 00001 main.go:245] VXLAN mode initialized
Jul 10 12:46:41 coreos0 sdnotify-proxy[735]: I0710 12:46:41.538472 00001 vxlan.go:141] Watching for L2/L3 misses
Jul 10 12:46:41 coreos0 sdnotify-proxy[735]: I0710 12:46:41.538939 00001 vxlan.go:147] Watching for new subnet leases
Jul 10 12:46:41 coreos0 systemd[1]: Started Network fabric for containers.
Jul 10 12:47:07 coreos0 sdnotify-proxy[735]: I0710 12:47:07.405754 00001 vxlan.go:210] Subnet added: 10.244.42.0/24
Jul 10 12:47:08 coreos0 sdnotify-proxy[735]: I0710 12:47:08.895302 00001 vxlan.go:210] Subnet added: 10.244.39.0/24
```

my ip configurtion : 
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:a2:99:99 brd ff:ff:ff:ff:ff:ff
    inet 10.115.200.90/16 brd 10.115.255.255 scope global dynamic eth0
       valid_lft 20778sec preferred_lft 20778sec
    inet 10.115.77.86/16 brd 10.115.255.255 scope global secondary eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fea2:9999/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default 
    link/ether 7a:a8:12:ea:6e:d9 brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::78a8:12ff:feea:6ed9/64 scope link 
       valid_lft forever preferred_lft forever
4: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 4e:78:4b:34:06:f5 brd ff:ff:ff:ff:ff:ff
    inet 10.244.19.0/16 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::4c78:4bff:fe34:6f5/64 scope link 
       valid_lft forever preferred_lft forever
```
routes
```
default via 10.115.255.253 dev eth0  proto static 
10.0.0.0/8 via 10.115.255.254 dev eth0  proto static 
10.115.0.0/16 dev eth0  proto kernel  scope link  src 10.115.200.90 
10.244.0.0/16 dev flannel.1  proto kernel  scope link  src 10.244.19.0 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.42.1 
192.168.0.0/17 via 10.115.255.254 dev eth0  proto static
```
my logs are available here https://gist.github.com/Smana/0dd847b0fe52d0e44ab4

Please let me know if you need further info.

Regards,
Smana

**Comment by jon-shanks** [comment]
Hi actually I have resolved this, it was some dependency chain in other things causing this to mess up. i've cleaned up the cloud config a lot and now it "Almost" works, though, docker0 doesn't come up. is there a reason why docker0 actually requires a start unit in the cloud-config for it to start. It's almost like the coreos-overlay with early-docker prevents it actually coming up without this?

**Comment by jon-shanks** [comment]
I'm going to close this issue and let smana raise one separately to relate it as the issue i have is now different to what i've put in and that issue isn't an issue for me right now
