### ISSUE TITLE
Ability to overlap exposed `PublicIp` on subnet instead of using only `extIp`

### ISSUE THREAD

**Issue by cusspvz** [coreos/flannel#258]
I've set `cloud-config.coreos.flannel.interface` as `$public_ip` but it doesn't work since i don't have any interface with that IP.

`flannel` keeps posting its **private ip** as **PublicIP** on subnet config files, since other nodes cannot reach those IPs flannel isn't working.

Is there a way to overlap this behavior? If not, is there a way to implement this as an option on `config`?

Thanks,
José Moreira

**Comment by cusspvz** [comment]
After reading a huge part of this repo code and submitted issues I would suggest the addition of an attribute on `SubNet` called `PrivateIp`.

`PublicIp` would be the endpoint for node external relative connections and `PrivateIp` for internal configurations such as interface and ip tables. For avoiding BC on future **CoreOS** updates, `PrivateIp` should default to `PublicIp` in case it isn't defined or is invalid;

Pros:
* Real distinguish between `PublicIP` and `PrivateIP` (as **CoreOS** does);
* `udp` backend could be used on different network structures (depending on them, `vxnet` could be also), allowing expansion of a cluster on different IaaS providers or even bare metal without having to configure their network structures manually;

Cons: 
* Don't know if it could be a BC on updates. Suppose that it hasn't with defaulting of `PrivateIp` by `PublicIp`, but as I'm not sure it could be a Con.

I would like to hear your oppinion @eyakubovich .

**Comment by eyakubovich** [comment]
@cusspvz I'm sorry but I'm not sure I understand your proposal. flannel needs just one IP/interface over which it can operate. That's the interface over which the packets are forwarded to other nodes on the flannel network. I must admit that the name `PublicIP` is not great -- it's the "real" IP that is route-able on the network.

CoreOS has private and public IPs that refer to LAN and WAN addresses (e.g. 10.x.x.x and 54.x.x.x). Depending on the environment, it's sometimes better to set `cloud-config.coreos.flannel.interface` to `$private_ip` so the cluster communicates between each other on RFC1918 addresses. By default, flannel uses the interface associated with the default route -- unfortunately this is often not the best choice but there's no good way to guess the right choice.

Are you running in IaaS? If so, which one? I'm not sure why your nodes can't communicate over their private IP? Vagrant does have this problem and needs to use `$public_ip`.

**Comment by cusspvz** [comment]
@eyakubovich sorry for not being 100% verbose. :p 

**flannel** accepts an `interface` configuration which can be an interface **name** or **ip**, and uses that config to define internal variables `extIf` and `extIp`. Those variables should match so it can add routes properly on running system.

We have 5 Azure accounts and 2 AWS ones. As far as i know, there isn't a way to connect multiple azure clouds subnets, or even to connect them with AWS subnets.

If I set `interface` as our `$public_ip`, it wont work since Azure and AWS have their Public IP traffic routed into virtual subnet.

My proposal is to:
* add a configuration where you can set an host ip endpoint;
* renaming of `PublicIp` to `InterfaceIp` (makes more sense, i think);
* in case host has received and endpoint ip, it should be set on subnet config as `PublicIp` or `EndpointIp`;

> Are you running in IaaS?
Although I've already referenced Azure and AWS, the only PaaS we will use from them is their cloud storage.

>  I'm not sure why your nodes can't communicate over their private IP?
We are configuring each node on Azure: is unique on its cloud (one cloud per node), has a storage (one storage per node). Same will happen on `AWS`. That will allow us to move and scale along providers and be IaaS independent.
