### ISSUE TITLE
Getting "fdb already populated with: <nil>" when starting flannel 

### ISSUE THREAD

**Issue by syed** [coreos/flannel#260]
I have set up flannel between two hosts using the client-server method. One of the hosts has the flannel server running and both hosts connect to it as clients. During the initial setup, everything went fine and containers inside both hosts were able to ping each other. However, after rebooting, I see that the pings fail and instead of having a host IP in when a new host joins, flannel gives the message 

    fdb already populated with: <nil> MACADDRESS

here MACADDRESS is some random mac ( I'm assuming it is the container's veth's mac)

Am I doing somthing wrong?

**Comment by syed** [comment]
Update: I am using the VXLAN backend. I have to mention that I rebooted with a more recent kernel (3.19) from the default (3.13). I rebooted back with the older kernel (3.13) and it seems to work now. 

Does anyone else have this problem?

**Comment by MohdAhmad** [comment]
Hi @syed, can you share which flannel version you are using? 

The MACADDRESS is the mac address of the flannel.1 interface.

**Comment by syed** [comment]
I'm running the master.  Here is the error

    I0723 05:40:20.880912 03061 vxlan.go:280] fdb already populated with: <nil> 33:33:00:00:00:01
    I0723 05:40:20.881117 03061 vxlan.go:280] fdb already populated with: <nil> 01:00:5e:00:00:01
    I0723 05:40:20.881280 03061 vxlan.go:280] fdb already populated with: <nil> 33:33:ff:c0:7c:2a

My host has the following interfaces and their mac addresses.

docker0:  56:84:7a:fe:97:99
eth0: 02:00:09:0e:00:0a
flannel1.1: 2e:68:05:c0:7c:2a

**Comment by eyakubovich** [comment]
@syed These `fdb already populated with` messages are not errors -- they're just informational and just dump the fdb database. These MAC addresses are special purpose and are to be expected.

The fact that pings fail is something else. Do you see any log lines with "AddL3" in them? What about "Subnet added:" lines?

**Comment by eyakubovich** [comment]
@syed Seems like some kernel versions (or variants) return these built in FDB entries and it causes a nil slice dereference in flannel code (for some odd reason, it does not trigger a panic but just hangs). We'll get the fix in shortly.
