### ISSUE TITLE
mk-docker-opts.sh do not handle -m parameter at all

### ISSUE THREAD

**Issue by linfan** [coreos/flannel#268]
In code `flannel/dist/mk-docker-opts.sh`:

**1) There is no "m" in getopts, so -m parameter is ignored**

```
while getopts "f:d:ick:" opt; do
    case $opt in
        m)
            ipmasq=false
            ;;
done
```

User would always get an error when use -m parameter:

```
$ sudo flannel-0.5.2/mk-docker-opts.sh -m
flannel-0.5.2/mk-docker-opts.sh: illegal option -- m
flannel-0.5.2/mk-docker-opts.sh [-f FLANNEL-ENV-FILE] [-d DOCKER-ENV-FILE] [-i] [-c] [-m] [-k COMBINED-KEY]

Generate Docker daemon options based on flannel env file
OPTIONS:
	-f	Path to flannel env file. Defaults to /run/flannel/subnet.env
	-d	Path to Docker env file to write to. Defaults to /run/docker_opts.env
	-i	Output each Docker option as individual var. e.g. DOCKER_OPT_MTU=1500
	-c	Output combined Docker options into DOCKER_OPTS var
	-k	Set the combined options key to this value (default DOCKER_OPTS=)
	-m	Do not output --ip-masq (useful for older Docker version)
```

**2) variable FLANNEL_IPMASQ never have a value**

Even I add "m" to getops list, the -m parameter still not works as expected. Below result shows no matter -m is used or not, DOCKER_OPT_IPMASQ is not created at all.

```
$ sudo flannel-0.5.2/mk-docker-opts.sh -d /run/flannel_docker_opts.env -i -m
$ cat /run/flannel_docker_opts.env
DOCKER_OPT_BIP="--bip=172.17.78.1/24"
DOCKER_OPT_MTU="--mtu=8973"
$ sudo flannel-0.5.2/mk-docker-opts.sh -d /run/flannel_docker_opts.env -i
$ cat /run/flannel_docker_opts.env
DOCKER_OPT_BIP="--bip=172.17.78.1/24"
DOCKER_OPT_MTU="--mtu=8973"
```

From the code I found the root cause is the judgement variable "FLANNEL_IPMASQ" never defined, so it won't equal true ever.

```
if [ "$FLANNEL_IPMASQ" = true ] && [ $ipmasq = true ] ; then
        DOCKER_OPT_IPMASQ="--ip-masq=false"
fi
```

Actually just remove the "FLANNEL_IPMASQ" judgement will fix the issue. Like below:

```
if [ $ipmasq = true ]; then
        DOCKER_OPT_IPMASQ="--ip-masq=false"
fi
```

**3) Also there is a small problem with default Docker env file**

Current the default Docker env file is `/run/docker_opts.env`, however in CoreOS the default env file for Docker is `/run/flannel_docker_opts.env`. It's a bit inconvenient.

I do wondering how no one ever find 'DOCKER_OPT_IPMASQ' missing from their env file generated...

**Comment by eyakubovich** [comment]
- Item 1 is a bug.
- Item 2: note that `-m` is `Do not output --ip-masq (useful for older Docker version)` -- if no `-m` is specified, it should output `DOCKER_OPT_IPMASQ`
- Item 3: CoreOS originally used `/run/docker_opts.env`. It later changed the name but I prefer not to change the default file name here for backward compatibility.

**Comment by linfan** [comment]
For Item 2: I understand the -m is for remove DOCKER_OPT_IPMASQ from output.

But the actually result is, no matter '-m' is used or not, DOCKER_OPT_IPMASQ won't added. See below:

```
$ sudo flannel-0.5.2/mk-docker-opts.sh -i -m
$ cat /run/docker_opts.env
DOCKER_OPT_BIP="--bip=172.17.78.1/24"
DOCKER_OPT_MTU="--mtu=8973"
$ sudo flannel-0.5.2/mk-docker-opts.sh -i
$ cat /run/docker_opts.env
DOCKER_OPT_BIP="--bip=172.17.78.1/24"
DOCKER_OPT_MTU="--mtu=8973"
```

And it's caused by judgement variable 'FLANNEL_IPMASQ' no defined.

**Comment by linfan** [comment]
Got the point, `FLANNEL_IPMASQ` is sourced from `/run/flannel/subnet.env` file.
