### ISSUE TITLE
how to run flannel with --ip-masq 

### ISSUE THREAD

**Issue by gangadhars** [coreos/flannel#271]
I have 3 machines(vs01, vs02 and os2). vs01 nad vs02 are in local network and os2 is GCE. All are connected through bridge VPN.

vs01: (vm-1)
```
tap0 - 10.20.0.72
eth0 - 172.16.2.88
```
vs02: (vm-2)
```
tap0 -10.20.0.71
eth0 - 172.16.2.64
```
os2: (gce)
```
tap0 - 10.20.0.74
eth0 - 10.240.148.109
```
After Running kubernetes cluster
vs01: (vm-1)
```
tap0 - 10.20.0.72
eth0 - 172.16.2.88
flannel0 - 15.1.84.0
docker0 - 15.1.84.1
```
vs02: (vm-2)
```
tap0 -10.20.0.71
eth0 - 172.16.2.64
flannel0 - 15.1.45.0
docker0 - 15.1.45.1
```
os2: (gce)
```
tap0 - 10.20.0.74
eth0 - 10.240.148.109
flannel0 - 15.1.7.0
docker0 - 15.1.7.1
```
vs01 and vs02 docker containers are able to communicate with each other but we are unable to communicate with os2 conatiners. 

\# cat /run/flannel/subnet.env
```
FLANNEL_SUBNET=15.1.84.1/24
FLANNEL_MTU=1472
FLANNEL_IPMASQ=false
```
Kubernetes is starting docker and flannel services. Here is the configuration file:
```
export FLANNEL_NET=${FLANNEL_NET:-15.1.0.0/16}
echo "FLANNEL_NET"
echo $FLANNEL_NET
export FLANNEL_OPTS=${FLANNEL_OPTS:-"Network": 15.1.0.0/16}
```
How can I edit this file so that flannel will run with --ip-masq?

**Comment by eyakubovich** [comment]
I think `export FLANNEL_OPTS=${FLANNEL_OPTS:-"Network": 15.1.0.0/16}` might be wrong. `{ "Network": "15.1.0.0/16" }` is written into etcd but it looks like `FLANNEL_NET` is there for that. I am assuming you're on Ubuntu. Can you try placing `FLANNELD_OPTS=--ip-masq` into `/etc/default/flanned`?

However, `--ip-masq` controls whether or not flannel will install iptables rules on the host. The rules specify that traffic going from flannel net to the outside (i.e. from containers to the Internet) should be masqueraded. But it sounds like your instances are behind a NAT (IP Masquerade) and flannel is trying to communicate via RFC1918 addresses over the WAN (e.g. 10.x.x.x and 172.16.x.x). In that case, you can use newly added `--public-ip` option to specify the public (routable) IP.

**Comment by gangadhars** [comment]
@eyakubovich, As you said I changed the content of  `/etc/default/flanneld` to `FLANNEL_OPTS="--public-ip=172.16.2.10"`
Now flanneld is not running and log says:
```
flag provided but not defined: -public-ip
Usage of /opt/bin/flanneld:
  -alsologtostderr=false: log to standard error as well as files
  -etcd-cafile="": SSL Certificate Authority file used to secure etcd communication
  -etcd-certfile="": SSL certification file used to secure etcd communication
  -etcd-endpoints="http://127.0.0.1:4001,http://127.0.0.1:2379": a comma-delimited list of etcd endpoints
  -etcd-keyfile="": SSL key file used to secure etcd communication
  -etcd-prefix="/coreos.com/network": etcd prefix
  -help=false: print this message
  -iface="": interface to use (IP or name) for inter-host communication
  -ip-masq=false: setup IP masquerade rule for traffic destined outside of overlay network
  -log_backtrace_at=:0: when logging hits line file:N, emit a stack trace
  -log_dir="": If non-empty, write log files in this directory
  -logtostderr=false: log to standard error instead of files
  -stderrthreshold=0: logs at or above this threshold go to stderr
  -subnet-file="/run/flannel/subnet.env": filename where env variables (subnet and MTU values) will be written to
  -v=0: log level for V logs
  -version=false: print version and exit
  -vmodule=: comma-separated list of pattern=N settings for file-filtered logging
```

And also I tried with `./flanneld --public-ip=172.16.2.10` and printing same error.
I'm using flannel version 0.4.0
How to run --public-ip option?

**Comment by eyakubovich** [comment]
@gangadhars `--public-ip` has been added very recently and is only available in 0.5.2

**Comment by gangadhars** [comment]
Thanks @eyakubovich 

Problem is flannel is using eth0 interface by default. When I run it with --iface=tap0 it's working good.

**Comment by vinayk06** [comment]
@eyakubovich  can you give a solution for this in coreos
