### ISSUE TITLE
Picture in Documentation is 404

### ISSUE THREAD

**Issue by ZYWJ** [coreos/flannel#291]
https://github.com/coreos/flannel/blob/master/Documentation/gce-backend.md

**Comment by eyakubovich** [comment]
Yeah, that folder get compiled into our docs on the site (https://coreos.com/flannel/docs/latest/gce-backend.html) and so there are special directives that don't work in raw form. Don't know if there's something that we can do to make it work both on GH and when run thru Jekyll. /cc @robszumski

**Comment by robszumski** [comment]
You can make this look correct on Github, we now have scripts in place that rewrite links and such.

**Comment by robszumski** [comment]
IE remove `{{site.baseurl}}/assets/images/media/` from stuff

**Comment by eyakubovich** [comment]
Fixed in #329 329
