### ISSUE TITLE
Adding new node to flannel network.

### ISSUE THREAD

**Issue by gangadhars** [coreos/flannel#293]
Hi All.

I have a two node Kubernetes cluster. And I want to add a new node to that running cluster. Every thing working fine except Flannel. 

Cluster info:
```
172.16.2.179   kubernetes.io/hostname=172.16.2.179   Ready
172.16.2.92    kubernetes.io/hostname=172.16.2.92    Ready
```
After adding the new node:
```
172.16.2.179   kubernetes.io/hostname=172.16.2.179   Ready
172.16.2.63    kubernetes.io/hostname=172.16.2.63    Ready
172.16.2.92    kubernetes.io/hostname=172.16.2.92    Ready
```
On every node:
```
# /opt/bin/etcdctl get /coreos.com/network/config
{"Network":"17.16.0.0/16"}
```
After running  `/root/kube/reconfDocker.sh` on every node.
**172.16.2.179**:
flannel0 - 17.16.84.0    docker0 - 17.16.84.1
**172.16.2.92**:
flannel0 - 17.16.29.0    docker0 - 17.16.29.1
**172.16.2.63**: (new node)
flannel0 - 17.16.46.0    docker0 - 17.16.46.1

Verifying flannel network is communicating:
On 172.16.2.179:
```
#ping 17.16.46.1
100% packet loss
```
On 172.16.2.63:
```
#ping 17.16.84.1
100% packet loss
#ping 17.16.29.1
100% packet loss
```
Do I have to do any configuration to bring new node flannel into existing flannel etwork?

**Comment by eyakubovich** [comment]
@gangadhars Was it working fine before the new node? After the new node has been added, can the old two nodes still ping each other via flannel?

- Please make sure the firewall/security groups allow traffic on UDP port 8285. 
- Look at the flannel logs and see if there are any errors there but also look for "Subnet added: " messages. Each node should have added the other two subnets.
- While running ping, try to use tcpdump to see where the packets get dropped. Try src flannel0 (icmp), src host interface (udp port 8285), dest host interface (udp port 8285), dest flannel0 (icmp), docker0 (icmp).

**Comment by gangadhars** [comment]
I run reconfDocker.sh script agan and everything is working fine. You can close the issue. 

But when I look into the  reconfDocker.sh:

```
source ~/kube/config-default.sh

attempt=0
while true; do
  /opt/bin/etcdctl get /coreos.com/network/config
  if [[ "$?" == 0 ]]; then
    break
  else
        # enough timeout??
   ...
   ...
  fi
done

#wait some secs for /run/flannel/subnet.env ready
sleep 15
sudo ip link set dev docker0 down
sudo brctl delbr docker0
...
```
After running `/opt/bin/etcdctl get /coreos.com/network/config`, script is waiting for 15sec to create  `/run/flannel/subnet.env` file. I didn't understand how does it create `/run/flannel/subnet.env` file?

**Comment by eyakubovich** [comment]
`/run/flannel/subnet.env` is created by flanneld once it has acquired the subnet.

**Comment by gangadhars** [comment]
Hi @eyakubovich.

We are facing new problem when we try to add a new node to flannel. The subnet is adding and removing immediately.

Logs on Master Node (172.16.2.63): 
```
I0831 22:20:45.059449 15652 main.go:278] Installing signal handlers
I0831 22:20:45.059498 15652 main.go:138] Determining IP address of default interface
I0831 22:20:45.059757 15652 main.go:228] Using 172.16.2.63 as external interface
I0831 22:20:45.060532 15652 subnet.go:334] Picking subnet in range 10.10.1.0 ... 10.10.255.0
I0831 22:20:45.114696 15652 subnet.go:97] Subnet lease acquired: 10.10.42.0/24
I0831 22:20:45.115529 15652 main.go:245] UDP mode initialized
I0831 22:20:45.115552 15652 udp.go:212] Watching for new subnet leases
I0831 22:20:45.118005 15652 udp.go:237] Subnet added: 10.10.98.0/24
I0831 22:27:02.817575 15652 udp.go:237] Subnet added: 10.10.83.0/24
I0831 22:27:03.157287 15652 udp.go:242] Subnet removed: 10.10.83.0/24
```
Logs on newly added node: (172.16.2.70)
```
I0827 20:29:33.301961 03133 main.go:278] Installing signal handlers
I0827 20:29:33.302009 03133 main.go:138] Determining IP address of default interface
I0827 20:29:33.303593 03133 main.go:228] Using 172.16.2.70 as external interface
I0827 20:29:33.307968 03133 subnet.go:334] Picking subnet in range 10.10.1.0 ... 10.10.255.0
I0827 20:29:33.408002 03133 subnet.go:97] Subnet lease acquired: 10.10.83.0/24
I0827 20:29:33.415929 03133 main.go:245] UDP mode initialized
I0827 20:29:33.415953 03133 udp.go:212] Watching for new subnet leases
I0827 20:29:33.418714 03133 udp.go:237] Subnet added: 10.10.98.0/24
I0827 20:29:33.418741 03133 udp.go:237] Subnet added: 10.10.42.0/24
```
I didn't see any errors but in master and other minion nodes are removing newly added subnet. 
Master and minion subnets are are pinging each other. But newly added node subnet is not pinging both ways.
