### ISSUE TITLE
Move away from glog logger

### ISSUE THREAD

**Issue by eyakubovich** [coreos/flannel#295]
glog is overly verbose and always prints a timestamp. The logger should detect if it runs under journald and not log the timestamp in that case.

**Comment by philips** [comment]
@jonboulle we are using github.com/coreos/pkg/capnslog everywhere else, right?

**Comment by jonboulle** [comment]
@philips not everywhere yet but  that is the idea

**Comment by steveeJ** [comment]
@mischief pointed out that we are using https://godoc.org/github.com/Sirupsen/logrus in recent projects.

**Comment by tomdee** [comment]
Glog is still widely used elsewhere (e.g. in kubernetes) so I don't see a compelling need to move away from it. Given that this issue has been open for >18 months without much interest I think it can be closed. 

If people have strong feelings about moving away from glog then please write here and I can reopen the issue.
