### ISSUE TITLE
Can i run two flannel bridges on single host

### ISSUE THREAD

**Issue by kgrvamsi** [coreos/flannel#297]
Hello,

i have a requirement to make sure there will be one subnet which will be used by docker and the other subnet will be used by my Kubernetes Cluster Ip range.

saw the Experiment Model on the readme page as well and thought if this can be achieved ?Is there any specific flanneld args to create two bridges on the host?

Thanks,
Vamsi KGR

**Comment by eyakubovich** [comment]
flannel does not actually create any bridges. For some backends (`udp` and `vxlan`) it creates an interface through which the traffic can be tunneled through to the other hosts. What flannel really does is ensure that traffic on the flannel network will be routed appropriately. So for example, if you define a flannel network to be `10.1.0.0/16` and your host gets allocated `10.1.5.0/24`, flannel ensures that other hosts sending packets to `10.1.5.0/24` will get to your host.

Your allocated subnet is written out into `/run/flannel/subnet.env` but something else has to set up the bridge. In case of Docker, the contents of  `/run/flannel/subnet.env` are fed to the docker daemon and it creates the bridge (`docker0`).

The experimental multi-network mode allows you to set up multiple networks. For example `10.1.0.0/16` and `10.2.0.0/16`. So your host might get `10.1.5.0/24` and `10.2.8.0/24`. You can certainly then set up two bridges with each configured with the corresponding subnets. Please keep in mind that this is all done through host routing so containers attached to different bridges will still be able cross-talk to the other network. Using iptables of course, you can forbid this cross-talk.

**Comment by eyakubovich** [comment]
@kgrvamsi Has this been resolved and can I close the issue?
