### ISSUE TITLE
Performance test

### ISSUE THREAD

**Issue by wulonghui** [coreos/flannel#303]
Hi all,
Any performance test report of Flannel, or any case in production ?

Thanks

**Comment by eyakubovich** [comment]
We haven't yet published any performance tests but if you Google, some blogs have posted a few measurements. I know this post has benchmarked flannel: http://www.generictestdomain.net/docker/weave/networking/stupidity/2015/04/05/weave-is-kinda-slow/

**Comment by wulonghui** [comment]
@eyakubovich Thanks very much

**Comment by MohdAhmad** [comment]
@wulonghui here is another http://paulbakker.io/docker/docker-cloud-network-performance/

**Comment by wulonghui** [comment]
@MohdAhmad 
Thanks
