### ISSUE TITLE
flannel build - failed to create symbolic link `gopath/src/github.com/coreos/flannel': Protocol error

### ISSUE THREAD

**Issue by tdeheurles** [coreos/flannel#309]
I'm trying to build flannel using the docker golang build but I encounter that error :

```
failed to create symbolic link `gopath/src/github.com/coreos/flannel': Protocol error
```

Does this one tells something to someone ?

For information i'm using docker toolbox (under windows)

**Comment by eyakubovich** [comment]
You're probably building on a filesystem that does not support symbolic linux. I don't know about docker toolbox and what it uses for the filesystem.

**Comment by philips** [comment]
@tdeheurles I am going to close this out because it isn't really a flannel issue but a filesystem issue with docker toolbox.
