### ISSUE TITLE
Network with a VM and a BareMetal

### ISSUE THREAD

**Issue by tdeheurles** [coreos/flannel#313]
hi,

### I'm trying to create a flannel network between :
- a `baremetal` CoreOS (v801)
- a `VirtualMachine` CoreOS(v801)
    - It runs on VirtualBox (v5.0.2)
    - It starts with Vagrant (v1.7.3)
    - The host is a Windows 7

For now the machines seems to not be able to communicate.  
Here are the details of my configuration :

#### NETWORK
My local network is 192.168.1.0/24
- baremetal : 192.168.1.13
- VM : 192.168.1.7

#### ETCD2 :
- Etcd is configured on the 2 machines, with the BareMetal as the `etcd2 server` and the VirtualMachine as a `proxy`. 
- I can transmit data through the KV store.

#### FLANNELD :
- flanneld is started via systemd.  
- It runs without error on each machine.  
- the flannel0 network is created on each machine
- the flannel0 network has the requested range
   - baremetal : 10.1.18.0
   - vm : 10.1.46.0

#### BAREMETAL CONFIGURATION
```bash
➜  ~  cat /run/flannel/subnet.env
FLANNEL_NETWORK=10.1.0.0/16
FLANNEL_SUBNET=10.1.18.1/24
FLANNEL_MTU=1472
FLANNEL_IPMASQ=true

➜  ~  cat /run/flannel/options.env
FLANNELD_IFACE=192.168.1.13

➜  ~  cat /run/flannel_docker_opts.env
DOCKER_OPT_BIP="--bip=10.1.18.1/24"
DOCKER_OPT_IPMASQ="--ip-masq=false"
DOCKER_OPT_MTU="--mtu=1472"
```

```yaml
  flannel:
    interface: 192.168.1.13

  units:
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl \
              set                         \
                /coreos.com/network/config  \
               '{                           \
                  "Network": "10.1.0.0/16", \
                  "Backend": {              \
                    "Type": "udp",          \
                    "Port": 7890            \
                } }'
      command: start
```

#### VM CONFIGURATION

```bash
➜  ~  cat /run/flannel/subnet.env
FLANNEL_NETWORK=10.1.0.0/16
FLANNEL_SUBNET=10.1.46.1/24
FLANNEL_MTU=1472
FLANNEL_IPMASQ=true

➜  ~  cat /run/flannel/options.env
➜  ~  cat /run/flannel_docker_opts.env
DOCKER_OPT_BIP="--bip=10.1.46.1/24"
DOCKER_OPT_IPMASQ="--ip-masq=false"
DOCKER_OPT_MTU="--mtu=1472"
```
==> **`/run/flannel/options.env` is empty ... it's different than in the `baremetal`**

Flanneld configuration is the standard one with this addition :
```bash
# /etc/systemd/system/flanneld.service.d/10-publicip.conf
[Service]
Environment=FLANNELD_INTERFACE=192.168.1.7
```

#### FIREWALL
- BareMetal : As I'm using CoreOS with no firewall configuration, I think that this point is ok.
- VM: I'm also using CoreOS without firewall configuration
- Windows 7 should notify me if the firewall is in cause.

#### TESTED FLANNEL CONFIGURATION :

Standard
```json
{ 
  "Network": "10.1.0.0/16"
}
```
UDP (same as standard ?)
```json
{ 
  "Network": "10.1.0.0/16",
  "Backend": {              
    "Type": "udp",          
    "Port": 7890            
  } 
}
```

host-gw (don't really understand that)
```json
{
  "Network": "10.1.0.0/16",
  "Backend": {
    "Type": "host-gw"
  }
}
```

#### TEST
I don't exactly know how to test my flannel network. For now I just create a container on each machine and try to have a ping between each container :
```
docker run -ti busybox sh
```

**Comment by tdeheurles** [comment]
I have just tried with vxlan, here are the `journalctl -fu flanneld` for each machine.

The communication seems to pass as the log says after a ping from a machine to the other :

**baremetal** (IPv4:  10.1.18.0 and 192.168.1.13):
```
➜  ~  journalctl -fu flanneld
-- Logs begin at Thu 2015-09-03 09:55:16 UTC. --
Sep 12 15:09:42 bm0-coreos sdnotify-proxy[827]: I0912 15:09:42.708636 00001 vxlan.go:232] Subnet added: 10.1.46.0/24
Sep 12 15:09:42 bm0-coreos sdnotify-proxy[827]: I0912 15:09:42.708728 00001 device.go:164] calling NeighAdd: 10.0.2.15, b6:a2:bc:32:d7:74
Sep 12 15:11:02 bm0-coreos sdnotify-proxy[827]: I0912 15:11:02.982397 00001 vxlan.go:345] L3 miss: 10.1.46.2
Sep 12 15:11:02 bm0-coreos sdnotify-proxy[827]: I0912 15:11:02.982456 00001 device.go:187] calling NeighSet: 10.1.46.2, b6:a2:bc:32:d7:74
Sep 12 15:11:02 bm0-coreos sdnotify-proxy[827]: I0912 15:11:02.982601 00001 vxlan.go:356] AddL3 succeeded
Sep 12 15:11:23 bm0-coreos sdnotify-proxy[827]: I0912 15:11:23.134641 00001 vxlan.go:340] Ignoring not a miss: b6:a2:bc:32:d7:74, 10.1.46.2
```

**VM** (IPv4: 10.1.46.0 and  10.0.2.15 and 192.168.1.4):
```
core@tdeheurles-vm-coreos ~ $ journalctl -fu flanneld
-- Logs begin at Sat 2015-09-12 15:08:55 UTC. --
Sep 12 15:09:42 tdeheurles-vm-coreos sdnotify-proxy[1242]: I0912 15:09:42.720068 00001 device.go:164] calling NeighAdd: 192.168.1.13, 22:de:e0:39:62:8d
Sep 12 15:09:42 tdeheurles-vm-coreos systemd[1]: Started Network fabric for containers.
Sep 12 15:11:02 tdeheurles-vm-coreos sdnotify-proxy[1242]: I0912 15:11:02.958771 00001 vxlan.go:345] L3 miss: 10.1.18.3
Sep 12 15:11:02 tdeheurles-vm-coreos sdnotify-proxy[1242]: I0912 15:11:02.958835 00001 device.go:187] calling NeighSet: 10.1.18.3, 22:de:e0:39:62:8d
Sep 12 15:11:02 tdeheurles-vm-coreos sdnotify-proxy[1242]: I0912 15:11:02.958995 00001 vxlan.go:356] AddL3 succeeded
Sep 12 15:11:21 tdeheurles-vm-coreos sdnotify-proxy[1242]: I0912 15:11:21.871119 00001 vxlan.go:340] Ignoring not a miss: 22:de:e0:39:62:8d, 10.1.18.3
Sep 12 15:15:26 tdeheurles-vm-coreos sdnotify-proxy[1242]: I0912 15:15:26.547585 00001 vxlan.go:345] L3 miss: 10.1.18.1
```

**Comment by tdeheurles** [comment]
I found the problem, but not how to solve for now.
Here is the `journalctl -fu flanneld` from the VM :

```
 journalctl -fu flanneld
-- Logs begin at Sat 2015-09-12 15:58:16 UTC. --
Sep 12 15:59:22 tdeheurles-vm-coreos sdnotify-proxy[1179]: I0912 15:59:22.349934 00001 main.go:188] Using 10.0.2.15 as external interface
Sep 12 15:59:22 tdeheurles-vm-coreos sdnotify-proxy[1179]: I0912 15:59:22.350178 00001 main.go:189] Using 10.0.2.15 as external endpoint
Sep 12 15:59:22 tdeheurles-vm-coreos sdnotify-proxy[1179]: I0912 15:59:22.355440 00001 etcd.go:204] Picking subnet in range 10.1.1.0 ... 10.1.255.0
Sep 12 15:59:22 tdeheurles-vm-coreos sdnotify-proxy[1179]: I0912 15:59:22.357291 00001 etcd.go:84] Subnet lease acquired: 10.1.23.0/24
Sep 12 15:59:22 tdeheurles-vm-coreos sdnotify-proxy[1179]: I0912 15:59:22.370172 00001 ipmasq.go:48] Adding iptables rule: FLANNEL -d 10.1.0.0/16 -j ACCEPT
Sep 12 15:59:22 tdeheurles-vm-coreos sdnotify-proxy[1179]: I0912 15:59:22.373826 00001 ipmasq.go:48] Adding iptables rule: FLANNEL ! -d 224.0.0.0/4 -j MASQUERADE
Sep 12 15:59:22 tdeheurles-vm-coreos sdnotify-proxy[1179]: I0912 15:59:22.385713 00001 ipmasq.go:48] Adding iptables rule: POSTROUTING -s 10.1.0.0/16 -j FLANNEL
Sep 12 15:59:22 tdeheurles-vm-coreos sdnotify-proxy[1179]: I0912 15:59:22.395429 00001 udp.go:222] Watching for new subnet leases
Sep 12 15:59:22 tdeheurles-vm-coreos sdnotify-proxy[1179]: I0912 15:59:22.400209 00001 udp.go:247] Subnet added: 10.1.5.0/24
Sep 12 15:59:22 tdeheurles-vm-coreos systemd[1]: Started Network fabric for containers.
```

At the top of the log :
```
Using 10.0.2.15 as external interface
```

So my configuration is not taken in account :
```
# /etc/systemd/system/flanneld.service.d/10-publicip.conf
[Service]
Environment=FLANNELD_INTERFACE=192.168.1.7
```

I know that on vagrant, we have to add that parameter :

```
  flannel:
    interface: $public_ipv4
```

But the `$public_ipv4` is not change with a good parameter for my configuration. It's translated to `10.0.2.15` and not `192.168.1.7`.

So I do not use cloud_config :
- I run `vagrant up`
- I run a script that :
  - add etcd2 unit and start etcd2 (it's working)
  - add flanneld drop-ins :

```
# /etc/systemd/system/flanneld.service.d/10-publicip.conf
[Service]
Environment=FLANNELD_INTERFACE=192.168.1.7
```

So it seems that the problem come from that drop-ins.

**Comment by tdeheurles** [comment]
Finally I write `FLANNELD_IFACE=192.168.1.7` to `/run/flannel/options.env`.

It's working.

**Comment by tdeheurles** [comment]
For now my solution is a workaround.

What is the good name of that environment ?

All these ones doesn't work :
```
Environment=FLANNELD_IFACE=192.168.1.7
Environment=FLANNELD_INTERFACE=192.168.1.7
Environment=FLANNEL_INTERFACE=192.168.1.7
Environment=FLANNEL_IFACE=192.168.1.7
```

**Comment by eyakubovich** [comment]
@tdeheurles Unfortunately flannel drop-ins can not be used for setting environment variables for the flanneld executable. This is because flanneld runs inside a container and Docker does not pass inherited environment variables to the container. Instead we use `/run/flannel/options.env` to pass env vars into the flanneld. `/run/flannel/options.env` however is meant to be automatically generated from the cloud config. So just add
```
  flannel:
    interface: 192.168.1.7
```
to your cloud-config and it'll be propagated all the way to flannel.

**Comment by tdeheurles** [comment]
Thanks for your answer.

The fact that drop-ins does not write that Environments is good to know.

But the problem is that the ip is allocated at runtime, so I can't write it like this.

On vagrant, the `$public_ipv4` seems to not be working. I found a solution by putting a first unit to extract the ipv4, write it to a file and then the next unit can acces it.


If someone need, here is a snippet, or you can look to [the project](https://github.com/tdeheurles/homecores/blob/master/templates/template.cloud-config.yml) :
```yaml
    # Here is a unit, that will extract the Public_IP
    - name: write_public_ip.service
      command: start
      content: |
        [Unit]
        Description=Systemd test
        [Service]
        Type=oneshot
        ExecStartPre=/usr/bin/mkdir -p __PUBLIC_IP_FILE_PATH__
        ExecStart=__PROGRAMS_PATH__/write_ip.sh __PUBLIC_IP_FILE_PATH__/public_ip
        #ExecStartPost=__PROGRAMS_PATH__/sed_kubernetes_public_ip.sh
        [Install]
        WantedBy=multi-user.target

write_files:
  # This script will get the public ipv4 that correspond
  #   to the network mask given in the config
  - path:        __PROGRAMS_PATH__/write_ip.sh
    permissions: "0755"
    owner:       "root"
    content: |
      #!/bin/bash -
      FILE_TO_WRITE=$1
      echo "PUBLIC_IP=`ifconfig | grep __NETWORK_MASK__ | awk '{print $2}'`" > $FILE_TO_WRITE

```

**Comment by eyakubovich** [comment]
The fact that $public_ipv4 on vagrant is not working is troubling. I'm opened a bug report on CoreOS.

**Comment by suquant** [comment]
My proposal force set "eth1" in interface parameter of flannel

```
#cloud-config

coreos:
  flannel:
    public-ip: $public_ipv4
    interface: eth1
```
