### ISSUE TITLE
NewEtcdManager and newEtcdManager should return *EtcdManager

### ISSUE THREAD

**Issue by gouyang** [coreos/flannel#314]
While reading the codes, I'm just curious why it returns Manger interface, based on my understandings it should return *EtcdManager, is it a typo?

https://github.com/coreos/flannel/blob/master/subnet/etcd.go#L55
https://github.com/coreos/flannel/blob/master/subnet/etcd.go#L66

**Comment by gouyang** [comment]
I understand it now. Close this bug.

**Comment by gouyang** [comment]
@eyakubovich I'd like to know what if by changing Manager to *EtcdManager? isn't it more golang idiomatic?

**Comment by eyakubovich** [comment]
@gouyang It tries to hide the actual type and just return the interface. I don't know what is more golang idiomatic, certainly returning an interface is an OOP-ism.

**Comment by gouyang** [comment]
@eyakubovich I thought newEtcdManager() returns *EtcdManager is a bit more readable than Manager, please never mind if it does not looks so.
