### ISSUE TITLE
No available IP addresses on network

### ISSUE THREAD

**Issue by apatil** [coreos/flannel#315]
Hi everyone,

With flanneld version 0.5.3, docker 1.8.2, on kernel 3.10.0, I eventually see

```
/# docker run -ti --rm ubuntu:14.04 /bin/bash
Error response from daemon: Cannot start container bb8ad72f1a8aac0263266552bae6a159e408c06ac9c3be1b9a00b1643f617648: no available ip addresses on network
```

My /coreos.com/network/config has a subnet length of 24, and I have only 25 containers running, so I don't actually have enough containers up to claim the entire subnet. I've seen this happen with both the vxlan and udp backends. I don't see anything in flannel's logs when I run it with -v 4.

Is this a known issue?

**Comment by eyakubovich** [comment]
@apatil This is probably a Docker issue. flannel just allocates a subnet (/24 in your case) and passes that range over to Docker. Can you do "ip link" on the host? How many veth interfaces do you see? Can you also do "docker ps -a" and check how many are running and how many have exited. There has been lots of changes in Docker networking code lately, I wonder if the IPs are not getting released.

**Comment by apatil** [comment]
@eyakubovich It looks like you may be right. I had only 25 containers running, but 1k+ stopped containers; so if Docker is not releasing their IP addresses, that would exhaust the subnet. I'm deleting the stopped containers to see if that helps.

**Comment by apatil** [comment]
@eyakubovich I spoke too soon, unfortunately that didn't fix the problem.

```
# docker ps -a | wc -l
25
# ip link | grep veth | wc -l
11
# docker run -ti --rm ubuntu:14.04 /bin/bash
Error response from daemon: Cannot start container 54a522db212f2adc7e1c3c38699a84b1dd7dd3ddfe589fdbc84f19c3906b0c0e: no available ip addresses on network
```

**Comment by eyakubovich** [comment]
Quick Googling showed that some people had luck with restarting Docker daemon: https://github.com/docker/docker/issues/14788

**Comment by apatil** [comment]
@eyakubovich That works for me too, but I'd like to avoid restarting docker if possible. Anyway, it looks like this isn't a flannel issue, so I'll close it. Thanks for looking into it.

**Comment by osterman** [comment]
Getting this as well. Can't confirm or deny it's a flannel issue. Restarting docker "works" by it's a pretty disruptive/violent operation. Running CoreOS stable (835.8.0) - docker 1.8.3.

**Comment by osterman** [comment]
Oh, when this happens it's cluster-wide. All docker daemons report the same problem. I have to restart all docker daemons on all cluster nodes.
