### ISSUE TITLE
--ip-masq should also add masquerade from outer net to flannel net

### ISSUE THREAD

**Issue by eyakubovich** [coreos/flannel#318]
From email discussion with @thockin:

> When accessing a pod (overlay) from a node (native), the routing decision is made before we ever see the packet.  We can add routes for every service as described in prev. email or we can just MASQUERADE. Note that this SNATs to the .0 of the source host.
>    `iptables -t nat -A POSTROUTING -d $FLANNEL_NETWORK ! -s $FLANNEL_SUBNET -j MASQUERADE`

**Comment by thockin** [comment]
In what flannel release can we depend on this fix?

**Comment by eyakubovich** [comment]
@thockin The next one :) There has been a lot of movement in key parts lately (related to more multi-network features) so we need to re-stabilize head and then cut a release. I'm hoping to do a release mid-October.

**Comment by streamnsight** [comment]
FYI: there may be unintended consequences to this PR

https://github.com/coreos/flannel/issues/433#issuecomment-222380448
