### ISSUE TITLE
Flannel interface with physical eth0 in one container

### ISSUE THREAD

**Issue by viatcheslavmogilevsky** [coreos/flannel#320]
Some of endpoints does not support NAT (in my case HDFS MapR 3.x). Containers which work under flannel network need to use such HDFS nodes (outside flannel network). This is why I'm trying to set up two interfaces inside one container: first is host's eth0 added by @jpetazzo's [pipework](https://github.com/jpetazzo/pipework) tool, the second is flannel0 interface (added through `DOCKER_NETWORK_OPTIONS` variable for docker daemon).
For example:
I have set up flannel in two docker hosts (their IPs -  `10.20.30.237` and `10.20.30.238`). Each host have two containers under flannel (`--net=bridge`).
Flannel daemon params: `--ip-masq=true`.
Network config: `{'Network': '10.20.44.0/22', 'SubnetLen': 28}`
Docker daemon params:
First host: `DOCKER_NETWORK_OPTIONS="--bip=10.20.44.81/28 --mtu=8972 --ip-masq=false"`
Second host: `DOCKER_NETWORK_OPTIONS="--bip=10.20.46.33/28 --mtu=8972 --ip-masq=false"`
Containers' flannel IPs:
First host: `10.20.44.83`, `10.20.44.85`
Second host: `10.20.46.41`, `10.20.46.42`

Let's consider the first container of first host:
This is routes inside container:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.20.44.81     0.0.0.0         UG    0      0        0 eth0
10.20.44.80     0.0.0.0         255.255.255.240 U     0      0        0 eth0
```
And what it can:
```bash
# ping container inside host
$ docker exec myfirstcontainerid ping -c 1 10.20.44.85 # => OK
# ping container outside host
$ docker exec myfirstcontainerid ping -c 1 10.20.46.41 # => OK
# use hdfs 
$ docker exec myfirstcontainerid hadoop fs  -ls  maprfs://old.mapr.node  # => FAIL
```

Then I attached eth0 interface to considered container:
```bash
$ ./pipework eth0 myfirstcontainerid dhclient 
```
And routing table is:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.20.0.1       0.0.0.0         UG    0      0        0 eth1
10.20.0.0       0.0.0.0         255.255.0.0     U     0      0        0 eth1
10.20.44.80     0.0.0.0         255.255.255.240 U     0      0        0 eth0
```

And what it can:
```bash
# ping container inside host
$ docker exec myfirstcontainerid ping -c 1 10.20.44.85 # => OK
# ping container outside host
$ docker exec myfirstcontainerid ping -c 1 10.20.46.41 # => FAIL
# use hdfs 
$ docker exec myfirstcontainerid hadoop fs  -ls  maprfs://old.mapr.node  # => OK
```

It's obvious that traffic to  `10.20.46.XX` net (outside host but still inside flannel) handeled by `eth1` device. 

I tried to change `--bip` docker daemon parameter of first host from `10.20.44.81/28` to `10.20.44.81/22` to handle all flannel traffic, but with no success - containers have not any access outside.

How workaround this to allow access outside flannel *act as like* `--net=host` with keeping flannel functionality?

**Comment by eyakubovich** [comment]
With flanneld being started with `--ip-masq=true`, traffic going from the container but outside of flannel will get masqueraded and appear as coming from the host's interface. I wonder why MapR is not working -- I'm assuming because it has problems with masqueraded IPs.

I don't know much about pipework, but can you use it to add a route like `10.20.44.0/22 via 10.20.44.81 dev eth0`? Looking at https://github.com/jpetazzo/pipework#setting-a-default-gateway, it looks like it can manipulate the routes to some degree.

**Comment by viatcheslavmogilevsky** [comment]
Thanks for advice
