### ISSUE TITLE
flanneld run with -listen option can not be run as a service

### ISSUE THREAD

**Issue by ingvagabund** [coreos/flannel#324]
Hi,

When running flanneld with -listen option, it does not notify systemd of its readiness. Without -listen option and without multinetwork, initAndRun function is called which calls daemon.SdNotify("READY=1"). When -listen option set, remote.RunServer function is run and there is not execution path leading to daemon.SdNotify("READY=1").

Is it intended or is it bug/missing notification? Running with 0.5.3.

Thanks
Jan

**Comment by eyakubovich** [comment]
I guess it is a missing feature that should be added. However in server mode, flannel does support systemd's socket activation. This way you can achieve the same "non-waiting" startup as with with `notify`. Just create a .socket file and launch flannel with `--listen=fd://`

**Comment by ingvagabund** [comment]
Thanks Eugene. I am not familiar with creating the socket file. Can you help enlighten me how to do that? Or maybe what would be the correct place to put daemon.SdNotify("READY=1")? From my point of view I see it as a one liner. What about https://github.com/coreos/flannel/blob/master/remote/server.go#L278 ?

**Comment by eyakubovich** [comment]
@ingvagabund Sure, feel free to submit a PR.

Also, here's some info on socket activation:
http://0pointer.de/blog/projects/socket-activation.html
http://www.freedesktop.org/software/systemd/man/systemd.socket.html

**Comment by ingvagabund** [comment]
Thanks for the links. Here is the PR https://github.com/coreos/flannel/pull/326.

**Comment by ingvagabund** [comment]
One minor glitch. When -listen is not specified, flanneld creates /run/flannel directory as a consequence of creating /run/flannel/subnet.env file. If -listen is not specified, it does not created /run/flannel. Running mk-docker-opts.sh with -d /run/flannel/docker fails is the directory does not exists. Thus by default, /run/docker_opts.env is used. This is service file issue related, not the flannel itself.

**Comment by ingvagabund** [comment]
@eyakubovich, I suppose client-server feature is still not stable, right?

**Comment by eyakubovich** [comment]
@ingvagabund When flannel is running with `-listen`, it should not be used with `mk-docker-opts.sh`. You would need to write a separate service file for the server mode.

**Comment by eyakubovich** [comment]
Fixed by #326
