### ISSUE TITLE
No log if failed to authenticate to etcd server when run as a service

### ISSUE THREAD

**Issue by gouyang** [coreos/flannel#330]
If I forgot the argument -etcd-cafile, it looks like run very well.

```
./flanneld --version
0.5.3+git

# ./flanneld  -etcd-certfile=/etc/ssl/certs/host.crt -etcd-keyfile=/etc/ssl/certs/host.key --remote-certfile=/etc/ssl/certs/host.crt --remote-keyfile=/etc/ssl/certs/host.key --remote-cafile=/etc/ssl/certs/rootCA.crt -listen=dhcp-15-25.com:8002
I0926 06:52:31.672842 20274 main.go:111] Installing signal handlers
I0926 06:52:31.673015 20274 main.go:124] running as server
```

I expect it report something that it could not connect to etcd server because of the handshake is failed.

**Comment by eyakubovich** [comment]
The default value for `--etcd-endpoints` is `http://` and not `https://...` so it won't actually end up using TLS. However this is not the behavior of `--listen` which looks at the presence of those other TLS flags. This is partly done for compatibility with other etcd clients but this is a bad UX. Leaving open so we can improve it.

**Comment by tomdee** [comment]
Client/server mode specific so closing
