### ISSUE TITLE
Issue with Flannel on CentOS 7

### ISSUE THREAD

**Issue by PhilibertDugas** [coreos/flannel#332]
Hi,

I'm trying to setup flannel with CentOS7 and I can't seem to make it work.

Basically, I'm unable to reach a docker container from another host using flanneld.

The ip address assigned to Flanneld looks fine with the docker one
![ifconfig](https://cloud.githubusercontent.com/assets/5460957/10175703/744e1ada-66be-11e5-9f17-e39d13944904.JPG)

Status doesn't reveal anything in particular
![flanneld-status](https://cloud.githubusercontent.com/assets/5460957/10175710/7a205126-66be-11e5-80f6-d0856542f0bf.JPG)

However, in the ip route, I don't see flannel0 being there. I was able to install flannel on Ubuntu 14.04 before and I would see flannel0 being in the ip route. Not sure how to troubleshoot this :(
![centos-ip-route](https://cloud.githubusercontent.com/assets/5460957/10175713/7e99758e-66be-11e5-9e21-926012da8b7c.JPG)

**Comment by PhilibertDugas** [comment]
Manually running the following will do the trick.. but still wondering why it's not appearing by default

 ` route add -net 172.16.0.0 netmask 255.255.0.0 dev flannel0`

**Comment by eyakubovich** [comment]
Usually the kernel will add this route when an address is given to the interface. However the kernel will not do that if there is a more restrictive one already there (in this case 17.16.60.0/24). But flannel even forces this addition (https://github.com/coreos/flannel/blob/master/backend/udp/udp.go#L208) so I'm not sure what's going on here.

**Comment by PhilibertDugas** [comment]
I tried to change the docker0 netmask from /24 to /16. Afterwards the ip route is added automatically. But by letting docker0 with a /24 netmask and flannel with a /16 netmask, it doesn't add it automatically
