### ISSUE TITLE
/_coreos.com or /coreos.com

### ISSUE THREAD

**Issue by glerchundi** [coreos/flannel#334]
is it safe to use `/_coreos.com/network` as etcd prefix? do you have any plans to use this in the future? Fleet is already using it and I don't know if flannel does this deliberately or not.

I prefer to keep everything related to cluster level data hidden.

Thanks!

**Comment by eyakubovich** [comment]
@glerchundi We moved away from `/_coreos.com` to `/coreos.com` for our prefixes (although fleet still uses former). However if you'd like, you can use the hidden form.

**Comment by glerchundi** [comment]
ok, i'll use `/coreos.com/{fleet,network,whatever}` then, thanks.
