### ISSUE TITLE
upd vs vxlan, whose performance is better

### ISSUE THREAD

**Issue by Oscarzhao** [coreos/flannel#341]
When I ping another flannel on one iaas from another flannel on differnet iaas, the latency is >4ms (both vxlan and udp, very little diffence), have anyone done test on that ? udp and vxlan, which has lower latency, esp. on virtual machines across different iaas?

**Comment by eyakubovich** [comment]
vxlan will have lower latency overhead but the difference obviously becomes less noticeable when the overall latency increases, as is the case if you're going across cloud providers.
