### ISSUE TITLE
Update flannel on yum

### ISSUE THREAD

**Issue by apeeyush** [coreos/flannel#346]
`yum install -y etcd` installs flannel 0.5.0 (instead of 0.5.3).

The command is used to install flannel in [Vagrant setup of Kubernetes](https://github.com/kubernetes/kubernetes/tree/master/cluster/vagrant). Update the yum package since the networking might fail in flannel 0.5.0 #325 

Alternatively, please provide alternate setup instructions for setting up with systemd and I'll be happy to update it in Kubernetes repo.

Thanks :)

**Comment by eyakubovich** [comment]
If `yum install -y etcd` installs flannel, there are bigger issues to address. We don't do the packaging so it would be up to RedHat to update their rpm.

You can download x64 binaries from Release section on GitHub. I assume you can just re-use the .service file that gets installed with 0.5.0 rpm.

**Comment by jeremyeder** [comment]
Ahh - I meant to reply to this.  Assuming OP meant ```yum install -y flanneld``` gets him 0.5.0 and he wants a later version.  That's true in Fedora 22.  Fedora rawhide has 0.5.3.

I've not tried it, but you might be able to just install the rawhide version of flannel on F22.

http://mirror.cc.vt.edu/pub/fedora/linux/development/rawhide/x86_64/os/Packages/f/

I asked in BZ https://bugzilla.redhat.com/show_bug.cgi?id=1273211 if we intend to update flannel in F22/F23.  Please feel free to comment there as well @apeeyush thanks!

**Comment by apeeyush** [comment]
Sorry! I meant `yum install -y flannel` and not `yum install -y etcd`. I'll try using the rawhide version of flannel sometime next week. Thanks for the help :)

**Comment by jeremyeder** [comment]
By then, we might have 0.5.4 in F22:  https://bodhi.fedoraproject.org/updates/FEDORA-2015-52e1ca8443

**Comment by ingvagabund** [comment]
The update will lie in updates until it gets 3 karmas. @apeeyush, can you test the build if it is working properly? Thanks

**Comment by philips** [comment]
Ping @jeremyeder and @apeeyush. What is the status?

**Comment by jeremyeder** [comment]
0.5.4 is in updates-testing in Fedora 23.  0.5.5 is in Fedora Rawhide.  I've pinged in the BZ about moving it to the regular updates repo in F23.  Some feedback on the testing F23 package would likely be appreciated.  https://dl.fedoraproject.org/pub/fedora/linux/updates/testing/23/x86_64/f/

@philips I also added you to the cc-list on the BZ.

**Comment by ingvagabund** [comment]
Would be great to have at least one karma. To make sure flannel-0.5.4 is installable and working elsewhere than on my machine. E.g. it could collide with other packages or introduce missing dependencies.

**Comment by tomdee** [comment]
Closing as this has been open for a long time. It would be great to sort out OS packaging of flannel but this isn't the best place to track that.

**Comment by ingvagabund** [comment]
flannel-0.7.0-2.fc25 is in stable and available since January 2017.

**Comment by tomdee** [comment]
@ingvagabund How do I get the latest version of flannel (v0.9.0) in stable?
