### ISSUE TITLE
*: flannel v0.5.4

### ISSUE THREAD

**Issue by jonboulle** [coreos/flannel#347]
Per https://github.com/coreos/flannel/pull/339#issuecomment-149054683 this would be a branch from 0.5.3 with at least https://github.com/jonboulle/flannel/commit/b2407f4bc306c07783c67b18289c7864ad109523 cherry-picked. @eyakubovich what else do you think should go in?

**Comment by eyakubovich** [comment]
I'd like to also do a5e1177ea803c1de5aaaca3fb47e847a6c644f6a, c623d5666ef076de1b79c7b86d72a9d68847f672, 40b61ef499145c2a399eb4e0dae046d30c2bbd7e

**Comment by jonboulle** [comment]
Fixed: https://github.com/coreos/flannel/releases/tag/v0.5.4
