### ISSUE TITLE
flanneld failed to retrieve network config with systemd but success when running standalone

### ISSUE THREAD

**Issue by xdays** [coreos/flannel#350]
Here's my systemd unit file:

<pre>
[Unit]
Description=Network fabric for containers
Documentation=https://github.com/coreos/flannel

[Service]
Type=notify
Restart=always
RestartSec=5
LimitNOFILE=40000
LimitNPROC=1048576
ExecStart=/opt/everstring/flannel/bin/flanneld -etcd-endpoints="http://10.50.0.116:2379"
ExecStartPost=/opt/everstring/flannel/bin/mk-docker-opts.sh
</pre>

and the error log is:

<pre>
Oct 21 10:58:46 ip-10-50-0-116 flanneld[13686]: E1021 10:58:46.203168 13686 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
Oct 21 10:58:47 ip-10-50-0-116 flanneld[13686]: E1021 10:58:47.203428 13686 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
Oct 21 10:58:48 ip-10-50-0-116 flanneld[13686]: E1021 10:58:48.203685 13686 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
Oct 21 10:58:49 ip-10-50-0-116 flanneld[13686]: E1021 10:58:49.203922 13686 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
Oct 21 10:58:50 ip-10-50-0-116 flanneld[13686]: E1021 10:58:50.204183 13686 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
Oct 21 10:58:51 ip-10-50-0-116 flanneld[13686]: E1021 10:58:51.204414 13686 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
Oct 21 10:58:52 ip-10-50-0-116 flanneld[13686]: E1021 10:58:52.204669 13686 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
</pre>

but when I start flannel alone, it works:

<pre>
/opt/everstring/flannel/bin/flanneld -etcd-endpoints="http://10.50.0.116:2379"
I1021 10:59:04.928831 13738 main.go:275] Installing signal handlers
I1021 10:59:04.928950 13738 main.go:130] Determining IP address of default interface
I1021 10:59:04.929139 13738 main.go:188] Using 10.50.0.116 as external interface
I1021 10:59:04.929154 13738 main.go:189] Using 10.50.0.116 as external endpoint
I1021 10:59:04.930951 13738 etcd.go:129] Found lease (10.0.58.0/24) for current IP (10.50.0.116), reusing
I1021 10:59:04.931680 13738 etcd.go:84] Subnet lease acquired: 10.0.58.0/24
I1021 10:59:04.932180 13738 udp.go:222] Watching for new subnet leases
</pre>

**Comment by eyakubovich** [comment]
This one is very surprising. Can you confirm that `ExecStart=/opt/everstring/flannel/bin/flanneld -etcd-endpoints="http://10.50.0.116:2379"` is exactly like that and not something with variable substitution? systemd is sometimes funky with variable expansion so that's the only thing I could think of.

**Comment by xdays** [comment]
Yes, you are right. I change the nit file to:

<pre>
[Unit]
Description=Network fabric for containers
Documentation=https://github.com/coreos/flannel

[Service]
Type=notify
Restart=always
RestartSec=5
LimitNOFILE=40000
LimitNPROC=1048576
EnvironmentFile=/opt/everstring/flannel/etc/option.env
ExecStart=/opt/everstring/flannel/bin/flanneld
ExecStartPost=/opt/everstring/flannel/bin/mk-docker-opts.sh
</pre>

and option.env is:
<pre>
FLANNELD_ETCD_ENDPOINTS="http://10.50.0.149:2379"
</pre>

it works now.
