### ISSUE TITLE
flannel design ideas

### ISSUE THREAD

**Issue by coocla** [coreos/flannel#352]
Hi:
    I would like to know some details about the flannel distribution network and IP.  When kubernetes is created or destroyed container, the flanneld is aware of how the resource changes are distributed, such as watch some key of etcd or the other?
   I tried to find these from the source code, but it was nothing to gain.

**Comment by eyakubovich** [comment]
flannel does not actually know anything about Docker or kubernetnes. It's designed to start up first, allocate an entire subnet (something like a /24) to a node and then hand that subnet to Docker or kubernetes. It's assumed that the operator can properly size the subnet for the maximum number of containers a single node can run.

**Comment by coocla** [comment]
Thank you very much.
