### ISSUE TITLE
Add consistent flannel configuration.

### ISSUE THREAD

**Issue by eveny** [coreos/flannel#360]
Hi, 
it is extremely annoying to configure flannel from cloud-config. When doing flannel configuration, you have to think about YAML, JSON, SHELL syntaxes and catch bugs in different files.
Please add consistent configuration for flannel in single file.

**Comment by tomdee** [comment]
Flannel is configured through command line options and JSON in etcd. I'm going to close this issue as I can't see a better way to do this, if you have some suggestions I can reopen it.
