### ISSUE TITLE
Change ca-certificate folder, or make it at least changeable

### ISSUE THREAD

**Issue by xoss** [coreos/flannel#365]
The entire documentation of coreos says, that ca.pem should be  put to `/etc/ssl/certs`, as this folder consists of the trusted ca.
 Strange enough, the flanneld service maps following volumes into the docker container:

``` bash
ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock \
  /usr/bin/docker run --net=host --privileged=true --rm \
  --volume=/run/flannel:/run/flannel \
  --env=NOTIFY_SOCKET=/run/flannel/sd.sock \
  --env=AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
  --env=AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
  --env-file=${FLANNEL_ENV_FILE} \
  --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro \
  --volume=${ETCD_SSL_DIR}:/etc/ssl/etcd:ro \
  quay.io/coreos/flannel:${FLANNEL_VER} /opt/bin/flanneld --ip-masq=true
```
1. `/usr/share/ca-certificates` is the read-only coreos partition
2. `${ETCD_SSL_DIR}` should contain the `client.pem` and `client-key.pem` files,  but not the `ca.pem`. This should be stored in `/etc/ssl/certs`.
   Within the container, `ca.pem` file is not found, since the path `/etc/ssl/certs/ca.pem` does not exists because of obvious reasons.

Either add a ${OPTIONS_VOLUME_ENV} variable to make this behavior changeable,
or map hosts `/etc/ssl/certs:/etc/ssl/certs:ro` into the container instead of `/usr/share/ca-certificates`

**Comment by eyakubovich** [comment]
@xoss You're right that it's not ideal but see https://github.com/coreos/flannel/issues/302 for explanation on why it is done this way.

**Comment by vboginskey** [comment]
This doesn't appear to be the case anymore:

```
core@ip-10-88-20-186 /etc/ssl/certs $ ls -l *.pem | head -5
-rw-r--r--. 1 root root 1383 Dec  7 09:11 A-Trust-nQual-03.pem
-rw-r--r--. 1 root root 2772 Dec  7 09:11 ACCVRAIZ1.pem
-rw-r--r--. 1 root root 2041 Dec  7 09:11 ACEDICOM_Root.pem
-rw-r--r--. 1 root root 2281 Dec  7 09:11 AC_Raíz_Certicámara_S.A..pem
-rw-r--r--. 1 root root 2049 Dec  7 09:11 Actalis_Authentication_Root_CA.pem
```

flanneld shouldn't enforce a separate SSL directory for certs and keys that work just fine when placed in the standard locations `/etc/ssl/certs` and `/etc/ssl/private`.
