### ISSUE TITLE
Flanneld restarted with out of memory error

### ISSUE THREAD

**Issue by kbrwn** [coreos/flannel#367]
tested on both flannel:0.5.3 and flannel:0.5.4. @kayrus was able to reproduce and found flannel ignores bonding and infinitely tries to add fdb entry for eth0 and eth1 instead of bond0

journal:
[flannel_output.txt](https://github.com/coreos/flannel/files/33557/flannel_output.txt)

**Comment by eyakubovich** [comment]
Fixed in https://github.com/coreos/flannel/releases/tag/v0.5.5
