### ISSUE TITLE
flannel should ship a binary release hosted on GitHub

### ISSUE THREAD

**Issue by kelseyhightower** [coreos/flannel#37]
Is it to early to start cutting binary releases of Rudder?

**Comment by sbhaskaran** [comment]
we are running CoreOS behind firewall and have no internet access. Will it be possible to get flannel binary available ?

**Comment by eyakubovich** [comment]
@sbhaskaran I've created binaries for v0.3.0 release: https://github.com/coreos/flannel/releases/download/v0.3.0/flannel-linux-amd64-0.3.0.tar.gz

I'll try to make amd64 binaries from now on.

**Comment by denisura** [comment]
Link to v0.3.0 release: https://github.com/coreos/flannel/releases/download/v0.3.0/flannel-0.3.0-linux-amd64.tar.gz
