### ISSUE TITLE
Detect iptables version and avoid --wait

### ISSUE THREAD

**Issue by bprashanth** [coreos/flannel#374]
Logs seem to indicate it isn't available on 1.4.14 which comes with a stock gce vm.
```
E1121 06:03:55.025714 03163 network.go:80] Failed to set up IP Masquerade for network : Failed to create/clear FLANNEL chain in NAT table: exit status 2: iptables v1.4.14: unknown option "--wait"
```

**Comment by jonboulle** [comment]
coreos/go-iptables#8

**Comment by philips** [comment]
@jonboulle since https://github.com/coreos/go-iptables/pull/12 is merged can we just bump the dependency to move forward?

**Comment by jonboulle** [comment]
Yes AFAICT

**Comment by davidsiefert** [comment]
Having enormous trouble with godep to update dependencies... what version of dep are you guys using where it works to update?

**Comment by jonboulle** [comment]
Almost always want to use the very latest version of godep.

**Comment by davidsiefert** [comment]
Okay I figured out this godep issue (I think) and have another open issue #406 which blocked me from updating the coreos/go-iptables dependency using godep.  Once that PR is merged, I have another fix on a branch to update go-iptables with the fix needed.
