### ISSUE TITLE
firewalld & flannel

### ISSUE THREAD

**Issue by robtaireeo** [coreos/flannel#375]
I am looking for help with firewalld rules to allow flannel to work in my environment, sorry if this is the wrong place to post this.

I have flannel setup across 2 RHEL 7 hosts with firewalld enabled as it is a requirement for me.

I can ping a running container across hosts, but I cannot curl the same container; i get a "Failed connect to 172.32.68.2:8080; No route to host"

Watching tcpdump on my main eth I see:
17:13:26.811485 IP 172.32.12.0.46667 > 172.32.68.2.webcache: Flags [S], seq 4148879903, win 29200, options [mss 1460,sackOK,TS val 4898533 ecr 0,nop,wscale 7], length 0

The curl works once I stop firewalld.

I assume I need to allow the subnet range somehow?

Any help will be appreciated.

**Comment by xiang90** [comment]
@robtaireeo Why this is closed? Have you figured it out yourself? Sorry for the delay. @eyakubovich is on a vacation.

**Comment by robtaireeo** [comment]
@xiang90 I did not figure it out, but I believe my issue is not flannel, but really libreswan/ipsec, as I am trying to encrypt flannel traffic between the two hosts.

**Comment by xiang90** [comment]
OK. Thank you.
