### ISSUE TITLE
Flannel 0.5.5 will not write subnet.env file

### ISSUE THREAD

**Issue by stepanstipl** [coreos/flannel#387]
I have experienced problem when flannel will not write subnet.env file. First I've tried to use it with `FLANNELD_SUBNET_FILE` env variable set to custom location, but even without it no file is written.

I'm using official quay.io/coreos/flannel container.

This seems to be specific to 0.5.5 version, when I downgrade to 0.5.4 file is written as expected.

**Comment by philips** [comment]
Hrm, we haven't had any particular reports of this issue and 0.5.5 has been the default since Dec. 8th 2015. Can you show me how you are running it? The exact flags.

**Comment by macropin** [comment]
Not sure if it is related but we are having an race condition with `/run/flannel/subnet.env` generation. 

The flannel systemd service starts the flannel docker container (`ExecStart`) and then runs `/opt/bin/mk-docker-opts.sh` in a following container (`ExecStartPost`) but the `subnet.env` file has not yet been generated, so the resulting `/run/flannel_docker_opts.env` is empty.

**Comment by stepanstipl** [comment]
I'll close this one, to be honest not sure what was the issue. I've since changed to use flannel in client/server mode and I don't experience this anymore even with flannel 0.5.5. Quite possible it was related to some race condition in my CoreOS services config. I shamefully admin I didn't note enough details and changed too many things in my setup to be able to reproduce easily. Thanks though for coming back
