### ISSUE TITLE
Problems from vxlan depolyment

### ISSUE THREAD

**Issue by Zpandas** [coreos/flannel#388]
I deployed a kubernetes cluster which used flannel as an overlay network.  Tun mode works great. However, it did not work when I switched to vxlan mode. Much more details are described as below:
# etcd config

```
etcdctl set /coreos.com/network/blue/config  '{ "Network": "11.1.0.0/16", "Backend": { "Type": "vxlan", "VNI": 1 } }'
```
# 1st minion node
## vxlan flannel.1 ip

```
flannel.1 Link encap:Ethernet  HWaddr 9e:4c:6b:54:b6:36
          inet addr:11.1.16.0  Bcast:0.0.0.0  Mask:255.255.0.0
```
## route tables

```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.122.1   0.0.0.0         UG    0      0        0 eth0
11.1.0.0        *               255.255.0.0     U     0      0        0 flannel.1
```
# 2nd minion node
## vxlan flannel.1 ip

```
flannel.1 Link encap:Ethernet  HWaddr ae:82:99:72:21:49
          inet addr:11.1.100.0  Bcast:0.0.0.0  Mask:255.255.0.0
```
## route tables

```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.122.1   0.0.0.0         UG    0      0        0 eth0
11.1.0.0        *               255.255.0.0     U     0      0        0 flannel.1
```

I did a simple test to verify vxlan connectitviy by tying to ping 11.1.100.0 from 11.1.16.0. Howerver, I got nothing, can someone give me some suggestion to that. Thanks a lot in advance!

**Comment by philips** [comment]
What environment did you deploy this in? Can you try dumping the packets between the hosts? Is there anything in the `dmesg` or `flanneld` logs? Can you try running some simple TCP service between hosts instead of ping?

**Comment by tomdee** [comment]
Closing as not enough info to diagnose.
