### ISSUE TITLE
Build flannel statically

### ISSUE THREAD

**Issue by luxas** [coreos/flannel#389]
Hello,
Would it be supported to build `flanneld` statically with the argument `--ldflags '-extldflags "-static"'` to `go build`?

I'm wondering if it would be possible to package `flannel` in an `alpine` container with `iptables`
That would decrease image size a lot
I'm testing it right now

**Comment by philips** [comment]
@luxas Yea, that should work. Do you want to give us a PR that makes this change? I just tried it and it works.

```
diff --git a/build b/build
index f56cabf..7973006 100755
--- a/build
+++ b/build
@@ -18,7 +18,7 @@ function linker_dashX {
 ORG_PATH="github.com/coreos"
 REPO_PATH="${ORG_PATH}/flannel"
 VERSION=$(git describe --dirty)
-GLDFLAGS="-X $(linker_dashX github.com/coreos/flannel/version.Version ${VERSION})"
+GLDFLAGS="-X $(linker_dashX github.com/coreos/flannel/version.Version ${VERSION}) -extldflags '-static'"

 if [ ! -h gopath/src/${REPO_PATH} ]; then
        mkdir -p gopath/src/${ORG_PATH}
```

**Comment by luxas** [comment]
Yeah, I can make the PR soon.

**Comment by davidsiefert** [comment]
Be so nice to get this merged... +1 :smiley:

**Comment by tomdee** [comment]
See also #439

**Comment by tomdee** [comment]
This is now merged in master.
