### ISSUE TITLE
Kubernets UI not getting access for kubernets cluster

### ISSUE THREAD

**Issue by yogeshmsharma** [coreos/flannel#391]
setup Details
===============
1. Atomic Host 7.2 
2.  Oracle Virtual Box  
3. Kubernet-master and kubelets are installed on two vms
4. Using flammer 

Pod details 
=======================
bash-4.2# kubectl get po --namespace=kube-system
NAME               READY     STATUS    RESTARTS   AGE
kube-ui-v4-xnkwx   1/1       Running   0          8m

Getting below error both from browser  and curl (from kubernet-masster)

Error: 'dial tcp 10.20.10.15:8080: no route to host'
Trying to reach: 'http://10.20.10.15:8080/

**Comment by philips** [comment]
@yogeshmsharma I don't see what your question is. Can you please provide a way for me to reproduce or a deeper explanation of what you are doing and what you expected to happen? Most importantly I need to understand how flannel is involved here.

I am closing this for now as it is unclear where a flannel bug exists.
