### ISSUE TITLE
UDP backend listening on 0.0.0.0 instead of specified interface

### ISSUE THREAD

**Issue by smessmer** [coreos/flannel#394]
I'm setting up a kubernetes cluster. All servers are connected using a VPN and flannel is meant to run on the vpn internal IPs. Each server has the following interfaces
 - eth0: public IP. The only service using this interface is the VPN service.
 - vpn: internal IP (10.1.0.3)

````
docker -H unix:///var/run/docker-bootstrap.sock run --net=host --log-driver=syslog --privileged -v /dev/net:/dev/net --name='flannel' --restart=always -d 'quay.io/coreos/flannel:0.5.5' /opt/bin/flanneld -alsologtostderr=true -iface '10.1.0.3'
````

Flannel starts up, connects and everything works fine.

However, netstat shows it connected its UDP port to 0.0.0.0 instead of 10.1.0.3:

    $ sudo netstat -plunt
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
    [...]
    tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      946/etcd        
    tcp        0      0 10.1.0.3:2379           0.0.0.0:*               LISTEN      946/etcd        
    tcp        0      0 10.1.0.3:2380           0.0.0.0:*               LISTEN      946/etcd         
    udp        0      0 0.0.0.0:8285            0.0.0.0:*                           1632/flanneld   
    [...]

This is a security hole I'd like to avoid. Shouldn't the **-iface** parameter restrict flannel to the internal interface?

**edit: Steps to reproduce:**

    docker run --net=host -d gcr.io/google_containers/etcd:2.0.12 /usr/local/bin/etcd --addr=127.0.0.1:4001 --bind-addr=0.0.0.0:4001 --data-dir=/var/etcd/data
    docker run --net=host gcr.io/google_containers/etcd:2.0.12 etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
    docker run --net=host --privileged -v /dev/net:/dev/net --name='flannel' --restart=always -d 'quay.io/coreos/flannel:0.5.5' /opt/bin/flanneld -alsologtostderr=true -iface '127.0.0.1'
    sudo netstat -plunt

**Comment by smessmer** [comment]
Any news on this? Is this a bug or am I using it wrongly?

**Comment by philips** [comment]
Sorry about this. I am taking a look at this now.

**Comment by smessmer** [comment]
Sure. The pull request I attached is fixing it.

**Comment by philips** [comment]
Fixed via https://github.com/coreos/flannel/commit/6c95ca9086cf7f5fc6e1d415fb23c50aeec34c04
