### ISSUE TITLE
Etcd Auth

### ISSUE THREAD

**Issue by cvle** [coreos/flannel#395]
What are your thoughts on supporting Basic Auth using the [etcd auth api](https://github.com/coreos/etcd/blob/master/Documentation/auth_api.md)?

**Comment by shanegibbs** [comment]
:+1: here

**Comment by shanegibbs** [comment]
For those that are interested -> https://github.com/coreos/flannel/pull/409

**Comment by tomdee** [comment]
Now merged to master so closing
