### ISSUE TITLE
kubernetes integration

### ISSUE THREAD

**Issue by philips** [coreos/flannel#402]
We need to think through how locksmith will integrate with kubernetes and the kubelet. For example perhaps the locksmithd daemon needs to present a filesystem based API that the kubelet can consume to know when an update is applied and the node is ready for reboot. This would be something like the node out of disk or node ready state: https://github.com/kubernetes/kubernetes/blob/c4b66f66f3fb1d1f284b3b67a8df276d246cf8bf/pkg/kubelet/kubelet.go#L2865

![screen shot 2016-02-09 at 3 46 17 pm](https://cloud.githubusercontent.com/assets/33544/12934555/48df373c-cf44-11e5-85b6-293549a4362e.png)

**Comment by philips** [comment]
Oops, I meant to file this on locksmith.

**Comment by sjpotter** [comment]
Are you just asking for a way to programatically tell k8s that a node has to go offline for maintenance purposes so stop scheduling pods to it?  i.e. should it care about why its going down for maintenance?  i.e. seems generic functionality.  

thinking

https://github.com/kubernetes/kubernetes/issues/3885
