### ISSUE TITLE
[Bug] Lease could not be renewed without NTP synchronization

### ISSUE THREAD

**Issue by yingfeng** [coreos/flannel#404]
We've found that the subnet route would be lost once a day on each physical host because our distributed environment had not been made synchronized to NTP time.  Also we've found that the reason might be caused according to the following code snippet:

```
dur := n.bn.Lease().Expiration.Sub(time.Now()) - renewMargin
    for {
        select {
        case <-time.After(dur):
            err := n.sm.RenewLease(n.ctx, n.Name, n.bn.Lease())
            if err != nil {
                log.Error("Error renewing lease (trying again in 1 min): ", err)
                dur = time.Minute
                continue
            }

            log.Info("Lease renewed, new expiration: ", n.bn.Lease().Expiration)
            dur = n.bn.Lease().Expiration.Sub(time.Now()) - renewMargin
```

I have a question on the above snippet: currently, the lease renew time interval is based on the local TTL, why not adopt timer after starting creating subnet to etcd which might not trigger the route lost bug mentioned above? It makes the lease renew fragile.

Another problem of the above design is: whenever a subnet route has been lost, the internal subnet within docker containers of the host could not be connected with other subnets due to the lost of routing information, then we have to restart docker dameon which makes the overall system more fragile.

**Comment by tomdee** [comment]
I'm going to track this clock sync issue under #340 so closing this issue
