### ISSUE TITLE
Docker pull fails with flannel images

### ISSUE THREAD

**Issue by idvoretskyi** [coreos/flannel#410]
I've tried to pull an image from flannel repo, but all the attempts have failed:

```
docker pull quay.io/coreos/flannel
Using default tag: latest
Pulling repository quay.io/coreos/flannel
Tag latest not found in repository quay.io/coreos/flannel
```
or
```
docker pull quay.io/coreos/flannel:latest
Pulling repository quay.io/coreos/flannel
Tag latest not found in repository quay.io/coreos/flannel
```
or
```
docker pull quay.io/coreos/flannel:v0.5.5
Pulling repository quay.io/coreos/flannel
Tag v0.5.5 not found in repository quay.io/coreos/flannel
```

What might be the reason on how is it possible to fix?

**Comment by someword** [comment]
Check out the list of tags here https://quay.io/repository/coreos/flannel?tab=tags

In this repo they don't have a 'v' in the version tag.  So you should be able to pull the following
 quay.io/coreos/flannel:0.5.5

Also fwiw doing 'docker pull -a quay.io/coreos/flannel' would pull every tag which could help you find the specific tag you want.

**Comment by idvoretskyi** [comment]
@someword thank you.
