### ISSUE TITLE
flanneld.service start issue

### ISSUE THREAD

**Issue by gembin** [coreos/flannel#413]
CoreOS version: 970.1.0
I already pulled `quay.io/coreos/flannel:0.5.5`,  and then start flanneld `sudo systemctl start flanneld.service`
```
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
quay.io/coreos/flannel   0.5.5               9d9e3922a0dc        3 months ago        26.29 MB
```
But, it still cannot find the image and try to pull it again
```
sdnotify-proxy[23982]: Unable to find image 'quay.io/coreos/flannel:0.5.5' locally
sdnotify-proxy[23982]: 0.5.5: Pulling from coreos/flannel
```

**Comment by gembin** [comment]
Because the VM cannot access the Internet, so the images was pulled from local docker registry and re-tag to `quay.io/coreos/flannel:0.5.5`.  And the images was already exists, I don't understand why it pulls again, as a result it will fail to pull because it cannot access the Internet.

**Comment by brianredbeard** [comment]
In the `flanneld.service` file there are two environment variables one may set:

```
Environment="FLANNEL_VER=0.5.5"
Environment="FLANNEL_IMG=quay.io/coreos/flannel"
```

Which are then consumed as:
```
ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock \
  /usr/bin/docker run --net=host --privileged=true --rm \
  --volume=/run/flannel:/run/flannel \
  --env=NOTIFY_SOCKET=/run/flannel/sd.sock \
  --env=AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
  --env=AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
  --env-file=${FLANNEL_ENV_FILE} \
  --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro \
  --volume=${ETCD_SSL_DIR}:${ETCD_SSL_DIR}:ro \
  ${FLANNEL_IMG}:${FLANNEL_VER} /opt/bin/flanneld --ip-masq=true
```

If you fix those up with a systemd drop-in, everything should work just fine.

**Comment by gembin** [comment]
Yes, it works if i change the image points to local docker registry. But if image is already pulled locally, and then if the vm cannot access the local registry because of some network issues, it failed to work, complains about cannot find the image and will try to pull it again.

So, does it mean it will always try to access the docker registry to check if the images already pulled or not ?

**Comment by tomdee** [comment]
If the image exists locally, Docker won't try to repull it. 

Hopefully this answers your question, please feel free to reopen the issue if you need more help.

**Comment by teestone** [comment]
I met the same problem.

Jun 18 13:20:00 localhost sdnotify-proxy[1931]: See '/usr/bin/docker run --help'.
Jun 18 13:20:00 localhost systemd[1]: flanneld.service: Main process exited, code=exited, status=125/n/a
Jun 18 13:20:00 localhost systemd[1]: Failed to start Network fabric for containers.
Jun 18 13:20:00 localhost systemd[1]: Dependency failed for Docker Application Container Engine.
Jun 18 13:20:00 localhost systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Jun 18 13:20:00 localhost systemd[1]: flanneld.service: Unit entered failed state.
Jun 18 13:20:00 localhost systemd[1]: flanneld.service: Failed with result 'exit-code'.
Jun 18 13:20:05 localhost systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
Jun 18 13:20:05 localhost systemd[1]: Stopped Network fabric for containers.
Jun 18 13:20:05 localhost systemd[1]: Starting Network fabric for containers...
Jun 18 13:20:06 localhost dockerd[1374]: time="2016-06-18T13:20:06.541049401Z" level=error msg="Handler for POST /v1.22/containers/create returned error: No such image: quay.io/coreos/flannel:0.5.5"
Jun 18 13:20:06 localhost sdnotify-proxy[1969]: Unable to find image 'quay.io/coreos/flannel:0.5.5' locally
Jun 18 13:20:17 localhost sdnotify-proxy[1969]: 0.5.5: Pulling from coreos/flannel
Jun 18 13:20:17 localhost sdnotify-proxy[1969]: 7bfac8493465: Pulling fs layer
Jun 18 13:20:17 localhost sdnotify-proxy[1969]: a3ed95caeb02: Pulling fs layer
Jun 18 13:20:17 localhost sdnotify-proxy[1969]: fdaeea203ca1: Pulling fs layer
Jun 18 13:20:17 localhost sdnotify-proxy[1969]: 1f0ee8606937: Pulling fs layer
Jun 18 13:20:17 localhost sdnotify-proxy[1969]: a3ed95caeb02: Download complete
Jun 18 13:20:17 localhost sdnotify-proxy[1969]: 1f0ee8606937: Download complete



Jun 18 13:21:36 localhost systemd[1]: flanneld.service: Start operation timed out. Terminating.
Jun 18 13:21:36 localhost systemd[1]: flanneld.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 18 13:21:36 localhost systemd[1]: Failed to start Network fabric for containers.
Jun 18 13:21:36 localhost systemd[1]: Dependency failed for Docker Application Container Engine.
Jun 18 13:21:36 localhost systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Jun 18 13:21:36 localhost systemd[1]: flanneld.service: Unit entered failed state.
Jun 18 13:21:36 localhost systemd[1]: flanneld.service: Failed with result 'exit-code'.
Jun 18 13:21:41 localhost systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
Jun 18 13:21:41 localhost systemd[1]: Stopped Network fabric for containers.
Jun 18 13:21:41 localhost systemd[1]: Starting Network fabric for containers...
Jun 18 13:21:42 localhost dockerd[1374]: time="2016-06-18T13:21:42.076656400Z" level=error msg="Handler for POST /v1.22/containers/create returned error: No such image: quay.io/coreos/flannel:0.5.5"
Jun 18 13:21:42 localhost sdnotify-proxy[2016]: Unable to find image 'quay.io/coreos/flannel:0.5.5' locally
Jun 18 13:21:50 localhost sdnotify-proxy[2016]: 0.5.5: Pulling from coreos/flannel
Jun 18 13:21:50 localhost sdnotify-proxy[2016]: 7bfac8493465: Pulling fs layer
Jun 18 13:21:50 localhost sdnotify-proxy[2016]: a3ed95caeb02: Pulling fs layer
Jun 18 13:21:50 localhost sdnotify-proxy[2016]: fdaeea203ca1: Pulling fs layer
Jun 18 13:21:50 localhost sdnotify-proxy[2016]: 1f0ee8606937: Pulling fs layer
Jun 18 13:21:50 localhost sdnotify-proxy[2016]: a3ed95caeb02: Download complete
Jun 18 13:21:50 localhost sdnotify-proxy[2016]: 1f0ee8606937: Download complete

Repeat and repeat again.

**Comment by teestone** [comment]
Found the root cause.
flannel is pulled by early-docker service, not docker service.

**Comment by voa808** [comment]
teestone: I am facing a similar issue. Could you please help how did you surpass the error.

**Comment by faxioman** [comment]
rkt fetch quay.io/coreos/flannel:0.5.5 always get a "fetch: discovery failed" error.
Please, move flannel to docker hub ... please :(
