### ISSUE TITLE
Env file gets overridden by the systemd service

### ISSUE THREAD

**Issue by aabed** [coreos/flannel#429]
/run/flanneld/options.env
works fine for the first time, but when I reboot it's all gone

**Comment by tomdee** [comment]
@aabed Can you describe your environment a little more? This is the systemd service file included in CoreOS right? Which version of Coreos did you see this problem on?

**Comment by eyakubovich** [comment]
`/run` is usually tmpfs so will be gone on a reboot. If you want settings to persist, you will need to use `/etc`.

**Comment by tomdee** [comment]
Closing as I'm not sure what the issue is. @aabed Please reopen if you're still having a problem here.
