### ISSUE TITLE
https: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by clinta** [coreos/flannel#432]
To reproduce:
1. Create certificates with openssl, following instructions here: https://github.com/kelseyhightower/etcd-production-setup
2. Run etcd in docker:

```
docker run -it \
  --rm \
  --net=host \
  -v /home/clint/ssl:/etc/ssl:ro \
  gcr.io/google_containers/etcd-amd64:2.2.1 \
    /usr/local/bin/etcd \
    --advertise-client-urls https://127.0.0.1:2379 \
    --listen-client-urls https://127.0.0.1:2379 \
    --key-file /etc/ssl/private/etcd0.example.com.key \
    --cert-file /etc/ssl/certs/etcd0.example.com.crt \
    --trusted-ca-file /etc/ssl/certs/ca.crt \
    --client-cert-auth
```
1. Use curl to verify client auth works:

```
curl \
  --cacert certs/ca.crt \
  --cert certs/etcd-client.crt \
  --key private/etcd-client.key \
  -L https://127.0.0.1:2379/health
{"health": "true"}% 
```
1. Run Flannel with options for etcd client tls

```
docker run -it \
  --rm \
  --net=host \
  --privileged \
  -v /home/clint/ssl:/etc/ssl:ro \
  -v /dev/net:/dev/net \
  quay.io/coreos/flannel:0.5.5 \
    /bin/sh -c /opt/bin/flanneld \
    --etcd-keyfile="/etc/ssl/private/etcd-client.key" \
    --etcd-certfile="/etc/ssl/certs/etcd-client.crt" \
    --etcd-cafile="/etc/ssl/certs/ca.crt" \
    --etcd-endpoints="https://127.0.0.1:2379" 
```

Flannel repeatedly logs `Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured`

Also tested without `--client-cert-auth` on etcd and without `--etcd-keyfile` and `--etcd-certfile`, and get the same results. So it appears to be a tls issue independent of client auth.

**Comment by clinta** [comment]
It looks like this issue only occurs when using the cli flags, using environment variables works fine.

**Comment by tomdee** [comment]
This etcd client has been updated so this should no longer be a problem. Please comment and I can reopen if anyone can still repro this bug.
