### ISSUE TITLE
nginx reverse-proxy gets real remote IP with CoreOS 835.11, but not with CoreOS 899.15

### ISSUE THREAD

**Issue by streamnsight** [coreos/flannel#433]
I use Kubernetes on CoreOS + Flannel.

I have a `nginx` reverse-proxy that is running on a CoreOS `835.11` node (yes a few months old). 
On this node, I can get the real remote IP with `$remote_addr` in logging with `nginx`.

I started a few more nodes the same way (iPXE boot with same cloud-config) and started a new instance of the nginx pod on one of the new node, but this one does not get the remote IP: it gets the IP of the `docker0` bridge on that node.

Has something changed in the networking setting, Flannel, or Docker that would cause this?
I'm not a network expert.

I have tried using the `real_ip` module in nginx, but that did not help; I also tried logging all the different ip lookup names like `$realip_remote_addr`, `$http_x_real_ip` `$http_x_forwarded_for` but they all return the `docker0` bridge address.

Any suggestion would be greatly appreciated.
Thanks

**Comment by tomdee** [comment]
Can you confirm what versions of docker and kubernetes you're using with the two different versions of CoreOS?

**Comment by streamnsight** [comment]
CoreOS stable (899.15.0)
Docker version 1.9.1, build 9894698

CoreOS stable (835.11.0)
Docker version 1.8.3, build cedd534-dirty

I use Kubernetes v1.2.2 on both
Thanks

**Comment by streamnsight** [comment]
@tomdee does that help?

**Comment by celevra** [comment]
same Problem here

**Comment by styxlab** [comment]
I experience the same problem.
Tracked it down to https://github.com/coreos/flannel/pull/327
To fix, I created a new flanneld drop-in and set the -ip-masq flag to **false**:

    - name: flanneld.service
      drop-ins:
        - name: 10-nomasq.conf
          content: |
            [Service]
            ExecStart=            
            ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock \
            /usr/bin/docker run --net=host --privileged=true --rm \
            --volume=/run/flannel:/run/flannel \
            --env=NOTIFY_SOCKET=/run/flannel/sd.sock \
            --env=AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
            --env=AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
            --env-file=${FLANNEL_ENV_FILE} \
            --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro \
            --volume=${ETCD_SSL_DIR}:${ETCD_SSL_DIR}:ro \
            ${FLANNEL_IMG}:${FLANNEL_VER} /opt/bin/flanneld --ip-masq=false 
                  
That change fixed it for me, but I think the coreos team should look closer into this issue because the default setting is --ip-masq=true.

**Comment by tomdee** [comment]
I think this problem was introduced in 0.5.4 and was fixed with https://github.com/coreos/flannel/pull/745 in v0.8.0
