### ISSUE TITLE
Is it usable with LXC?

### ISSUE THREAD

**Issue by sokoow** [coreos/flannel#440]
Did anybody use this with lxc and can share some thoughts about it ?

**Comment by tomdee** [comment]
Hi @sokoow, since there's not been a response on here I'm going to close this issue. It's probably worth asking on the coreos-users mailing list or the #coreos IRC channel on freenode.org

(See https://github.com/coreos/flannel/blob/master/CONTRIBUTING.md#email-and-chat)
