### ISSUE TITLE
[Question] Flannel client/server 

### ISSUE THREAD

**Issue by hectorj2f** [coreos/flannel#443]
Hello there! I have some questions regarding the client/server flannel new model. I need some answers to proceed with this setup.

Could I have multiple nodes in my cluster working as servers ? 
Will those servers talk to each other like in a by default setup ? 
Can a node work as server and keep doing the same job the daemon does without --listen ?

My idea is to modify the flanneld.service unit adding `--listen` to its definition for three of my nodes. Then I'll configure the nodes to be clients of some of these three servers.

Is that possible ? Thanks.

**Comment by hectorj2f** [comment]
I did some tests and it seems to behave correctly a deployment of multiple server/client hosts and multiple clients that depend of each server. However I'd like to know the answer of some of my questions in here.

**Comment by eyakubovich** [comment]
> Could I have multiple nodes in my cluster working as servers ? 

Yes. You can have as many servers as you want. They're stateless as the state is stored in etcd.

> Will those servers talk to each other like in a by default setup ?

No but they don't need to as they coordinate through etcd.

> Can a node work as server and keep doing the same job the daemon does without --listen ?

No. You'll need to run two instances of the flanneld binary.

**Comment by hectorj2f** [comment]
Thanks @eyakubovich I moved forward. I am happily using the client/server model.
