### ISSUE TITLE
subnet mask problem

### ISSUE THREAD

**Issue by xxyztwz** [coreos/flannel#445]
I have some vm hosts with coreos 899.6
The flannel network config is : { "Network":"172.18.0.0/16" }
flannel version is 0.5.5

for exapmle, host A get 172.18.3.0/24 and host B get 172.18.56.0/24
I run container on these two hosts.
the container with IP 172.18.3.2 can access 172.18.56.2
BUT the subnet mask of container is 24!

So the real problem is When I run  redis cluster use sentinel mode:
When I run redis sentinel on different hosts, they think they are in different subnet and found the master node with the wrong slave ip address.

```
# Replication
role:master
connected_slaves:2
slave0:ip=172.18.72.4,port=6379,state=online,offset=37705,lag=0
slave1:ip=172.18.82.0,port=6379,state=online,offset=37705,lag=1
master_repl_offset:37705
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:2
repl_backlog_histlen:37704
```

sentinel.conf

```
sentinel monitor mymaster 172.18.72.3 6379 2
sentinel down-after-milliseconds mymaster 60000
sentinel config-epoch mymaster 0
sentinel leader-epoch mymaster 0
# Generated by CONFIG REWRITE
port 26379
dir "/data"
sentinel known-slave mymaster 172.18.82.0 6379
sentinel known-slave mymaster 172.18.72.4 6379
sentinel known-sentinel mymaster 172.18.72.3 26379 86151ac2ef870902301aee1e584a7133a594a52c
sentinel known-sentinel mymaster 172.18.72.9 26379 3469343b69dbe7de1bc49b8f8c0c565631f03afa
sentinel current-epoch 0
```

```
NameSpace            Pod Name                                           Status          Pod IP               Host IP              
default              redis-04edy                                        Running         172.18.72.4          192.168.1.220        
default              redis-byl7k                                        Running         172.18.82.8          192.168.1.219        
default              redis-master                                       Running         172.18.72.3          192.168.1.220        
default              redis-sentinel-e9o9e                               Running         172.18.82.9          192.168.1.219        
default              redis-sentinel-y84h5                               Running         172.18.72.9          192.168.1.220
```

I deploy the redis sentinel by docs (https://github.com/kubernetes/kubernetes/tree/release-1.2/examples/redis/)

**Comment by tomdee** [comment]
Thanks for the question but I'm not a redis expert. I've taken a quick look at the redis sentinel documentation (http://redis.io/topics/sentinel) and I can't see that it would be a problem running it on flannel. 

Although the redis instances are on different subnets, they can still communicate with each other. I think you're saying they're using the wrong IP addresses but I don't understand where the wrong IP addresses are coming from.

**Comment by tomdee** [comment]
Hmm, looks like redis sentinel has caused problems before - #412

**Comment by xxyztwz** [comment]
same as #412

**Comment by tomdee** [comment]
Closing this old issue. Please comment if still a problem and I can reopen.
