### ISSUE TITLE
Is it possible to run Flanneld as a container

### ISSUE THREAD

**Issue by qianzhangxa** [coreos/flannel#448]
Hi,

I am trying to build a system where each management service will run as a Docker container, and I plan to use Flanneld to integrate with Docker engine to provide multi-host network for containers. So I'd like to know if it is possible to run Flanneld as a Docker container. Thanks!

**Comment by glevand** [comment]
@qianzhangxa CoreOS currently packages flannel as a docker container.
See https://github.com/glevand/coreos--coreos-overlay/blob/master/app-admin/flannel/files/flanneld.service

**Comment by qianzhangxa** [comment]
Great, thanks @glevand !
