### ISSUE TITLE
Docker build errors

### ISSUE THREAD

**Issue by mharj** [coreos/flannel#450]
When checkout from git Docker seems to use golang:1.4.1-onbuild and fails
```
../golang.org/x/net/context/ctxhttp/ctxhttp.go:35: req.Cancel undefined (type *http.Request has no field or method Cancel)
../github.com/coreos/etcd/client/cancelreq.go:13: req.Cancel undefined (type *http.Request has no field or method Cancel)
```
If I change golang:1.5-onbuild (which have Cancel method)
```
../github.com/coreos/flannel/subnet/registry.go:79: not enough arguments in call to transport.NewTransport
```
If change to golang:1.6-onbuild ... seems to compile ok, so should this Dockerfile updated to use 1.6 instead?

**Comment by tomdee** [comment]
Dockerfile is now updated

**Comment by sunflower9973** [comment]
Still an error:
core@coreos01vt ~ $ docker run -i -t google/golang /bin/bash -c "go get github.com/coreos/flannel"

# github.com/coreos/flannel/subnet
../github.com/coreos/flannel/subnet/registry.go:79: not enough arguments in call to transport.NewTransport

**Comment by nwjeeper33** [comment]
I am using the same docker command above, and got same exact error. Can you help please?
Is it related to etcd2 configuration, not installing CA on the box? Any feedback would be appreciated!!

**Comment by migeorge** [comment]
@sunflower9973 @nwjeeper33 I had success building with the newer golang container:
`docker run -i -t golang:1.6 /bin/bash -c "go get github.com/coreos/flannel"`

The binary will be located at `/go/bin/flannel`

**Comment by kdx99** [comment]
Many thanks, with the version 1.6 it worked !
(...
Status: Downloaded newer image for golang:1.6)
