### ISSUE TITLE
building flannel in docker fails

### ISSUE THREAD

**Issue by sbezverk** [coreos/flannel#454]
Hello I am trying to build flannel in docker following the documentation.

Here is what I get when I start building process:

docker run -v /root/deployments/kubernetes/source/flannel/flannel:/opt/flannel -i -t google/golang /bin/bash -c "cd /opt/flannel && ./build"
Building flanneld...
gopath/src/github.com/coreos/flannel/backend/awsvpc/awsvpc.go:21:2: cannot find package "github.com/aws/aws-sdk-go/aws" in any of:
        /usr/local/go/src/github.com/aws/aws-sdk-go/aws (from $GOROOT)
        /opt/flannel/gopath/src/github.com/aws/aws-sdk-go/aws (from $GOPATH)
gopath/src/github.com/coreos/flannel/backend/awsvpc/awsvpc.go:22:2: cannot find package "github.com/aws/aws-sdk-go/aws/awserr" in any of:
        /usr/local/go/src/github.com/aws/aws-sdk-go/aws/awserr (from $GOROOT)
        /opt/flannel/gopath/src/github.com/aws/aws-sdk-go/aws/awserr (from $GOPATH)
gopath/src/github.com/coreos/flannel/backend/awsvpc/awsvpc.go:23:2: cannot find package "github.com/aws/aws-sdk-go/aws/ec2metadata" in any of:
        /usr/local/go/src/github.com/aws/aws-sdk-go/aws/ec2metadata (from $GOROOT)
        /opt/flannel/gopath/src/github.com/aws/aws-sdk-go/aws/ec2metadata (from $GOPATH)
gopath/src/github.com/coreos/flannel/backend/awsvpc/awsvpc.go:24:2: cannot find package "github.com/aws/aws-sdk-go/service/ec2" in any of:
        /usr/local/go/src/github.com/aws/aws-sdk-go/service/ec2 (from $GOROOT)
        /opt/flannel/gopath/src/github.com/aws/aws-sdk-go/service/ec2 (from $GOPATH)
gopath/src/github.com/coreos/flannel/subnet/local_manager.go:23:2: cannot find package "github.com/coreos/etcd/client" in any of:
        /usr/local/go/src/github.com/coreos/etcd/client (from $GOROOT)
        /opt/flannel/gopath/src/github.com/coreos/etcd/client (from $GOPATH)
gopath/src/github.com/coreos/flannel/subnet/registry.go:27:2: cannot find package "github.com/coreos/etcd/pkg/transport" in any of:
        /usr/local/go/src/github.com/coreos/etcd/pkg/transport (from $GOROOT)
        /opt/flannel/gopath/src/github.com/coreos/etcd/pkg/transport (from $GOPATH)
gopath/src/github.com/coreos/flannel/network/ipmasq.go:21:2: cannot find package "github.com/coreos/go-iptables/iptables" in any of:
        /usr/local/go/src/github.com/coreos/go-iptables/iptables (from $GOROOT)
        /opt/flannel/gopath/src/github.com/coreos/go-iptables/iptables (from $GOPATH)
gopath/src/github.com/coreos/flannel/remote/server.go:28:2: cannot find package "github.com/coreos/go-systemd/activation" in any of:
        /usr/local/go/src/github.com/coreos/go-systemd/activation (from $GOROOT)
        /opt/flannel/gopath/src/github.com/coreos/go-systemd/activation (from $GOPATH)
gopath/src/github.com/coreos/flannel/network/manager.go:29:2: cannot find package "github.com/coreos/go-systemd/daemon" in any of:
        /usr/local/go/src/github.com/coreos/go-systemd/daemon (from $GOROOT)
        /opt/flannel/gopath/src/github.com/coreos/go-systemd/daemon (from $GOPATH)
gopath/src/github.com/coreos/flannel/main.go:26:2: cannot find package "github.com/coreos/pkg/flagutil" in any of:
        /usr/local/go/src/github.com/coreos/pkg/flagutil (from $GOROOT)
        /opt/flannel/gopath/src/github.com/coreos/pkg/flagutil (from $GOPATH)
gopath/src/github.com/coreos/flannel/subnet/local_manager.go:25:2: cannot find package "github.com/golang/glog" in any of:
        /usr/local/go/src/github.com/golang/glog (from $GOROOT)
        /opt/flannel/gopath/src/github.com/golang/glog (from $GOPATH)
gopath/src/github.com/coreos/flannel/remote/server.go:31:2: cannot find package "github.com/gorilla/mux" in any of:
        /usr/local/go/src/github.com/gorilla/mux (from $GOROOT)
        /opt/flannel/gopath/src/github.com/gorilla/mux (from $GOPATH)
gopath/src/github.com/coreos/flannel/subnet/clock.go:17:8: cannot find package "github.com/jonboulle/clockwork" in any of:
        /usr/local/go/src/github.com/jonboulle/clockwork (from $GOROOT)
        /opt/flannel/gopath/src/github.com/jonboulle/clockwork (from $GOPATH)
gopath/src/github.com/coreos/flannel/pkg/ip/iface.go:22:2: cannot find package "github.com/vishvananda/netlink" in any of:
        /usr/local/go/src/github.com/vishvananda/netlink (from $GOROOT)
        /opt/flannel/gopath/src/github.com/vishvananda/netlink (from $GOPATH)
gopath/src/github.com/coreos/flannel/backend/vxlan/device.go:26:2: cannot find package "github.com/vishvananda/netlink/nl" in any of:
        /usr/local/go/src/github.com/vishvananda/netlink/nl (from $GOROOT)
        /opt/flannel/gopath/src/github.com/vishvananda/netlink/nl (from $GOPATH)
gopath/src/github.com/coreos/flannel/subnet/local_manager.go:26:2: cannot find package "golang.org/x/net/context" in any of:
        /usr/local/go/src/golang.org/x/net/context (from $GOROOT)
        /opt/flannel/gopath/src/golang.org/x/net/context (from $GOPATH)
gopath/src/github.com/coreos/flannel/backend/gce/api.go:23:2: cannot find package "golang.org/x/oauth2" in any of:
        /usr/local/go/src/golang.org/x/oauth2 (from $GOROOT)
        /opt/flannel/gopath/src/golang.org/x/oauth2 (from $GOPATH)
gopath/src/github.com/coreos/flannel/backend/gce/api.go:24:2: cannot find package "golang.org/x/oauth2/google" in any of:
        /usr/local/go/src/golang.org/x/oauth2/google (from $GOROOT)
        /opt/flannel/gopath/src/golang.org/x/oauth2/google (from $GOPATH)
gopath/src/github.com/coreos/flannel/backend/gce/api.go:25:2: cannot find package "google.golang.org/api/compute/v1" in any of:
        /usr/local/go/src/google.golang.org/api/compute/v1 (from $GOROOT)
        /opt/flannel/gopath/src/google.golang.org/api/compute/v1 (from $GOPATH)
gopath/src/github.com/coreos/flannel/backend/gce/gce.go:47:2: cannot find package "google.golang.org/api/googleapi" in any of:
        /usr/local/go/src/google.golang.org/api/googleapi (from $GOROOT)
        /opt/flannel/gopath/src/google.golang.org/api/googleapi (from $GOPATH)

**Comment by brendonmatheson** [comment]
I just hit this too - switching to the code as at the latest release (0.5.5) worked for me: 

git checkout cb8284fb60737793596dd2fc98d9608d3d0d66f0
docker run -v `pwd`:/opt/flannel -i -t google/golang /bin/bash -c "cd /opt/flannel && ./build"

**Comment by eyakubovich** [comment]
Looks like the build is getting overhauled but in the meanwhile, you can do:
```
docker run -v $SRC:/opt/go/src/github.com/coreos/flannel -i -t -e GOPATH=/opt/go/ golang:1.6 /bin/bash -c "cd /opt/go/src/github.com/coreos/flannel && make binary"
```

Where $SRC is the fullpath to the flannel source code.

**Comment by tomdee** [comment]
This now works in master so closing.
