### ISSUE TITLE
Dynamic multi-network support

### ISSUE THREAD

**Issue by cizixs** [coreos/flannel#467]
Glad to know that flannel supports multi-network now. But right now, networks must be configured before `flanneld` starts, and used in parameter `--networks`.

It would be better if I can create network(s) while `flanneld` is running. flannel can listen for new networks changes on `etcd`, and create necessary networks and subnets accordingly.

**Comment by cizixs** [comment]
Any comment?

**Comment by tomdee** [comment]
Closing given #638
