### ISSUE TITLE
Provide DNS name to FLANNELD_IFACE?

### ISSUE THREAD

**Issue by dghubble** [coreos/flannel#470]
On a CoreOS Alpha 1109.1.0 host running flanneld in rkt, a name node1.example.com can be resolved and /etc/resolv.conf includes the network nameserver. No custom networkd configs are in use. Setting an `/etc/flannel/options.env` with

    FLANNELD=node1.example.com
    FLANNELD_ETCD_ENDPOINTS=http://node1.example.com:2379

flannel does not start: "Error looking up interface node1.example.com: not such network interface"

Would it be reasonable to find the interface which has the IP that the DNS entry resolves to? Previously, Kubernetes examples have provided an IP address for this value. We'd like to avoid explicitly providing a fixed interface name or IP on each host.

**Comment by dghubble** [comment]
This is undocumented, but the default behavior is to parse the interface of the default route https://github.com/coreos/flannel/blob/master/network/manager.go#L134, which is suitable for our use cases. I'll remove my workaround `ip route show 0.0.0.0/0 | cut -f5 -d ' '`.

**Comment by eyakubovich** [comment]
`--iface` also accepts interface name such as `eth0` instead of IP. Accepting domain name is a possibility but somewhat unorthodox.

**Comment by dghubble** [comment]
Yeah, my first workaround was to get the interface name and pass it that way. Then I noticed the default that is chosen and that it wasn't needed. I don't have a need for the feature after all, esp. if you'd consider  it unorthodox. Closing.
