### ISSUE TITLE
v0.6.0 planned release date

### ISSUE THREAD

**Issue by luxas** [coreos/flannel#477]
Hey all,

I'd like to know when you're planning to release v0.6.0?
I know it mostly contains bug fixes, but that will be useful.

BTW: We're planning to build flannel into a Kubernetes DaemonSet for easier deployments of overlay networks. If you're interested in that, follow the discussion there.

**Comment by tomdee** [comment]
Hi @luxas, no firm commitment right now but I'm working on it today, so possibly this week and if not then hopefully by the end of next week. Can you point me to the DaemonSet discussion?

**Comment by antoineco** [comment]
Flannel 0.6.0 is now released. Would it be possible to push it to quay.io before closing this issue?

**Comment by luxas** [comment]
I hope you will push the images ASAP (I'm waiting for them :smile:), then we may close this issue

**Comment by tomdee** [comment]
@antoineco @luxas Images are now pushed https://quay.io/repository/coreos/flannel?tab=tags :fireworks:
