### ISSUE TITLE
build file not exist

### ISSUE THREAD

**Issue by oiovoyo** [coreos/flannel#480]
![image](https://cloud.githubusercontent.com/assets/4905623/17364912/a39a4f44-59b5-11e6-863a-9a3f33bf2c02.png)

![image](https://cloud.githubusercontent.com/assets/4905623/17364925/b6685abc-59b5-11e6-8866-32a1e3874ab5.png)

**Comment by eyakubovich** [comment]
The build was recently overhauled and docs not updated. You should be able to just type `make` now.

**Comment by yuxiangning** [comment]
Got error like this, seems like it doesn't find pthread and libc, while apparently those are installed on my system. Am I missing anything?

# make
go build -o dist/flanneld \
  -ldflags "-extldflags -static -X github.com/coreos/flannel/version.Version=v0.5.3-107-g982dbdb"
# github.com/coreos/flannel
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

make: *** [dist/flanneld] Error 2

**Comment by tomdee** [comment]
The make problem should be fixed on current HEAD
