### ISSUE TITLE
securing flannel

### ISSUE THREAD

**Issue by streamnsight** [coreos/flannel#485]
Hello,

I'm using flannel, but I'm still confused about how to secure it.

I'm not a networking expert, so I hope this is not too dumb of a question:

I understand flannel encapsulates the TCP packets into UDP packets, and those are sent through the interface to other nodes. 
The discovery part is done with etcd, and I have that secured with TLS, but let's say I were to use a public interface between nodes, how is flannel securing the communication between nodes? 
Is it actually handling any 'communication' per say, or merely encapsulating the packets and leaving it up to the host networking to handle security?

If someone could enlighten me here, that's be very helpful.
Thanks.

**Comment by eyakubovich** [comment]
Currently flannel does not secure the data packets. There is PR (https://github.com/coreos/flannel/pull/290) to add an IPSEC backend that would encrypt the data packets. I hope it gets merged at some point.

Short of that, the easiest thing is to just secure your traffic at the application layer via TLS (e.g. https). This is no different than if you were running without flannel overlay and just using regular networking.
