### ISSUE TITLE
Persist Flannel network in Etcd

### ISSUE THREAD

**Issue by chenzhiwei** [coreos/flannel#488]
Hi, I am running Flannel in a Docker container, the deployment process is:
1. Start Flannel in a Docker container using restart=always policy
2. Configure Docker daemon to use Flannel
3. Restart Docker daemon

But in real use case, when a user's node is down for 2 days, and starting the node will cause Flannel get a new network. See: https://github.com/coreos/flannel/issues/205

One of the solution I can find is to mount the flannel subnet.env to host path and update the Docker systemd unit file to source subnet.env file and append the flannel config to docker daemon. This need to restart Docker daemon twice.

I think adding an option to flanneld, such as `--persist-network` to make the Flannel network persist in Etcd to solve this issue.

And, is there any other solution? Thanks.

**Comment by MikeSpreitzer** [comment]
Are you suggesting that `--persist-network` would make the assignments of subnets to hosts persist forever, no timeouts?  I presume there is a need to handle the case of a host that leaves the system permanently.  How would that be handled?

**Comment by chenzhiwei** [comment]
@MikeSpreitzer Users should manually remove the network from Etcd.

And maybe a simple tool to scan and clean the network which will be run by a user manually.

**Comment by tomdee** [comment]
@chenzhiwei See https://github.com/coreos/flannel/blob/master/Documentation/reservations.md#reservations for some guidance on this

**Comment by chenzhiwei** [comment]
@tomdee Thanks, I think I can close this issue now.
