### ISSUE TITLE
OpenVSwitch integration through a plugin

### ISSUE THREAD

**Issue by mrunalp** [coreos/flannel#49]
Would the maintainers consider having OVS as an option for the tunnelling functionality?
If a plugin API were implemented, then the underlying tunnelling could be replaced by whatever users see fit.

**Comment by moritzheiber** [comment]
As far as I can see VXLAN support is done, right?

How about getting this "back on track"?

**Comment by eyakubovich** [comment]
Yes, vxlan is done. Could you elaborate as to which feature you would like us to tackle next?

**Comment by moritzheiber** [comment]
I'm referring to your earlier comment regarding multi-tenancy and adding support for it after VXLAN implementation is over.

I'm pretty sure this is a feature flannel is suited for. And OVS is a pretty good backend for it as well.

**Comment by steveeJ** [comment]
I'm definitely a supporter of the multi-tenancy feature. What's the status of this?

**Comment by eyakubovich** [comment]
We've merged multi-network support (https://github.com/coreos/flannel/pull/169) that can be used as a start for multi-tenancy. That PR only adds support at the subnet allocation layer. The traffic isolation is something that needs to be supported at the backend layer (e.g. using multiple VNIs). @mrunalp and @rajatchopra were working on an OVS based backend that would make it multi-tenant.

**Comment by moritzheiber** [comment]
What about collaborating with [Socketplane](http://socketplane.io/)? I know they're a part of Docker now, but their project looked very promising.

**Comment by tomdee** [comment]
I think multi-network support is now out of scope of flannel. see #638
