### ISSUE TITLE
Will not build from latest HEAD on master

### ISSUE THREAD

**Issue by peterkellyonline** [coreos/flannel#493]
> github.com/coreos/flannel/pkg/ip
> coreos/flannel/pkg/ip/iface.go:32: cannot use link (type *netlink.Device) as type *netlink.Link in argument to netlink.AddrList:
       	*netlink.Link is pointer to interface, not interface
> coreos/flannel/pkg/ip/tun.go:55: undefined: syscall.IFF_TUN
> coreos/flannel/pkg/ip/tun.go:55: undefined: syscall.IFF_NO_PI
> coreos/flannel/pkg/ip/tun.go:57: undefined: syscall.TUNSETIFF

Run `go build` from master, latest commit 18ddbd573b1a6b9568ade96d69f6ca51f6a9dd86

**Comment by tomdee** [comment]
This works fine for me. What version of Go are you using? Can you share a little more about your environment

**Comment by tomdee** [comment]
Closing without a repro.
