### ISSUE TITLE
All hosts get same subnet and do not recognize the other hosts

### ISSUE THREAD

**Issue by helander** [coreos/flannel#51]
I trying out flannel using cores-vagrant. I start up 3 hosts and install the flannel binary in each of them. I add the network configuration using etcdctl and then start flannel on each host using

   sudo /opt/bin/flanneld &

and on all hosts I get the same output
Installing signal handlers
I0926 06:56:56.933827 00733 main.go:89] Determining IP address of default interface
I0926 06:56:56.934355 00733 main.go:164] Using 10.0.2.15 as external interface
I0926 06:56:56.997207 00733 subnet.go:80] Subnet lease acquired: 10.0.78.0/24
I0926 06:56:57.001976 00733 main.go:175] UDP mode initialized
I0926 06:56:57.002595 00733 udp.go:238] Watching for new subnet leases

coreos-vagrant creates two network adapters on each host : one nat and one host only

Could my problem be that flannel selects the NAT adapter (10.0.2.15)?

**Comment by pires** [comment]
Life-saver right here!

**Comment by kiddkai** [comment]
Life-saver :+1:
