### ISSUE TITLE
flannel-v0.6.1 install error

### ISSUE THREAD

**Issue by gl328518397** [coreos/flannel#510]
I0920 17:34:26.813001 07716 main.go:126] Installing signal handlers
I0920 17:34:26.813431 07716 manager.go:133] Determining IP address of default interface
E0920 17:34:26.813737 07716 main.go:146] Failed to create NetworkManager: failed to get default interface: Unable to find default route

**Comment by tomdee** [comment]
@gl328518397 Thanks for the report. Have you tried this with a previous flannel release? Can you confirm that it was working before?

**Comment by tomdee** [comment]
Closing as there's no repro.

**Comment by gl328518397** [comment]
i am sorry ,i forget reply.  i have fix it ,thank you .

**Comment by tomdee** [comment]
@gl328518397 How did you fix it? Was the fix something that other people would benefit from?

**Comment by AirLu** [comment]
HI @gl328518397 ,I met the same issue  , what was your solution?

**Comment by gl328518397** [comment]
hello ,  -iface="eth0"  just try。
