### ISSUE TITLE
Hybrid vxlan+hostgw networking for optimal performance

### ISSUE THREAD

**Issue by garo** [coreos/flannel#519]
When working with big clusters in a cloud environment (such as AWS VPC) where some of the machines are in a different subnets, VXLAN needs to be used.

Is there any reason why flannel could not use best of the both VXLAN and host-gw backends so that flannel would add routing table entries for the prefixes which are living in machines in the same subnet? Because they would have smaller prefix than the default route to the entire flannel managed vxlan prefix, they would take preference and kernel would route the packets directly to the destination when a direct L2 connection is possible (this requires to disable source/dest check in AWS VPC for the instances)

This should eliminate the VXLAN overhead this kind of traffic with quite minimal modifications. I haven't yet benchmarked this, but I merely verified that this would be possible. Has anybody given any thought on this?

Possible issues: mixed MTUs as some connections would have encapsulation overhead and some would not and in a big cluster the routing table would start to get big (one entry per VM in the same subnet).

**Comment by panga** [comment]
+1

**Comment by tomdee** [comment]
Sounds like a very interesting idea. Would you be interested in trying it out and/or writing it up into a longer guide.

**Comment by jonaz** [comment]
Do we have a config example of this?

**Comment by tomdee** [comment]
Fixed in v0.9.0
