### ISSUE TITLE
Endian problem in pkg/ip/ipnet.go

### ISSUE THREAD

**Issue by tnakaike** [coreos/flannel#526]
Functions in pkg/ip/ipnet.go do not work correctly on a big-endian machine. I built flannel on a Linux mainframe machine (IBM System Z) and used it with kubernetes. The build succeeded, but it does not work well. When I specified an IP range as "Network": 10.0.0.0/16, flannel created a subnet as FLANNEL_SUBNET=11.2.0.0/24 (in /run/flannel/subnet.env). Of course, this does not work.

I found that a specified IP range is parsed by the net.parseIP function, which returns a byte array to represent the IP address. After that, the byte-array-format IP address is converted to an integer-format IP address in the ip.FromBytes function. This conversion is done differently based on the endian type of the target platform. The endian-type check is done correctly by the ip.NativelyLittle function in endian.go. However, the net.parseIP function returns the byte-array-format IP address in a common array-element order independent on the endian type. Therefore, I think that the endian-type check by the ip.NativelyLittle function is unneeded. Actually, after I modified the ip.NativelyLittle function to return true unconditionally, my flannel worked correctly.

I am not sure why the endian-type check is introduced. But, this check did not work well on my big-endian machine.

**Comment by salamaniibm** [comment]
Facing same issue, built flannel on s390x (IBM zSystem) machine.
Modified the ip.NativelyLittle function to return true unconditionally, flannel worked correctly.
Any further update on this.
Is endian-type check is needed?

Regards,
Salamani

**Comment by tomdee** [comment]
PRs welcome :smile:

**Comment by tomdee** [comment]
A fix for this is now merged
