### ISSUE TITLE
what is the upper speed limit for flannel0 interface

### ISSUE THREAD

**Issue by andyxning** [coreos/flannel#529]
Our monitor system read the speed of flannel0 from **/sys/class/net/flannel0/speed** and it shows that the value is 10(Mbit/s). However, in our situation, we recently receive more alarm about the flannel0 interface usage is above 100%, sometimes nearly 200%. 

I am curious about the speed value of flannel0. I think it is a virtual interface, so the value is not the real speed upper limit? Any one can explain this?

**Comment by tomdee** [comment]
There is no speed limit on this interface as it's virtual.
