### ISSUE TITLE
Intermittent behaviour with -> tcp_tw_recycle=1

### ISSUE THREAD

**Issue by fvigotti** [coreos/flannel#530]
Hi,
Sorry for the post but I'm here because I wasted more than 1 week on kubernetes with flannel (vxlan) because 
`net.ipv4.tcp_tw_recycle=1`

now after 1 week I've found that the cause of very strange timeout behaviour in my frontend was this param!
it should be set to : 
`net.ipv4.tcp_tw_recycle=0`

now, googling for "flannel" + "tcp_tw_recycle" give me nothing then  a famous post (http://machinezone.github.io/research/networking-solutions-for-kubernetes/) where this value is **WRONG**

I think that because the headhache caused by this was not small..  ( connections works, but only some kind of connections , ( ie: apache benchmark ) cause the drop of all other connections for 1 minute, then everything works again ) , .. so I think that should be written somewhere.. maybe in the coreos/kubernetes guide too ?

Thank you,
Francesco Vigotti

**Comment by outworlder** [comment]
I can't believe it.

I have wasted more than one week on that too. More like a couple of months on and off. 

I do not understand why this happens though. Can someone shed some light? By the way, I experienced it in GCE, with connections from K8s pods to a VM-based RMQ node.

**Comment by tomdee** [comment]
Other than the machinezone article, I'm not aware of the interaction of this parameter with flannel. Flannel itself doesn't change the value an it doesn't document that it should be a different value.

Also, this parameter has been removed from recent kernels - https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4396e46187ca5070219b81773c4e65088dac50cc

Some more background on it is here https://vincent.bernat.im/en/blog/2014-tcp-time-wait-state-linux
