### ISSUE TITLE
used flannel cni plugin error！

### ISSUE THREAD

**Issue by swqmaven** [coreos/flannel#531]
hi，
Can’t start quay.io/coreos/flannel-git:latest container
I got container logs
Failed to create SubnetManager: unable to initialize inclusterconfig: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

how to resolve this error must be user k8s auth config?

**Comment by pires** [comment]
This means your controller-manager is not able to properly start the token manager, thus can't mount the service account. Check its logs for errors.

**Comment by swqmaven** [comment]
@pires i had resolved this error thanks for you reply
