### ISSUE TITLE
crypto/tls: failed to find certificate PEM data

### ISSUE THREAD

**Issue by luohoufu** [coreos/flannel#536]
flanneld -version
v0.6.2

when i user cfssl gen ssl ca/cert/key file，my etcd cluster running。

-- etcd running info
etcd -name=etcd1 -data-dir=/var/lib/etcd/etcd1 -listen-client-urls=https://10.37.116.27:2379,https://127.0.0.1:2379 -listen-peer-urls=https://10.37.116.27:2380 -initial-advertise-peer-urls=https://10.37.116.27:2380 -initial-cluster=etcd1=https://10.37.116.27:2380,etcd2=https://10.37.116.30:2380 -advertise-client-urls=https://10.37.116.27:2379 -initial-cluster-state=new -initial-cluster-token=hitao-k8s-etcd-cluster -trusted-ca-file=/etc/share/ca.pem -cert-file=/etc/share/etcd1.pem -key-file=/etc/share/etcd1-key.pem -client-cert-auth -peer-trusted-ca-file=/etc/share/ca.pem -peer-cert-file=/etc/share/etcd1.pem -peer-key-file=/etc/share/etcd1-key.pem -peer-client-cert-auth

--etcd member info
etcdctl --endpoints=https://10.37.116.27:2379,https://10.37.116.30:2379 --ca-file=/etc/share/ca.pem --cert-file=/etc/share/etcd1.pem --key-file=/etc/share/etcd1-key.pem member list
8b49d3e7f4a37f70: name=etcd1 peerURLs=https://10.37.116.27:2380 clientURLs=https://10.37.116.27:2379 isLeader=true
cafcbeca9e84c386: name=etcd2 peerURLs=https://10.37.116.30:2380 clientURLs=https://10.37.116.30:2379 isLeader=false

--etcd flannel config
etcdctl --endpoints=https://10.37.116.27:2379,https://10.37.116.30:2379 --ca-file=/etc/share/ca.pem --cert-file=/etc/share/etcd1.pem --key-file=/etc/share/etcd1-key.pem get "/k8s/network/config"
{ "Network": "172.16.0.0/16", "Backend": { "Type": "vxlan" } }

--flannel run command
flanneld -etcd-endpoints=https://10.37.116.27:2379,https://10.37.116.30:2379 -etcd-prefix=/k8s/network -etcd-cafile=/etc/share/ca.pem -etcd-keyfile=/etc/share/client.pem -etcd-certfile=/etc/share/client-key.pem 
E1027 18:19:53.902076 01025 main.go:121] Failed to create SubnetManager: crypto/tls: failed to find certificate PEM data in certificate input, but did find a private key; PEM inputs may have been switched

how to config flannel with etcd https?

**Comment by luohoufu** [comment]
i found the reason.

**Comment by tomdee** [comment]
@luohoufu Is there anything that you can share here (or in a PR) to help future people who run into this problem?
