### ISSUE TITLE
Issues with glide and dependencies

### ISSUE THREAD

**Issue by vaijab** [coreos/flannel#537]
I am working on fixing a few issues in flannel: handling AWS API rate limits, etc.

I need to add a new dependency: `github.com/aws/aws-sdk-go/aws/session`, but I am having issues with glide. I followed official glide documentation how to add dependencies correctly. When I run `glide install` after `glide get github.com/aws/aws-sdk-go/aws/session`, glide downloads a a lot of stuff, it seems to update a lot of dependencies, however `github.com/aws/aws-sdk-go/aws/session` never gets added. Instead glide adds this:

```
> find vendor/ -name session.go | grep aws
vendor/k8s.io/kubernetes/vendor/github.com/aws/aws-sdk-go/aws/session/session.go
vendor/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/aws/session/session.go
```

This is my first time using glide for go deps management, but I cannot see what I am doing wrong. Any guidance would certainly help. Thanks!

**Comment by vaijab** [comment]
So in terms of `aws/session` I figured that out. The current version of aws-sdk-go is pinned to a version which does not have aws/session. But glide still updates lots of other dependencies, because quite a few of them aren't versioned.

Any plans to sort this out?

**Comment by tomdee** [comment]
There are no current plans - feel free submit a PR though.

**Comment by vaijab** [comment]
> There are no current plans - feel free submit a PR though.

I think I am slowly working towards that. :-)

**Comment by tomdee** [comment]
Closing as this is just a standard glide problem. It might be worth us pinning more in the glide.yaml, but I have no current plans to do this,
