### ISSUE TITLE
any hints how to not parallize the build/install process ?

### ISSUE THREAD

**Issue by toralf** [coreos/flannel#538]
flannel seems to be a package with does not respect -j1 under a Gentoo build system - at least it spawns a lot of "go" processes - any chance to convince it to be polite to other cpu applications ? ;)

The back ground is that I do maintain a tinderbox for QA purpose for Gentoo Linux - that machine has 12 cpus and is running usually with a load of 10.9 - which works most of the time as long as every technical user just uses 1 cpu - but flannel breaks that rule

**Comment by tomdee** [comment]
I have no hints but welcome any comments from the community (or PRs :smile:)

**Comment by tomdee** [comment]
@toralf Sorry I can't be more helpful here. I'm going to close this issue as it's quite specific. I think if you want it resolved you'll need to submit a PR.
