### ISSUE TITLE
Flannel env variables in docker.service must preceed $DOCKER_OPTS

### ISSUE THREAD

**Issue by Ahrotahntee** [coreos/flannel#541]
Using a drop-in on the docker unit file to set the DOCKER_OPTS environment variable causes problems with flannel's settings when using the --log-opt parameter.

The --log-opt parameter seems to take all remaining command line arguments as log options. It's also possible that it requires some kind of non-standard option terminator(?), but I haven't found any documentation on that.

Example:
```
/etc/systemd/system/docker.service.d/01-options.conf
[Service]
Environment=DOCKER_OPTS="--log-driver syslog --log-opt tag='{{.ImageName}}'"
```

Results:
```
time="2016-11-03T19:09:53.971319214Z" level=fatal msg="Failed to set log opts: unknown log opt '--bip' for json-file log driver"
```

**Comment by tomdee** [comment]
I think this is a Docker issue so is probably worth raising there. @Ahrotahntee are you still seeing this as a problem or can I close this issue?

**Comment by Ahrotahntee** [comment]
It is a problem (though admittedly not a very high priority one.) 

I had figured that since flannel is the one injecting the parameters that it should be the one to accommodate.

I will also raise an issue on the docker tracker for the log-opts not terminating correctly.

**Comment by tomdee** [comment]
I'm not able to repro this so I assume it's been fixed already on the docker side. Closing.
