### ISSUE TITLE
use etcd api v3 if available

### ISSUE THREAD

**Issue by chulkilee** [coreos/flannel#542]
To avoid closed connection by ELB, flannel should use etcd API v3 which sends heartbeat.

To preserve backward compatibility for etcd, try v3 and use it if possible, otherwise keep the current version (don't know what it is. Is it v1? https://github.com/coreos/flannel/blob/v0.6.2/remote/client.go#L80)

Related: #508 #528 coreos/etcd#6810

**Comment by tomdee** [comment]
See also #554
