### ISSUE TITLE
duplicate MAC

### ISSUE THREAD

**Issue by suchisubhra** [coreos/flannel#550]
I see duplicate MAC for containers 
arp -n | grep "10.244.98"

10.244.98.0              ether   0e:e7:49:fb:0e:04   C                     flannel.1
10.244.98.5              ether   0e:e7:49:fb:0e:04   C                     flannel.1
10.244.98.4              ether   0e:e7:49:fb:0e:04   C                     flannel.1
10.244.98.3              ether   0e:e7:49:fb:0e:04   C                     flannel.1

is it by  design?

~Suchi

**Comment by tomdee** [comment]
@suchisubhra I'm not sure I understand the question, could you elaborate?

**Comment by tomdee** [comment]
Yes, it's by design. The arp table is showing the VTEP mac of the host that "owns" the containers. So, it's the same for them all because they are on the same subnet.
