### ISSUE TITLE
"Client/Server mode" docs refer to deprecated etcd-ca

### ISSUE THREAD

**Issue by eliasp** [coreos/flannel#551]
The [Client/Server mode](https://coreos.com/flannel/docs/latest/client-server.html) docs still refer to the [now deprecated](https://github.com/coreos/etcd-ca/commit/fe7df579072ae5ea19872fb4b834463afb6b853c) [etcd-ca](https://github.com/coreos/etcd-ca/) project.

Those should be updated to make use of [cfssl](https://github.com/cloudflare/cfssl) instead.

**Comment by tomdee** [comment]
client/server mode has been removed
