### ISSUE TITLE
flannel subnet don

### ISSUE THREAD

**Issue by swqmaven** [coreos/flannel#553]

**Comment by swqmaven** [comment]
in my environment
node1:192.168.1.41
node2:192.168.1.42

node1 ping node2 docker0 ok
node2 ping node1 containers ok
but node1 ping node2 other containers not ok!!
It's means the flannel is ok?
I check nodes route and flannel config is ok.
why this happened? i think the problem exits in node2. what is it?
thanks for help!

**Comment by tomdee** [comment]
Sorry, there's not enough information here for me to help.
