### ISSUE TITLE
flannel doesn't update /run/flannel/subnet.env

### ISSUE THREAD

**Issue by gufranmmu** [coreos/flannel#556]
Upon node reboot, /run/flannel/subnet.env file is lost from centos since it's a runtime directory. Then when systemd starts flannel, flannel gets a new subnet lease, but does't update the information to any file.

```
[root@mesos-slave-4 ~]# cat /run/flannel/subnet.env
FLANNEL_NETWORK=192.168.0.0/16
FLANNEL_SUBNET=192.168.14.1/24
FLANNEL_MTU=8142
FLANNEL_IPMASQ=false
```

```
10: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 8142 qdisc noqueue state UNKNOWN
    link/ether 26:50:b3:40:bf:47 brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.0/16 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::2450:b3ff:fe40:bf47/64 scope link
       valid_lft forever preferred_lft forever
```
```
[root@mesos-slave-4 ~]# etcdctl ls /coreos.com/network/subnets
/coreos.com/network/subnets/192.168.94.0-24
/coreos.com/network/subnets/192.168.75.0-24
/coreos.com/network/subnets/192.168.100.0-24
/coreos.com/network/subnets/192.168.34.0-24

```
which part of the code should i make change to change subnet file?

**Comment by gufranmmu** [comment]
@djsly

**Comment by djsly** [comment]
it looks like the file is created upon service start

`ExecStartPost=/usr/libexec/flannel/mk-docker-opts.sh -k DOCKER_NETWORK_OPTIONS -d /run/flannel/docker`

**Comment by tomdee** [comment]
@djsly Where is that ExecStartPost line coming from?

**Comment by djsly** [comment]
/usr/lib/systemd/system/flannel.service on centOS

**Comment by tomdee** [comment]
So this is a CentOS packaging issue? Do you know who maintains the CentOS package?

**Comment by djsly** [comment]
Im not sure about @gufranmmu but for me on centOS I don't have any issues. 

I suspect that the OP is running on a different distribution

**Comment by tomdee** [comment]
I'm going to close this issue as there's not enough information to diagnose. Please add more and I can reopen the issue.
