### ISSUE TITLE
road map - Will Flannel support network policy? When?

### ISSUE THREAD

**Issue by SydOps** [coreos/flannel#558]
Read this document which was published in Septmeber. 

http://blog.kubernetes.io/2016/09/high-performance-network-policies-kubernetes.html

>By themselves, simple routed networks or the commonly used flannel network driver, for example, cannot apply network policy.

So will Flannel support network policy? Then when?

**Comment by caseydavenport** [comment]
@SydOps You can get network policies with flannel today if you use Canal!

Check it out - https://github.com/tigera/canal

It runs Calico alongside Flannel for network policy.

**Comment by SydOps** [comment]
@caseydavenport 

Thanks, will take a look.

**Comment by hacker-h** [comment]
So why should I use flannel at all rather than calico?
