### ISSUE TITLE
Build Flannel on Debian Issue

### ISSUE THREAD

**Issue by Nick777818** [coreos/flannel#570]
Hello,

I am currently building a Kubernetes cluster on dedicated Linux machines for our company to run our Dev/Uat/Prod environments.

The architecture consists of the following for each host in the cluster of servers:

- Debian Jessie amd64 OS

- ETCD running on host OS

- Flannel running on host OS

- Docker running on host OS

Currently there seem to be 2 methods to get flannel running on Debian based on the github documentation:

1. Flannel service running on host OS

2. Flannel running on Docker container with ETCD

I am able to run Flannel in a docker container however this is not idea for the setup I am going for - I do not want to run container management services within a container ;) When I try to build the Flannel service on the Debian host (using make, ./build or make dist/flanneld) I get the following:

root@cch114:/home/tyrone/flannel# make

go build -o dist/flanneld \

  -ldflags "-X github.com/coreos/flannel/version.Version=v0.6.1-47-gb5ea6d3"

main.go:37:2: cannot find package "github.com/coreos/flannel/backend/alloc" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/backend/alloc(from $GOROOT)

($GOPATH not set)

main.go:38:2: cannot find package "github.com/coreos/flannel/backend/awsvpc" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/backend/awsvpc(from $GOROOT)

($GOPATH not set)

main.go:39:2: cannot find package "github.com/coreos/flannel/backend/gce" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/backend/gce(from $GOROOT)

($GOPATH not set)

main.go:40:2: cannot find package "github.com/coreos/flannel/backend/hostgw" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/backend/hostgw(from $GOROOT)

($GOPATH not set)

main.go:41:2: cannot find package "github.com/coreos/flannel/backend/udp" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/backend/udp(from $GOROOT)

($GOPATH not set)

main.go:42:2: cannot find package "github.com/coreos/flannel/backend/vxlan" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/backend/vxlan(from $GOROOT)

($GOPATH not set)

main.go:30:2: cannot find package "github.com/coreos/flannel/network" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/network(from $GOROOT)

($GOPATH not set)

main.go:31:2: cannot find package "github.com/coreos/flannel/remote" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/remote(from $GOROOT)

($GOPATH not set)

main.go:32:2: cannot find package "github.com/coreos/flannel/subnet" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/subnet(from $GOROOT)

($GOPATH not set)

main.go:33:2: cannot find package "github.com/coreos/flannel/subnet/kube" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/subnet/kube(from $GOROOT)

($GOPATH not set)

main.go:34:2: cannot find package "github.com/coreos/flannel/version" in any of:

/usr/lib/go/src/pkg/github.com/coreos/flannel/version(from $GOROOT)

($GOPATH not set)

main.go:26:2: cannot find package "github.com/coreos/pkg/flagutil" in any of:

/usr/lib/go/src/pkg/github.com/coreos/pkg/flagutil(from $GOROOT)

($GOPATH not set)

main.go:27:2: cannot find package "github.com/golang/glog" in any of:

/usr/lib/go/src/pkg/github.com/golang/glog(from $GOROOT)

($GOPATH not set)

main.go:28:2: cannot find package "golang.org/x/net/context" in any of:

/usr/lib/go/src/pkg/golang.org/x/net/context(from $GOROOT)

($GOPATH not set)

Makefile:38: recipe for target 'dist/flanneld' failed

**Comment by Nick777818** [comment]
Any feedback on the following?

Thanks

**Comment by ashishth09** [comment]
You should specify the GOPATH. If you already have one then you can git clone so that
flannel is at $GOAPTH/src/github.com/coreos/flannel

Run go  get ./... after cd flannel to install all the required packages

**Comment by ashishth09** [comment]
Well you can skip go get ./... as the project already has dependencies in the vendor folder which will be made available to go compiler >= 1.6 :)

**Comment by ashishth09** [comment]
https://blog.gopheracademy.com/advent-2015/vendor-folder/

**Comment by besnik** [comment]
Hi, I replied with a solution that worked for me in #552 

Basically:
```
cd ~
export GOPATH=$(pwd)
mkdir -p src/github.com/coreos
cd src/github.com/coreos
git clone https://github.com/coreos/flannel.git
cd flannel
make dist/flanneld
```

**Comment by tomdee** [comment]
Hi, please re-open if you're still having problems
