### ISSUE TITLE
Containers are not working inside flannel

### ISSUE THREAD

**Issue by abdoo** [coreos/flannel#582]
hi all,

I'm using kubernetes 1.4.7 on premises, I have three nodes.

 root@kuber-master:~# kubectl get nodes
NAME           STATUS    AGE
10.103.12.20   Ready     1h
10.103.12.21   Ready     1h
10.103.12.22   Ready     1h
root@kuber-master:~#

I installed fabric8 on top of it. and I have issue that containers on different nodes can't see each other.
master node:
root@kuber-master:~# cat /run/flannel/subnet.env
FLANNEL_NETWORK=172.16.0.0/16
FLANNEL_SUBNET=172.16.55.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
root@kuber-master:~#

slave01
FLANNEL_NETWORK=172.16.0.0/16
FLANNEL_SUBNET=172.16.34.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
root@kuber-slave01:~#

root@kuber-slave02:~# cat /run/flannel/subnet.env
FLANNEL_NETWORK=172.16.0.0/16
FLANNEL_SUBNET=172.16.54.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
root@kuber-slave02:~#

root@kuber-master:~# kubectl get endpoints
NAME                      ENDPOINTS           AGE
fabric8                   172.16.54.3:9090    53m
fabric8-docker-registry   172.16.55.4:5000    53m
fabric8-forge             172.16.34.4:8080    53m
gogs                      172.16.55.3:3000    53m
gogs-ssh                  172.16.55.3:2222    53m
jenkins                   172.16.34.5:8080    53m
jenkins-jnlp              172.16.34.5:50000   53m
jenkinshift               172.16.54.3:9191    53m
kubernetes                10.103.12.20:6443   1h
nexus                     172.16.55.6:8081    53m
root@kuber-master:~

root@kuber-master:~# ping 172.16.55.4
PING 172.16.55.4 (172.16.55.4) 56(84) bytes of data.
64 bytes from 172.16.55.4: icmp_seq=1 ttl=64 time=0.232 ms
64 bytes from 172.16.55.4: icmp_seq=2 ttl=64 time=0.083 ms
64 bytes from 172.16.55.4: icmp_seq=3 ttl=64 time=0.119 ms
^C
--- 172.16.55.4 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.083/0.144/0.232/0.064 ms
root@kuber-master:~# ping 172.16.54.3
PING 172.16.54.3 (172.16.54.3) 56(84) bytes of data.
^C
--- 172.16.54.3 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3024ms

root@kuber-master:~# ping 172.16.34.4
PING 172.16.34.4 (172.16.34.4) 56(84) bytes of data.
^C
--- 172.16.34.4 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 3999ms

Thanks,
best regards,

**Comment by abdoo** [comment]
I tried from a container to check other nodes gateway and it could be reached

root@ingress-nginx-2015555637-t7ln5:/# traceroute 172.16.54.1
traceroute to 172.16.54.1 (172.16.54.1), 30 hops max, 60 byte packets
 1  172.16.55.1 (172.16.55.1)  0.107 ms  0.029 ms  0.018 ms
 2  172.16.54.1 (172.16.54.1)  0.913 ms  0.783 ms  0.664 ms
root@ingress-nginx-2015555637-t7ln5:/# traceroute 172.16.34.1
traceroute to 172.16.34.1 (172.16.34.1), 30 hops max, 60 byte packets
 1  172.16.55.1 (172.16.55.1)  0.047 ms  0.014 ms  0.010 ms
 2  172.16.34.1 (172.16.34.1)  0.697 ms  0.694 ms  0.648 ms
root@ingress-nginx-2015555637-t7ln5:/#

**Comment by tomdee** [comment]
Hi @abdoo, I can't tell from the issue report what the problem is. Could you try to net it down to something that I can repro?

**Comment by abdoo** [comment]
@tomdee simply pods on on other nodes can't be reached. there is any specific requirements for NIC cards?

**Comment by tomdee** [comment]
Not that I'm aware of.
