### ISSUE TITLE
make errors building flanneld 

### ISSUE THREAD

**Issue by drishticode** [coreos/flannel#583]
Dependency info:
kernel 4.1.12-61.1.22.el7uek.x86_64,
kernel-uek-devel 4.1.12 x86_64,
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9),
go version go1.7.4 linux/amd64

Followed the build steps listed on github for Linux:
Step 1: Make sure you have required dependencies installed on your machine. On Ubuntu, run sudo apt-get install linux-libc-dev golang gcc. On Fedora/Redhat, run sudo yum install kernel-headers golang gcc.
Step 2: Git clone the flannel repo: git clone https://github.com/coreos/flannel.git
Step 3: Run the build script: cd flannel; make dist/flanneld

On executing the make step it throws the following error:

go build -o dist/flanneld \
  -ldflags "-X github.com/coreos/flannel/version.Version=v0.6.1-62-g6d631ba"
main.go:37:2: cannot find package "github.com/coreos/flannel/backend/alloc" in any of:
	/usr/local/go/src/github.com/coreos/flannel/backend/alloc (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/backend/alloc (from $GOPATH)
main.go:38:2: cannot find package "github.com/coreos/flannel/backend/awsvpc" in any of:
	/usr/local/go/src/github.com/coreos/flannel/backend/awsvpc (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/backend/awsvpc (from $GOPATH)
main.go:39:2: cannot find package "github.com/coreos/flannel/backend/gce" in any of:
	/usr/local/go/src/github.com/coreos/flannel/backend/gce (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/backend/gce (from $GOPATH)
main.go:40:2: cannot find package "github.com/coreos/flannel/backend/hostgw" in any of:
	/usr/local/go/src/github.com/coreos/flannel/backend/hostgw (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/backend/hostgw (from $GOPATH)
main.go:41:2: cannot find package "github.com/coreos/flannel/backend/udp" in any of:
	/usr/local/go/src/github.com/coreos/flannel/backend/udp (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/backend/udp (from $GOPATH)
main.go:42:2: cannot find package "github.com/coreos/flannel/backend/vxlan" in any of:
	/usr/local/go/src/github.com/coreos/flannel/backend/vxlan (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/backend/vxlan (from $GOPATH)
main.go:30:2: cannot find package "github.com/coreos/flannel/network" in any of:
	/usr/local/go/src/github.com/coreos/flannel/network (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/network (from $GOPATH)
main.go:31:2: cannot find package "github.com/coreos/flannel/remote" in any of:
	/usr/local/go/src/github.com/coreos/flannel/remote (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/remote (from $GOPATH)
main.go:32:2: cannot find package "github.com/coreos/flannel/subnet" in any of:
	/usr/local/go/src/github.com/coreos/flannel/subnet (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/subnet (from $GOPATH)
main.go:33:2: cannot find package "github.com/coreos/flannel/subnet/kube" in any of:
	/usr/local/go/src/github.com/coreos/flannel/subnet/kube (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/subnet/kube (from $GOPATH)
main.go:34:2: cannot find package "github.com/coreos/flannel/version" in any of:
	/usr/local/go/src/github.com/coreos/flannel/version (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/flannel/version (from $GOPATH)
main.go:26:2: cannot find package "github.com/coreos/pkg/flagutil" in any of:
	/usr/local/go/src/github.com/coreos/pkg/flagutil (from $GOROOT)
	/scratch/gopath/src/github.com/coreos/pkg/flagutil (from $GOPATH)
main.go:27:2: cannot find package "github.com/golang/glog" in any of:
	/usr/local/go/src/github.com/golang/glog (from $GOROOT)
	/scratch/gopath/src/github.com/golang/glog (from $GOPATH)
main.go:28:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/local/go/src/golang.org/x/net/context (from $GOROOT)
	/scratch/gopath/src/golang.org/x/net/context (from $GOPATH)
make: *** [dist/flanneld] Error 1

**Comment by drishticode** [comment]
Manually importing dependencies fixed the errors.

go get "github.com/coreos/flannel/backend/alloc"
go get "github.com/coreos/flannel/backend/awsvpc"
go get "github.com/coreos/flannel/backend/gce"
go get "github.com/coreos/flannel/backend/hostgw"
go get "github.com/coreos/flannel/backend/udp"
go get "github.com/coreos/flannel/backend/vxlan"
go get "github.com/coreos/flannel/network"
go get "github.com/coreos/flannel/remote"
go get "github.com/coreos/flannel/subnet"
go get "github.com/coreos/flannel/subnet/kube"
go get "github.com/coreos/flannel/version"
go get "github.com/coreos/pkg/flagutil"
go get "github.com/golang/glog"
go get "golang.org/x/net/context"

go build -o dist/flanneld \
  -ldflags "-X github.com/coreos/flannel/version.Version=v0.6.1-62-g6d631ba"

**Comment by ashishth09** [comment]
You should specify the GOPATH.
You can run go get ./...  after cd flannel to install all the required packages

**Comment by ashishth09** [comment]
Well you can skip go get ./... as the project already has dependencies in the vendor folder which will be made available to go compiler :)

**Comment by ashishth09** [comment]
https://blog.gopheracademy.com/advent-2015/vendor-folder/

**Comment by drishticode** [comment]
@ashishth09 , guess I am still missing something.  
Do you mean specify the GOPATH in make command ? I already have GOPATH in my PATH. Seems to me the problem occurs when everything is installed fresh and GOPATH has nothing to begin with. Shouldn't the build scripts pull these dependencies  automatically ?

**Comment by ashishth09** [comment]
If you already have the GOPATH then the following will make sense
```
mkdir -p $GOPATH/src/github.com/coreos
cd $GOPATH/src/github.com/coreos
git clone https://github.com/coreos/flannel.git
cd flannel; make dist/flanneld
```

Probably you cloned at some other path which was not in the GOPATH .
I think the documentation needs to be more clear on that.

**Comment by drishticode** [comment]
Ah I see. You are right about _"Probably you cloned at some other path which was not in the GOPATH ."_ . I will test it in a couple of days and update how it goes. Thanks @ashishth09 !

**Comment by drishticode** [comment]
@ashishth09 that worked. I created a symlink inside $GOPATH/src/github.com/coreos to my git clone folder /foo/flannel. 

https://github.com/coreos/flannel#building-flannel needs to be updated if this step is expected.

**Comment by tomdee** [comment]
Hi @drishticode. If you clone to a directory in your GOPATH that matches the package name then you shouldn't have any problem. I'm going to close this issue but please raise a PR if you think the build instructions need to be improved.
