### ISSUE TITLE
panic: flanneld flag redefined: log_dir

### ISSUE THREAD

**Issue by drishticode** [coreos/flannel#584]
**Environment:**
kernel 4.1.12-61.1.22.el7uek.x86_64,
kernel-uek-devel 4.1.12 x86_64,
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9),
go version go1.7.4 linux/amd64
etcd Version: 3.0.15
cluster is healthy

While building flannel I had to manually download the dependencies: #583 

**Issue**
flanneld fails to start. flanneld command throws:

flanneld flag redefined: log_dir
panic: flanneld flag redefined: log_dir

goroutine 1 [running]:
panic(0x14ea8e0, 0xc420012800)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
flag.(*FlagSet).Var(0xc420018180, 0x22fc780, 0xc4200127b0, 0x17869ba, 0x7, 0x17b68d6, 0x2f)
	/usr/local/go/src/flag/flag.go:791 +0x43e
flag.(*FlagSet).StringVar(0xc420018180, 0xc4200127b0, 0x17869ba, 0x7, 0x0, 0x0, 0x17b68d6, 0x2f)
	/usr/local/go/src/flag/flag.go:694 +0x8b
flag.(*FlagSet).String(0xc420018180, 0x17869ba, 0x7, 0x0, 0x0, 0x17b68d6, 0x2f, 0xc4200127a0)
	/usr/local/go/src/flag/flag.go:707 +0x90
flag.String(0x17869ba, 0x7, 0x0, 0x0, 0x17b68d6, 0x2f, 0xc42005ff30)
	/usr/local/go/src/flag/flag.go:714 +0x69
github.com/coreos/flannel/vendor/github.com/golang/glog.init()
	/foo/gopath/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog_file.go:41 +0x148
github.com/coreos/flannel/network.init()
	/foo/gopath/src/github.com/coreos/flannel/network/network.go:197 +0x58
main.init()
	/foo/flannel/main.go:177 +0x64

**$GOPATH** 
./src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog_file.go
./src/github.com/golang/glog/glog_file.go

**Comment by drishticode** [comment]
Refer issue #583 

I cleared everything under $GOPATH, created a symlink inside $GOPATH/src/github.com/coreos to my git clone folder /foo/flannel and then ran make dist/flanneld. Now it runs fine.

**Comment by nigeldaniels** [comment]
@drishticode what is the destination of the symlink in /foo/flannel ?

**Comment by drishticode** [comment]
cd /foo
git clone https://github.com/coreos/flannel.git
mkdir -p $GOPATH/src/github.com/coreos
ln -s /foo/flannel $GOPATH/src/github.com/coreos/flannel

**Comment by tomdee** [comment]
I don't have this issue and I can't repro this with an official release so closing. Please reopen if you can repro with a released version.

**Comment by madhanrm** [comment]
https://github.com/kubernetes/kubernetes/issues/35096
