### ISSUE TITLE
flannel add option --public-ip it will delete subnet from etcd every 24 hours

### ISSUE THREAD

**Issue by wksw** [coreos/flannel#585]
in  k8s cluster some node i add option "--public-ip" when flannel start, and some not add this option, the node add option "--public-ip" will delete subnet from etcd, other node not add option "--public-ip" not delete subnet from etcd, why???

**Comment by wksw** [comment]
etcd network config is '{"Network":"172.16.0.0/16", "Backend":{"Type":"vxlan"}}'
the normal flannel start option ’--etcd-endpoints="http://etcd_host_ip:4003" --iface="eth0"‘
the unnormal flannel start option  '--etcd-endpoints="http://etcd_host_ip:4003" --public-ip="node_ip"'
fail log is 'vxlan.go:349] Route for 172.16.88.4 not found'

**Comment by tomdee** [comment]
@wksw Could you run with v0.7.0 which has improved logging in this area? And let me know the full output?

**Comment by wksw** [comment]
@tomdee issue solved,Time synchronization problem.
