### ISSUE TITLE
Flannel 0.5.3 not in yum anymore

### ISSUE THREAD

**Issue by kanor1306** [coreos/flannel#590]
Hello, 

today I was deploying some machines (CentOS 7) that should be using flannel 0.5.3, but suddenly yum tells me that the package is not available, and if if ask for a list of flannel packages I only can see the 0.5.5. Is this happening to any of you or it could be some problem with my setup?

It would be nice to have that old package while I move my scripts to be able to use the 0.5.5

Thanks in advance for the help.

**Comment by tomdee** [comment]
@steveeJ Is this something you could help with? It would be great to get v0.7.0 in yum too, but I have no idea where to start?

**Comment by tomdee** [comment]
Also ping @jeremyeder would you be able to help?

**Comment by tomdee** [comment]
Actually closing in favor of #346

**Comment by jeremyeder** [comment]
@tomdee what is a good email address for you, I'd like to connect and try to smooth out this process.  Note that I'm actually not involved in the process at all -- just want to help.

**Comment by jeremyeder** [comment]
@kanor1306 centos7.3 has 0.5.5. centos7.2 has 0.5.3.  you can grab 0.5.3 from here:  http://mirror.linux.duke.edu/pub/centos/7.2.1511/extras/x86_64/Packages/

As a side note, I see that fedora rawhide has 0.6.2. @ingvagabund do you still own the flannel package?

**Comment by kanor1306** [comment]
Thanks @jeremyeder! good to know it!

**Comment by ingvagabund** [comment]
I still do. Already updating flannel in Fedora rawhide. It just takes time to update all its deps and generate new spec file.

**Comment by jeremyeder** [comment]
Question remains how to update it in CentOS.

**Comment by tomdee** [comment]
Awesome, thanks for the replies and help. I would love to get v0.7.0 in Centos and Fedora and to nderstand the way way to keep those packages up to date. @jeremyeder you can get me at tom@tigera.io if you want to discuss further

**Comment by ingvagabund** [comment]
flannel-0.7.0 in f25 updates-testing: https://bodhi.fedoraproject.org/updates/FEDORA-2017-013e53830f

**Comment by tomdee** [comment]
Excellent, thanks @ingvagabund!
