### ISSUE TITLE
Flannel.1 drop packets regularly in a 80 nodes cluster 

### ISSUE THREAD

**Issue by peiqi-caicloud** [coreos/flannel#592]
Hi,

We deployed flannel version0.5.5 in our productive env. however, we found the flannel.1 interface drop packets regularly. we looked the flannel log file and also dig into the vxlan kernel module, but have not found any strong raison.

Right now, I am only suspending that the FDB table in flannel.1 expired after some time, the flannel.1 then has no idea where to send the packet, then drop it. and as the fdb is watched from etcd, there may be a delay to update the fdb table. 

thank you very much for any advice for our problem

<img width="737" alt="2017-01-19 4 01 01" src="https://cloud.githubusercontent.com/assets/5621794/22098330/a7ba92c0-de60-11e6-9dde-8b174bff8887.png">

cc @keontang @mqliang

**Comment by peiqi-caicloud** [comment]
@tomdee @YungSang

**Comment by tomdee** [comment]
@peiqi-caicloud are you able to reproduce this on a smaller cluster or with the latest release of flannel?

**Comment by peiqi-caicloud** [comment]
With smaller cluster, it should be ok. The problem is we have deployed it
in production env and drop packets from time to time (about 1 days per
week), and I think we need to find the exact cause.

2017-01-20 2:21 GMT+08:00 Tom Denham <notifications@github.com>:

**Comment by tomdee** [comment]
Possibly related to #414

**Comment by feisan** [comment]
@peiqi-caicloud 
Do you have any new clues?
