### ISSUE TITLE
flannel logging lots of L3 Miss

### ISSUE THREAD

**Issue by jeremyd** [coreos/flannel#599]
I'm running a kubernetes cluster with flannel/vxlan and I'm seeing a lot of these messages in the logs.  Are these messages benign?  Could not find anywhere mentioning this.  If they're benign it'd be cool if it didn't sound as much like an error...  If it's an error, any idea why?  I setup the cluster with kube-aws pretty recently but I've been seeing this error for a while and then decided to find out why.  Thanks for any help!

```
I0126 19:12:33.583598 01411 network.go:225] L3 miss: 10.2.17.143
```

**Comment by jeremyd** [comment]
bueller?

**Comment by tomdee** [comment]
It's not an error. The logging in this area has been improved in v0.7.0

**Comment by jeremyd** [comment]
Ok great thanks!
