### ISSUE TITLE
flannel 0.7.0 + docker 1.13.0 issue

### ISSUE THREAD

**Issue by bobonovski** [coreos/flannel#603]
Hey guys,
Does flannel 0.7.0 support docker 1.13.0?

I installed docker 1.13.0 and flannel 0.7.0, and after starting them after like this:

service docker stop
source /run/flannel/subnet.env
ifconfig docker0 ${FLANNEL_SUBNET}
echo "DOCKER_OPTS=\"--bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}\"" >> /etc/default/docker
service docker start

I tried to do the basic ping test between machineA and machineB (they are in the same vpc), but didn't get any response, what could be the problems?

on both machines, I ran ubuntu 14.04 in docker and ping each other

flannel's network config:
`{
  "Network": "9.0.0.0/8",
  "SubnetLen": 20,
  "Backend": {
    "Type": "udp",
    "Port": 7890
  }
}`

**machineA's network**

docker0   Link encap:Ethernet  HWaddr 02:42:60:59:16:82
          inet addr:9.5.208.1  Bcast:0.0.0.0  Mask:255.255.240.0
          UP BROADCAST RUNNING MULTICAST  MTU:1472  Metric:1
          RX packets:238 errors:0 dropped:0 overruns:0 frame:0
          TX packets:140 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:18153 (18.1 KB)  TX bytes:74430 (74.4 KB)

eth0      Link encap:Ethernet  HWaddr 00:16:3e:0d:54:ac
          inet addr:192.168.0.28  Bcast:192.168.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2630697 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2205770 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1739519537 (1.7 GB)  TX bytes:898254895 (898.2 MB)

flannel0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:9.5.208.0  P-t-P:9.5.208.0  Mask:255.0.0.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1472  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:27 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500
          RX bytes:0 (0.0 B)  TX bytes:2004 (2.0 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2459444 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2459444 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:759296252 (759.2 MB)  TX bytes:759296252 (759.2 MB)

veth5931f8c Link encap:Ethernet  HWaddr 56:b8:8d:0b:5b:75
          UP BROADCAST RUNNING MULTICAST  MTU:1472  Metric:1
          RX packets:41 errors:0 dropped:0 overruns:0 frame:0
          TX packets:47 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:3390 (3.3 KB)  TX bytes:3618 (3.6 KB)

machineB's network

docker0   Link encap:Ethernet  HWaddr 02:42:c4:9c:c4:92
          inet addr:9.1.144.1  Bcast:0.0.0.0  Mask:255.255.240.0
          UP BROADCAST RUNNING MULTICAST  MTU:1472  Metric:1
          RX packets:94226 errors:0 dropped:0 overruns:0 frame:0
          TX packets:96027 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:14541418 (14.5 MB)  TX bytes:14011345 (14.0 MB)

eth0      Link encap:Ethernet  HWaddr 00:16:3e:0d:4c:44
          inet addr:192.168.0.29  Bcast:192.168.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:809026 errors:0 dropped:0 overruns:0 frame:0
          TX packets:486848 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:678043196 (678.0 MB)  TX bytes:89928261 (89.9 MB)

flannel0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:9.1.144.0  P-t-P:9.1.144.0  Mask:255.0.0.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1472  Metric:1
          RX packets:135 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:500
          RX bytes:9060 (9.0 KB)  TX bytes:264 (264.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:12 errors:0 dropped:0 overruns:0 frame:0
          TX packets:12 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:600 (600.0 B)  TX bytes:600 (600.0 B)

veth5d21c43 Link encap:Ethernet  HWaddr a2:c0:59:a9:64:7e
          UP BROADCAST RUNNING MULTICAST  MTU:1472  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:107 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:648 (648.0 B)  TX bytes:7962 (7.9 KB)

commands I used in machineA

`docker exec ubuntu-master ping -c4 9.1.144.2`

**Comment by lipixun** [comment]
I met exactly the same issue, why this issue is closed without any further information or comments? thx.

**Comment by lipixun** [comment]
After I downgrade docker to 1.12.0 (and reboot the system), things go right. I have no idea why 1.13.0 doesn't work.

**Comment by bobonovski** [comment]
@lipixun Sorry for closing this issue, because I found out later that it was not the problem of flannel 0.7.0. Currently, I can use flannel 0.7.0 with docker 1.13.0. I fixed the issue like this:
1. reset iptables
2. reboot
3. start flannel 0.7.0
4. start docker 1.13.0 with DOCKER_OPTS pointed to flannel bridge net

then it works!
so I guess it's all because of the weird behavior of iptables

**Comment by adaiguoguo** [comment]
@lipixun 
`sudo iptables -P FORWARD ACCEPT` fix this.
[Docker change log ](https://github.com/docker/docker/pull/28257)

**Comment by lipixun** [comment]
got it, thanks @adaiguoguo @bobonovski

**Comment by daniilyar** [comment]
Fix from @adaiguoguo helped me on K8 1.5.4 + Flannel 0.6.2 + Docker 1.13.1 also.

**Comment by flyingglass** [comment]
Fix from @adaiguoguo worker for me on K8 1.5.4, Flannel 0.6.2 and Docker 19.03.8
