### ISSUE TITLE
centos flannel vxlan, ping cross host failed

### ISSUE THREAD

**Issue by CocaCola183** [coreos/flannel#604]
I have tried udp as backend and there is no problem, but when I use vxlan, I can not ping cross host.

**what I have read:**

- #216 
- #370 
- #111 
- #415 
- #87 
- #481 

**linux info:** CentOS release 6.8 (Final)

**kernnel version:** 2.6.32-573.22.1.el6.x86_64

**docker version:** 1.7.1

**vxlan support:**
```bash
$ sudo modprobe vxlan && echo $?
0

$ ip link add type vxlan help
Usage: ... vxlan id VNI [ group ADDR ] [ local ADDR ]
                 [ ttl TTL ] [ tos TOS ] [ dev PHYS_DEV ]
                 [ port MIN MAX ] [ [no]learning ]
                 [ [no]proxy ] [ [no]rsc ]
                 [ [no]l2miss ] [ [no]l3miss ]

Where: VNI := 0-16777215
       ADDR := { IP_ADDRESS | any }
       TOS  := { NUMBER | inherit }
       TTL  := { 1..255 | inherit }
```
sames support vxlan

**etcd version:** 
```bash
$ etcd --version
etcd Version: 3.0.16
Git SHA: a23109a
Go Version: go1.6.4
Go OS/Arch: linux/amd64
```

**flanneld version:** v0.7.0

**route:**
172.17.0.0      *               255.255.0.0     U     0      0        0 flannel.1

**flannel config:**
```json
{ "Network": "172.17.0.0/16", "SubnetLen": 24, "Backend": { "Type": "vxlan", "VNI": 1, "Port": 8472 }}
```

**port:**
![e5d04aaf-6f4e-44e4-9574-316bd8a8b7d7](https://cloud.githubusercontent.com/assets/8912876/22578973/a34ee47c-ea07-11e6-97a5-656544fc7f0e.png)

**subnet info:**
/coreos.com/network/subnets/172.17.49.0-24
/coreos.com/network/subnets/172.17.70.0-24
/coreos.com/network/subnets/172.17.63.0-24

**flannel log:**
![c2350510-1416-479c-aeb2-dcc9aba0742e](https://cloud.githubusercontent.com/assets/8912876/22579009/d4dd6c52-ea07-11e6-9be9-08158794fd2b.png)

It sames that **adding subnet not done**, but there is no error info and ping failed cross host. What's the right output when add subnet succeeds? 

**ping:**
![98a3609a-bac1-47f6-903f-455e022f6a71](https://cloud.githubusercontent.com/assets/8912876/22579021/ebbf9bfc-ea07-11e6-8137-cfdd66d10dd5.png)

```bash
arp -v 
172.17.49.0                      (incomplete)                              flannel.1
```

What should I do? Is there any way to fix or debug this problem? Thank you!

**Comment by CocaCola183** [comment]
```bash
arp -v 
172.17.49.0                      (incomplete)                              flannel.1
```

**Comment by tomdee** [comment]
Your kernel version is very old and I assume has limited vxlan support. Flannel really should provide some indication that it's not working, but doesn't appear to at the moment. 

From a quick internet search, it would seem that a Kernel version of >3.9 is normally recommended, though this page does seem to say that Centos >6.5 should be enough for VXLAN in general -http://docs.cloudstack.apache.org/en/latest/networking/vxlan.html

**Comment by CocaCola183** [comment]
@tomdee Thanks for response.

I thought my system should support vxlan after read this: http://docs.cloudstack.apache.org/en/latest/networking/vxlan.html#check-the-capability-of-your-system

I think flannel should give some more advise about Kernel version, there is no specific error info when I use, after all.

**Comment by laverite** [comment]
I am seeing the same issue with centos 7.3 (kernel 4.9.13), flannel (0.5.3 | 0.5.5) and docker (1.12.6 | 1.13.1) using vxlan.  I did not have this problem with centos 7.2 but I'm not sure why and I'm not sure how better to debug this.

If I ping between two pods that are on two different hosts, I see traffic hitting the destination flannel.1  interface, but don't see it getting through to docker0.  Pinging between two pods that live on the same host works.
