### ISSUE TITLE
Info related to CI infrastructure setup for Flannel

### ISSUE THREAD

**Issue by ryan-ibm** [coreos/flannel#605]
We wanted some details on how the current CI infrastructure is setup for Flannel, so that we can setup CI infrastructure on z Systems (big endian)?
1.             How frequent the CI runs on average?
2.             What is the recommended H/W and configuration requirement?
3.             Special S/W requirements (if any).

Thanks,
Ryan D'Mello

**Comment by tomdee** [comment]
It's all public. Just take a look at the .travis.yml file.

1. Once per commit
2. Whatever travis uses
3. Whatever travis uses
