### ISSUE TITLE
container-to-container communication with flannel is slow

### ISSUE THREAD

**Issue by sugun999** [coreos/flannel#607]
Hi,

I have setup kubernetes with coreOS using flannel overlay networking for pod-to-pod(docker container-to-container) communication.
But I noticed that response is very slow for http requests which requires one pod/container need to communicate with other.

Followed this doc for kubernetes multinode setup on coreOS with docker container:
https://coreos.com/kubernetes/docs/latest/getting-started.html

Environment:

coreOS 1235.9.0
Kubernetes v1.5.2_coreos.0

**Comment by tomdee** [comment]
Could you share a little more detail? In what way is it slow?

**Comment by sugun999** [comment]
Hi,

After disabling ipv6, it works now fast.

Hence closing this ticket

**Comment by nemo83** [comment]
> Hi,
> 
> After disabling ipv6, it works now fast.
> 
> Hence closing this ticket

hey, how did you disable ipv6?

can you tell me more about the slowness? I have 2 k3s clusters: 1 on cloud managed bare host, and another on a workstation at home. they both run ubuntu. I've deployed literally the same workload on both clusters, but the one in the cloud goes much faster, while the one at home (similar hardware) is much slower, and it looks like it's a k3s internal networking issue.

Wondering if it's related to the same issue you were having?
