### ISSUE TITLE
Feature idea: on startup, read subnet.env and attempt to acquire that lease

### ISSUE THREAD

**Issue by rosenhouse** [coreos/flannel#610]
### Background

We are concerned about preserving network connectivity for containers in the face of etcd outages and data loss.  For example, during upgrades of etcd, Cloud Foundry users have encountered various "split-brain"-like scenarios.   These scenarios are most easily resolved by stopping all etcd nodes, removing all the data directories, and finally restarting all the nodes.  But CF users expect their containers to remain connected to the network throughout.  Therefore, we prefer that etcd clients like flannel be resilient to etcd outages and data loss. 

### Problem
In manual testing of etcd outages that included data loss, we've found that flannel networks retain connectivity *only* if the `flanneld` processes remain alive throughout the outage.

Consider this sequence:
1. deploy container hosts A & B, running `flanneld` connected to a remote etcd cluster.
2. launch some containers on each host, using flannel CNI plugin; verify network connectivity between containers on different hosts
3. etcd outage begins: stop all etcd nodes
4. restart flanneld on host A; leave it running on host B
5. etcd data loss: `rm -rf ` the etcd data directories on every etcd node
6. etcd outage ends: start all etcd nodes (but with empty data directories)
7. check network connectivity across hosts

In testing, we've found that after step 6, host B correctly re-acquires its existing subnet lease -- the one in use by its running containers.  But host A does not: instead it picks a new subnet at random, which invariably does not match the IP addresses of containers it is hosting.  As a result, the containers on host A cannot reach host B. 

### Proposed solution

On startup, `flanneld` reads from the `subnet.env` file, if it exists.  If it contains a subnet valid for the current configuration, then `flanneld` attempts to re-acquire that subnet from etcd.  In the case of a conflict, `flanneld` falls back to picking a new subnet at random (current behavior).

**What do y'all think?  Would you be open to a PR?**

### References
- [Issue 520: "What should flannel do when it loses a lease?"](https://github.com/coreos/flannel/issues/520)
- [etcd disaster recovery in Cloud Foundry](https://github.com/cloudfoundry-incubator/etcd-release#failed-deploys-upgrades-split-brain-scenarios-etc)
- [more guidance on etcd cluster failures in Cloud Foundry](https://discuss.pivotal.io/hc/en-us/articles/228109388-How-to-recover-ETCD-cluster-after-failure)
- [notes on our investigation](https://www.pivotaltracker.com/story/show/137627203)

cc: @genevievelesperance @jaydunk @rusha19

**Comment by tomdee** [comment]
Yes, I think this sounds like a really useful feature.

**Comment by tomdee** [comment]
Originally raised and tracked in #29 - I'm going to close this issue and just track it from #29.
