### ISSUE TITLE
question; how to set the cni cidr make one node run 1000+ pods

### ISSUE THREAD

**Issue by xiaoping378** [coreos/flannel#612]
flannel config:
![image](https://cloud.githubusercontent.com/assets/5623173/23031589/82580c4e-f4ac-11e6-915a-a26ea6cf1cc0.png)

i have set  "--allocate-node-cidrs=true",  "--cluster-cidr=10.244.0.0/12" in kube-controller-manager,

but ``ip a show cni0`` , the inet scope shows 10.240.0.1/24, so can only run 255 pods, 
when scale 1000 pods, the log say "Error adding network: no IP addresses available in network: cbr0"
so how do i ?

**Comment by xiaoping378** [comment]
i found the code ， so can't make number of pods larger then /24 ? 
```golang
if cfg.Network.PrefixLen < 24 {
    cfg.SubnetLen = 24
} else {
    cfg.SubnetLen = cfg.Network.PrefixLen + 1
}
```

**Comment by rosenhouse** [comment]
@xiaoping378 I think you're mis-reading this code -- the `Network.PrefixLen` is for the whole network -- in your case `/12`.  If you've configured things correctly, you shouldn't even get to that conditional.  Instead you should end up [here](https://github.com/coreos/flannel/blob/ff46071357208d25d36d9907a5f6dbd8200f3d1b/subnet/config.go#L57).  

Are you sure you've installed that Network config in your etcd cluster under `coreos.com/network/config`?

For what it's worth, we've tested Flannel VXLAN with a /22 per host on Cloud Foundry and found it to work fine ([see here](https://www.pivotaltracker.com/story/show/138121065)).

**Comment by xiaoping378** [comment]
@rosenhouse i am using flannel-v0.7.0, it's configration is net-conf.json, i have set the ``SubnetLen`` as the first picture,  but it didn't work. 
can you type your ``coreos.com/network/config`` ?

**Comment by rosenhouse** [comment]
@xiaoping378 :

```bash
curl -s --cacert ca.crt --cert client.crt --key client.key \
   https://etcd.service.cf.internal:4001/v2/keys/coreos.com/network/config | jq
```
shows
```json
{
   "action" : "get",
   "node" : {
      "key" : "/coreos.com/network/config",
      "modifiedIndex" : 336245,
      "createdIndex" : 336245,
      "value" : "{\n  \"Network\": \"10.240.0.0/12\",\n  \"SubnetLen\": 22,\n  \"Backend\": {\n    \"Type\": \"vxlan\",\n    \"Port\": 8472,\n    \"VNI\": 1,\n    \"GBP\": true\n  }\n}"
   }
}
```

**Comment by rosenhouse** [comment]
For reference, the `flanneld` stderr logs show
```
I0222 03:44:52.173843    8218 main.go:133] Installing signal handlers
I0222 03:44:52.173915    8218 manager.go:136] Determining IP address of default interface
I0222 03:44:52.174103    8218 manager.go:149] Using interface with name eth0 and address 10.0.16.20
I0222 03:44:52.174133    8218 manager.go:166] Defaulting external address to interface address (10.0.16.20)
I0222 03:44:52.318989    8218 local_manager.go:134] Found lease (10.241.124.0/22) for current IP (10.0.16.20), reusing
I0222 03:44:52.326175    8218 manager.go:250] Lease acquired: 10.241.124.0/22
I0222 03:44:52.337205    8218 network.go:58] Watching for L3 misses
I0222 03:44:52.337237    8218 network.go:66] Watching for new subnet leases
```

And the `subnet.env` file (defaults to `/run/flannel/subnet.env`) shows:

```
FLANNEL_NETWORK=10.240.0.0/12
FLANNEL_SUBNET=10.241.124.1/22
FLANNEL_MTU=8951
FLANNEL_IPMASQ=false
```

**Comment by tomdee** [comment]
Thanks @rosenhouse that information all looks correct to me. @xiaoping378 hopefully that resolves your issue to closing this.
