### ISSUE TITLE
flannel 0.7.0 docker image with aws-vpc backend failed to request AWS api (SSL issue)

### ISSUE THREAD

**Issue by Dieken** [coreos/flannel#615]
Similar to #302,  https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml uses quay.io/coreos/flannel:v0.7.0-amd64, this docker image doesn't have /etc/ssl/certs so flannel can't verify AWS x509 certificate.

I bypassed the issue by this patch on Ubuntu 16.04:
```diff
--- kube-flannel.yml.orig	2017-02-19 23:25:33.000000000 +0800
+++ kube-flannel.yml	2017-02-19 23:28:52.000000000 +0800
@@ -24,7 +24,7 @@
     {
       "Network": "10.244.0.0/16",
       "Backend": {
-        "Type": "vxlan"
+        "Type": "aws-vpc"
       }
     }
 ---
@@ -64,6 +64,9 @@
         volumeMounts:
         - name: run
           mountPath: /run
+        - name: sslcerts
+          mountPath: /etc/ssl/certs
+          readOnly: true
         - name: flannel-cfg
           mountPath: /etc/kube-flannel/
       - name: install-cni
@@ -78,6 +81,9 @@
         - name: run
           hostPath:
             path: /run
+        - name: sslcerts
+          hostPath:
+            path: /etc/ssl/certs
         - name: cni
           hostPath:
             path: /etc/cni/net.d
```

I remember different Linux distributions have different path for that directory "certs",  so it's better flannel can package a copy of CA certificates.

**Comment by tomdee** [comment]
As of v0.9.0 flannel is packaging ca-certificates (at least for amd64) so I think this can be closed.
