### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by rosenhouse** [coreos/flannel#616]
As an operator, I would like to be alerted if my `flanneld` is unable to connect to etcd.

Currently, if flannel loses its connection to etcd, it prints error messages to stderr but does not fail.

I could write some tooling to process those logs and alert me if certain strings are printed.

But I'd rather have some kind of healthcheck, e.g. I set up a script to periodically `curl` a special endpoint on `localhost`.  If I get back a `200 OK` then I know `flanneld` is healthy.  Otherwise, I can raise an alert, maybe restart the VM, etc.

I could imagine the healthcheck returning some basic information, like when it last renewed its lease with etcd.  But the important thing is a simple status code that could be easily interpreted and acted on.

A CNI plugin could even probe this healthcheck during the `ADD` action.  That way it could ensure that `flanneld` is alive, and that the `subnet.env` file on disk is up-to-date.

Would you be open to a PR like this?

cc: @rusha19 @mcwumbly @jaydunk

**Comment by rosenhouse** [comment]
Ping @lxpollitt.  We're probably going to implement this in some form on a fork in order to support integration with Cloud Foundry.  Any input you have would be appreciated.

**Comment by tomdee** [comment]
Sounds useful to me.

**Comment by jsravn** [comment]
@tomdee Wonder why you closed this? It's a pretty big gap. We recently had an outage because of this and there is no way to monitor flanneld health properly at the moment, as far as I can tell.
