### ISSUE TITLE
flannel node allocating a new subnet every 24 hours

### ISSUE THREAD

**Issue by Agrosis** [coreos/flannel#621]
Hello,

I'm running a Kubernetes cluster with flannel as an overlay network, and it works like a charm! Awesome work!

flannel is supposed to renew a lease for the allocated IP on the overlay network for the machine its currently running on. In my setup, after ~24 hours, flannel seems to be just leasing a completely new allocated IP on the network, and using that instead. That breaks container networking and I have to restart the cluster to get it back into sync.

For example, one of the machines had 172.16.28.0/24 leased. 24 hours later, it instead had 172.168.55.0/24 leased.

Any solutions to this?

flannel version 0.6.2

**Comment by philips** [comment]
How are you running flannel? Are you using the etcd or kubernetes backend?

**Comment by Agrosis** [comment]
Sorry I didn't specify in the original issue, but I'm using etcd as the backend. So, since then, I found the flannel reservations features in 0.7.0, so I've upgraded to that and just set the TTL of the subnet key to 0, and I haven't had any problems since then. Haven't tried out the auto-renew mode on 0.7.0 yet to see if it works, but let me know if you want me to dig into this more.

**Comment by tomdee** [comment]
@Agrosis It would be great to understand why your're hitting this

**Comment by tomdee** [comment]
Without some more info this can't be debugged or fixed. Unless we can find a repro for this I'm going to have to close it.

**Comment by cizixs** [comment]
Has this issues too, but it does not happen every 24 hour, but occasionally.

The headache is there is no easy way to **reproduce**, and the issue does not have enough information/logs to tell me why it is behaving like this.

**Comment by cizixs** [comment]
@Agrosis So you manually set TTL for all subnets to `0`?

**Comment by cizixs** [comment]
@tomdee  What is the purpose of TTL of subnets? 
In my opinion, flannel will renew the lease 1 hour before expiration by default. In the worst case, flannel will reallocate a subnet if it stopped for one hour and restarted.

Does it make more sense if flannel  periodically update TTL? 
Or if I'm not using TTL, can I turn it off with a parameter instead of setting etcd subnets key TTL to 0 by hand?

**Comment by tomdee** [comment]
TTL of the subnets is so they are cleaned up if the host goes away.
You can change the renewal time so it does it more than an hour before it would expire.
