### ISSUE TITLE
vxlan network flannel.1 lost packets sometimes

### ISSUE THREAD

**Issue by guanjunding** [coreos/flannel#623]
We have used this solution on the production line,  More than 30 running docker instance .
Recently we found that several nic flannel.1  of servers drop the packets sometimes, and then I carried out the following checks, but I did not find anything unusual:

$ sar -n EDEV  1
11:25:46 AM     IFACE   rxerr/s   txerr/s    coll/s  rxdrop/s  txdrop/s  txcarr/s  rxfram/s  rxfifo/s  txfifo/s
11:25:46 AM veth3c0c3c1      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
......
11:25:46 AM      eth0      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
11:25:46 AM      eth1      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
11:25:46 AM        lo      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
11:25:46 AM flannel.1      0.00      0.00      0.00      0.00     **51.32**      0.00      0.00      0.00      0.00
11:25:46 AM   docker0      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00

Average:        IFACE   rxerr/s   txerr/s    coll/s  rxdrop/s  txdrop/s  txcarr/s  rxfram/s  rxfifo/s  txfifo/s
Average:    veth789dfbf      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
.......
Average:         eth0      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:         eth1      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:           lo      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00
Average:    flannel.1      0.00      0.00      0.00      0.00     **92.51**      0.00      0.00      0.00      0.00
Average:      docker0      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00      0.00

$sar -n DEV 1
02:27:37 PM     IFACE   rxpck/s   txpck/s    rxkB/s    txkB/s   rxcmp/s   txcmp/s  rxmcst/s
02:27:38 PM        lo      0.00      0.00      0.00      0.00      0.00      0.00      0.00
02:27:38 PM veth2461ba0   1107.00   1028.00    135.67    516.67      0.00      0.00      0.00
.....
02:27:38 PM flannel.1   9470.00   8829.00   4235.92   2614.62      0.00      0.00      0.00
02:27:38 PM   docker0   7257.00   7642.00   2219.48   1769.04      0.00      0.00      0.00

$ flanneld -version
0.5.3

$ iptables -L -vnx | grep DROP
       0        0 DROP       icmp --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8
       0        0 DROP       udp  --  *      *       0.0.0.0/0            10.0.0.0/8           udp dpts:1:10000
       0        0 DROP       tcp  --  *      *       0.0.0.0/0            10.0.0.0/8           state NEW tcp dpts:1:10000
       0        0 DROP       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpts:1:1024
       ....

$ journalctl -fxe -u flanneld
Feb 27 14:18:01  flanneld[2276]: I0227 14:18:01.255544 02276 vxlan.go:340] Ignoring not a miss: 3a:e4:01:b8:bd:69, 172.17.55.4
Feb 27 14:18:01  flanneld[2276]: I0227 14:18:01.255596 02276 vxlan.go:340] Ignoring not a miss: 4e:cf:81:4a:29:1b, 172.17.19.13
Feb 27 14:18:01  flanneld[2276]: I0227 14:18:01.359661 02276 vxlan.go:340] Ignoring not a miss: 52:90:a6:75:47:13, 172.17.42.0
Feb 27 14:18:01  flanneld[2276]: I0227 14:18:01.383508 02276 vxlan.go:340] Ignoring not a miss: da:6c:b3:d0:06:61, 172.17.64.7
Feb 27 14:18:01  flanneld[2276]: I0227 14:18:01.447447 02276 vxlan.go:340] Ignoring not a miss: c2:3d:ae:3c:30:ca, 172.17.39.0
Feb 27 14:18:01  flanneld[2276]: I0227 14:18:01.751822 02276 vxlan.go:340] Ignoring not a miss: c2:67:de:ed:85:fd, 172.17.105.0
Feb 27 14:18:01  flanneld[2276]: I0227 14:18:01.879283 02276 vxlan.go:345] L3 miss: 172.17.55.10
Feb 27 14:18:01  flanneld[2276]: I0227 14:18:01.879337 02276 device.go:187] calling NeighSet: 172.17.55.10, 3a:e4:01:b8:bd:69
Feb 27 14:18:01  flanneld[2276]: I0227 14:18:01.880383 02276 vxlan.go:356] AddL3 succeeded
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.003467 02276 vxlan.go:340] Ignoring not a miss: 12:6a:a2:ea:01:82, 172.17.77.0
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.151455 02276 vxlan.go:340] Ignoring not a miss: 4e:cf:81:4a:29:1b, 172.17.19.7
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.215432 02276 vxlan.go:340] Ignoring not a miss: 3a:19:00:6b:94:ed, 172.17.12.5
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.343445 02276 vxlan.go:340] Ignoring not a miss: b6:15:64:1a:d7:1e, 172.17.60.0
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.503832 02276 vxlan.go:340] Ignoring not a miss: c2:67:de:ed:85:fd, 172.17.105.0
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.592088 02276 vxlan.go:345] L3 miss: 172.17.60.8
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.592143 02276 device.go:187] calling NeighSet: 172.17.60.8, b6:15:64:1a:d7:1e
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.593090 02276 vxlan.go:356] AddL3 succeeded
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.727446 02276 vxlan.go:340] Ignoring not a miss: 3a:19:00:6b:94:ed, 172.17.12.8
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.753825 02276 vxlan.go:340] Ignoring not a miss: c2:67:de:ed:85:fd, 172.17.105.0
Feb 27 14:18:02  flanneld[2276]: I0227 14:18:02.791472 02276 vxlan.go:340] Ignoring not a miss: 92:99:e2:37:3a:01, 172.17.5.7
Feb 27 14:18:03  flanneld[2276]: I0227 14:18:03.005461 02276 vxlan.go:340] Ignoring not a miss: 12:6a:a2:ea:01:82, 172.17.77.0
Feb 27 14:18:03  flanneld[2276]: I0227 14:18:03.047444 02276 vxlan.go:340] Ignoring not a miss: b6:15:64:1a:d7:1e, 172.17.60.22

Do you have any good suggestions? Look forward to your help. Thank  you.

**Comment by jsravn** [comment]
@guanjunding did you find anything? I don't think it's a flannel issue btw, most likely something in the vxlan driver drops packets occasionally.
