### ISSUE TITLE
Unexplained overhead in container to container communication

### ISSUE THREAD

**Issue by erevoss** [coreos/flannel#643]
Hello,

I'm running a test with flannel (0.7.0 with vxlan - not UDP) and docker (1.12) on two of my (to be) kubernetes nodes and I am experiencing a very large bandwidth overhead that I can't explain:

* Running iperf from worker01 to worker02 shows that my bandwidth is 8.4Gbps
* When I run iperf from a container on worker01 to another container on worker02 the bandwidth drops to 2.4Gbps.

Docker is running like this:
```bash
worker01: /usr/bin/dockerd --bip=172.16.11.1/24 --ip-masq=true --mtu=1450
worker02: /usr/bin/dockerd --bip=172.16.71.1/24 --ip-masq=true --mtu=1450
```

Here's the flannel network settings set in etcd:
```bash
{"Network":"172.16.0.0/16","Backend":{"Type":"vxlan","VNI":1}}
```

Here's the flannel environment settings on each worker node:
```bash
[root@worker01 ~]# cat /run/flannel/subnet.env
FLANNEL_NETWORK=172.16.0.0/16
FLANNEL_SUBNET=172.16.11.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false

[root@worker02 ~]# cat /run/flannel/subnet.env
FLANNEL_NETWORK=172.16.0.0/16
FLANNEL_SUBNET=172.16.71.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false
```

Here's the iperf output:
(host to host test)
```bash
[root@worker01 ~]# iperf -c worker02
------------------------------------------------------------
Client connecting to worker02, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local 10.89.144.33 port 10343 connected with        10.89.144.35 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  9.78 GBytes  8.40 Gbits/sec
```

(container to container test - running on different hosts)
```bash
[root@ec8bde30de43 /]# iperf -c 172.16.71.2   
------------------------------------------------------------
Client connecting to 172.16.71.2, TCP port 5001
TCP window size: 45.0 KByte (default)
------------------------------------------------------------
[  3] local 172.16.11.2 port 52811 connected with 172.16.71.2 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  2.82 GBytes  2.43 Gbits/sec
```

Is this the normal overhead for flannel? (-75%). I can't think of anything that could be misconfigured but I would be glad to provide any additional information that might help.

**Comment by tomdee** [comment]
I see slightly better performance on my laptop, but yes, if you use vxlan you will get less than wirespeed. You can get back up towards 10 GBits/sec by using a larger MTU, more streams and by having a NIC that supports VXLAN offload.
