### ISSUE TITLE
Provide tar.gz for releases for different archs

### ISSUE THREAD

**Issue by Pensu** [coreos/flannel#646]
Hi,

As seen here: https://github.com/coreos/flannel/releases, there are releases available for different archs, but the tar is only available for amd64. Now, ansible playbooks for kubernetes use tar.gz to install flannel. To make those playbooks arch neutral, we need tar.gz files for ppc64le and arm. Is there any plan/possibility to provide that?

**Comment by tomdee** [comment]
That sounds fine to me, but I'm not sure I can promise it for the next release. If you'd like to submit a PR (changing the Makefile) then I'll happily merge it.

**Comment by Pensu** [comment]
Sure, I will submit a PR soon.
