### ISSUE TITLE
Current Flannel config fails by default on Kube 1.6.beta4

### ISSUE THREAD

**Issue by cmluciano** [coreos/flannel#648]
xref: https://github.com/kubernetes/kubernetes.github.io/issues/2942

The [current Kube deploy file](https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml) will fail automatically without first [running the rbac settings](https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel-rbac.yml). 

Two options:
- Add a note in the Kube docs that mentions the need to run the rbac file first
- Try a combination of the rbac file with the flannel deploy file
  - A combined file seems to be the pattern other cni-plugins like Calico and Weave are leveraging

**Comment by cmluciano** [comment]
cc @tomdee

**Comment by cmluciano** [comment]
I think the current deploy file also needs updated to run in the kube-system namespace. If this should run on every node, I would also need to add the taint bypass lines so that it will be deployed to the Kube controller.

**Comment by tomdee** [comment]
@cmluciano Do you have a working 1.6 file that you could submit as a PR?

**Comment by cmluciano** [comment]
Not yet, I added the namespace to the relevant sections in both, but I’m getting errors about the cni plugin not updating the pod network correctly
