### ISSUE TITLE
flannel does not get rid of unused config in etcd

### ISSUE THREAD

**Issue by xh3b4sd** [coreos/flannel#659]
When Flannel manages a lot of subnets there will be a lot of data created in etcd. I see that this data is always kept, even though the subnets do not exist anymore. I did not find configuration for making flannel cleaning up etcd data over time. How is this supposed to work? IMO Flannel should take care of the state within etcd and should curate orphaned data from time to time. WDYT?

**Comment by tomdee** [comment]
Thanks for raising this but it doesn't match my understanding. Flannel shouldn't be leaving any state data in etcd - can you give me a specific example of what you're seeing?

**Comment by tomdee** [comment]
@xh3b4sd I'm going to close this issue as I think flannel is getting rid of unused config in etcd. If you're still seeing this problem then please reopen the issue
