### ISSUE TITLE
k8s svc error

### ISSUE THREAD

**Issue by timchenxiaoyu** [coreos/flannel#660]
In k8s env,do we need keep --service-cluster-ip-range and flannel network same?

**Comment by euank** [comment]
Those two ranges should not overlap.

Service ips in a K8s cluster are "fake" ips which are redirected by kube-proxy to real ips, irrespective of the pod network. Kube-proxy will make rules that redirect the service-ips to pod-ips, and those pod-ips are what flannel should understand.

**Comment by timchenxiaoyu** [comment]
ok,I have found the problem ,k8s kubelet config change --pod-cidr
