### ISSUE TITLE
Docs: Rework the README.md

### ISSUE THREAD

**Issue by tomdee** [coreos/flannel#672]
Here are my thoughts on what should go in the README.md

# Intro 
What is Flannel (k8s focused, but introduce concepts of having different datastores and different networking backends), mention K8s (/CNI) and Docker integration, and maybe container linux integration. Also worth dropping in a few networking details - e.g. L3 routed, no L2 traffic between hosts
Interaction with Network Policy - Flannel is for networking, but Canal (Flannal+Calico) is great way to get policy on K8s

# Getting started
Look! It’s this easy to use flannel with K8s
- Why would I use flannel with Kubernetes?
- What are the pre reqs? What are the limitations?
- What is the exact command to run?
- What can I do now? (ping between pods)

# Index into other docs in docs dir
# Contact details and contributing information

**Comment by tomdee** [comment]
@joshix and @zbwright Can you run with the intro section?

**Comment by zbwright** [comment]
I believe Josh is going to take a stab at this, and I'll edit/massage. We've added notes to the original google doc plan for this project.

**Comment by tomdee** [comment]
For the getting started guide, this is what I'm thinking so far (it's a bit rough and ready but you hopefully get the idea):

# Getting started
It's really easy to use flannel with Kubernetes. Flannel supports using the kubernetes API server as its backing datastore which means there's no need to deploy an etcd server for flannel, or even for flannel to access the etcd server that Kubernetes uses. This flannel mode is known as the "kube subnet manager" and demonstrated below.

## Adding flannel
Flannel can be added to an existing Kubernetres clusters but it's easiest if no pods have been started yet (host networked pods are fine). A great way to create a new Kubernetes cluster is with [kubeadm](https://kubernetes.io/docs/getting-started-guides/kubeadm/) which helpfully points out the need to define "a pod network CIDR" for example by passing in `--pod-network-cidr 10.244.0.0/16` when running kubeadm init. This pod network CIDR is the key prerequisite for using flannel with the kube subnet manager. If you're running flannel through some other means, then the pod cidr might be set automatically for you or you can set it manually by passing [`--pod-cidr`](https://kubernetes.io/docs/admin/kubelet/) to each of your `kubelet`s. It's also possible to set it per-node using kubectl, e.g.
```
kubectl patch node minikube -p '{"spec":{"podCIDR":"10.33.12.0/24"}}'
```

Adding flannel to the cluster is then as simple as:
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```

And if you're using RBAC also applying
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml
```

Although not required, it's highly recommended that you use CNI for starting your pods. This requires your kubelets to be started with `--network-plugin=cni`. This is already the default if you're using kubeadm.

## What just happened
The manifest creates three things
1. A service account for flannel to use
2. A ConfigMap containing both a CNI configuration and a flannel configuration. The network in the flannel configuration should match the pod network CIDR. The choice of backend is also made here and defaults to vxlan.
3. A DaemonSet to deploy the flannel pod on each Node. The pod has two containers 1) the flannel daemon itself 2) a container for deploying the CNI configuration to a location that the kubelet can read it from.

## What can I do now
When you run pods, they will be allocated IP addresses from the from the pod network CIDR. No matter which node those pods end up on, they will be able to communicate with each other. Try it by running a couple of simple pods and pinging between them, e.g. using `kubectl run -i -t busybox1 --image=busybox --restart=Never`

**Comment by zbwright** [comment]
I can add this to the ReadMe. Question: Should I remove the Theory of Operation text and diagram? is it outdated? Or should I leave it, and add the Getting Started materials after?

**Comment by zbwright** [comment]
This sentence doesn't make any sense. Maybe a little rewrite? does kubeadm tell you to create a CIDR?

A great way to create a new Kubernetes cluster is with kubeadm which helpfully points out the need to define "a pod network CIDR" for example by passing in --pod-network-cidr 10.244.0.0/16 when running kubeadm init.

**Comment by zbwright** [comment]
I believe that the ReadMe could still use some introductory information. Some of your original plan is still missing.
- Flannel is k8s focused and offers different datastores and different networking backends 
- mention K8s (/CNI) and Docker integration, and maybe Container Linux integration. 
- Flannel's relationship to Calico isn't mentioned yet
- networking details are not introduced:  L3 routed, no L2 traffic between hosts
- *kube subnet manager* info was removed - pinging between two pods is going to become another doc

**Comment by zbwright** [comment]
I'm going to pull the remaining tasks out of this issue, create a new one referencing them, and close this issue. 

ping between two pods: https://github.com/coreos/flannel/issues/741
add a few items to the readme: https://github.com/coreos/flannel/issues/742

closing this ticket.
