### ISSUE TITLE
Docs: Make the "Running" doc better

### ISSUE THREAD

**Issue by tomdee** [coreos/flannel#673]
Now that it's moved, it needs to be reworked so it can standalone. e.g. add some intro text and fix up missing references

I also think the following extra content would be good
- [x] Running manually
- [x] Interface selection
- [x] Making changes at runtime
- [ ] Then zero-downtime restarts should be moved into an upgrade section (or standalone doc) with some extra k8s focused content
- [x] A link should be added to existing leases/reservations doc I added to answer the questions "How do I make sure that a specific host has a specific IP range"

**Comment by tomdee** [comment]
For running manually, I was thinking a complete etcd-based mini-guide would be instructive, e.g.
1) Download a flannel binary - wget https://github.com/coreos/flannel/releases/download/v0.7.0/flanneld-amd64 && chmod +x flanneld-amd64
2) Run the binary - `sudo ./flanneld-amd64` it will hang waiting to talk to etcd
3) Run etcd - see instructions at https://github.com/coreos/etcd/releases/latest or if you have docker just do `docker run --rm --net=host quay.io/coreos/etcd`
4) Observe that flannel can now talk to etcd, but can't find any config. So write some config. EIther get etcdctl from the releases page above or just use docker again
`docker run --rm --net=host quay.io/coreos/etcd etcdctl set /coreos.com/network/config '{ "Network": "10.5.0.0/16", "Backend": {"Type": "vxlan"}}' `

Now flannel is running, it has created a vxlan tunnel device on the host and written a subnet config file
```
cat /var/run/flannel/subnet.env
FLANNEL_NETWORK=10.5.0.0/16
FLANNEL_SUBNET=10.5.72.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false
```

**Comment by tomdee** [comment]
For interface selection, it ties in with the existing vagrant content a little. It should highlight the importance of choosing the right interface as this is how flannel registers itself in the datastore. The important options are
```
-iface string
    	interface to use (IP or name) for inter-host communication
-public-ip string
    	IP accessible by other nodes for inter-host communication
```
The combination of the defaults, the autodetection and these two flags ultimately result in the following being determined
* An interface (used for MTU detection and selecting the VTEP MAC in vxlan)
* An IP address for that interface - WIBNI each backend documents clearly how it uses this address...
* A public IP that can be used for reaching this node - in host-gw it should match the interface address. Again would be nice to know how each backend uses this.

This documentation should guide users well enough that they understand the how, when, what and why of this configuration.

**Comment by tomdee** [comment]
For k8s upgrade guidance I was thinking of tying in with the k8s 1.6 daemonset rolling upgrade feature. Help from a CoreOS kubernetes expert would be appreciated here!

**Comment by tomdee** [comment]
For making changes at runtime I think we just needs statements that say
- You can't change the datastore type (we don't have a migration path currently from etcd backed flannel to kube-subnet-mgr backed flannel)
- You can't change the backend type (without stopping all your workloads and restarting all your flannel daemons)
- You can change the the subnetlen/subnetmin/subnetmax with a daemon restart (but be careful if pods are already using IP addresses outside the new range as they will stop working)
- I think you probably can't change the clusterwide network range (without downtime)

**Comment by zbwright** [comment]
I've got a draft going of this - will need more input from Josh or another source to flesh it out more. I can continue working from this Issue's comments, and generate a PR when you think it's time.

**Comment by zbwright** [comment]
these two items have not yet been addressed:

- [ ] zero-downtime restarts should be moved into an upgrade section (or standalone doc) with some extra k8s focused content
- [ ] A link should be added to existing leases/reservations doc I added to answer the questions "How do I make sure that a specific host has a specific IP range"

**Comment by zbwright** [comment]
Created a new issue to add a doc on zero downtime restarts, in order to close this issue. Closing.
