### ISSUE TITLE
flanneld binary is quite large

### ISSUE THREAD

**Issue by tomdee** [coreos/flannel#674]
The flanneld binary got quite large when we added the kube-subnet-mgr (which imports a _lot_ of code to get a k8s client). It would be nice to get the size back down, some options are:
- Start using https://github.com/kubernetes/client-go
- Start using https://github.com/ericchiang/k8s

**Comment by tomdee** [comment]
Even with the move to `client-go` the binary is still ~52MB

**Comment by tomdee** [comment]
I think to make them smaller we'd need to use `upx` (and maybe some stripping)

**Comment by euank** [comment]
A crazier option would be shipping different binaries for k8s vs etcd backed flanneld.
