### ISSUE TITLE
vxlan src ip 

### ISSUE THREAD

**Issue by timchenxiaoyu** [coreos/flannel#691]
In my env, flannel+vxlan.  I get vxlan package from wireshark, i find src IP is not container but flannel.1 ?why not source container IP rather than  source host flannel.1?
eg:
Internet Protocol Version 4, Src: 192.168.5.0 (192.168.5.0), Dst: 192.168.49.2 (192.168.49.2)
192.168.5.0 is flannel.1 ip

**Comment by timchenxiaoyu** [comment]
I see, 
192.168.5.0/24 dev docker0  proto kernel  scope link  src 192.168.5.1 
this route  will lead package to docker0 ,then to container

**Comment by tomdee** [comment]
The source IP address should be for the container. How are you sending the packet from the container?

**Comment by timchenxiaoyu** [comment]
you are right, is my err.I want to ask another question,about vxlan outerIP ,what's the different between use vxlan vtep  and use host eth?
