### ISSUE TITLE
Centos node join ubuntu master Permission denied

### ISSUE THREAD

**Issue by insoz** [coreos/flannel#704]
I run join command on centos minon, the flannel container create faild.
master is ubuntu
kubernetes 1.6.2
flannel 0.7.1

```docker logs 
cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-flannel.conf
cp: can't create '/etc/cni/net.d/10-flannel.conf': Permission denied
```

**Comment by tomdee** [comment]
Hi @insoz . The flannel daemon needs permissions to write to that directory. You can change the permissions with `chmod`

**Comment by insoz** [comment]
`setenforce 0` resolved my problem.
