### ISSUE TITLE
Failed to create SubnetManager: 501: All the given peers are not reachable

### ISSUE THREAD

**Issue by aelmehra** [coreos/flannel#708]
when starting flanneld on my manager and the nodes I am receiving the following error:

E0504 09:15:03.238657   31865 main.go:151] Failed to create SubnetManager: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

I am running a cluster of CentOS VMs

**Comment by tomdee** [comment]
This sounds like an etcd problem. I'm not an etcd expert, but try searching google "All the given peers are not reachable" and it looks like there are many other issues like this.
