### ISSUE TITLE
cp: can't create '/etc/cni/net.d/10-flannel.conf': Permission denied

### ISSUE THREAD

**Issue by rafagsiqueira** [coreos/flannel#709]
After installing kubernetes using kubeadm init and running:
`kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml`
`kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml`
kube-flannel install-cni will fail with CrashLoopBackOff.

## Expected Behavior
Both kube-flannel containers should be running

## Current Behavior
kube-flannel install-cni container with CrashLoopBackOff error and logs show cp: can't create '/etc/cni/net.d/10-flannel.conf': Permission denied

## Possible Solution
I have tried deleting the directory, it recreates it automatically but still can't copy the flannel.conf.

## Steps to Reproduce (for bugs)
I have used kubeadm init --pod-network-cidr 10.244.0.0/16

## Context
Kubernetes nodes won't get ready.

## Your Environment

* Kubernetes version (if used): 1.6
* Operating System and version: CentOS 7.3

**Comment by rafagsiqueira** [comment]
Selinux was enabled.

**Comment by tomdee** [comment]
@rafagsiqueira Thanks for the update

**Comment by nithu0115** [comment]
Heya! Is it possible to re-open this issue as disabling selinux is not correct solution, probably?
