### ISSUE TITLE
Problem connecting to a TLS secured etcd

### ISSUE THREAD

**Issue by raeesbhatti** [coreos/flannel#718]
## Expected Behavior
`flanneld` should have connected to the `etcd` server TLS certificates and should've verified the response using the certificated provided by `--remote-cafile` parameter.
## Current Behavior
It fails with the following error:
```
failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: x509: certificate signed by unknown authority
```
## Steps to Reproduce (for bugs)

1. Setup a TLS secured `etcd` server
2. Use [Kubernetes setup guide](https://coreos.com/kubernetes/docs/latest/deploy-master.html#set-up-the-kube-scheduler-pod) to setup `flannel`
3. Use following as `FLANNEL_OPTS` env variable in service dropin `--ip-masq=true --remote-certfile=/etc/kubernetes/ssl/client.pem --remote-keyfile=/etc/kubernetes/ssl/client-key.pem --remote-cafile=/etc/kubernetes/ssl/ca.pem`

### Context
I can access the `etcd` server using the same client cert and CA cert using CURL.

## Your Environment
* Flannel version: `v0.7.1`
* Backend used (e.g. vxlan or udp):
* Etcd version: `v3.1.7 `
* Operating System and version: `CoreOS Beta 1381.1.0`

**Comment by tomdee** [comment]
Is this just bad certificates in the flannel container (or a container linux flannel-wrapper problem where the certs aren't being mounted in properly)?

**Comment by raeesbhatti** [comment]
The parameters to mount certificates are same as they are for other services (etcd, kube-apiserver, etc.). The cert files are there because if they were not, it would throw an error about not being able to open the file. As I said before, I tried the same `ca.pem` with CURL and it works alright.

**Comment by glennmcallister** [comment]
I'm observing similar behaviour with a new cluster I'm trying to deploy, although the versions are slightly different:

* Flannel version: v0.7.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: v3.1.6
* Operating System and version: Container Linux by CoreOS stable (1353.7.0)

```
sudo etcdctl --endpoints=https://<ip1>:2379,https://<ip2>:2379,https://<ip3>:2379 --cert-file=/etc/kubernetes/ssl/apiserver.pem --key-file=/etc/kubernetes/ssl/apiserver-key.pem cluster-health
member 2b83d802c287600 is healthy: got healthy result from https://<ip1>:2379
member a2f15b71c0182d77 is healthy: got healthy result from https://<ip2>:2379
member c40650a32d25891b is healthy: got healthy result from https://<ip3>:2379
cluster is healthy
```

I've tried various ways of providing the certificate configuration to `flanneld`, last one looks like the following values in `/etc/flannel/options.env`:

```
FLANNELD_IFACE=<vmip>
ETCD_SSL_DIR=/etc/kubernetes/ssl
FLANNEL_OPTS="-v=9 --etcd-certfile=/etc/kubernetes/ssl/apiserver.pem --etcd-keyfile=/etc/kubernetes/ssl/apiserver-key.pem --etcd-endpoints=https://<ip1>:2379,https://<ip2>:2379,https://<ip3>:2379"
```

I've also used the `FLANNELD_*` environment variables, same results:

```
May 23 14:20:34 <vm-name> flannel-wrapper[4617]: E0523 14:20:34.434201    4617 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
May 23 14:20:35 <vm-name> flannel-wrapper[4617]: E0523 14:20:35.447655    4617 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
May 23 14:20:36 <vm-name> flannel-wrapper[4617]: E0523 14:20:36.462808    4617 network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
``` 

And before anyone chimes in with my missing the CA file, it's already been included in `/etc/ssl/certs` and `sudo update-ca-certificates` run during an earlier provisioning step.

**Comment by glennmcallister** [comment]
So, I managed to get this to work. The TL;DR is that `/etc/ssl/certs` is not in the set of directory mounts that `flannel-wrapper` provides by default. 

The quick workaround was for me to copy my cert chain into `/etc/kubernetes/ssl` as `bcl-ca.pem`, and voila, it all worked:

```
May 23 15:30:57 <vmname> flannel-wrapper[8314]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/flannel-wrapper.uuid --trust-keys-from-https --volume ssl,kind=host,source=/etc/kubernetes/ssl,readOnly=true --mount volume=ssl,target=/etc/kubernetes/ssl --mount volume=notify,target=/run/systemd/notify --volume notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/systemd/notify --net=host --volume run-flannel,kind=host,source=/run/flannel,readOnly=false --volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=run-flannel,target=/run/flannel --mount volume=etc-ssl-certs,target=/etc/ssl/certs --mount volume=usr-share-certs,target=/usr/share/ca-certificates --mount volume=etc-hosts,target=/etc/hosts --mount volume=etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-from-dir=stage1-fly.aci quay.io/coreos/flannel:v0.7.0 -- -v=9 --etcd-certfile=/etc/kubernetes/ssl/apiserver.pem --etcd-keyfile=/etc/kubernetes/ssl/apiserver-key.pem --etcd-endpoints=https://10.241.129.21:2379,https://10.241.129.22:2379,https://10.241.129.23:2379 --etcd-cafile=/etc/kubernetes/ssl/bcl-ca.pem
May 23 15:30:57 <vmname> flannel-wrapper[8314]: I0523 15:30:57.924696    8314 main.go:132] Installing signal handlers
May 23 15:30:57 <vmname> flannel-wrapper[8314]: I0523 15:30:57.925035    8314 manager.go:124] Searching for interface using 10.241.129.31
May 23 15:30:57 <vmname> flannel-wrapper[8314]: I0523 15:30:57.925331    8314 manager.go:149] Using interface with name ens192 and address 10.241.129.31
May 23 15:30:57 <vmname> flannel-wrapper[8314]: I0523 15:30:57.925486    8314 manager.go:166] Defaulting external address to interface address (10.241.129.31)
May 23 15:30:57 <vmname> flannel-wrapper[8314]: I0523 15:30:57.996613    8314 local_manager.go:179] Picking subnet in range 10.2.1.0 ... 10.2.255.0
May 23 15:30:58 <vmname> flannel-wrapper[8314]: I0523 15:30:58.002767    8314 manager.go:250] Lease acquired: 10.2.60.0/24
May 23 15:30:58 <vmname> flannel-wrapper[8314]: I0523 15:30:58.003039    8314 network.go:58] Watching for L3 misses
May 23 15:30:58 <vmname> flannel-wrapper[8314]: I0523 15:30:58.003049    8314 network.go:66] Watching for new subnet leases
May 23 15:30:58 <vmname> systemd[1]: Started flannel - Network fabric for containers (System Application Container).
```
So, what I'm confused about is the following:

```
--volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true 
--volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true
```

And later:

```
--mount volume=etc-ssl-certs,target=/etc/ssl/certs 
--mount volume=usr-share-certs,target=/usr/share/ca-certificates
```

We have two volume mounts pointing at the *same* directory. Why?  Why doesn't the first actually point at `/etc/ssl/certs` as expected? If it did, I wouldn't be broken.

**Comment by glennmcallister** [comment]
So, in all fairness, what I'm observing isn't a flannel bug, it's a Container Linux bug; any advice as to the best place to write this up?

**Comment by tomdee** [comment]
@glennmcallister Thanks for investigating this - I think it can be raised at https://github.com/coreos/coreos-overlay but I'll flag it with the CoreOS team too.

**Comment by crawford** [comment]
It should be fixed by https://github.com/coreos/coreos-overlay/pull/2571.
