### ISSUE TITLE
cannot delete bridge flannel.1

### ISSUE THREAD

**Issue by gojoy** [coreos/flannel#733]
Hi:
I deployed docker with flannel  for test. the deployment env is :
OS: Centos 7.3
flannel: 0.7.0
docker: 1.12.6

Now I want to remove flannel. but cannot delete bridge flannel.1 
`ifconfig flannel.1 down`
`brctl delbr flannel.1`
then I got following message:
`can't delete bridge flannel.1: Operation not permitted`(I have used root to run  commands)
so How can I delete flannel.1 ?   thanks

**Comment by KDF5000** [comment]
I use "ip link del flannel.1" to delete the device on ubuntu. I guess that it will work too.

**Comment by tomdee** [comment]
flannel.1 isn't a bridge, it's a vxlan device, so the suggestion from @KDF5000 is what you need

**Comment by gojoy** [comment]
Got it. Thanks
