### ISSUE TITLE
Failed to install kube-flannel add-on on kubeadm

### ISSUE THREAD

**Issue by willise** [coreos/flannel#736]
I try to install flannel addon after installing kubeadm but there got "CrashLoopBackOff" when **get pods**.

## Expected Behavior
kube-flannel-ds- pod's status becomes running.

## Current Behavior
**kcm logs kube-flannel-ds-hdqb4**
```
Error from server (BadRequest): a container name must be specified for pod kube-flannel-ds-hdqb4, choose one of: [kube-flannel install-cni]
```

## Steps to Reproduce
YAML link is:
https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml

**kubectl apply -f kube-flannel.yml**

## Your Environment
* Flannel version: 
**dc images | g flannel**
`quay.io/coreos/flannel                                   v0.7.1-amd64        cd4ae0be5e1b        5 weeks ago         77.76 MB`
* Kubernetes version :
**kubeadm version**
`kubeadm version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}`
* Operating System and version:
CentOS Linux release 7.3.1611 (Core)

**Comment by gunjan5** [comment]
@willise I think you're getting that `BadRequest` error because you haven't specified the container in the pod. you should add the flag `-c  kube-flannel` to specify the container in the pod (since there are two containers in the pod)

Alternatively, you can also do a `kubectl describe pod <pod-name> -n kube-system` to see what's going on in the pod

**Comment by willise** [comment]
@gunjan5 But where to add the flag `-c kube-flannel`? command like `kubectl apply -f kube-flannel.yml -c kube-flannel` makes errors.

**Comment by ericchiang** [comment]
@willise the error is telling you to provide an argument like `kube-flannel` to your kubectl log command. That error isn't from flannel.

```
Error from server (BadRequest): a container name must be specified for pod kube-flannel-ds-hdqb4, choose one of: [kube-flannel install-cni]
```

**Comment by willise** [comment]
@ericchiang Got it and thanks.

**Comment by AlawnWong** [comment]
How to deal with this problem?

**Comment by vglisin** [comment]
Starting kubernetes and having flannel working is really a master move. I have everything done by a book for CentOS 7 but flannel gets "CrashLoopBackOff". Can you make this working? Is it possible?
