### ISSUE TITLE
flannel network state not cleaned up

### ISSUE THREAD

**Issue by xh3b4sd** [coreos/flannel#739]
## Expected Behavior
When adding network configuration to etcd Flannel picks it up and creates a lot of state, like bridges and env files and config files. When removing the state from etcd, the file system is not cleaned up nor is the bridge. I would expect Flannel to take care about a cleanup in case some network is not used anymore, but this does not happen. 

## Current Behavior
Unused/unwanted networks just stay alive as well as their corresponding state on the file system, etcd, network stack. 

## Possible Solution
It depends. Don't know about technical implementation details of Flannel at the moment. I am wondering what Flannel's API is. I have the feeling it is etcd at the moment, which is rather uncommon. Anyway, I think in case etcd is Flannel's API, creation and deletion should be supported. 

## Steps to Reproduce (for bugs)

1. Create a configuration like described in https://github.com/coreos/flannel/blob/master/Documentation/configuration.md#example-configuration-json. 
2. See Flannel do its do. 
3. Remove the configuration from etcd. 
4. See Flannel's state is kept everywhere on the file system and network stack. 

## Context
I am working on a Flannel operator and realized that the deletion part is just not a thing. I want to setup and teardown Flannel networks on demand and reuse IPs. Therefore networks for IPs I want to reuse have to be removed/cleaned. I wonder if etcd is really Flannel's API and if this is on purpose or if there are any plans to change this and provide like a HTTP API or the like. 

## Your Environment

* Flannel version: `quay.io/coreos/flannel:v0.7.1-amd64`
* Backend used (e.g. vxlan or udp): `vxlan`
* Etcd version: `quay.io/coreos/etcd:v3.1.7`
* Kubernetes version (if used): -
* Operating System and version: `CoreOS 1185.3.0 (MoreOS)`
* Link to your project (optional): https://github.com/giantswarm/flannel-operator/

**Comment by tomdee** [comment]
I don't fully understand your problem, so maybe you can add a little more detail. 

The filesystem state is only a single file.
The network stack is left up on purpose, in order to facilitate zero-downtime restart/upgrade.

I'd love to hear more about the flannel-operator that you're writing but your link above doesn't work.

**Comment by xh3b4sd** [comment]
> I don't fully understand your problem, so maybe you can add a little more detail.

You may want to ask a specific question. I was under the impression to provide a detailed description of the problem. I cannot be more specific out of thin air. 

> The filesystem state is only a single file.
> The network stack is left up on purpose, in order to facilitate zero-downtime restart/upgrade.

Even though this is only a single file it would be better to not "pollute" the server host. I fear to reuse certain configuration by accident which is not supposed to be reused because another bridge was created for the same VNI. The bottom line is, when something creates state on demand, it should be able to remove this state on demand. Keeping something across restarts/upgrades is fine. What is missing is a teardown/cleanup mechanism which an administrator can invoke via some API, whatever that API might be when talking about Flannel. 

> I'd love to hear more about the flannel-operator that you're writing but your link above doesn't work.

I just realized the project is still private. We will make it public at some point.

**Comment by calvix** [comment]
> The network stack is left up on purpose, in order to facilitate zero-downtime restart/upgrade
This creates a problem when we delete network with specific VNI and later want to use the same VNI with a different network. `flannel.x` will still have the old network and this broke flannel functionality

Is there a way how to force remove it?
