### ISSUE TITLE
kube-flannel-ds pod fails on worker nodes with a timeout when trying to reach the Service IP

### ISSUE THREAD

**Issue by ecsumed** [coreos/flannel#743]
I have an existing HA cluster with 2 masters and 2 nodes created using [the CoreOS k8 guide.](https://coreos.com/kubernetes/docs/latest/getting-started.html) Everything looks good until I try to add flannel. The problem is that the kube-flannel-ds pod on the WORKER nodes keeps failing and restarting. The kube-flannel-ds pods on the masters work fine. 

## Expected Behavior
The kube-flannel-ds pods on the worker nodes shouldn't fail.

## Current Behavior
The kube-flannel-ds pods are failing on the workers. This is the error log for one of those pods:
```
kubectl logs -f kube-flannel-ds-fxbfs -n kube-system kube-flannel
E0609 10:22:28.486911       1 main.go:127] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-fxbfs': Get https://10.3.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-fxbfs: dial tcp 10.3.0.1:443: i/o timeout
```

## Steps to Reproduce (for bugs)
1. Create a cluster using [the CoreOS k8 guide](https://coreos.com/kubernetes/docs/latest/getting-started.html)
2. Download https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
3. Replace Network with the one used in the guide "10.2.0.0/16" (I've also tried leaving the network as it is but the problem persists)
4. Then run: `kubectl apply kube-flannel.yml`
5. The created pods on the Master nodes will work fine, but the ones on the Worker nodes will start crashing.

## Context
The crashed pods (both of the crashed ones are on the worker nodes):
```
kube-flannel-ds-6xjzb                     2/2       Running            0          3h
kube-flannel-ds-fxbfs                     1/2       CrashLoopBackOff   42         3h
kube-flannel-ds-kl18n                     2/2       Running            0          3h
kube-flannel-ds-rt09q                     1/2       CrashLoopBackOff   42         3h
```

The other pods run without any issues:
```NAME                                      READY     STATUS              RESTARTS   AGE
kube-apiserver-<master-1-ip>              1/1       Running             0          31m
kube-apiserver-<master-2-ip>              1/1       Running             0          26m
kube-controller-manager-<master-1-ip>     1/1       Running             3          33m
kube-controller-manager-<master-2-ip>     1/1       Running             2          26m
kube-proxy-<master-1-ip>                  1/1       Running             0          33m
kube-proxy-<master-2-ip>                  1/1       Running             0          26m
kube-proxy-<worker-1-ip>                  1/1       Running             0          21m
kube-proxy-<worker-2-ip>                  1/1       Running             0          22m
kube-scheduler-<master-1-ip>              1/1       Running             3          33m
kube-scheduler-<master-2-ip>              1/1       Running             2          26m
```

Test pod runs without any problems as well:
```
# kubectl run test --image=tutum/curl -- sleep 10000
deployment "test" created
# kubectl get pods -o wide
NAME                    READY     STATUS    RESTARTS   AGE       IP           NODE
test-1741613794-hx8zb   1/1       Running   0          39s       172.17.0.2   <worker-1-ip>
```

etcd2 network conf:
```
ans-k8-m1 core # etcdctl get /coreos.com/network/config
{ "Network": "10.2.0.0/16" }
```

Master interfaces:
```ifconfig | grep flags -A 1
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
--
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet <ip-removed>  netmask 255.255.240.0  broadcast <bcast-removed>
--
flannel0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1472
        inet 10.2.48.0  netmask 255.255.0.0  destination 10.2.48.0
--
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
```

Worker interfaces:
```
ifconfig | grep flags -A 1
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
--
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet <ip-removed>  netmask 255.255.192.0  broadcast <bcast-removed>
--
flannel0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1472
        inet 10.2.39.0  netmask 255.255.0.0  destination 10.2.39.0
--
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
```

`nc` service IP from any of the masters:
```
# ncat 10.3.0.1 443 -v
Ncat: Version 7.12 ( https://nmap.org/ncat )
Ncat: Connected to 10.3.0.1:443
```

`nc` service IP from any of the workers:
```
# ncat 10.3.0.1 443 -v
Ncat: Version 7.12 ( https://nmap.org/ncat )
Ncat: Connection timed out.
```

## Your Environment
* CoreOS Version: 1353.8.0
* Flannel Version:
* Kubernetes version: 1.6.4
* etcd Version: 2.3.7
* Backend used (e.g. vxlan or udp): vxlan

**Comment by tomdee** [comment]
The problem is that flannel can't contact the K8s API server
` Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-fxbfs': Get https://10.3.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-fxbfs: dial tcp 10.3.0.1:443: i/o timeout`

Flannel shouldn't be using the flannel network for contacting the API server. Do you know where that IP (10.3.0.1) has come from?

Maybe try the CoreOS IRC channel for help with setting up your K8s cluster.

**Comment by tadas-subonis** [comment]
@ecsumed Did you find a solution for this?

**Comment by deimosfr** [comment]
@ecsumed have the same issue. Any solution ?

**Comment by tadas-subonis** [comment]
@ecsumed I had a problem with this because iptables where disabled on Docker.

**Comment by deimosfr** [comment]
I didn't have --iptables=false so it's not the problem. Any other idea ?

**Comment by ecsumed** [comment]
@tadas-subonis @deimosfr Nope. I retried the guide multiple times and made sure I ran it down to the dot. After about a week I moved on to [kubespray](https://github.com/kubernetes-incubator/kubespray) which worked without any hitch.

I can't recall if I tried removing `iptables=false`, but good to know.

**Comment by pmagos00** [comment]
10.3.0.1 must be the kubernetes svc.
Having the same issue, digging if is something related to RBAC ... 
For me, this issue is happening after the Node evicted all the kube-system Pods after a DiskPressure condition ...
