### ISSUE TITLE
flannel can not work on node

### ISSUE THREAD

**Issue by fatg1988** [coreos/flannel#746]
flanneld/docker version
docker-17.04.0-ce
flannel-v0.7.1-linux-amd64
4.4.71-1.el7.elrepo.x86_64

node1 
`[root@iz2ze8 k8s]# ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 192.168.31.1  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 02:42:4f:e1:46:4a  txqueuelen 0  (Ethernet)
        RX packets 17166  bytes 3295342 (3.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 17119  bytes 7264976 (6.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 192.168.31.0  netmask 255.255.255.255  broadcast 0.0.0.0
        ether 4a:26:ca:2c:f6:37  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 31  bytes 2084 (2.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.47.253   0.0.0.0         UG    0      0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eth0
172.17.32.0     0.0.0.0         255.255.240.0   U     0      0        0 eth0
192.168.0.0     0.0.0.0         255.255.0.0     U     0      0        0 flannel.1
192.168.31.0    0.0.0.0         255.255.255.0   U     0      0        0 docker0

iptables -nL
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-ISOLATION  all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0           
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */

Chain DOCKER (1 references)
target     prot opt source               destination         

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0           

`

node2
`docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.65.1  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 02:42:61:ad:bf:52  txqueuelen 0  (Ethernet)
        RX packets 100607  bytes 6264329 (5.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5778  bytes 243694 (237.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 192.168.65.0  netmask 255.255.255.255  broadcast 0.0.0.0
        ether fa:0d:7b:bd:98:76  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 31004  bytes 2200334 (2.0 MiB)
        TX errors 0  dropped 15 overruns 0  carrier 0  collisions 0

Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
default         gateway         0.0.0.0         UG        0 0          0 eth0
link-local      0.0.0.0         255.255.0.0     U         0 0          0 eth0
172.17.128.0    0.0.0.0         255.255.240.0   U         0 0          0 eth0
192.168.0.0     0.0.0.0         255.255.0.0     U         0 0          0 flannel.1
192.168.65.0    0.0.0.0         255.255.255.0   U         0 0          0 docker0

`

etcd:
` /root/local/bin/etcdctl \
>   --endpoints=${ETCD_ENDPOINTS} \
>   --ca-file=/etc/kubernetes/ssl/ca.pem \
>   --cert-file=/etc/flanneld/ssl/flanneld.pem \
>   --key-file=/etc/flanneld/ssl/flanneld-key.pem \
>   ls ${FLANNEL_ETCD_PREFIX}/subnets
2017-06-13 15:22:46.072777 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
/kubernetes/network/subnets/192.168.31.0-24
/kubernetes/network/subnets/192.168.65.0-24`

[root@ manifests]# ping 192.168.31.1
PING 192.168.31.1 (192.168.31.1) 56(84) bytes of data.
64 bytes from 192.168.31.1: icmp_seq=1 ttl=64 time=0.035 ms
64 bytes from 192.168.31.1: icmp_seq=2 ttl=64 time=0.055 ms
64 bytes from 192.168.31.1: icmp_seq=3 ttl=64 time=0.038 ms
^C
--- 192.168.31.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.035/0.042/0.055/0.011 ms
[root@iz2ze8xweru0d8hflpglrdz manifests]# ping 192.168.65.1
PING 192.168.65.1 (192.168.65.1) 56(84) bytes of data.
^C
--- 192.168.65.1 ping statistics ---
284 packets transmitted, 0 received, 100% packet loss, time 283018ms

 ip n
192.168.31.3 dev docker0 lladdr 02:42:c0:a8:1f:03 REACHABLE
192.168.31.2 dev docker0 lladdr 02:42:c0:a8:1f:02 REACHABLE
192.168.65.1 dev flannel.1 lladdr fa:0d:7b:bd:98:76 STALE
192.168.31.5 dev docker0 lladdr 02:42:c0:a8:1f:05 STALE
192.168.31.7 dev docker0 lladdr 02:42:c0:a8:1f:07 REACHABLE
192.168.31.8 dev docker0 lladdr 02:42:c0:a8:1f:08 STALE
192.168.31.6 dev docker0 lladdr 02:42:c0:a8:1f:06 REACHABLE
192.168.65.9 dev flannel.1 lladdr fa:0d:7b:bd:98:76 STALE
172.17.47.253 dev eth0 lladdr ee:ff:ff:ff:ff:ff REACHABLE
[root@manifests]# ping 192.168.65.1
PING 192.168.65.1 (192.168.65.1) 56(84) bytes of data.
^C
--- 192.168.65.1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

[root@manifests]# ip n
192.168.31.3 dev docker0 lladdr 02:42:c0:a8:1f:03 REACHABLE
192.168.31.2 dev docker0 lladdr 02:42:c0:a8:1f:02 REACHABLE
192.168.65.1 dev flannel.1 lladdr fa:0d:7b:bd:98:76 DELAY
192.168.31.5 dev docker0 lladdr 02:42:c0:a8:1f:05 STALE
192.168.31.7 dev docker0 lladdr 02:42:c0:a8:1f:07 REACHABLE
192.168.31.8 dev docker0 lladdr 02:42:c0:a8:1f:08 STALE
192.168.31.6 dev docker0 lladdr 02:42:c0:a8:1f:06 REACHABLE
192.168.65.9 dev flannel.1 lladdr fa:0d:7b:bd:98:76 STALE
172.17.47.253 dev eth0 lladdr ee:ff:ff:ff:ff:ff REACHABLE

**Comment by fatg1988** [comment]
@spacexnice 你好 这是阿里云两个账户下面的两台ecs ，是不是用ali-vpc这个类型 就可以了~~~

**Comment by tomdee** [comment]
I'm not sure what problem you're describing here. I appreciate the detailed diags, but could you describe the actual problem your seeing.
