### ISSUE TITLE
vendor/k8s.io/client-go/rest/request

### ISSUE THREAD

**Issue by anthony-joyeux** [coreos/flannel#747]
Hi, I don't know why but when I am trying to setup flannel using make dist/flanneld, I get this answer :

make dist/flanneld
go build -o dist/flanneld \
  -ldflags "-X github.com/coreos/flannel/version.Version=v0.8.0-rc1-10-g402fdde"
# github.com/coreos/flannel/vendor/k8s.io/client-go/rest
vendor/k8s.io/client-go/rest/request.go:660: req.WithContext undefined (type *http.Request has no field or method WithContext)
vendor/k8s.io/client-go/rest/request.go:732: req.WithContext undefined (type *http.Request has no field or method WithContext)
vendor/k8s.io/client-go/rest/request.go:810: req.WithContext undefined (type *http.Request has no field or method WithContext)
Makefile:45: recipe for target 'dist/flanneld' failed
make: *** [dist/flanneld] Error 2

Before doing that, I did : 
cd ~
export GOPATH=$(pwd)
mkdir -p src/github.com/coreos
cd src/github.com/coreos
git clone https://github.com/coreos/flannel.git
cd flannel

**Comment by euank** [comment]
> type *http.Request has no field or method WithContext

This method was introduced in go1.7. It seems likely you're using an old, unsupported, version of go.
