### ISSUE TITLE
docs: sync CoreOS docs to reflect flannel readme.md

### ISSUE THREAD

**Issue by zbwright** [coreos/flannel#749]
CoreOS flannel page (https://coreos.com/flannel/docs/0.7.1/) is incomplete, and should list all files linked to from the flannel ReadMe (https://github.com/coreos/flannel/blob/master/README.md). can we fix, please?

**Comment by zbwright** [comment]
@joshix I can neither assign nor label issues in this repo.

**Comment by tomdee** [comment]
@zbwright Who are you asking 😄?

**Comment by zbwright** [comment]
maybe @athai can help with this?
