### ISSUE TITLE
flannel does not generate correct ip route rules

### ISSUE THREAD

**Issue by answer1991** [coreos/flannel#751]
Hi, I use fannel to set up a virtual network for multi nodes docker cluster.

Network Config: 

````
{ "Network": "192.168.0.0/16", "Backend": {"Type": "udp"}}
````

- 1. I Run fanneld using docker container

````
$ docker run -dit --name=flannel   \
 --restart=always  \
 --net=host   \
 --privileged    \
 -v /dev/net:/dev/net    \
 -v /run/flannel:/run/flannel    \
 quay.io/coreos/flannel:v0.7.1-amd64   \
 /opt/bin/flanneld    \
 --etcd-endpoints=http://10.244.24.97:2379 \
  --ip-masq=true  \
  --iface=$(ip -o -4 addr list $(ip -o -4 route show to default | awk '{print $5}' | head -1) | awk '{print $4}' | cut -d/ -f1 | head -1)
```` 

- 2. replace "bip" and "mtu" in docker.service file

````
$ cat /run/flannel/subnet.env
FLANNEL_NETWORK=192.168.0.0/16
FLANNEL_SUBNET=192.168.38.1/24
FLANNEL_MTU=1472
FLANNEL_IPMASQ=true

$ cat /etc/systemd/system/docker.service |grep "ExecStart"
ExecStart=/usr/bin/docker daemon -H fd:// --tlsverify --tlscacert /etc/docker/ca.pem --tlscert=/etc/docker/server.pem --tlskey=/etc/docker/server-key.pem --log-opt max-size=200m  --log-opt max-file=5 -H tcp://0.0.0.0:2376  --insecure-registry=acs-reg.sqa.alipay.net  --insecure-registry=alipay.docker.io  --registry-mirror=https://ant.mirror.aliyuncs.com --cluster-store= --storage-driver=overlay --bip= 192.168.38.1/24 --mtu= 1472
````

- 3. Remove docker0 link

````
$ ip link set docker0 down
$ ip link del docker0
````

- 4. Restart Docker

````
$ systemctl daemon-reload
$ systemctl restart docker
````

After these 4 steps, the ``ip route`` result is:

````
$ ip route
default via 10.244.31.247 dev eth0
10.0.0.0/8 via 10.244.31.247 dev eth0
10.244.16.0/20 dev eth0  proto kernel  scope link  src 10.244.25.48
11.0.0.0/8 via 10.244.31.247 dev eth0
30.0.0.0/8 via 10.244.31.247 dev eth0
100.64.0.0/10 via 10.244.31.247 dev eth0
169.254.0.0/16 dev eth0  scope link  metric 1002
192.168.0.0/16 via 10.244.31.247 dev eth0
192.168.38.0/24 dev docker0  proto kernel  scope link  src 192.168.38.1
````

Then, I try to ping a container(ip: 192.168.14.2) on an another node (it set up by the same steps), FAILED:

````
$ping 192.168.14.2
PING 192.168.14.2 (192.168.14.2) 56(84) bytes of data.

...hang
````

I found the ip route rule ``192.168.0.0/16 via 10.244.31.247 dev eth0`` may be not correct. And I delete it, then add a new rule ``192.168.0.0/16 dev flannel0``.

````
$ ip route del 192.168.0.0/16 via 10.244.31.247 dev eth0
$ ip route add 192.168.0.0/16 dev flannel0
````

Then, I can ping `192.168.14.2` successfully.

````
ping 192.168.14.2
PING 192.168.14.2 (192.168.14.2) 56(84) bytes of data.
64 bytes from 192.168.14.2: icmp_seq=1 ttl=61 time=0.787 ms
64 bytes from 192.168.14.2: icmp_seq=2 ttl=61 time=0.622 ms
````

So, why the fanneld does not generate ``192.168.0.0/16 dev flannel0`` ip route rule.

## Expected Behavior

flanneld generate ``192.168.0.0/16 dev flannel0`` ip route rule.

## Current Behavior

flanneld generated ``192.168.0.0/16 via 10.244.31.247 dev eth0``, it does not work. I need delete it and add ip rule ``192.168.0.0/16 dev flannel0`` manually.

## Steps to Reproduce (for bugs)

See above

## Your Environment

* Flannel version:  v0.7.1-amd64
* Backend used (e.g. vxlan or udp): udp
* Etcd version: v3.2.0
* Kubernetes version (if used): -
* Operating System and version: alios7, likely centos7
* Link to your project (optional): -

**Comment by tomdee** [comment]
Do you know what created the bad route originally? Could you repro on a clean host and find out when that route gets created (using `ip mon`

**Comment by answer1991** [comment]
Hi @tomdee , thanks for your reply.

I found the bad route is created by the vm clone template. I re-cloned the machine and try to reproduce this issue, the ``ip route`` command result : 

````
$ ip route
default via 10.244.31.247 dev eth0
10.0.0.0/8 via 10.244.31.247 dev eth0
10.244.16.0/20 dev eth0  proto kernel  scope link  src 10.244.25.48
11.0.0.0/8 via 10.244.31.247 dev eth0
30.0.0.0/8 via 10.244.31.247 dev eth0
100.64.0.0/10 via 10.244.31.247 dev eth0
169.254.0.0/16 dev eth0  scope link  metric 1002
172.16.0.0/12 via 10.244.31.247 dev eth0
192.168.0.0/16 via 10.244.31.247 dev eth0
````

After del ``192.168.0.0/16 via 10.244.31.247 dev eth0`` rule, and create the network, then the correct route rule generated.

Thanks for your reply. I will close this issue.
