### ISSUE TITLE
Pods network traffic doesn't goes through the flannel

### ISSUE THREAD

**Issue by yurchenkosv** [coreos/flannel#753]
## Expected Behavior

I expected that pods can communicate with kubernetes api-server and dns service via kubernetes services.

## Current Behavior

At this moment, pods only can communicate with apiserver via public address, not via address, leased by flannel.
I can see that on kubernetes node: 
> docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:b6ff:fe70:c144  prefixlen 64  scopeid 0x20<link>
        ether 02:42:b6:70:c1:44  txqueuelen 0  (Ethernet)
        RX packets 1824  bytes 151812 (148.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1301  bytes 200850 (196.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

> eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.16.87  netmask 255.255.255.0  broadcast 172.16.16.255
        inet6 fe80::dc5f:b8ff:fee9:308f  prefixlen 64  scopeid 0x20<link>
        ether de:5f:b8:e9:30:8f  txqueuelen 1000  (Ethernet)
        RX packets 426959  bytes 577280770 (550.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 60500  bytes 5824859 (5.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

> flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.2.74.0  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::68a9:6ff:fe32:51d  prefixlen 64  scopeid 0x20<link>
        ether 6a:a9:06:32:05:1d  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 15 overruns 0  carrier 0  collisions 0

> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 760  bytes 38140 (37.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 760  bytes 38140 (37.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

> veth8b36a18: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet6 fe80::e0f7:ccff:fe15:ba8a  prefixlen 64  scopeid 0x20<link>
        ether e2:f7:cc:15:ba:8a  txqueuelen 0  (Ethernet)
        RX packets 1824  bytes 177348 (173.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1318  bytes 202128 (197.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

As I can understand, packets dorps on flannel.1 interface, but what with  it could be connected?
I've tried to issue iptables -P FORWARD ACCEPT command, but it is no luck. 
By now, any traffic, that needs to flow through private cluster network, couldn't reach destination.

## Your Environment

* Flannel version: 0.7.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.1.3
* Kubernetes version (if used): 1.5.7
* Operating System and version: CoreOS 1353.8.0
* In my setup, I've used [this manual](https://coreos.com/kubernetes/docs/latest/getting-started.html)

**Comment by tomdee** [comment]
Why are you trying to access the k8s-api using the the pod network? It's better to just use the host network for the API server.

**Comment by yurchenkosv** [comment]
@tomdee Thanks for your answer. Actualy, I've tried many ways to get it run. If I've specify host network it's run as I expecting, but question is no one pod can communicate with internal k8s services. And no one pod can resolve dns name of another pod because of no traffic can reach pods via pod network. This is very sad, because I've no ability to use internal k8s services and all connections with pods can only be established via host network.
It seems, that something wrong with iptables or flannel configuration, but I can't locate the problem.

**Comment by yurchenkosv** [comment]
Here is my configs, if it's might be helpfull
```
cat /etc/systemd/system/flanneld.service.d/50-network-config.conf
[Service]
Environment="FLANNELD_ETCD_PREFIX=/coreos.com/network/"
Environment="FLANNELD_IFACE=172.16.16.87"
Environment="FLANNELD_ETCD_ENDPOINTS=http://kube-test-node1:2379"
ExecStartPre="/bin/echo -e  'FLANNELD_IFACE=172.16.16.87 \nFLANNELD_ETCD_ENDPOINTS=http://kube-test-node1:2379 \nFLANNELD_ETCD_PREFIX=/coreos.com/network' > /etc/flannel/options.env"
ExecStartPre=/usr/bin/ln -sf /etc/flannel/options.env /run/flannel/options.env
```
```
cat /etc/flannel/options.env
FLANNELD_IFACE=172.16.16.87
FLANNELD_ETCD_ENDPOINTS=http://kube-test-node1:2379
```
```
cat /etc/systemd/system/docker.service.d/40-flannel.conf
[Unit]
Requires=flanneld.service
After=flanneld.service
[Service]
EnvironmentFile=/etc/kubernetes/cni/docker_opts_cni.env
```
```
cat /etc/kubernetes/cni/docker_opts_cni.env
DOCKER_OPT_BIP=""
DOCKER_OPT_IPMASQ=""
```
```
cat /etc/kubernetes/cni/net.d/10-flannel.conf
{
    "name": "podnet",
    "type": "flannel",
    "delegate": {
        "isDefaultGateway": true
    }
}
```

**Comment by tomdee** [comment]
Do you have the log output? Have you considered just using the kube-subnet-mgr?

**Comment by tomdee** [comment]
Closing stale support issue. @yurchenkosv if you're still having problems let us know.
