### ISSUE TITLE
flannel 0.7 cannot get network config from etcdv3.1.5 with api version2, how to configure flannel to use etcd v3 api

### ISSUE THREAD

**Issue by wjp719** [coreos/flannel#755]
## Your Environment

* Flannel version: 0.7
* Backend used (e.g. vxlan or udp): udp
* Etcd version: 3.1.5
* Kubernetes version (if used): 1.6.6
* Operating System and version: ubuntu 16.04
* Link to your project (optional):

the flannel log:
E0622 14:04:43.257244    6229 network.go:102] failed to retrieve network config: 100: Key not found (/coreos.com) [17]
E0622 14:04:44.261566    6229 network.go:102] failed to retrieve network config: 100: Key not found (/coreos.com) [17]
E0622 14:04:45.276585    6229 network.go:102] failed to retrieve network config: 100: Key not found (/coreos.com) [17]
E0622 14:04:46.280412    6229 network.go:102] failed to retrieve network config: 100: Key not found (/coreos.com) [17]
E0622 14:04:47.284005    6229 network.go:102] failed to retrieve network config: 100: Key not found (/coreos.com) [17]
E0622 14:04:48.309350    6229 network.go:102] failed to retrieve network config: 100: Key not found (/coreos.com) [17]

the etcd log:
Jun 22 14:04:35 master etcd[1365]: [GET] /v2/keys/coreos.com/network/config?quorum=true&recursive=false&sorted=false remote:10.10.10.4:45468

and when I use the etcdctl cdl with etcd version 3, I can get the network config

**Comment by tomdee** [comment]
Flannel currently only supports the etcdv2 API (but you can still run etcd v3.x)

**Comment by wjp719** [comment]
@tomdee Hi, in my environment, flannel cannot get the network config from etcdv3 with v2 api, does it need additional configuration in etcd or flannel, thanks

**Comment by lghinet** [comment]
same problem here

**Comment by tomdee** [comment]
@lghinet @wjp719 please open a new issue if you're still having problems

**Comment by justdigitalfilm** [comment]
Did anyone ever resolve this issue?  It seems to still be effecting Flannel 0.7.1 >> etcd 3.3.11

**Comment by xh3b4sd** [comment]
The rather unfortunate UX in this case implies that the command structure for `etcdctl` is pretty different between V2 and V3. In my case I can do something like this. Also check the changing help usage of the commands between versions. 

```
sudo ETCDCTL_API=2 etcdctl --cert-file /etc/kubernetes/ssl/etcd/etcd.pem --key-file /etc/kubernetes/ssl/etcd/etcd-key.pem --ca-file /etc/kubernetes/ssl/etcd/etcd-ca.pem --endpoints "https://127.0.0.1:2379" ls /coreos.com/network
```
