### ISSUE TITLE
docs: Add a Documentation/kubernetes.md page

### ISSUE THREAD

**Issue by luxas** [coreos/flannel#758]
## Current Behavior

Currently there is no documentation about the Kubernetes CNI integration works.
It's not obvious that you have to install RBAC rules.
The users have no idea what the `kube-flannel.yml` manifest will do, but apply it anyway.
It's nowhere stated the requirement for having `10.244.0.0/16` as the `cluster-cidr` in controller-manager's args.
etc. etc. etc.

## Expected Behavior

There should be a `kubernetes.md` page like the one Canal/Calico have: 

 - https://github.com/projectcalico/canal/blob/master/k8s-install/README.md
 - http://docs.projectcalico.org/v2.3/getting-started/kubernetes/installation/hosted/kubeadm/

## Possible Solution

I'd bundle RBAC rules by default.
I'd create proper documentation for the Kubernetes integration.

## Context

I hear about ~4 users per week that have issues trying to install Flannel on kubeadm clusters.
The absence of documentation is affecting the UX heavily and bringing both flannel and Kubernetes/kubeadm in a bad position.

## Your Environment

* Flannel version: any
* Kubernetes version (if used): any
* Link to your project (optional): kubeadm

**Comment by luxas** [comment]
Example: https://github.com/kubernetes/kubernetes.github.io/pull/2389#issuecomment-311076232

**Comment by tomdee** [comment]
@luxas Thanks for raising this. I'm working on fixing it at the moment

**Comment by tomdee** [comment]
I see that did try to get this added to the README back in April - https://github.com/coreos/flannel/issues/672#issuecomment-293684413
