### ISSUE TITLE
Flannel service errors on start: unsupported protocol scheme "" using systemd

### ISSUE THREAD

**Issue by IanLuites** [coreos/flannel#766]
## Expected Behavior
No connection errors through systemd.

## Current Behavior
Currently the following service file will fail to start `Flannel`, because it can not connect to etcd:
```
[Unit]
Description=Network fabric for containers
Documentation=https://github.com/coreos/flannel
After=etcd.service
Before=docker.service

[Service]
Type=notify
Restart=always
RestartSec=5

ExecStart=/usr/local/bin/flanneld \
  -iface=10.132.57.158 \
  -etcd-endpoints="https://10.132.57.158:2379" \
  -etcd-prefix=/kubernetes/network \
  -etcd-cafile=/lib/kubernetes/cert/ca.pem \
  -etcd-certfile=/lib/kubernetes/cert/kubernetes-etcd.pem \
  -etcd-keyfile=/lib/kubernetes/cert/kubernetes-etcd-key.pem \
  -public-ip=10.132.57.158

[Install]
WantedBy=multi-user.target
```

Starting flannel will generate following error message over and over:
```
network.go:102] failed to retrieve network config: client: etcd cluster is unavailable or misconfigured; error #0: unsupported protocol scheme ""
```

I've tested all the certificates by testing the connection to `etcd` with `curl`, `wget`, and `etcdctl`.

I also ran the following command in console and `Flannel` runs without any problems:
```
/usr/local/bin/flanneld \
  -iface=10.132.57.158 \
  -etcd-endpoints="https://10.132.57.158:2379" \
  -etcd-prefix=/kubernetes/network \
  -etcd-cafile=/lib/kubernetes/cert/ca.pem \
  -etcd-certfile=/lib/kubernetes/cert/kubernetes-etcd.pem \
  -etcd-keyfile=/lib/kubernetes/cert/kubernetes-etcd-key.pem \
  -public-ip=10.132.57.158
```
_(exactly the same as the ExecStart entry)_

## Manual Solution
I can manually start and run `Flannel` by running the follow command and everything works, but I also have to manually start docker.

```
nohup /usr/local/bin/flanneld \
  -iface=10.132.57.158 \
  -etcd-endpoints="https://10.132.57.158:2379" \
  -etcd-prefix=/kubernetes/network \
  -etcd-cafile=/lib/kubernetes/cert/ca.pem \
  -etcd-certfile=/lib/kubernetes/cert/kubernetes-etcd.pem \
  -etcd-keyfile=/lib/kubernetes/cert/kubernetes-etcd-key.pem \
  -public-ip=10.132.57.158 &
```

## My Environment
* Flannel version: 0.7.1
* vxlan
* Etcd version: 3.2.2
* Operating System and version: CentOS 7
* systemd: 219

**Comment by tomdee** [comment]
Hmmm, that seems strange. Maybe @euank has an idea? My only suggestion would be to try environment variables. https://github.com/coreos/flannel/blob/master/Documentation/configuration.md#environment-variables

**Comment by IanLuites** [comment]
Thanks for the response!

I started with replacing them with environment variables when I noticed the difference in the arguments.

I've used single `-` in stead of `--`. Funny that it parsed the arguments with single dashes when I manually entered them.

```
[Unit]
Description=Network fabric for containers
Documentation=https://github.com/coreos/flannel
After=etcd.service
Before=docker.service

[Service]
Type=notify
Restart=always
RestartSec=5

ExecStart=/usr/local/bin/flanneld \
  --iface=10.132.57.158 \
  --etcd-endpoints="https://10.132.57.158:2379" \
  --etcd-prefix=/kubernetes/network \
  --etcd-cafile=/lib/kubernetes/cert/ca.pem \
  --etcd-certfile=/lib/kubernetes/cert/kubernetes-etcd.pem \
  --etcd-keyfile=/lib/kubernetes/cert/kubernetes-etcd-key.pem \
  --public-ip=10.132.57.158

[Install]
WantedBy=multi-user.target
```

Is now working! Sorry for the trouble, I'll close it.
