### ISSUE TITLE
flannel not working with portmap plugin

### ISSUE THREAD

**Issue by wzhliang** [coreos/flannel#772]
With 0.8.0, flannel doesn't work with portmap plugin in a plugin chain

## Expected Behavior

when flannel is configured to work with portmap plugin in a chain, any container with `hostPort` should have a iptables rule setting up on the host.

## Current Behavior

No firewall rule is added. No host port available.

## Steps to Reproduce (for bugs)

1. install k8s 1.7
2. install flannel with yaml attached. basically, rename conf to conflist, config flannel to and portmap in a plugin chain
3. create a pod with `ports.hostPort` defined
4. use `wget http://node:hostPort` to test

## Your Environment

* Flannel version: 0.8.0
* Backend used (e.g. vxlan or udp): vxlan and host-gw
* Etcd version:
* Kubernetes version (if used): 1.7.0
* Operating System and version: centos 7

[flannel.txt](https://github.com/coreos/flannel/files/1148078/flannel.txt)

* Link to your project (optional):

**Comment by tomdee** [comment]
plugin chaining is a CNI concept so the issue here is most likely with the CNI plugin. It's a little confusing but the CNI plugin is actually in a different repo - it's over at https://github.com/containernetworking/plugins. So I'm going to close this issue and raise a new one over there.
