### ISSUE TITLE
ERROR  with ali-vpc backend !!!

### ISSUE THREAD

**Issue by liyehaha** [coreos/flannel#783]
error when create flannel daemonSet with ali-vpc backend on aliyun ec2.

## Steps to Reproduce (for bugs)

just create ds with config file below :
1. https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel-rbac.yml
2. https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel-aliyun.yml (with access key and secret changed)

also add service account by name flannel

## Context

I0724 13:08:39.155650       1 main.go:446] Determining IP address of default interface
I0724 13:08:39.156198       1 main.go:459] Using interface with name eth1 and address 120.55.214.170
I0724 13:08:39.157231       1 main.go:476] Defaulting external address to interface address (120.55.214.170)
I0724 13:08:39.174751       1 kube.go:130] Waiting 10m0s for node controller to sync
I0724 13:08:39.174821       1 kube.go:283] Starting kube subnet manager
I0724 13:08:40.174946       1 kube.go:137] Node controller sync successful
I0724 13:08:40.174982       1 main.go:226] Created subnet manager: Kubernetes Subnet Manager - master
I0724 13:08:40.174990       1 main.go:229] Installing signal handlers
I0724 13:08:40.175087       1 main.go:330] Found network config - Backend type: ali-vpc
I0724 13:08:40.175190       1 alivpc.go:62] Unmarshal Configure : { }
E0724 13:11:10.179244       1 main.go:256] Error registering network: Get http://100.100.100.200/latest/meta-data/region-id: dial tcp 100.100.100.200:80: i/o timeout
I0724 13:11:10.179304       1 main.go:303] Waiting for cancel to propagate...
I0724 13:11:11.179472       1 main.go:305] Exiting...

## Your Environment

* Flannel version: v0.8.0-amd64
* Backend used (e.g. vxlan or udp): ali-vpc
* Etcd version: none
* Kubernetes version (if used): 1.7.1
* Operating System and version: centos 7.3
* Link to your project (optional):

**Comment by tomdee** [comment]
@spacexnice Can you help?

**Comment by spacexnice** [comment]
Please make  sure your ECS is under VPC network environment ,this backend is only suitable for VPC network.@liyehaha
