### ISSUE TITLE
extreme low network speed

### ISSUE THREAD

**Issue by delfer** [coreos/flannel#784]
Server-Clinet (two nodes): **3.03 Mbits/sec**
Server-Clinet (same node): 9.51 Gbits/sec
Server-HostPort-Clinet speed (two nodes): 900 Mbits/sec

## Your Environment

* Flannel version: v0.6.2 / v0.8.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version:  v3.0.17
* Kubernetes version (if used): 1.6.7 / 1.7.2
* Operating System and version: Container Linux by CoreOS stable (1409.6.0)

docker inspect 9981b1ad4da1
```
[
    {
        "Id": "9981b1ad4da1c01f9d852d7f27ef57292be3399d266c7e6bbd646b324534eb37",
        "Created": "2017-07-19T19:26:54.796807292Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "/opt/bin/flanneld -etcd-endpoints https://10.57.47.13:2379 -etcd-prefix /cluster.local/network -etcd-cafile /etc/flannel/certs/ca_cert.crt -etcd-certfile /etc/flannel/certs/cert.crt -etcd-keyfile /etc/flannel/certs/key.pem  -public-ip 10.57.47.12"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1435,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-07-19T19:26:56.707365307Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:5094347281dcc2993c6861c543d455bb1ad5ee8d70bcbc47eea5aa73ea8e6dac",
        "ResolvConfPath": "/var/lib/docker/containers/6fc8afe8df92e2016dcaeefff286c47a6a69a8eeddd6b30bc8cd2272da7ea44b/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/6fc8afe8df92e2016dcaeefff286c47a6a69a8eeddd6b30bc8cd2272da7ea44b/hostname",
        "HostsPath": "/var/lib/docker/containers/6fc8afe8df92e2016dcaeefff286c47a6a69a8eeddd6b30bc8cd2272da7ea44b/hosts",
        "LogPath": "/var/lib/docker/containers/9981b1ad4da1c01f9d852d7f27ef57292be3399d266c7e6bbd646b324534eb37/9981b1ad4da1c01f9d852d7f27ef57292be3399d266c7e6bbd646b324534eb37-json.log",
        "Name": "/k8s_flannel-container_flannel-terraform-k8s-node-nf-2_kube-system_a63b9792ea2842034f245a8693c20d30_4",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "system_u:object_r:svirt_lxc_file_t:s0:c276,c708",
        "ProcessLabel": "system_u:system_r:svirt_lxc_net_t:s0:c276,c708",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/run/flannel:/run/flannel",
                "/etc/flannel/certs:/etc/flannel/certs:ro",
                "/var/lib/kubelet/pods/a63b9792ea2842034f245a8693c20d30/containers/flannel-container/8d6574c1:/dev/termination-log:Z"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "container:6fc8afe8df92e2016dcaeefff286c47a6a69a8eeddd6b30bc8cd2272da7ea44b",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "container:6fc8afe8df92e2016dcaeefff286c47a6a69a8eeddd6b30bc8cd2272da7ea44b",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 997,
            "PidMode": "",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "seccomp=unconfined"
            ],
            "UTSMode": "host",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 153,
            "Memory": 500000000,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 100000,
            "CpuQuota": 30000,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 1000000000,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/var/lib/docker/overlay/73b04db248dc08483dc881c9eed6cf0d2e74143a98522b3e3addde2a7cad6f35/root",
                "MergedDir": "/var/lib/docker/overlay/4672f8afbabe61ba5701de015db8f92095e24d3a02a0b0193416041db2ebb9f2/merged",
                "UpperDir": "/var/lib/docker/overlay/4672f8afbabe61ba5701de015db8f92095e24d3a02a0b0193416041db2ebb9f2/upper",
                "WorkDir": "/var/lib/docker/overlay/4672f8afbabe61ba5701de015db8f92095e24d3a02a0b0193416041db2ebb9f2/work"
            }
        },
        "Mounts": [
            {
                "Source": "/run/flannel",
                "Destination": "/run/flannel",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/etc/flannel/certs",
                "Destination": "/etc/flannel/certs",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Source": "/var/lib/kubelet/pods/a63b9792ea2842034f245a8693c20d30/containers/flannel-container/8d6574c1",
                "Destination": "/dev/termination-log",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "terraform-k8s-node-nf-2.novalocal",
            "Domainname": "",
            "User": "0",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "KUBE_DNS_PORT=udp://10.233.0.3:53",
                "KUBE_DNS_PORT_53_TCP=tcp://10.233.0.3:53",
                "TILLER_DEPLOY_SERVICE_PORT=44134",
                "DEFAULT_HTTP_BACKEND_SERVICE_HOST=10.233.42.220",
                "DEFAULT_HTTP_BACKEND_SERVICE_PORT=80",
                "KUBERNETES_SERVICE_HOST=10.233.0.1",
                "KUBE_REGISTRY_PORT=tcp://10.233.61.61:5000",
                "KUBE_REGISTRY_PORT_5000_TCP_PORT=5000",
                "KUBE_DNS_PORT_53_UDP_PROTO=udp",
                "TILLER_DEPLOY_SERVICE_HOST=10.233.38.254",
                "KUBERNETES_PORT_443_TCP_PROTO=tcp",
                "KUBE_DNS_SERVICE_PORT=53",
                "KUBE_DNS_PORT_53_UDP=udp://10.233.0.3:53",
                "KUBE_REGISTRY_SERVICE_PORT=5000",
                "KUBE_DNS_PORT_53_TCP_PORT=53",
                "DEFAULT_HTTP_BACKEND_PORT_80_TCP_PROTO=tcp",
                "KUBE_DNS_PORT_53_UDP_PORT=53",
                "KUBE_DNS_PORT_53_UDP_ADDR=10.233.0.3",
                "TILLER_DEPLOY_SERVICE_PORT_TILLER=44134",
                "TILLER_DEPLOY_PORT_44134_TCP=tcp://10.233.38.254:44134",
                "DEFAULT_HTTP_BACKEND_PORT_80_TCP_PORT=80",
                "KUBERNETES_SERVICE_PORT=443",
                "KUBE_REGISTRY_PORT_5000_TCP_PROTO=tcp",
                "KUBE_DNS_SERVICE_PORT_DNS=53",
                "TILLER_DEPLOY_PORT_44134_TCP_ADDR=10.233.38.254",
                "DEFAULT_HTTP_BACKEND_PORT_80_TCP_ADDR=10.233.42.220",
                "KUBERNETES_PORT=tcp://10.233.0.1:443",
                "KUBE_REGISTRY_PORT_5000_TCP_ADDR=10.233.61.61",
                "KUBE_DNS_PORT_53_TCP_PROTO=tcp",
                "KUBE_REGISTRY_SERVICE_HOST=10.233.61.61",
                "KUBE_DNS_SERVICE_PORT_DNS_TCP=53",
                "KUBE_DNS_PORT_53_TCP_ADDR=10.233.0.3",
                "DEFAULT_HTTP_BACKEND_PORT=tcp://10.233.42.220:80",
                "TILLER_DEPLOY_PORT=tcp://10.233.38.254:44134",
                "TILLER_DEPLOY_PORT_44134_TCP_PROTO=tcp",
                "TILLER_DEPLOY_PORT_44134_TCP_PORT=44134",
                "KUBERNETES_PORT_443_TCP_ADDR=10.233.0.1",
                "KUBE_REGISTRY_SERVICE_PORT_REGISTRY=5000",
                "KUBE_REGISTRY_PORT_5000_TCP=tcp://10.233.61.61:5000",
                "KUBE_DNS_SERVICE_HOST=10.233.0.3",
                "DEFAULT_HTTP_BACKEND_PORT_80_TCP=tcp://10.233.42.220:80",
                "KUBERNETES_SERVICE_PORT_HTTPS=443",
                "KUBERNETES_PORT_443_TCP=tcp://10.233.0.1:443",
                "KUBERNETES_PORT_443_TCP_PORT=443",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "quay.io/coreos/flannel@sha256:03b0d14e3cb5013825cb73101b1686c39ccad5fd980b232e9efaa311c854f7af",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "/opt/bin/flanneld -etcd-endpoints https://10.57.47.13:2379 -etcd-prefix /cluster.local/network -etcd-cafile /etc/flannel/certs/ca_cert.crt -etcd-certfile /etc/flannel/certs/cert.crt -etcd-keyfile /etc/flannel/certs/key.pem  -public-ip 10.57.47.12"
            ],
            "OnBuild": null,
            "Labels": {
                "annotation.io.kubernetes.container.hash": "4127a72b",
                "annotation.io.kubernetes.container.ports": "[{\"hostPort\":10253,\"containerPort\":10253,\"protocol\":\"TCP\"}]",
                "annotation.io.kubernetes.container.restartCount": "4",
                "annotation.io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
                "annotation.io.kubernetes.container.terminationMessagePolicy": "File",
                "annotation.io.kubernetes.pod.terminationGracePeriod": "30",
                "io.kubernetes.container.logpath": "/var/log/pods/a63b9792ea2842034f245a8693c20d30/flannel-container_4.log",
                "io.kubernetes.container.name": "flannel-container",
                "io.kubernetes.docker.type": "container",
                "io.kubernetes.pod.name": "flannel-terraform-k8s-node-nf-2",
                "io.kubernetes.pod.namespace": "kube-system",
                "io.kubernetes.pod.uid": "a63b9792ea2842034f245a8693c20d30",
                "io.kubernetes.sandbox.id": "6fc8afe8df92e2016dcaeefff286c47a6a69a8eeddd6b30bc8cd2272da7ea44b"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": null,
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": null
        }
    }
]
```

iperf server
`core@terraform-k8s-node-nf-1 ~ $ docker run  -d --name=iperf3-server -p 5201:5201 networkstatic/iperf3 -s
`

Server-Clinet (on other node)
**10.233.91.6** - Container's IP

> core@terraform-k8s-node-nf-2 ~ $ docker run  -it --rm networkstatic/iperf3 -c 10.233.91.6
> Connecting to host 10.233.91.6, port 5201
> [  4] local 10.233.82.5 port 36766 connected to 10.233.91.6 port 5201
> [ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
> [  4]   0.00-1.00   sec  52.7 KBytes   431 Kbits/sec   15   2.63 KBytes
> [  4]   1.00-2.00   sec   158 KBytes  1.30 Mbits/sec   65   2.63 KBytes
> [  4]   2.00-3.00   sec   424 KBytes  3.47 Mbits/sec  164   2.63 KBytes
> [  4]   3.00-4.00   sec   467 KBytes  3.83 Mbits/sec  162   2.63 KBytes
> [  4]   4.00-5.00   sec   427 KBytes  3.49 Mbits/sec  164   2.63 KBytes
> [  4]   5.00-6.00   sec   428 KBytes  3.51 Mbits/sec  164   2.63 KBytes
> [  4]   6.00-7.00   sec   466 KBytes  3.82 Mbits/sec  160   2.63 KBytes
> [  4]   7.00-8.00   sec   421 KBytes  3.45 Mbits/sec  162   2.63 KBytes
> [  4]   8.00-9.00   sec   462 KBytes  3.78 Mbits/sec  166   2.63 KBytes
> [  4]   9.00-10.00  sec   465 KBytes  3.81 Mbits/sec  158   2.63 KBytes
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bandwidth       Retr
> [  4]   0.00-10.00  sec  3.68 MBytes  3.09 Mbits/sec  1380             sender
> [  4]   0.00-10.00  sec  3.62 MBytes  3.03 Mbits/sec                  receiver
> 
> iperf Done.

Server-Clinet (same node)
**10.233.91.6** - Container's IP

> core@terraform-k8s-node-nf-1 ~ $  docker run  -it --rm networkstatic/iperf3 -c 10.233.91.6
> Connecting to host 10.233.91.6, port 5201
> [  4] local 10.233.91.7 port 34220 connected to 10.233.91.6 port 5201
> [ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
> [  4]   0.00-1.00   sec  1023 MBytes  8.58 Gbits/sec    0    852 KBytes
> [  4]   1.00-2.00   sec  1.13 GBytes  9.74 Gbits/sec    0   1.06 MBytes
> [  4]   2.00-3.00   sec  1.16 GBytes  9.93 Gbits/sec    0   1.06 MBytes
> [  4]   3.00-4.00   sec   984 MBytes  8.26 Gbits/sec    0   1.06 MBytes
> [  4]   4.00-5.00   sec  1.11 GBytes  9.53 Gbits/sec    0   1.06 MBytes
> [  4]   5.00-6.00   sec  1.16 GBytes  9.98 Gbits/sec    0   1.17 MBytes
> [  4]   6.00-7.00   sec  1.11 GBytes  9.52 Gbits/sec    0   1.23 MBytes
> [  4]   7.00-8.00   sec  1.15 GBytes  9.89 Gbits/sec    0   1.23 MBytes
> [  4]   8.00-9.00   sec  1.14 GBytes  9.82 Gbits/sec    0   1.23 MBytes
> [  4]   9.00-10.00  sec  1.15 GBytes  9.88 Gbits/sec    0   1.23 MBytes
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bandwidth       Retr
> [  4]   0.00-10.00  sec  11.1 GBytes  9.51 Gbits/sec    0             sender
> [  4]   0.00-10.00  sec  11.1 GBytes  9.51 Gbits/sec                  receiver
> 
> iperf Done.

Server-HostPort-Clinet
**10.57.47.15** - host's IP

> core@terraform-k8s-node-nf-2 ~ $ docker run  -it --rm networkstatic/iperf3 -c 10.57.47.15
> Connecting to host 10.57.47.15, port 5201
> [  4] local 10.233.82.5 port 59426 connected to 10.57.47.15 port 5201
> [ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
> [  4]   0.00-1.00   sec   110 MBytes   920 Mbits/sec    0   2.99 MBytes
> [  4]   1.00-2.00   sec   108 MBytes   902 Mbits/sec    0   2.99 MBytes
> [  4]   2.00-3.00   sec   109 MBytes   912 Mbits/sec    0   2.99 MBytes
> [  4]   3.00-4.00   sec   108 MBytes   902 Mbits/sec    0   2.99 MBytes
> [  4]   4.00-5.00   sec   108 MBytes   902 Mbits/sec    0   2.99 MBytes
> [  4]   5.00-6.00   sec   108 MBytes   902 Mbits/sec    0   2.99 MBytes
> [  4]   6.00-7.00   sec   108 MBytes   902 Mbits/sec    0   2.99 MBytes
> [  4]   7.00-8.00   sec   109 MBytes   912 Mbits/sec    0   2.99 MBytes
> [  4]   8.00-9.00   sec   108 MBytes   901 Mbits/sec    0   2.99 MBytes
> [  4]   9.00-10.00  sec   108 MBytes   903 Mbits/sec    0   2.99 MBytes
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bandwidth       Retr
> [  4]   0.00-10.00  sec  1.05 GBytes   906 Mbits/sec    0             sender
> [  4]   0.00-10.00  sec  1.05 GBytes   905 Mbits/sec                  receiver
> 
> iperf Done.

**Comment by delfer** [comment]
With `host-gw` and fix from https://github.com/kubernetes-incubator/kubespray/blob/master/docs/openstack.md

> core@test-k8s-node-nf-2 ~ $ docker run -it --rm networkstatic/iperf3 -c 10.233.77.4
> Connecting to host 10.233.77.4, port 5201
> [  4] local 10.233.100.3 port 36420 connected to 10.233.77.4 port 5201
> [ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
> [  4]   0.00-1.00   sec  98.3 MBytes   825 Mbits/sec    4    376 KBytes
> [  4]   1.00-2.00   sec   106 MBytes   886 Mbits/sec   33    537 KBytes
> [  4]   2.00-3.00   sec   104 MBytes   873 Mbits/sec    0    660 KBytes
> [  4]   3.00-4.00   sec   105 MBytes   882 Mbits/sec    0    767 KBytes
> [  4]   4.00-5.00   sec   108 MBytes   904 Mbits/sec    0    862 KBytes
> [  4]   5.00-6.00   sec   107 MBytes   898 Mbits/sec    0    946 KBytes
> [  4]   6.00-7.00   sec   106 MBytes   891 Mbits/sec    0   1.00 MBytes
> [  4]   7.00-8.00   sec   107 MBytes   901 Mbits/sec  158   1.07 MBytes
> [  4]   8.00-9.00   sec   108 MBytes   902 Mbits/sec    0   1.14 MBytes
> [  4]   9.00-10.00  sec   109 MBytes   912 Mbits/sec    0   1.20 MBytes
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bandwidth       Retr
> [  4]   0.00-10.00  sec  1.03 GBytes   887 Mbits/sec  195             sender
> [  4]   0.00-10.00  sec  1.03 GBytes   885 Mbits/sec                  receiver
> 
> iperf Done.

**Comment by delfer** [comment]
With `udp`

> core@testing-k8s-node-nf-2 ~ $ docker run -it --rm networkstatic/iperf3 -c 10.233.76.4
> Connecting to host 10.233.76.4, port 5201
> [  4] local 10.233.65.3 port 56772 connected to 10.233.76.4 port 5201
> [ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
> [  4]   0.00-1.00   sec  9.97 MBytes  83.6 Mbits/sec    9    139 KBytes      
> [  4]   1.00-2.00   sec  7.31 MBytes  61.3 Mbits/sec   23   77.6 KBytes      
> [  4]   2.00-3.00   sec  9.33 MBytes  78.3 Mbits/sec   12    106 KBytes      
> [  4]   3.00-4.00   sec  10.4 MBytes  87.5 Mbits/sec   15    103 KBytes      
> [  4]   4.00-5.00   sec  7.80 MBytes  65.3 Mbits/sec   14   87.0 KBytes      
> [  4]   5.00-6.00   sec  9.46 MBytes  79.4 Mbits/sec    7   82.9 KBytes      
> [  4]   6.00-7.00   sec  8.90 MBytes  74.7 Mbits/sec    5    108 KBytes      
> [  4]   7.00-8.00   sec  8.68 MBytes  72.8 Mbits/sec   15   88.3 KBytes      
> [  4]   8.00-9.00   sec  8.97 MBytes  75.2 Mbits/sec    3   89.6 KBytes      
> [  4]   9.00-10.00  sec  9.52 MBytes  79.8 Mbits/sec    6   91.0 KBytes      
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bandwidth       Retr
> [  4]   0.00-10.00  sec  90.4 MBytes  75.8 Mbits/sec  109             sender
> [  4]   0.00-10.00  sec  90.1 MBytes  75.6 Mbits/sec                  receiver
> 
> iperf Done.

**Comment by delfer** [comment]
With vxlan and flannel v0.8.0

> core@testing-k8s-node-nf-2 ~ $ docker run -it --rm networkstatic/iperf3 -c 10.233.126.4
> Connecting to host 10.233.126.4, port 5201
> [  4] local 10.233.89.3 port 51086 connected to 10.233.126.4 port 5201
> [ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
> [  4]   0.00-1.00   sec  52.7 KBytes   430 Kbits/sec   17   2.63 KBytes
> [  4]   1.00-2.00   sec   411 KBytes  3.37 Mbits/sec  154   2.63 KBytes
> [  4]   2.00-3.00   sec   432 KBytes  3.54 Mbits/sec  154   2.63 KBytes
> [  4]   3.00-4.00   sec   424 KBytes  3.47 Mbits/sec  158   2.63 KBytes
> [  4]   4.00-5.00   sec   421 KBytes  3.45 Mbits/sec  160   2.63 KBytes
> [  4]   5.00-6.00   sec   427 KBytes  3.49 Mbits/sec  162   2.63 KBytes
> [  4]   6.00-7.00   sec   469 KBytes  3.84 Mbits/sec  162   2.63 KBytes
> [  4]   7.00-8.00   sec   424 KBytes  3.47 Mbits/sec  160   2.63 KBytes
> [  4]   8.00-9.00   sec   432 KBytes  3.54 Mbits/sec  164   2.63 KBytes
> [  4]   9.00-10.00  sec   429 KBytes  3.52 Mbits/sec  162   2.63 KBytes
> - - - - - - - - - - - - - - - - - - - - - - - - -
> [ ID] Interval           Transfer     Bandwidth       Retr
> [  4]   0.00-10.00  sec  3.83 MBytes  3.21 Mbits/sec  1453             sender
> [  4]   0.00-10.00  sec  3.79 MBytes  3.18 Mbits/sec                  receiver
> 
> iperf Done.

**Comment by philips** [comment]
What environment (aws, azure, etc)? Does ` ethtool -K eth0 tx off sg off tso off` help?

**Comment by delfer** [comment]
@philips My environment is OpenStack with vxlan Neutron. I will check **ethtool**.

**Comment by tomdee** [comment]
Closing this support issue without further diags/info
