### ISSUE TITLE
Wrong mountpoins for etc-ssl-certs volume in flannel-wrapper for coreos-stable-1409-7-0-v20170719, distributed on GCE

### ISSUE THREAD

**Issue by Unb0rn** [coreos/flannel#788]
Seems like mountpoint for etc-ssl-certs volume, specified in flannel-wrapper is wrong:
`        --volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true \` 
`        --volume usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true \` 
It's duplicated with usr-share-certs volume, which prevents /etc/ssl/certs to be mounted properly.
## Expected Behavior

Mount usr-share-certs volume as /usr/share/ca-certificates and etc-ssl-certs as /etc/ssl/certs

## Possible Solution

Fix flannel-wrapper typo?

## Steps to Reproduce (for bugs)

1.Start flanneld with ssl support on coreos-stable-1409-7-0-v20170719 on GCE
2.Check flannel-wrapper
3.
4.

## Your Environment

* Flannel version:0.8.0-amd64
* Backend used (e.g. vxlan or udp):gce
* Etcd version:3.2
* Kubernetes version (if used):
* Operating System and version:coreos-stable-1409-7-0-v20170719
* Link to your project (optional):

**Comment by gunjan5** [comment]
@Unb0rn seems like it's fixed in this commit https://github.com/coreos/coreos-overlay/commit/e9eeca8d90023441703b18c49e29769299a86348
and flannel-wrapper is in a different repo :)
