### ISSUE TITLE
Cannot start flanneld with Kubernetes API server (instead of etcd)

### ISSUE THREAD

**Issue by minhdanh** [coreos/flannel#792]
I'm trying to start flanneld with Kubernetes API server instead of using etcd, as the document suggests. Here's my systemd file for flanneld:

```
[Unit]
Description=flannel - network fabric for containers
Documentation=https://github.com/coreos/flannel
After=network.target
After=network-online.target
Wants=network-online.target
Before=docker.service

[Service]
Type=notify
ExecStart=/usr/bin/flanneld \
  --public-ip={{ ansible_eth0.ipv4.address }} \
  --ip-masq \
  --kube-api-url=https://{{ hostvars[groups['k8s-controller'][0]].ansible_eth0.ipv4.address }}:8080 \
  --kube-subnet-mgr \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service
```

## Current Behavior
When systemd starts flannel, it exits right away with the following output:

```
Aug  9 13:47:10 k8s-node-1 systemd[1]: Starting flannel is a network fabric for containers, designed for Kubernetes...
Aug  9 13:47:10 k8s-node-1 flanneld[10463]: I0809 13:47:10.231225   10463 main.go:446] Determining IP address of default interface
Aug  9 13:47:10 k8s-node-1 flanneld[10463]: I0809 13:47:10.232058   10463 main.go:459] Using interface with name eth1 and address xxx.xxx.xxx.xxx
Aug  9 13:47:10 k8s-node-1 flanneld[10463]: I0809 13:47:10.232301   10463 main.go:472] Using 10.5.xxx.xxx as external address
Aug  9 13:47:10 k8s-node-1 flanneld[10463]: E0809 13:47:10.232864   10463 main.go:223] Failed to create SubnetManager: env variables POD_NAME and POD_NAMESPACE must be set
Aug  9 13:47:10 k8s-node-1 systemd[1]: flanneld.service: Main process exited, code=exited, status=1/FAILURE
Aug  9 13:47:10 k8s-node-1 systemd[1]: Failed to start flannel is a network fabric for containers, designed for Kubernetes.
Aug  9 13:47:10 k8s-node-1 systemd[1]: flanneld.service: Unit entered failed state.
Aug  9 13:47:10 k8s-node-1 systemd[1]: flanneld.service: Failed with result 'exit-code'.
```

I'm not starting flannel in a pod. Why is flanneld asking for env vars `POD_NAME` and `POD_NAMESPACE` here?

## Your Environment

* Flannel version: v0.8.0
* Kubernetes version (if used): 1.7.3
* Operating System and version: Ubuntu 16.04

**Comment by tomdee** [comment]
Flannel needs to interact with the K8s API server. When running as a pod it can be given permission to access those details. I did add some experimental support for running outside a pod, but it's not currently documented (and may never be). If you want to try to understand it, you can look at the change - https://github.com/coreos/flannel/commit/c9970d056974bc8c8ffa782c2eb07478ae61e3d8 in particular, see that it's possible to pass in a kube-config file - https://github.com/coreos/flannel/commit/c9970d056974bc8c8ffa782c2eb07478ae61e3d8#diff-7ddfb3e035b42cd70649cc33393fe32cR106 and the need to specify the node name as an environment variable - https://github.com/coreos/flannel/commit/c9970d056974bc8c8ffa782c2eb07478ae61e3d8#diff-a279837d654920d2f60c5ac4db8c2401R96

**Comment by minhdanh** [comment]
Thank you

**Comment by little-dude** [comment]
> When running as a pod it can be given permission to access those details. I did add some experimental support for running outside a pod, but it's not currently documented (and may never be)

@tomdee so running flannel as a systemd service is not supported? Or is it just `--kube-subnet-mgr` that is not supported when running flannel as a systemd service?

**Comment by little-dude** [comment]
Alright that seems to work. For posterity, here is my flannel service file:

```ini
# /etc/systemd/system/flannel.service

[Unit]
Description=Network fabric for containers
Documentation=https://github.com/coreos/flannel
After=network.target
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
Restart=always
RestartSec=5
# This is needed because of this: https://github.com/coreos/flannel/issues/792
# Kubernetes knows the nodes by their FQDN so we have to use the FQDN
Environment=NODE_NAME=my-node.foo.bar.com
# Note that we don't specify any etcd option. This is because we want to talk
# to the apiserver instead. The apiserver then talks to etcd on flannel's
# behalf.
ExecStart=/opt/bin/flanneld \
  --kube-subnet-mgr=true \
  --kubeconfig-file=/etc/kube-flannel/kube.config.yml \
  --v=1 \
  --ip-masq=true \
  --iface=eth0
```

**Comment by johanot** [comment]
@little-dude @tomdee Had I similar issue yesterday which I fixed by setting `NODE_NAME`, but this leads to a follow-up question: Is flannel restricted to run only on nodes which has a kubelet running? 
I now get: `Error registering network: failed to acquire lease: node "master" not found`

Before switching from etcd to kubernetes configuration backend, I had flannel running on my k8s master node, which haven't got an active kubelet service on it - i.e. the master node is not a cluster node as such.

**Comment by zhangguanzhang** [comment]
@minhdanh  @johanot @little-dude I also want to run the flanneld with Kubernetes API server, I want to know if you have succeeded.

**Comment by johanot** [comment]
@zhangguanzhang I did. Setting `NODE_NAME` solved the issues I had. But no-one responded to my followup question :-) I just ended up running a kubelet on all nodes, and tainted it Unschedulable when I didn't want any pods.

**Comment by little-dude** [comment]
@zhangguanzhang yes see my service file above.

**Comment by zhangguanzhang** [comment]
@johanot @minhdanh I see there has files `net-conf.json` and the `cni-conf.json` at the `kube-flannel.yml`, should I touch the file and write the same word in the two files when I use the systemd?

**Comment by zhangguanzhang** [comment]
I have run successfully. Thanks

**Comment by zhangguanzhang** [comment]
@little-dude I found the command is always hung when I use the command of the `systemctl restart flanneld`
