### ISSUE TITLE
k8s: response package from flannel0 cannot send out

### ISSUE THREAD

**Issue by zengbiao** [coreos/flannel#793]
## Expected Behavior

response package (eg: dns response) can send out via eth0

## Current Behavior

DNS query--->eth0-->flannel0--->docker0--->k8sdns
-------------------- x--flannel0 <---docker0<---|

This mean "tcpdump -i eth0  -n udp port 8285 " not print any package send from local pc, only have 
packages send to local pc.
eg:

> 09:49:30.547665 IP 172.31.11.139.8285 > 172.31.11.78.8285: UDP, length 93
> 09:49:30.547715 IP 172.31.11.139.8285 > 172.31.11.78.8285: UDP, length 93

**I have set "iptable -P FORWARD ACCEPT"**

> root@euca-172-31-11-78:~# iptables -nvL
> Chain INPUT (policy ACCEPT 85 packets, 34529 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
> 32733 7446K KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 32779 7464K KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
> 
> Chain FORWARD (policy ACCEPT 14 packets, 1302 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
>  361K   53M DOCKER-ISOLATION  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
>  298K   48M ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
> 53097 4437K DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
> 10340 1086K ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
> 50134 4197K ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           
> 
> Chain OUTPUT (policy ACCEPT 70 packets, 6826 bytes)
>  pkts bytes target     prot opt in     out     source               destination         
> 31419   15M KUBE-FIREWALL  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 31473   15M KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
> 
> Chain DOCKER (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
> 
> Chain DOCKER-ISOLATION (1 references)
>  pkts bytes target     prot opt in     out     source               destination         
>  361K   53M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
> 
> Chain KUBE-FIREWALL (2 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000
> 
> Chain KUBE-SERVICES (2 references)
>  pkts bytes target     prot opt in     out     source               destination         
>     0     0 REJECT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* ns-cdc/cdc-svc-mq:mq-port has no endpoints */ ADDRTYPE match dst-type LOCAL tcp dpt:30301 reject-with icmp-port-unreachable
>     0     0 REJECT     tcp  --  *      *       0.0.0.0/0            192.168.3.5          /* ns-cdc/cdc-svc-mq:mq-port has no endpoints */ tcp dpt:80 reject-with icmp-port-unreachable
> root@euca-172-31-11-78:~# 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I don't know what happed, i was ok yesterday, but not worked today.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

**Comment by tomdee** [comment]
@zengbiao Did you manage to resolve this? Without more information I don't think I can help.
