### ISSUE TITLE
Inconsistency in iptables after upgrade

### ISSUE THREAD

**Issue by simonklb** [coreos/flannel#797]
When upgrading flannel from 0.7.1 to 0.8.0, specifically to get [this patch](https://github.com/coreos/flannel/pull/745), I noticed that one host didn't work as expected (the source IP was not preserved in the requests).

I compared the iptables on a working host to the faulty one and discovered what was wrong. In the faulty host the POSTROUTING rules looked like this:
```
-A POSTROUTING -s 10.2.0.0/16 -d 10.2.0.0/16 -j RETURN
-A POSTROUTING -s 10.2.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
-A POSTROUTING ! -s 10.2.0.0/16 -d 10.2.0.0/16 -j MASQUERADE
-A POSTROUTING ! -s 10.2.0.0/16 -d 10.2.100.0/24 -j RETURN
```
I flipped the new `RETURN` rule so that they looked like this:
```
-A POSTROUTING ! -s 10.2.0.0/16 -d 10.2.100.0/24 -j RETURN
-A POSTROUTING -s 10.2.0.0/16 -d 10.2.0.0/16 -j RETURN
-A POSTROUTING -s 10.2.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
-A POSTROUTING ! -s 10.2.0.0/16 -d 10.2.0.0/16 -j MASQUERADE
```

And everything started working as intended. 

When upgrading flannel from one version to another, are you supposed to flush the iptables or is this a bug?

CoreOS: 1409.9.0
Kubernetes: 1.6.4

**Comment by tomdee** [comment]
Should be fixed in v0.9.0
