### ISSUE TITLE
Problem manually setting up single node flannel v0.8.0-amd64 cluster

### ISSUE THREAD

**Issue by vnalla** [coreos/flannel#798]
I am trying to setup a single node Kubernetes cluster on Ubuntu 16.04 using docker containers, hyperkube for kubernetes and https://quay.io/repository/coreos/flannel?tag=v0.8.0-amd64&tab=tags for flannel. I had a setup which is working, which was using etcd, flannel, and kubernetes processes setup as services in which flannel depends on etcd, and docker depends on flannel. Trying to setup via containers and not able to get flannel working, ran in to multiple issues. Currently I am stuck with the following error messages. Need help with the correct instructions on how to setup flannel overlay network with out using etcd and via dockerized flannel container.

2017-08-21T13:39:08.234445293Z I0821 13:39:08.234212       1 main.go:446] Determining IP address of default interface
2017-08-21T13:39:08.234583658Z I0821 13:39:08.234521       1 main.go:459] Using interface with name enp0s3 and address 10.0.2.15
2017-08-21T13:39:08.23459441Z I0821 13:39:08.234554       1 main.go:476] Defaulting external address to interface address (10.0.2.15)
## Your Environment

* Flannel version: v0.8.0-amd64 (https://quay.io/repository/coreos/flannel?tag=v0.8.0-amd64&tab=tags)
* Backend used (e.g. vxlan or udp): vxlan - using kube-flannel.yaml (https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml)
* Etcd version:
* Kubernetes version (if used): 1.6.8_coreos.0 (hyperkube)
* Operating System and version: Ubuntu 16.04
* Link to your project (optional):

Thanks for your time and help.

**Comment by vnalla** [comment]
flannel daemon set is failing. appreciate your help. thanks

{"log":"E0822 00:28:17.613136       1 config.go:265] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory\n","stream":"stderr","time":"2017-08-22T00:28:17.613518972Z"}
{"log":"E0822 00:28:47.615504       1 main.go:127] Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-hrnm2': Get https://10.254.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-hrnm2: dial tcp 10.254.0.1:443: i/o timeout\n","stream":"stderr","time":"2017-08-22T00:28:47.615694906Z"}

**Comment by oilbeater** [comment]
https://github.com/coreos/flannel/commit/53d1855d7eead6e519f43b75cec725b2121e3557
fix this, but flannel doesn't release a new image. You can build you own image by base from flannel:v0.8.0 add add the CA.

**Comment by gwind** [comment]
@vnalla I've install flannel daemonset successful, you can saw my steps in
https://github.com/kubernetes/kubernetes/issues/51881

**Comment by vnalla** [comment]
@gwind Thanks for the information. Yes it deploy flannel and starts cni0 upon deploying the first pod. But the pods are not talking to the pod network. kubedns  and dashboard are in endless crash loop because they can not talk to apiserver. Tried the trouble shooting as suggested in https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md, the test pod give no route to host error, however curl from host machine is able to connect.

`kubectl exec test-1741613794-lvj32 -- curl -k https://10.253.0.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 10.253.0.1 port 443: No route to host
`
`kubectl get services
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   10.253.0.1   <none>        443/TCP   21h
`
`curl -k https://10.253.0.1
Unauthorized
`
`TOKEN_VALUE=$(kubectl exec test-1741613794-lvj32 -- cat /var/run/secrets/kubernetes.io/serviceaccount/token)

curl --cacert /srv/kubernetes/ca.crt -H  "Authorization: Bearer $TOKEN_VALUE" https://10.253.0.1
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/apps",
    "/apis/apps/v1beta1",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/autoscaling/v2alpha1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v2alpha1",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1beta1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/policy",
    "/apis/policy/v1beta1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1alpha1",
    "/apis/rbac.authorization.k8s.io/v1beta1",
    "/apis/settings.k8s.io",
    "/apis/settings.k8s.io/v1alpha1",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1",
    "/apis/storage.k8s.io/v1beta1",
    "/healthz",
    "/healthz/ping",
    "/healthz/poststarthook/bootstrap-controller",
    "/healthz/poststarthook/ca-registration",
    "/healthz/poststarthook/extensions/third-party-resources",
    "/logs",
    "/metrics",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]
}
`

**Comment by tomdee** [comment]
@vnalla It's probably best to try to solve this interactively. Try asking for help on the #coreos IRC channel on the #flannel channel on the Calico users slack (https://github.com/coreos/flannel#contact)
