### ISSUE TITLE
flannel [network.go:102] failed to register network: failed to open TUN device: ioctl failed with 'operation not permitted'

### ISSUE THREAD

**Issue by SFHfeihong** [coreos/flannel#802]
We use a general user to start flanneld.service, but it didn't work. The error message is as below:
[network.go:102] failed to register network: failed to open TUN device: ioctl failed with 'operation not permitted'
 
## Your Environment

* Flannel version:  flannel-0.7.1-1.el7.x86_64.rpm
* Backend used (e.g. vxlan or udp):  udp
* Etcd version: 3.1.9
* Kubernetes version (if used): 1.5.2
* Operating System and version: centos 7.3
* Link to your project (optional):

The service file is as follows:
[Unit]
Description=Flanneld overlay address etcd agent
After=network.target
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service
[Service]
Type=notify
EnvironmentFile=/etc/sysconfig/flanneld
EnvironmentFile=-/etc/sysconfig/docker-network
_**User=yanfa**_
ExecStart=/usr/bin/flanneld-start $FLANNEL_OPTIONS
ExecStartPost=/usr/libexec/flannel/mk-docker-opts.sh -k DOCKER_NETWORK_OPTIONS -d /run/flannel/docker
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service

We add User=yanfa .  Finally, it didn't work.

**Comment by tomdee** [comment]
Your user needs the right permissions to TUN device. It's easiest to just run flannel as root.
