### ISSUE TITLE
Flannel can create an overlap

### ISSUE THREAD

**Issue by CallMeFoxie** [coreos/flannel#805]
Hi
it seems that flannel can under some circumstanses create bad leases. I was unable to track down exactly why and I have only 1 possible solution at the moment, let me explain:
We have a subnet of /13 with /24 per host -> about 2k subnets for host node allocations.
On two nodes we have got a collision (took ages to figure it out that it happened btw).

Both nodes have the same `/run/flannel/subnet.env`:
```
FLANNEL_NETWORK=172.24.0.0/13
FLANNEL_SUBNET=172.25.95.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=false
```

log on one of the nodes when restarting flannel:
```
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.308745   18894 main.go:446] Determining IP address of default interface
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.309202   18894 main.go:459] Using interface with name eth0.795 and address 10.27.95.156
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.309216   18894 main.go:476] Defaulting external address to interface address (10.27.95.156)
Sep 06 16:27:49 theserver flanneld[18894]: warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.328823   18894 main.go:226] Created subnet manager: Etcd Local Manager with Previous Subnet: 172.25.95.0/24
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.328830   18894 main.go:229] Installing signal handlers
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.334377   18894 main.go:330] Found network config - Backend type: vxlan
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.345526   18894 local_manager.go:147] Found lease (172.25.95.0/24) for current IP (10.27.95.156), reusing
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.347605   18894 main.go:279] Wrote subnet file to /run/flannel/subnet.env
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.347624   18894 main.go:284] Finished starting backend.
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.347717   18894 vxlan_network.go:56] Watching for L3 misses
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.347730   18894 vxlan_network.go:64] Watching for new subnet leases
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.349460   18894 main.go:367] Waiting for 22h59m59.997673261s to renew lease
Sep 06 16:27:49 theserver flanneld[18894]: I0906 16:27:49.358010   18894 vxlan_network.go:157] Handling initial subnet events
... yada fdb stuff running ...
```

When I do `etcdctl -o extended get /coreos.com/network/subnets/172.25.95.0-24` I get:
```
{"PublicIP":"10.32.0.15","BackendType":"vxlan","BackendData":{"VtepMAC":"aa:bb:cc:dd:ee:ff"}}
```
which does not correspond to the above mentioned IP in the log of flannel.
It seems as it does not actually renew the lease in ETCD when restarting from a status ENV file, but I am not able to confirm it from the source code (not enough time today).

I've dumped the whole network/subnets/* and there is NO record of that host's IP. No idea where it renews to when starting from env/flannel.1 iface...

Flannel: a mix of 0.7.1/0.8.0 (happens on any)
ETCD: v3.1.10

**Comment by CallMeFoxie** [comment]
Sorry my bad, found the issue somewhere completely else :)

**Comment by tomdee** [comment]
@CallMeFoxie I'm excited to hear that you're running a 2K node cluster. Feel free to raise issues (or DM me on slack) for things which you think flannel should be doing better. For example, are there additional or clearer logs that flannel could have written to allow you to more quickly realise that this wasn't a flannel problem?

**Comment by CallMeFoxie** [comment]
It's not 2K node cluster, it's only several hundred, only 2K is the allocated limit. And we have two clusters. And the node was in the wrong cluster for whatever reason :).... Coincidentally on the same flannel IP as another node in the other cluster which made me go WTF until I noticed wrong config file.

Sorry!
