### ISSUE TITLE
Can I route outgoing traffic over flannel?

### ISSUE THREAD

**Issue by klausenbusk** [coreos/flannel#806]
Hello

I'm currently running OpenVPN on every node in my k8s cluster, and routing the traffic over one of two nodes, so the source ip is always either X or Y. This is to reduce the risk of a attacker getting all the server ips and so we don't need customer to update their whitelist "all the time".

I'm wondering if flannel can do the same somehow?
So I need a way to route all traffic to one of two nodes (ex: use them as default gateway). Is that possible?

Regards Kristian

## Your Environment
* Flannel version: v0.8.0
* Backend used: vxlan
* Etcd version: 3.1.8
* Kubernetes version (if used): 1.7.3
* Operating System and version: CoreOS 1409.6.0/1409.7.0

**Comment by tomdee** [comment]
Interesting idea, but this is not currently supported.

**Comment by klausenbusk** [comment]
> Interesting idea, but this is not currently supported.

It seems to work:
On the `outgoing` node:
```
ip addr add 10.2.5.1 dev flannel.1
```
On the rest of the nodes:
```
ip addr add 10.2.0.0/16 dev flannel.1
ip route add 216.239.32.21 via 10.2.5.1 # I have also tested with 
iptables -t nat -I POSTROUTING -j MASQUERADE
curl 216.239.32.21 -H "Host: ipinfo.io"
# Traffic is routed through `outgoing` node.
```

I'm wondering if I can do this in a less hackish-way. I need to add `10.2.0.0/16` to all `flannel.1` interface, and need some logic to route the traffic over another node if `10.2.5.1` goes down.

@tomdee Do you have any ideas?
