### ISSUE TITLE
Flannel does not start on Kubernetes with > 100 nodes

### ISSUE THREAD

**Issue by erez-rabih** [coreos/flannel#815]
I created a K8s 1.7.5 cluster on AWS using Kops 1.7.0
The cluster has 105 nodes - 3 of them master nodes
I always get exactly 4 nodes there kubelet cannot start pods
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

**Comment by klausenbusk** [comment]
Are you using flannel `v0.8.0`? It contain this fix: https://github.com/coreos/flannel/issues/719 which seems related.

**Comment by tomdee** [comment]
I'm assuming you just need to upgrade. Please comment with more diags if you're still having problems.

**Comment by erez-rabih** [comment]
Hi thanks for the tip, upgrading did solve the problem
