### ISSUE TITLE
flannel not cleanup

### ISSUE THREAD

**Issue by gensmusic** [coreos/flannel#820]
At first, I start a kubernetes cluster A using flannel with default 10.244.0.0.
Then I start a new kubernetes cluster B using flannel with 10.83.0.0.
One day, I decide to tear down the cluster A and move all the nodes to cluster B.
I cleanup all the nodes with 
```
kubeadm reset
systemctl stop kubelet
systemctl stop docker
rm -rf /var/lib/cni/
rm -rf /var/lib/kubelet/*
rm -rf /run/flannel
rm -rf /etc/cni/
ifconfig cni0 down
brctl delbr cni0
ifconfig flannel.1 down
systemctl start docker
```

Then I join them into cluster B.

## Expected Behavior
The cluster A nodes should have a flannel.1 like 10.83.x.x after joining cluster B.

## Current Behavior
The cluster A nodes still have 10.244.x.x after joining cluster B.

## Steps to Reproduce (for bugs)

1. start a kubernetes cluster A using flannel with default 10.244.0.0.
2. start a kubernetes cluster B using flannel with  10.83.0.0.
3. tear down cluster A and join all the nodes to cluster B

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):
flannel: v0.8.0-amd64
etcd: 3.0.17

**Comment by tomdee** [comment]
See also #739

**Comment by gensmusic** [comment]
Found a way see https://stackoverflow.com/questions/46276796/kubenetes-cannot-cleanup-flannel/46438072#46438072
