### ISSUE TITLE
enable hairpinMode in flannel cfg

### ISSUE THREAD

**Issue by Dieken** [coreos/flannel#846]
Please merge https://github.com/coreos/tectonic-installer/pull/1640 into https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml,  thanks!

**Comment by tomdee** [comment]
If you submit a PR I can merge it?

**Comment by Dieken** [comment]
@tomdee   sure, https://github.com/coreos/flannel/pull/849
