### ISSUE TITLE
Flannel not using SubnetLen json key

### ISSUE THREAD

**Issue by marchuobi** [coreos/flannel#847]
## Expected Behavior
"SubnetLen": 26 should make networks with a /26 bit net mask for kubernetes nodes 

I had this behavior with flannel 0.8( k8s 1.7.5) and 0.9( k8s 1.8.1)

## Current Behavior
"SubnetLen": 26 appears to be ignored and I get the default /24 bit mask

## Your Environment

* Flannel version: 0.8 and 0.9, at different times and currently 0.9
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.0.17, what came with kubernetes 
* Kubernetes version (if used): 1.7.5 and 1.8.1
* Operating System and version: ubuntu LTS 16.04
* Link to your project (optional): 

from kube-flannel.yml: 
```
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true
      }
    }
  net-conf.json: |
    {
      "Network": "{{ k8s_pod_network }}",
      "SubnetLen": {{ k8s_pod_local_netmask }},
      "Backend": {
        "Type": "vxlan"
      }
    }
```
this is from inside a flannel pod:
```
root@kube-m2:/etc/cni/net.d# kubectl -n kube-system exec -it kube-flannel-ds-thj8w -- /bin/sh
/ # cd /etc/kube-flannel/
/etc/kube-flannel # ls
cni-conf.json  net-conf.json
/etc/kube-flannel # cat cni-conf.json
{
  "name": "cbr0",
  "type": "flannel",
  "delegate": {
    "isDefaultGateway": true
  }
}
/etc/kube-flannel # cat net-conf.json
{
  "Network": "10.105.128.0/21",
  "SubnetLen": 26,
  "Backend": {
    "Type": "vxlan"
  }
}
```
and "ip address for the cni0 and flannel.1 interface, with cni0 getting a /24 :
```
60: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether da:37:51:4d:4b:c3 brd ff:ff:ff:ff:ff:ff
    inet 10.105.129.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::d837:51ff:fe4d:4bc3/64 scope link
       valid_lft forever preferred_lft forever
61: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default qlen 1000
    link/ether 0a:58:0a:69:81:01 brd ff:ff:ff:ff:ff:ff
    inet 10.105.129.1/24 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::a86b:38ff:fe7c:cc25/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by tomdee** [comment]
When using flannel with the kubernetes subnet manager (`--kube-subnet-mgr`), flannel will just use the `podCIDR` that's assigned to the node. See https://github.com/coreos/flannel/blob/master/Documentation/troubleshooting.md#kubernetes-specific

**Comment by marchuobi** [comment]
thanks for the help
