### ISSUE TITLE
flannel plugin binary not getting created in kubernetes cluster

### ISSUE THREAD

**Issue by phagunbaya** [coreos/flannel#851]
I manually deleted the flannel binary from `/opt/cni/bin` after deleting the kubernetes cluster. On the same VM, I'm trying to setup kubernetes + flannel but flannel binary is not getting created in folder `/opt/cni/bin`.

## Expected Behavior
flannel binary should get created everytime daemonset is deployed

## Current Behavior
flannel container starts but kube-dns stays in containercreating mode

## Your Environment
* Flannel version: 0.9.0
* Kubernetes version (if used): 1.7.5
* Operating System and version: Redhat 7

**Comment by tomdee** [comment]
@phagunbaya This repo doesn't install the CNI plugin. You'll need to raise an issue with your distro that installs the CNI plugin
