### ISSUE TITLE
[question] cni-conf.json configuration

### ISSUE THREAD

**Issue by tadas-subonis** [coreos/flannel#852]
There is a ConfigMap:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    tier: node
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true
      }
    }
```

What is cni-conf.json for? What is ""name": "cbr0"" used specifically for?

Thanks

**Comment by tomdee** [comment]
The docs are hard to find, sorry - https://github.com/containernetworking/plugins/tree/master/plugins/meta/flannel

Do they answer your question?

**Comment by tomdee** [comment]
Please let me know if you need more info. Closing for now
