### ISSUE TITLE
The behavior of writing route table in v0.9.0 is strange

### ISSUE THREAD

**Issue by cheyang** [coreos/flannel#867]
Hello, I fount it’s interesting in route table when testing flannel v0.9.0 vxlan. When I set pod network as 172.28.0.0/16, I expect the route rule to add is ‘172.28.0.0/16 via 172.28.0.0 dev flannel.1 onlink’, but in fact I found it’s 

```
[root@iZbp1acq02ar6yc7ar4wa6Z ~]# ip route
default via 192.168.35.253 dev eth0
169.254.0.0/16 dev eth0  scope link  metric 1002
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.28.0.0/24 via 172.28.0.0 dev flannel.1 onlink
172.28.2.0/24 via 172.28.2.0 dev flannel.1 onlink
172.28.3.0/24 via 172.28.3.0 dev flannel.1 onlink
172.28.4.0/24 via 172.28.4.0 dev flannel.1 onlink
192.168.35.0/24 dev eth0  proto kernel  scope link  src 192.168.35.99
```

4 routing rule is instead, it’s different from flannel v0.8.0.

```
v0.8.0
default via 192.168.33.253 dev eth0
169.254.0.0/16 dev eth0  scope link  metric 1002
172.28.0.0/16 dev flannel.1
192.168.33.0/24 dev eth0  proto kernel  scope link  src 192.168.33.83
```

So my question is if it’s a bug or work as design? And I really have concerns about the routing performance, and how do you think about this?

**Comment by tomdee** [comment]
@cheyang Yes, this is a change is was one of the main features of v0.9.0, so it is by design and not a bug that you see those routes. What is your concern about the routing performance?

**Comment by cheyang** [comment]
Is it introduced by [backend/vxlan: simplify vxlan processing](https://github.com/coreos/flannel/pull/785/files#diff-2fcdad83a560522bb17d06e480b6ed76R17)?

I'm wondering why we need change one routing rule (172.28.0.0/16 dev flannel.1, which is using subnet 16)into so many rules (172.28.2.0/24 via 172.28.2.0 dev flannel.1 onlink, which are using subnet 24). There will be more rules in the routing table. will it introduce performance overhead?

**Comment by vincentbernat** [comment]
With one routing rule to a directly attached interface, you'll generate L2MISS events that need to be handled. From my understanding, the goal was to remove any netlink events as the key/value store already told us all the info we need beforehand. Requests for unknown subnets won't trigger a lookup, a scan of the subnet won't trigger a lot of load on the key/value store and the latency of first packets will be lower. This new approach seems more robust.

The routing overhead is pretty low. See [this benchmark](https://vincent.bernat.im/en/blog/2017-ipv4-route-lookup-linux#performance). The /24 case is similar to the /32 case of the benchmark. The additional 5 ns you'll spent in the routing lookup is quite small compared to the time you spend in Netfilter. Moreover, you'll have less ARP entries, so less time spent in managing the hash table associated.

**Comment by cheyang** [comment]
Thanks.
