### ISSUE TITLE
master node flannel.1 state DOWN, can't bind inet

### ISSUE THREAD

**Issue by gnodli** [coreos/flannel#878]
when i reboot the master node and the other node ,use `ip a` , 
in master node ,it shows:
```
flannel.1: <BROADCAST,MULTICAST> mtu 1450 qdisc noqueue state DOWN 
    link/ether 92:7f:1d:28:02:42 brd ff:ff:ff:ff:ff:ff
```  
in other node, it shows:
```
flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether 16:68:99:b6:77:24 brd ff:ff:ff:ff:ff:ff
    inet 10.244.1.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::1468:99ff:feb6:7724/64 scope link 
       valid_lft forever preferred_lft forever
```
## Current Behavior

```
 flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether 92:7f:1d:28:02:42 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::907f:1dff:fe28:242/64 scope link 
       valid_lft forever preferred_lft forever
```  
but there is no inet   

the flannel pods show :  
```
NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE       IP               NODE
default       rudder-4281775016-j1qb8                1/1       Running   1          1h        192.168.56.100   master
kube-system   etcd-master                            1/1       Running   7          1d        192.168.56.100   master
kube-system   kube-apiserver-master                  1/1       Running   16         1d        192.168.56.100   master
kube-system   kube-controller-manager-master         1/1       Running   11         1d        192.168.56.100   master
kube-system   kube-dns-2425271678-r7b0z              3/3       Running   24         1d        10.244.0.14      master
kube-system   kube-flannel-ds-p1bx2                  2/2       Running   0          21m       192.168.56.110   node1
kube-system   kube-flannel-ds-vz1hc                  2/2       Running   0          21m       192.168.56.100   master
```

## Steps to Reproduce (for bugs)

Install k8s cluster v1.7.5 using kubeadm with CNI and flannel plugin.

## Your Environment

* Flannel version:0.8.0-amd64
* Backend used (e.g. vxlan or udp):
* Etcd version:3.0.17
* Kubernetes version (if used):v1.7.5
* Operating System and version:centos7.1
* Link to your project (optional):

**Comment by tomdee** [comment]
@gnodli Do you have logs from the master?

**Comment by gnodli** [comment]
there is my master node log, this problem has repeated many tims in my environment.
[master node log.txt](https://github.com/coreos/flannel/files/1489645/master.node.log.txt)
below file is my install script and configure file
[install script and config file.zip](https://github.com/coreos/flannel/files/1489707/install.script.and.config.file.zip)

thx

**Comment by tomdee** [comment]
@gnodli I'm not sure what the problem is but I would guess that NetworkManager is interfering. e.g.
```
Nov 21 08:42:12 localhost NetworkManager[622]: <info>  [1511224932.7115] device (flannel.1): state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
Nov 21 08:42:12 localhost NetworkManager[622]: <info>  [1511224932.7333] device (flannel.1): state change: unavailable -> unmanaged (reason 'connection-assumed') [20 10 41]
``` 
I'd suggest trying other support channels to try to diagnose this further.https://github.com/coreos/flannel#contact

**Comment by yaxu666** [comment]
@gnodli  I met the same issue after rebooting a node, how did you bring back the `inet ` property at last?
