### ISSUE TITLE
Omitting the scheme from -etcd-endpoints argument results in ambiguous behavior

### ISSUE THREAD

**Issue by vcaputo** [coreos/flannel#88]
It appears the scheme is required for an etcd endpoint to be utilized by flannel:
 # ./flanneld -etcd-endpoints=192.168.1.100:1234
E1124 19:34:07.531877 00626 main.go:137] Failed to create SubnetManager: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
E1124 19:34:08.534750 00626 main.go:137] Failed to create SubnetManager: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
E1124 19:34:09.535471 00626 main.go:137] Failed to create SubnetManager: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
^C$

Upon examining strace output for the above no connect is even being attempted, the error should say something about the absent scheme in such a situation then exit immediately.

**Comment by tobegit3hub** [comment]
Maybe `flanneld --etcd-endpoints=http://127.0.0.1:2379` should work.

**Comment by tomdee** [comment]
This is already fixed. The `http` is now required. 
without it, you get this message

```
E0313 11:35:30.968084   19078 main.go:114] Failed to create SubnetManager: parse 192.168.1.1:2379: first path segment in URL cannot contain colon
```
