### ISSUE TITLE
Flannel overlay network issue

### ISSUE THREAD

**Issue by mohammadobaid1** [coreos/flannel#881]
Basically I am creating blockchain network on three ubuntu servers on aws and and on these servers some docker containers are running. Flannel network is created so that dockers container between those hosts can communicate . but it seems like flannel is unable to create overlay network properly because containers need to communicate each other for data transfer and I am unable to do that. Everything was working fine for sometime but when I relaunch network it is not working
###### Testing
For testing I create busybox container and tries to ping all other containers from that busybox container. I am only able to ping container whiich is running on localhost server and default gateway of toher server. Other containers which is running on other servers unable to respond to that ping.

Following are the some test performed by me  but I am unable to fix this issue.
`systemctl status flanneld
`
output of above command is 

```
flanneld.service - Fabric Flanneld Service
   Loaded: loaded (/lib/systemd/system/flanneld.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-11-17 09:41:03 UTC; 16min ago
 Main PID: 10625 (flanneld)
    Tasks: 8
   Memory: 4.0M
      CPU: 54ms
   CGroup: /system.slice/flanneld.service
           └─10625 /opt/fabric/bin/flanneld

Nov 17 09:41:03 fabric001 flanneld[10625]: I1117 09:41:03.304418   10625 main.go:132] Installing signal handlers
Nov 17 09:41:03 fabric001 flanneld[10625]: I1117 09:41:03.304721   10625 manager.go:124] Searching for interface using 172.31.13.84
Nov 17 09:41:03 fabric001 flanneld[10625]: I1117 09:41:03.304922   10625 manager.go:149] Using interface with name eth0 and address 172.31.13.8
Nov 17 09:41:03 fabric001 flanneld[10625]: I1117 09:41:03.304940   10625 manager.go:166] Defaulting external address to interface address (172.
Nov 17 09:41:03 fabric001 flanneld[10625]: I1117 09:41:03.311404   10625 local_manager.go:179] Picking subnet in range 172.16.0.0 ... 172.16.25
Nov 17 09:41:03 fabric001 flanneld[10625]: I1117 09:41:03.314659   10625 manager.go:250] Lease acquired: 172.16.10.0/24
Nov 17 09:41:03 fabric001 systemd[1]: Started Fabric Flanneld Service.
Nov 17 09:41:03 fabric001 flanneld[10625]: I1117 09:41:03.316712   10625 network.go:98] Watching for new subnet leases
Nov 17 09:41:03 fabric001 flanneld[10625]: I1117 09:41:03.450429   10625 network.go:191] Subnet added: 172.16.84.0/24
Nov 17 09:41:03 fabric001 flanneld[10625]: I1117 09:41:03.972695   10625 network.go:191] Subnet added: 172.16.37.0/24

```
I can ping deafualt gateway which is added as subnet by flannel but cannot ping docker container's ip
Another command which I ran

`netstat -rn` 

Output is
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         172.31.0.1      0.0.0.0         UG        0 0          0 eth0
172.16.0.0      0.0.0.0         255.255.0.0     U         0 0          0 flannel0
172.16.10.0     0.0.0.0         255.255.255.0   U         0 0          0 docker0
172.31.0.0      0.0.0.0         255.255.240.0   U         0 0          0 eth0

```

## Expected Behavior
busybox container should be able to ping each and every other container

## Current Behavior
busybox container is unable to ping .
## Context
I am trying to deploy hyperledger-fabric architecture using ansible agent which uses flannel to create overlay network between dockers. 
## Your Environment

* Flannel version:0.7.1
* Backend used (e.g. vxlan or udp):
* Etcd version:3.2.0
* Kubernetes version (if used):1.7.0
* Operating System and version: Ubuntu 16.04 AWS instances
* Link to your project (optional): This is the project I am using https://github.com/hyperledger/cello/tree/master/src/agent/ansible

What should I do . I am unable to reoslve this issue on my own and completely lost in it.

**Comment by mohammadobaid1** [comment]
Fix this issue by modifying iptables in ubuntu servers . Seems like firewall blocking data packet to transfer from flannel interface to docker interface

**Comment by iver3on** [comment]
flanneld process is running ,but ifconfig no flannel0  devicehow to solve
