### ISSUE TITLE
Improvement: Change version kube-flannel.yml

### ISSUE THREAD

**Issue by Jnig** [coreos/flannel#882]
Hi everyone,

thank you for fixing the docker iptables rules in flannel 0.9.1. Just tested it and it works like a charm

It would be nice if https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml also references the new container image 0.9.1

## Expected Behavior
kube-flannel.yml should reference the image version 0.9.1

## Current Behavior
currently 0.9.0 is referenced

**Comment by outcoldman** [comment]
ping @tomdee

**Comment by tomdee** [comment]
This is now done
