### ISSUE TITLE
E1211 07:19:48.090611 00006 watch.go:43] Watch subnets: invalid character 'â' looking for beginning of value

### ISSUE THREAD

**Issue by garyyang85** [coreos/flannel#899]
I am using flannel 0.6.2 in my kubernetes, there are a lot of network error log suddenly in my flannel log:
E1211 07:19:40.077502 00006 watch.go:43] Watch subnets: invalid character 'â' looking for beginning of value

Etcd status is healthy,  some output for the etcdctl:
etcdctl --peers https://localhost:2379  ls /cluster.local/network/subnets
/cluster.local/network/subnets/10.254.21.0-24
/cluster.local/network/subnets/10.254.82.0-24
/cluster.local/network/subnets/10.254.98.0-24
/cluster.local/network/subnets/10.254.134.0-24

If I manually delete the subnets, it will generate a new one, then the error log gone.
I deleted two subnets, and a odd status here:
Pods on the new two subnets vm, can reach each other, but can not reach the other pods on the error logs vms. The pods on the error logs vm can reach each other but can not reach the pods on the two new subnets vm.

New subnet output like this:
{"PublicIP":"x.x.x.x","BackendType":"vxlan","BackendData":{"VtepMAC":"a2:81:90:6c:b0:ef"}}
Erros logs subnet output like this:
{"PublicIP":"x.x.x.x","BackendType":"vxlan","BackendData":{"VtepMAC":"66:1b:f8:95:7f:5c"}}

Looks the same. 

I am wondering where to find  the invalid character 'â' ?  It is very hard to input character like this..

**Comment by tomdee** [comment]
@garyyang85 Thanks for reporting this issue but I can't think what the problem could be. You are running quite an old version, if you can reproduce the problem on the latest version then maybe I can look at it.
