### ISSUE TITLE
Running flannel on K8s master which is not self hosted

### ISSUE THREAD

**Issue by akshaymankar** [coreos/flannel#900]
We're trying to run flannel with `--kube-subnet-mgr`. It works fine on worker nodes. When we try to run it on master node, it doesn't because it seems like flannel always expects to be run on a VM which runs a K8s node. But in this case we want to run flannel on master without self-hosting so `kubectl proxy` works.

Is there a reason you assume that master is always running inside a kubelet?
And, would you be open to supporting running flannel on master which is not self-hosted?

**Comment by tomdee** [comment]
The assumption is that flannel running with --kube-subnet-mgr is running under a kubelet. The kubernetes master components don't need to be running under the kubelet.

**Comment by akshaymankar** [comment]
> The assumption is that flannel running with --kube-subnet-mgr is running under a kubelet.

I guess I am looking for a reason for this assumption?
I am asking because it forces me to start kubelet on my master VM, when all I want is an interface and a route into my container network from master. It seems theoretically possible to achieve that. Which brings us to the second question, would you be open to supporting this use case?
