### ISSUE TITLE
flannel does not work in Kubernetes on CentOS hosts, but works on Ubuntu hosts

### ISSUE THREAD

**Issue by kgignatyev-inspur** [coreos/flannel#902]
## Expected Behavior

Flannel networking working fast and the same way on Ubuntu and CentoOS hosts

## Current Behavior

DNS resolution works slow (via DNS service in Kubernetes) or not working at all Alpine containers with complaint about 'reply from unexpected source'

## Possible Solution
--

## Steps to Reproduce (for bugs)

create simple cluster with kops in us-east-2 and edit nodes and masters to use CentoOS image (AMI: ami-e0eac385) per
https://github.com/kubernetes/kops/blob/master/docs/images.md

## Context

https://github.com/kubernetes/kops/issues/4040
## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version:
* Kubernetes version (if used):1.8.5
* Operating System and version: CentoOS 7
* Link to your project (optional):

More details in the original issue:
https://github.com/kubernetes/kops/issues/4040

**Comment by rajatchopra** [comment]
Resolve it by running:
$ modprobe br_netfilter
$ sysctl -w net.bridge.bridge-nf-call-iptables = 1
