### ISSUE TITLE
Error registering network: operation not supported

### ISSUE THREAD

**Issue by jiangxinshang** [coreos/flannel#905]
[root@localhost system]# /root/local/bin/flannel \
>   -etcd-cafile=/etc/kubernetes/ssl/ca.pem \
>   -etcd-certfile=/etc/flanneld/ssl/flanneld.pem \
>   -etcd-keyfile=/etc/flanneld/ssl/flanneld-key.pem \
>   -etcd-endpoints=https://10.20.42.56:2379,https://10.20.42.19:2379 \
>   -etcd-prefix=/kubernetes/network \
>   -iface=enp5s0
I1218 09:45:07.672940    6130 main.go:482] Using interface with name enp5s0 and address 10.20.42.56
I1218 09:45:07.673198    6130 main.go:499] Defaulting external address to interface address (10.20.42.56)
2017-12-18 09:45:07.678068 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
I1218 09:45:07.678274    6130 main.go:234] Created subnet manager: Etcd Local Manager with Previous Subnet: 0.0.0.0/0
I1218 09:45:07.678332    6130 main.go:237] Installing signal handlers
I1218 09:45:07.851906    6130 main.go:347] Found network config - Backend type: vxlan
I1218 09:45:07.852141    6130 vxlan.go:119] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
E1218 09:45:07.855617    6130 main.go:279] Error registering network: operation not supported
I1218 09:45:07.855746    6130 main.go:327] Stopping shutdownHandler...

what is wrong ? how to deal  with it ?

**Comment by tomdee** [comment]
Run as root?
