### ISSUE TITLE
Add resources requests and limits to kube-flannel.yml v0.9.1

### ISSUE THREAD

**Issue by BastienL** [coreos/flannel#918]
The `kube-flannel.yml` file in the v0.9.1 documentation (https://github.com/coreos/flannel/blob/v0.9.1/Documentation/kube-flannel.yml) does not set resources requests and limits. The resulting `kube-flannel-ds` pods will have a QoS class of `BestEffort`.

This can dangerous on low-cpu or low-ram nodes, as that would allow k8s to remove these pods if there's too much pressure on the node they are deployed to. Without a `kube-flannel-ds` pod running on a node, all the pods on that node become unreachable.

## Expected Behavior
The `kube-flannel.yml` file in the v0.9.1 documentation  (https://github.com/coreos/flannel/blob/v0.9.1/Documentation/kube-flannel.yml) should have resources limits and requests set, just like on https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml#L127-L133.

## Context
Create a fresh Kubernetes cluster with kubeadmin, using the official guide: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#pod-network. When you choose Flannel as a network overlay, you are recommended to apply https://github.com/coreos/flannel/blob/v0.9.1/Documentation/kube-flannel.yml.

I already opened an issue on the k8s side: https://github.com/kubernetes/website/issues/6682

**Comment by tomdee** [comment]
This already got fixed in master and should make it into the next release soon.
https://github.com/coreos/flannel/pull/855/files

I'm going to close this issue but if you don't think #855 fixes it then please let me know.
