### ISSUE TITLE
Query regarding flannel installation on multiple NICs

### ISSUE THREAD

**Issue by kumarshetty** [coreos/flannel#924]
Issue type: Query
When I tried to install flannel on 2 different eth of same host, I observed second instance has overwritten the first instance conf file(ie 10-flannel.conflist). So do we have to create instances by specifying different conf file in deamonset yaml?. Was interested to know what is the usual practice for creating multiple flannels on different NICs on single host on kubernetes, Can u pls help to know

**Comment by tomdee** [comment]
Sorry, it's not currently possible to run multiple copies of flannel on the same host with the kube subnet manager
