### ISSUE TITLE
RFC: Permit flannel to use kubernetes subnet manager running standalone (not in a pod)

### ISSUE THREAD

**Issue by ut0mt8** [coreos/flannel#932]
I am trying to migrate from an old setup running flannel in standalone mode (launched by systemd) and with config in etcd to the kubernetes subnet manager. For some reason (simplicity mostly) I am not comfortable with launching flannel in k8s with DaemonSet. I think the definition is rather complicated and I really prefer to launch all cluster component with systemd. (I know this is not the current move).

However when launching flannel in command line with -kube-subnet-mgr -kube-api-url flannel complain about not having POD_NAME and POD_NAMESPACE set.

Digging a bit, faking both env variable with the values of a pod  running on the current host doing the job ; for example : 

`POD_NAME=nginx-8586cf59-6fxd2 POD_NAMESPACE=default /usr/local/bin/flannel -kube-subnet-mgr -kube-api-url http://masterk8s:8080/ -kube-subnet-mgr ` 

I have not read the code but I suppose that these env vars are used internaly to find on which host flannel is running on. 

I think using hostname() is a viable alternative as k8s workers register by default with his value.

Funny thing I can make a working launch script using a fake DaemonSet deployment (assuring there is at least one pod running on this host), and matching this pod name with something like : 

`POD_NAME=$(kubectl get pod -o wide | grep $HOSTNAME | awk '{ print $1 }' | head -1)`

## Expected Behavior
Flannel should run standalone with  -kube-subnet-mgr -kube-api-url.

## Current Behavior
Flannel expect to be launched in a pod to run in the kube-subnet-mgr mode.

## Possible Solution
Flannel may guess the host it is running on with os.Hostname() or with a flag.

**Comment by tomdee** [comment]
You just need the NODE_NAME variable to be set - see https://github.com/coreos/flannel/blob/master/dist/functional-test-k8s.sh#L81

and the comment here - https://github.com/coreos/flannel/blob/master/subnet/kube/kube.go#L94


Hope that helps/

**Comment by ut0mt8** [comment]
Hey exactly what I need. I should have read the code :) 
I think we can close this one. Thanks you.
