### ISSUE TITLE
kube-flannel-ds Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by vincentmli** [coreos/flannel#945]
setup all-in-one locally k8s from https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md
fail to start up kube-flannel containers

## Expected Behavior

expect install-cni and kube-flannel running
## Current Behavior

[root@centos-k8s-master kubernetes]# cluster/kubectl.sh get po  -o wide --namesp
NAME                        READY     STATUS                  RESTARTS   AGE
kube-dns-754f9cd4f5-mb6tj   3/3       Running                 0          1h
kube-flannel-ds-jm782       0/1       Init:CrashLoopBackOff   24         1h

[root@centos-k8s-master kubernetes]# cluster/kubectl.sh   logs kube-flannel-ds-jm782  --namespace=kube-system
Error from server (BadRequest): container "kube-flannel" in pod "kube-flannel-ds-jm782" is waiting to start: PodInitializing

## Steps to Reproduce (for bugs)

1. follow https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md to setup locally k8s
2. download https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml
3. #cluster/kubectl.sh apply -f kube-flannel.yaml --namespace=kube-system
4.

## Context

trying to implement flannel as pod to talk to apiserver instead of etcd

## Your Environment

* Flannel version:
flannel:v0.10.0-amd64
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: (flannel get information from apiserver, not etcd)
etcdctl version: 3.1.10
API version: 2

* Kubernetes version (if used):

[root@centos-k8s-master kubernetes]# cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.3.14+bdde1961911138-dirty", GitCommit:"bdde1961911138c81ea2ffafb8859cf992d49917", GitTreeState:"dirty", BuildDate:"2018-02-02T22:02:34Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.3.14+bdde1961911138-dirty", GitCommit:"bdde1961911138c81ea2ffafb8859cf992d49917", GitTreeState:"dirty", BuildDate:"2018-02-02T22:02:34Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Operating System and version:

CentOS 7

* Link to your project (optional):

**Comment by vincentmli** [comment]
I found the problem
Feb 06 12:50:13 fed-master dockerd-current[2187]: cp: can't create '/etc/cni/net.d/10-flannel.conflist': Permission denied
https://github.com/coreos/flannel/issues/709 resolved the issue, sorry for the noise

**Comment by vijaychebium** [comment]
How did you resolve the issue? I have the same problem. can you please detail the steps.

**Comment by devops-team-92** [comment]
> 
> 
> How did you resolve the issue? I have the same problem. can you please detail the steps.

Disable SELINUX .
