### ISSUE TITLE
Possible conflict of subnets when using the "public" ip as its identity

### ISSUE THREAD

**Issue by balboah** [coreos/flannel#98]
When trying out flannel with vagrant configured for two coreos instances, it did not work out of the box.
The reason was that both instances had "10.0.2.15" configured and flannel used it as its identity / public ip. Since it also uses that information as the identity when defining and re-using the allocated subnets, both instances was trying to use the same range.

I resolved it easily with `-iface=$public_ipv4` but maybe the ip discovery logic should be the same as how $public_ipv4 gets set by default? Additionally maybe it should not use this ip as the mechanism to identify the subnets assigned to itself?

**Comment by RenoRainz** [comment]
Hi guys,

I have the same issue, where did you do the modification ?  
I put this in my vagrant file but still not working : 
  flanneld:
    iface: $public_ipv4

I try to modify this file /usr/lib64/systemd/system/flanneld.service  but /usr is readonly, so I suppose it's not the good way.

**Comment by eyakubovich** [comment]
@RenoRainz Looks like you're using one of the latest CoreOS alpha images. In that cause, you should be able to specify this in `user-data` file which contains the cloud-config. See https://coreos.com/docs/running-coreos/platforms/vagrant/.

You should have something like:
```
#cloud-config

coreos:
  flannel:
      interface: $public_ipv4
```

**Comment by RenoRainz** [comment]
@eyakubovich thx a lot, it works !

By the way do you know if a list of all parameters useable in cloud config exist, and if yes do you know where I can find it ?

**Comment by robszumski** [comment]
@RenoRainz You can find the docs here: https://coreos.com/docs/cluster-management/setup/cloudinit-cloud-config/

**Comment by RenoRainz** [comment]
Tks a lot !
