### ISSUE TITLE
cannot start a cluster on a flannel network

### ISSUE THREAD

**Issue by CrisMon-01** [coreos/flannel#985]
## Current Behavior
i had to create a network for my cluster (i have the kube-dns pending for that) this is the result of kubectl get pod --all-namespace
NAMESPACE     NAME                                      READY     STATUS    RESTARTS   AGE
kube-system   etcd-crismon01-xps15                      1/1       Running   0          8m
kube-system   kube-apiserver-crismon01-xps15            1/1       Running   0          8m
kube-system   kube-controller-manager-crismon01-xps15   1/1       Running   0          8m
kube-system   kube-dns-86f4d74b45-xzhmp                 0/3       Pending   0          9m
kube-system   kube-proxy-27mnf                          1/1       Running   0          9m
kube-system   kube-scheduler-crismon01-xps15            1/1       Running   0          8m

now i want to run the cluster on flunnel and this is the result:
` kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420866f00 0xc42035fe30  flannel https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 0xc420f2e070  false}
from server for: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml": clusterroles.rbac.authorization.k8s.io "flannel" is forbidden: User "system:node:crismon01-xps15" cannot get clusterroles.rbac.authorization.k8s.io at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420866fc0 0xc4202ce700  flannel https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 0xc420f2e4c0  false}
from server for: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml": clusterrolebindings.rbac.authorization.k8s.io "flannel" is forbidden: User "system:node:crismon01-xps15" cannot get clusterrolebindings.rbac.authorization.k8s.io at the cluster scope
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420098900 0xc420357ea0 kube-system flannel https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 0xc4200a6420  false}
from server for: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml": serviceaccounts "flannel" is forbidden: User "system:node:crismon01-xps15" cannot get serviceaccounts in the namespace "kube-system": disabled by feature gate TokenRequest
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4200989c0 0xc420122540 kube-system kube-flannel-cfg https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 0xc4200a6490  false}
from server for: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml": configmaps "kube-flannel-cfg" is forbidden: User "system:node:crismon01-xps15" cannot get configmaps in the namespace "kube-system": no path found to object
Error from server (Forbidden): error when retrieving current configuration of:
&{0xc420098b40 0xc420351f80 kube-system kube-flannel-ds https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 0xc4200a6578  false}
from server for: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml": daemonsets.extensions "kube-flannel-ds" is forbidden: User "system:node:crismon01-xps15" cannot get daemonsets.extensions in the namespace "kube-system"
`
OS: ubuntu 16.04
kubeadm version: GitVersion:"v1.10.1"

**Comment by kotnn** [comment]
+1 the same issue

**Comment by anguslees** [comment]
I don't know why, but you are running the pod as the node service-account: `User "system:node:crismon01-xps15" cannot get daemonsets.extensions in the namespace "kube-system"`

It needs to run as a new service-account, which has been given the required RBAC access.  See Documentation/k8s-manifests/kube-flannel-rbac.yml

**Comment by velmurugan-r** [comment]
+1 the same issue

**Comment by CrisMon-01** [comment]
@velmurugan-r i have change with weave. it work better for my purpouse, check the ethernet

**Comment by velmurugan-r** [comment]
I fixed the problem sorry for the confusion , forgot to copy the file to the kubeconfig export path, after copied to the path it works for me 
export KUBECONFIG=$HOME/.kube/admin.conf

**Comment by CrisMon-01** [comment]
i don't remeber how i solved this problem because is too old
